### ISSUE TITLE
If a latent slave spontaneously disconnects, buildbot will never try to start it.

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2914]
This ticket is a migrated Trac ticket [3170](http://trac.buildbot.net/ticket/3170)

People contributed to the original ticket: @djmitche, @tomprince
Ticket created on: `Jan 21 2015`
Ticket last modified on: `Feb 08 2015`

---

It appears this has something to do with buildbot thinking the slave is then disconnected, not latent.

---

_Comment from_: @dustin
_Date_: `Feb 04 2015`

Do you have logs or a repro recipe or something more concrete?

---
_Comment from_: @tom.prince
_Date_: `Feb 04 2015`

1. Have a buildbot with a latent slave.
2. Trigger a build that starts the slave.
3. Outside of buildbot, shutdown the slave, or otherwise forcibly disconnect it (destroy the VM).
4. Trigger another build that should start the slave, and notice that the latent slave never starts.

I haven't done this, but:
5. Login via manhole, notice that the associated slavebuilder is disconnected, not `LATENT`.

**Comment by seankelly** [comment]
Testing now and the build "starts" by pinging the worker but never progresses beyond that. At seven minutes in the pinging state with nothing further in the logs.

**Comment by seankelly** [comment]
After 15 minutes, the ping failed. This caused Buildbot to put the worker in quarantine. After the quarantine finished, Buildbot tried to start the worker by substantiating a VM:

    2017-03-09 14:47:20-0600 [-] starting build <Build latent number:None results:success> using worker <LatentWorkerForBuilder builder=u'latent' worker=u'os-worker-1' state=AVAILABLE>
    2017-03-09 14:47:20-0600 [-] <Build latent number:None results:success>.startBuild
    2017-03-09 14:47:20-0600 [-] acquireLocks(worker <OpenStackLatentWorker u'os-worker-1'>, locks [])
    2017-03-09 14:47:20-0600 [-] substantiating worker <LatentWorkerForBuilder builder=u'latent' worker=u'os-worker-1' state=DETACHED>
    2017-03-09 14:47:20-0600 [-] OpenStackLatentWorker os-worker-1 instance 414a6dd8-eec3-4270-ab4c-b273fa0605ad (os-worker-1) already terminated
    2017-03-09 14:47:20-0600 [-] while worker_prepare
            Traceback (most recent call last):
              File "/mnt/buildbot/venv/master/src/buildbot/master/buildbot/process/workerforbuilder.py", line 243, in substantiate
                return self.worker.substantiate(self, build)
              File "/mnt/buildbot/venv/master/src/buildbot/master/buildbot/worker/latent.py", line 112, in substantiate
                self._substantiate(build)
              File "/mnt/buildbot/venv/master/src/buildbot/master/buildbot/worker/latent.py", line 121, in _substantiate
                d = self.start_instance(build)
              File "/mnt/buildbot/venv/master/lib/python2.7/site-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
                return _inlineCallbacks(None, gen, Deferred())
            --- <exception caught here> ---
              File "/mnt/buildbot/venv/master/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
                result = g.send(result)
              File "/mnt/buildbot/venv/master/src/buildbot/master/buildbot/worker/openstack.py", line 191, in start_instance
                raise ValueError('instance active')
            exceptions.ValueError: instance active

This caused another quarantine. After that was done, the instance was successfully substantiated.

    2017-03-09 14:47:40-0600 [-] starting build <Build latent number:None results:success> using worker <LatentWorkerForBuilder builder=u'latent' worker=u'os-worker-1' state=AVAILABLE>
    2017-03-09 14:47:40-0600 [-] <Build latent number:None results:success>.startBuild
    2017-03-09 14:47:41-0600 [-] acquireLocks(worker <OpenStackLatentWorker u'os-worker-1'>, locks [])
    2017-03-09 14:47:41-0600 [-] substantiating worker <LatentWorkerForBuilder builder=u'latent' worker=u'os-worker-1' state=DETACHED>
    2017-03-09 14:47:50-0600 [-] OpenStackLatentWorker os-worker-1 starting instance f09e9483-cb7b-4cc5-961a-cc829caf7937 (image None)
    ...
    2017-03-09 14:48:24-0600 [-] OpenStackLatentWorker os-worker-1 instance f09e9483-cb7b-4cc5-961a-cc829caf7937 (os-worker-1) started in about 0 minutes 30 seconds
    2017-03-09 14:50:57-0600 [Broker,5,BBIP] worker 'os-worker-1' attaching from IPv4Address(TCP, 'IP', 50464)

**Comment by sitsofe** [comment]
Apologies for asking but does anyone know if this is fixed in the latest (1.3.0 at the time of writing) or whether it's still an issue?

**Comment by tardyp** [comment]
If the latent worker is started after two quarantine timers, I think the bug can be closed. We can open another bug for if open stack driver fails to cleanup the failing VM on the first try

@sitsofe what exact problem are you having?

**Comment by sitsofe** [comment]
@tardyp it was more of a exploratory query because we see this issue on an old 0.8 buildbot but it was unclear if the issue had was was solved in 0.9 and beyond (I think it's likely we'd go to 1.1). Presumably if `keepalive_interval` is small enough the time to the second quarantine timer failing will be dramatically reduced?

**Comment by tardyp** [comment]
0.9 has seen huge improvements in the management of latent workers. So what you see in 0.8 will probably behave much better in 0.9+

**Comment by sitsofe** [comment]
I can confirm that the dramatically better in 1.1. I found when an in-progress build was interrupted by the latent slave disappearing within a few seconds another latent slave was spun up. Additionally latent slaves are shutdown when the buildbot master is shut down too. Thanks @tardyp !
