### ISSUE TITLE
tests fail with mock-1.3.0

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2958]
This ticket is a migrated Trac ticket [3378](http://trac.buildbot.net/ticket/3378)

People contributed to the original ticket: @djmitche
Ticket created on: `Oct 29 2015`
Ticket last modified on: `Oct 29 2015`

---

    [ERROR]
    Traceback (most recent call last):
      File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
        result = g.send(result)
      File "/home/dustin/code/buildbot/t/buildbot/master/buildbot/test/unit/test_data_builders.py", line 226, in test__masterDeactivated
        self.rtype.update[[BuilderList]].assert_called_with(10, [])
      File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
        six.raise_from([[AssertionError]](_error_message(cause)), cause)
      File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/six.py", line 718, in raise_from
        raise value
    exceptions.[[AssertionError]]: Expected call: mock(10, [[    Actual call: mock(10, [|])]])
    too many positional arguments
    
    buildbot.test.unit.test_data_builders.Builder.test__masterDeactivated
    ===============================================================================
    [ERROR]
    Traceback (most recent call last):
      File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
        result = g.send(result)
      File "/home/dustin/code/buildbot/t/buildbot/master/buildbot/test/unit/test_reporters_mail.py", line 400, in test_buildMessage_nominal
        mn.find[[InterrestedUsersEmails]].assert_called_with([u'me@foo'])
      File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
        six.raise_from([[AssertionError]](_error_message(cause)), cause)
      File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/six.py", line 718, in raise_from
        raise value
    exceptions.[[AssertionError]]: Expected call: mock([[    Actual call: mock([u'me@foo'|u'me@foo'])]])
    too many positional arguments
    
    buildbot.test.unit.test_reporters_mail.[[TestMailNotifier]].test_buildMessage_nominal
    ===============================================================================
    [ERROR]
    Traceback (most recent call last):
      File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
        result = g.send(result)
      File "/home/dustin/code/buildbot/t/buildbot/master/buildbot/test/unit/test_www_auth.py", line 174, in test_render
        self.rsrc.renderLogin.assert_called_with(mock.ANY)
      File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
        six.raise_from([[AssertionError]](_error_message(cause)), cause)
      File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/six.py", line 718, in raise_from
        raise value
    exceptions.[[AssertionError]]: Expected call: mock(<ANY>)
    Actual call: mock(<buildbot.test.util.www.[[FakeRequest]] object at 0x7f8b293f4850>)
    too many positional arguments
    
    buildbot.test.unit.test_www_auth.[[LoginResource]].test_render

Looks like a bug in mock?  Thankfully Travis doesn't have this version installed..

---

**Comment by rodrigc** [comment]
I can't reproduce this with mock 2.0.0
