### ISSUE TITLE
Reference to deleted BuildStepStatus

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2967]
This ticket is a migrated Trac ticket [3401](http://trac.buildbot.net/ticket/3401)

People contributed to the original ticket: @unknown_contributor, @rutsky, @unknown_contributor
Ticket created on: `Jan 05 2016`
Ticket last modified on: `Feb 23 2016`

---

The following is referencing the recently deleted I[[BuildStepStatus]] interface in 0.9.0b5, causing a runtime exception:

buildbot/master/buildbot/status/master.py:182

---

_Comment from_: @unknown_contributor
_Date_: `Feb 22 2016`

I'm seeing this exception in the master log with 0.9.0b7 as well.

    2016-02-22 14:14:07-0800 [-] Unhandled Error
    	Traceback (most recent call last):
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\application\app.py", line 392, in startReactor
    	    self.config, oldstdout, oldstderr, self.profiler, reactor)
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\application\app.py", line 313, in run[[ReactorWithLogging]]
    	    reactor.run()
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\internet\base.py", line 1192, in run
    	    self.mainLoop()
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\internet\base.py", line 1201, in mainLoop
    	    self.run[[UntilCurrent]]()
    	--- <exception caught here> ---
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\internet\base.py", line 824, in run[[UntilCurrent]]
    	    call.func(*call.args, **call.kw)
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\buildbot\buildslave\base.py", line 317, in _missing_timer_fired
    	    text += "%s\n" % status.getURL[[ForThing]](self.slave_status)
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\buildbot\status\master.py", line 182, in getURL[[ForThing]]
    	    if interfaces.I[[BuildStepStatus]].providedBy(thing):
    	exceptions.[[AttributeError]]: 'module' object has no attribute 'I[[BuildStepStatus]]'

	

---
_Comment from_: @rutsky
_Date_: `Feb 22 2016`

@gtmacdonald, can you provide configuration example in which this issue can be reproduced?

---
_Comment from_: @unknown_contributor
_Date_: `Feb 23 2016`

It's very large. I'll see if I can narrow it down.

**Comment by seankelly** [comment]
The code references `buildbot.interfaces.IBuildStepStatus`, but that class was deleted in 2014. Some doc strings in buildbot.interfaces mentions the class still.

**Comment by tdesveaux** [comment]
Only reference left to `BuildStepStatus` is a compatibility class.
