### ISSUE TITLE
Default MailNotifier object missing fromaddr

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2968]
This ticket is a migrated Trac ticket [3402](http://trac.buildbot.net/ticket/3402)

People contributed to the original ticket: @unknown_contributor
Ticket created on: `Jan 05 2016`
Ticket last modified on: `Jan 05 2016`

---

I'm getting the following with a single master with missing slaves (haven't turned them on yet):

    2016-01-05 13:21:36-0800 [-] buildslave-missing msg using default [[MailNotifier]]
    2016-01-05 13:21:36-0800 [-] Unhandled Error
    	Traceback (most recent call last):
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\application\app.py", line 392, in startReactor
    	    self.config, oldstdout, oldstderr, self.profiler, reactor)
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\application\app.py", line 313, in run[[ReactorWithLogging]]
    	    reactor.run()
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\internet\base.py", line 1192, in run
    	    self.mainLoop()
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\internet\base.py", line 1201, in mainLoop
    	    self.run[[UntilCurrent]]()
    	--- <exception caught here> ---
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\twisted\internet\base.py", line 824, in run[[UntilCurrent]]
    	    call.func(*call.args, **call.kw)
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\buildbot\buildslave\base.py", line 317, in _missing_timer_fired
    	    return self._mail_missing_message(subject, text)
    	  File "C:\[[TrionBuildbot]]\python\lib\site-packages\buildbot\buildslave\base.py", line 532, in _mail_missing_message
    	    m['From'] = st.fromaddr
    	exceptions.[[AttributeError]]: '[[MailNotifier]]' object has no attribute 'fromaddr'

The odd thing is I have setup a mail notifier which worked with eight but isn't being detected in _mail_missing_message as indicated by the "using default" message. This is with 0.9.0b5

---

**Comment by seankelly** [comment]
Fixed in #2463.
