### ISSUE TITLE
duplicate worker use case is broken

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3030]
This ticket is a migrated Trac ticket [3656](http://trac.buildbot.net/ticket/3656)

People contributed to the original ticket: @rutsky, @tardyp
Ticket created on: `Dec 14 2016`
Ticket last modified on: `Feb 08 2017`

---

    2016-12-14 11:58:54+0100 [Broker,34,127.0.0.1] worker 'worker0' attaching from I[[Pv4Address]](TCP, '127.0.0.1', 65520)
    2016-12-14 11:58:54+0100 [Broker,34,127.0.0.1] Got duplication connection from 'worker0' starting arbitration procedure
    2016-12-14 11:58:54+0100 [Broker,30,127.0.0.1] Got error while trying to ping connected worker worker0:rejecting duplicate worker
    2016-12-14 11:58:54+0100 [Broker,30,127.0.0.1] Old connection for 'worker0' was lost, accepting new
    2016-12-14 11:58:54+0100 [Broker,30,127.0.0.1] Worker.detached(worker0)
    2016-12-14 11:58:54+0100 [[releaseLocks(<Worker u'worker0'>): [|Broker,30,127.0.0.1]]]
    2016-12-14 11:58:54+0100 [Broker,30,127.0.0.1] Worker worker0 detached from runtests
    2016-12-14 11:58:54+0100 [Broker,34,127.0.0.1] Got workerinfo from 'worker0'
    2016-12-14 11:58:54+0100 [-] False
    2016-12-14 11:58:54+0100 [-] from a running build; this is a serious error - please file a bug at http://buildbot.net
            Traceback (most recent call last):
              File "/Users/ptardy/dev/bb/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1355, in gotResult
                _inlineCallbacks(r, g, deferred)
              File "/Users/ptardy/dev/bb/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
                result = g.send(result)
              File "/Users/ptardy/dev/bb/buildbot/master/buildbot/process/build.py", line 298, in startBuild
                yield self.build[[PreparationFailure]](ready_or_failure, "worker_prepare")
              File "/Users/ptardy/dev/bb/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
                return _inlineCallbacks(None, gen, Deferred())
            --- <exception caught here> ---
              File "/Users/ptardy/dev/bb/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
                result = g.send(result)
              File "/Users/ptardy/dev/bb/buildbot/master/buildbot/process/build.py", line 352, in build[[PreparationFailure]]
                self.workerforbuilder.worker.put[[InQuarantine]]()
            exceptions.[[AttributeError]]: '[[NoneType]]' object has no attribute 'put[[InQuarantine]]'
    
    This is because of https://github.com/buildbot/buildbot/commit/7e3003d241072f18d2845b487cd6cdf7fd364960
    
    The [[RuntimeError]] is caught means it will stop the two workers, which will in turn kill a build.

---

**Comment by mojca** [comment]
Not sure if this is the same problem (I run into it when cloning virtual machines, or simply by accident when copy-pasting):

```
019-05-03 00:21:38+0200 [Broker,20,xxx.xxx.xxx.xxx] Unhandled Error
   Traceback (most recent call last):
     File "/path/to/sandbox/lib/python3.7/site-packages/twisted/internet/defer.py", line 501, in errback
       self._startRunCallbacks(fail)
     File "/path/to/sandbox/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
       self._runCallbacks()
     File "/path/to/sandbox/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
       current.result = callback(current.result, *args, **kw)
     File "/path/to/sandbox/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
       _inlineCallbacks(r, g, status)
   --- <exception caught here> ---
     File "/path/to/sandbox/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
       result = result.throwExceptionIntoGenerator(g)
     File "/path/to/sandbox/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
       return g.throw(self.type, self.value, self.tb)
     File "/path/to/sandbox/lib/python3.7/site-packages/buildbot/worker/protocols/pb.py", line 72, in _getPerspective
       accepted = yield workers.newConnection(conn, workerName)
     File "/path/to/sandbox/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
       result = g.send(result)
     File "/path/to/sandbox/lib/python3.7/site-packages/buildbot/worker/manager.py", line 113, in newConnection
       raise RuntimeError("rejecting duplicate worker")
   builtins.RuntimeError: rejecting duplicate worker
```

**Comment by buck-E** [comment]
I have a similar error on worker version 2.7.0 (debian package) and Twisted version 18.9.0:

```
2020-06-04 08:23:34+0200 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x7f778f699ca0>
2020-06-04 08:23:34+0200 [-] Main loop terminated.
2020-06-04 08:23:34+0200 [-] Server Shut Down.
2020-06-04 08:41:55+0200 [-] Loading buildbot.tac...
2020-06-04 08:41:56+0200 [-] Loaded.
2020-06-04 08:41:56+0200 [-] twistd 18.9.0 (/usr/bin/python3 3.8.3) starting up.
2020-06-04 08:41:56+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2020-06-04 08:41:56+0200 [-] Starting Worker -- version: 2.7.0
2020-06-04 08:41:56+0200 [-] recording hostname in twistd.hostname
2020-06-04 08:41:56+0200 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x7f9d6eec1e20>
2020-06-04 08:41:56+0200 [Broker,client] ReconnectingPBClientFactory.failedToGetPerspective
2020-06-04 08:41:56+0200 [Broker,client] While trying to connect:
        Traceback from remote host -- builtins.RuntimeError: rejecting duplicate worker
        
2020-06-04 08:41:56+0200 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x7f9d6eec1e20>
2020-06-04 08:41:56+0200 [-] Main loop terminated.
2020-06-04 08:41:56+0200 [-] Server Shut Down.
```

I do not know where to start debugging.  Please advise.

**Comment by tardyp** [comment]
@buck-E you have two machines connecting with the same creds
you need one cred per worker

**Comment by buck-E** [comment]
@tardyp  Thank you for replying but no I don't.  I only have one machine in total.
