### ISSUE TITLE
buildbot-worker 0.9.4 fails to start with python 3.6

### ISSUE THREAD

**Issue by pmatos** [buildbot/buildbot#3046]
Using Python-3.6.0 and testing the procedure in the tutorial but buildbot worker fails to start.
buildbot master pip requirements:
```
appdirs==1.4.3
attrs==16.3.0
autobahn==0.17.2
Automat==0.5.0
buildbot==0.9.4
buildbot-console-view==0.9.4
buildbot-waterfall-view==0.9.4
buildbot-worker==0.9.4
buildbot-www==0.9.4
constantly==15.1.0
decorator==4.0.11
future==0.16.0
incremental==16.10.1
Jinja2==2.9.5
MarkupSafe==1.0
packaging==16.8
pbr==2.0.0
PyJWT==1.4.2
pyparsing==2.2.0
python-dateutil==2.6.0
six==1.10.0
SQLAlchemy==1.1.6
sqlalchemy-migrate==0.11.0
sqlparse==0.2.3
Tempita==0.5.2
Twisted==17.1.0
txaio==2.6.1
zope.interface==4.3.3
```

buildbot worker pip requirements:
```
attrs==16.3.0
Automat==0.5.0
buildbot-worker==0.9.4
constantly==15.1.0
future==0.16.0
incremental==16.10.1
six==1.10.0
Twisted==17.1.0
zope.interface==4.3.3
```

I start the master as described in the tutorial for the Pyflakes app without a glitch. Then I create a slave as in the tutorial and when I try to start it, it says:
```
$ buildbot-worker start worker
Following twistd.log until startup finished..
The worker took more than 10 seconds to start and/or connect to the buildmaster,
so we were unable to confirm that it started and connected correctly. Please
'tail twistd.log' and look for a line that says 'message from master: attached'
to verify correct startup. If you see a bunch of messages like 'will retry in 6
seconds', your worker might not have the correct hostname or portnumber for the
buildmaster, or the buildmaster might not be running. If you see messages like   'Failure: twisted.cred.error.UnauthorizedLogin'
then your worker might be using the wrong botname or password. Please correct
these problems and then restart the worker.
```

twistd.log reveals:
```
2017-03-18 11:33:25+0100 [-] Loading buildbot.tac...
2017-03-18 11:33:25+0100 [-] Loaded.
2017-03-18 11:33:25+0100 [-] twistd 17.1.0 (/home/pmatos/.pyenv/versions/3.6.0/envs/ltbot-worker-venv-3.6.0/bin/python 3.6.0) starting up.
2017-03-18 11:33:25+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2017-03-18 11:33:25+0100 [-] Starting Worker -- version: 0.9.4
2017-03-18 11:33:25+0100 [-] recording hostname in twistd.hostname
2017-03-18 11:33:25+0100 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x7f455d9233c8>
2017-03-18 11:33:25+0100 [-] Connecting to localhost:9989
2017-03-18 11:33:25+0100 [HangCheckProtocol,client] <bound method BotBase.remote_print of <buildbot_worker.pb.BotPb object at 0x7f455d923198>> didn't accept () and {b'message': b'attached'}
2017-03-18 11:33:25+0100 [HangCheckProtocol,client] Peer will receive following PB traceback:
2017-03-18 11:33:25+0100 [HangCheckProtocol,client] Unhandled Error
        Traceback (most recent call last):
          File "/home/pmatos/.pyenv/versions/3.6.0/envs/ltbot-worker-venv-3.6.0/lib/python3.6/site-packages/twisted/spread/banana.py", line 173, in gotItem
            self.callExpressionReceived(item)
          File "/home/pmatos/.pyenv/versions/3.6.0/envs/ltbot-worker-venv-3.6.0/lib/python3.6/site-packages/twisted/spread/banana.py", line 136, in callExpressionReceived
            self.expressionReceived(obj)
          File "/home/pmatos/.pyenv/versions/3.6.0/envs/ltbot-worker-venv-3.6.0/lib/python3.6/site-packages/twisted/spread/pb.py", line 621, in expressionReceived
            method(*sexp[1:])
          File "/home/pmatos/.pyenv/versions/3.6.0/envs/ltbot-worker-venv-3.6.0/lib/python3.6/site-packages/twisted/spread/pb.py", line 1025, in proto_message
            self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
        --- <exception caught here> ---
          File "/home/pmatos/.pyenv/versions/3.6.0/envs/ltbot-worker-venv-3.6.0/lib/python3.6/site-packages/twisted/spread/pb.py", line 1054, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "/home/pmatos/.pyenv/versions/3.6.0/envs/ltbot-worker-venv-3.6.0/lib/python3.6/site-packages/twisted/spread/flavors.py", line 120, in remoteMessageReceived
            state = method(*args, **kw)
        builtins.TypeError: remote_print() keywords must be strings
        
2017-03-18 11:33:25+0100 [HangCheckProtocol,client] ReconnectingPBClientFactory.failedToGetPerspective
2017-03-18 11:33:25+0100 [HangCheckProtocol,client] While trying to connect:
        (unable to obtain traceback): must be str, not bytes
2017-03-18 11:33:25+0100 [HangCheckProtocol,client] Lost connection to localhost:9989
2017-03-18 11:33:25+0100 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x7f455d9233c8>
2017-03-18 11:33:25+0100 [-] Main loop terminated.
2017-03-18 11:33:25+0100 [-] Server Shut Down.
```

**Comment by tardyp** [comment]
Hi @pmatos As specified in pypi, buildbot 0.9.4 does not support python3
![image](https://cloud.githubusercontent.com/assets/109859/24072828/51859ef8-0bed-11e7-851c-0d385ead458b.png)

master branch has py3 support now, so 0.9.5 will be the first release compatible (in experimental mode)

**Comment by pmatos** [comment]
Apologies @tardyp , for some reason I thought that one of the novelties of buildbot-nine was that it was Python3 compatible. My fault!

**Comment by rodrigc** [comment]
@pmatos all my py3 fixes are in the 0.9.5 release now, so all the things that I asked you to test before are now in the release.  Thanks again!

**Comment by danni** [comment]
I'm seeing this same backtrace with buildbot-worker 0.9.7 and Python 3.5.

**Comment by rodrigc** [comment]
@dani in your environment, can you:

pip install  https://twistedmatrix.com/Releases/rc/17.5.0rc2/Twisted-17.5.0rc2.tar.bz2

and restart buildbot?

I think https://github.com/twisted/twisted/pull/722 might fix the problem, but this is not in Twisted 17.1
