### ISSUE TITLE
Python 3: builtins.TypeError: Object of type 'dict_keys' is not JSON serializable

### ISSUE THREAD

**Issue by rodrigc** [buildbot/buildbot#3052]
When starting buildbot on Python 3, I am seeing this stack trace in the master's twistd.log file:

```
2017-03-19 22:47:28-0700 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
            self.run()
          File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
            self._target(*self._args, **self._kwargs)
          File "/Users/crodrigues/stupid-venv1/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
            task()
          File "/Users/crodrigues/stupid-venv1/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
            task()
        --- <exception caught here> ---
          File "/Users/crodrigues/stupid-venv1/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
            result = inContext.theWork()
          File "/Users/crodrigues/stupid-venv1/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/Users/crodrigues/stupid-venv1/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/Users/crodrigues/stupid-venv1/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/Users/crodrigues/stupid-venv1/lib/python3.6/site-packages/buildbot/buildbot_net_usage_data.py", line 204, in _sendBuildbotNetUsageData
            res = _sendWithUrlib(PHONE_HOME_URL, data)
          File "/Users/crodrigues/stupid-venv1/lib/python3.6/site-packages/buildbot/buildbot_net_usage_data.py", line 174, in _sendWithUrlib
            data = json.dumps(data)
          File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
            return _default_encoder.encode(obj)
          File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
            chunks = self.iterencode(o, _one_shot=True)
          File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
            return _iterencode(o, 0)
          File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
            o.__class__.__name__)
        builtins.TypeError: Object of type 'dict_keys' is not JSON serializable
```

**Comment by rodrigc** [comment]
I put a debug statement in `buildbot_net_usage_data.py` in `computeUsageData()`
and found:

```
{'installid': 'dfc6e9d12a1fe4a1eaeba1cf1d099d94a8e36e31', 
 'versions': {'Python': '3.6.0', 'Buildbot': '0.9.4-393-g08db5d9', 'Twisted': '17.1.0'}, 
 'platform': {'platform': 'Darwin-16.4.0-x86_64-i386-64bit', 'system': 'Darwin', 'machine': 'x86_64', 'processor': 'i386', 'python_implementation': 'CPython', 'version': 'Darwin Kernel Version 16.4.0:', 'distro': '10.12.3'}, 'plugins': {'buildbot/worker/base/Worker': 1, 'buildbot/config/BuilderConfig': 1, 'buildbot/schedulers/basic/SingleBranchScheduler': 1, 'buildbot/schedulers/forcesched/ForceScheduler': 1, 'buildbot/changes/gitpoller/GitPoller': 1, 'buildbot/steps/source/git/Git': 1, 'buildbot/steps/shell/ShellCommand': 1},
 'db': 'sqlite', 'mq': 'simple', 
 'www_plugins': dict_keys(['waterfall_view', 'console_view'])}
```

The problem is that www_plugins is returning `dict_keys`,
which cannot be serialized via `json.dumps()`.
