### ISSUE TITLE
Build fails with 'signal 13' error

### ISSUE THREAD

**Issue by 0x777** [buildbot/buildbot#3153]
When I run the same build command directly on the worker, there is no error. 

Buildbot version: 0.9.6
Python: 3.5

This is the output in the web interface 
```
process killed by signal 13
program finished with exit code -1
elapsedTime=74.348216
```

These are the corresponding logs of the worker:
```
2017-04-26 15:11:47+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/process.py", line 291, in doRead
            return fdesc.readFromFD(self.fd, self.dataReceived)
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
            callback(output)
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/process.py", line 295, in dataReceived
            self.proc.childDataReceived(self.name, data)
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/process.py", line 961, in childDataReceived
            self.proto.childDataReceived(name, data)
          File "/home/buildbot/venv/lib/python3.5/site-packages/twisted/internet/protocol.py", line 604, in childDataReceived
            self.outReceived(data)
          File "/home/buildbot/venv/lib/python3.5/site-packages/buildbot_worker/runprocess.py", line 214, in outReceived
            data, self.command.builder.unicode_encoding)
          File "/home/buildbot/venv/lib/python3.5/site-packages/buildbot_worker/compat.py", line 55, in bytes2NativeString
            return x.decode(encoding)
        builtins.UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 69: ordinal not in range(128)
        
2017-04-26 15:11:47+0000 [-] command finished with signal 13, exit code None, elapsedTime: 74.348216
```

**Comment by seankelly** [comment]
Is the master running 3.5 as well?

**Comment by seankelly** [comment]
Also, what version of Twisted?

**Comment by 0x777** [comment]
On the worker:
Python: 3.5.2
Twisted: 17.1.0

On the master:
Python: 3.6.1
Twisted: 17.1.0

**Comment by tardyp** [comment]
It looks like you should set the unicode_encoding to utf8 in your buildbot.tac:

http://docs.buildbot.net/latest/manual/installation/worker.html#other-worker-configuration

**Comment by tardyp** [comment]
I believe ascii codec selection comes from this line:
https://github.com/buildbot/buildbot/blob/master/worker/buildbot_worker/base.py#L244

**Comment by 0x777** [comment]
> It looks like you should set the unicode_encoding to utf8 in your buildbot.tac:

Works now. Thanks !

**Comment by rodrigc** [comment]
@tardyp how is line http://docs.buildbot.net/latest/manual/installation/worker.html#other-worker-configuration getting to the part where it sets *ascii* ?  if unicode_encoding is None,
it should get the value of sys.getfilesystemencoding(), which should always return something, usually *utf-8*.

**Comment by tardyp** [comment]
@rodrigc the code is falling back to ascii. Is this a good idea? I don't think so.

then I don't know if the OP problem was because of sys.getfilesystemencoding() returning latin1 or ascii or if it is returning None.

I think the problem is not really related to py3 actually, and probably same would happen with py2

**Comment by rodrigc** [comment]
@0x777 can you re-run the test:
(1)  before line https://github.com/buildbot/buildbot/blob/master/worker/buildbot_worker/base.py#L244 , add two prints:

```
print("unicode_encoding: ", unicode_encoding)
print("sys.getfilesystemencoding(): ", sys.getfilesystemencoding())
```

Temporarily comment out *unicode_encoding* in your buildbot.tac

We should try to fix this so other people don't hit the problem.
