### ISSUE TITLE
PasswordManhole 'no host keys, failing'

### ISSUE THREAD

**Issue by nazarewk** [buildbot/buildbot#3160]
I'm trying to go through [Quick Tour](http://docs.buildbot.net/current/tutorial/tour.html#debugging-with-manhole) tutorial, but it looks like `PasswordManhole` isn't implemented properly for new Twisted version:

```
	Traceback (most recent call last):
	  File "/home/krna/dev/buildbot-master/.env/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/krna/dev/buildbot-master/.env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1357, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/home/krna/dev/buildbot-master/.env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/krna/dev/buildbot-master/.env/lib/python3.6/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	--- <exception caught here> ---
	  File "/home/krna/dev/buildbot-master/.env/lib/python3.6/site-packages/buildbot/master.py", line 308, in startService
	    yield self.reconfigServiceWithBuildbotConfig(self.config)
	  File "/home/krna/dev/buildbot-master/.env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/krna/dev/buildbot-master/.env/lib/python3.6/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/krna/dev/buildbot-master/.env/lib/python3.6/site-packages/buildbot/util/service.py", line 53, in reconfigServiceWithBuildbotConfig
	    yield svc.reconfigServiceWithBuildbotConfig(new_config)
	twisted.conch.error.ConchError: ('no host keys, failing', None)
```

I'm on:
```
asn1crypto==0.22.0
attrs==16.3.0
autobahn==0.18.2
Automat==0.5.0
buildbot==0.9.6
buildbot-console-view==0.9.6
buildbot-waterfall-view==0.9.6
buildbot-worker==0.9.6
buildbot-www==0.9.6
cffi==1.10.0
constantly==15.1.0
cryptography==1.8.1
decorator==4.0.11
future==0.16.0
idna==2.5
incremental==16.10.1
Jinja2==2.9.6
MarkupSafe==1.0
packaging==16.8
pbr==3.0.0
pyasn1==0.2.3
pycparser==2.17
PyJWT==1.5.0
pyparsing==2.2.0
python-dateutil==2.6.0
six==1.10.0
SQLAlchemy==1.1.9
sqlalchemy-migrate==0.11.0
sqlparse==0.2.3
Tempita==0.5.2
Twisted==17.1.0
txaio==2.7.0
zope.interface==4.4.0
```

**Comment by s0undt3ch** [comment]
Just hit the same issue

**Comment by Frodox** [comment]
It is related to twisted update
* https://stackoverflow.com/questions/40235033/not-able-to-run-carbon-cache-with-manhole-enabled
* https://twistedmatrix.com/trac/ticket/8229

and looks like @rodrigc touched it a bit :)

**Comment by blag** [comment]
Installing Twisted < 16.0 fixed it for me.
