### ISSUE TITLE
UserPasswordAuth: broken on py3?

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3162]
reported by @aliceinwire on IRC

if auth is configured with:
```
c['www']['auth'] = util.UserPasswordAuth(usernames_passwords)
```
Got error in the logs
```
        Traceback (most recent call last):
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/_auth/wrapper.py", line 133, in render
            return self._authorizedResource(request).render(request)
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/util.py", line 138, in render
            self.d.addCallback(self._cbChild, request).addErrback(
          File "/root/buildbot/lib/python3.4/site-packages/twisted/internet/defer.py", line 321, in addCallback
            callbackKeywords=kw)
          File "/root/buildbot/lib/python3.4/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/root/buildbot/lib/python3.4/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/util.py", line 144, in _cbChild
            request.render(resource.getChildForRequest(child, request))
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/server.py", line 241, in render
            body = resrc.render(self)
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/_auth/wrapper.py", line 59, in render
            generateWWWAuthenticate(fact.scheme, challenge))
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/_auth/wrapper.py", line 48, in generateWWWAuthenticate
            l.append(networkString("%s=%s" % (k, quoteString(v))))
          File "/root/buildbot/lib/python3.4/site-packages/twisted/web/_auth/wrapper.py", line 52, in quoteString
            return '"%s"' % (s.replace('\\', '\\\\').replace('"', '\\"'),)
        builtins.TypeError: 'str' does not support the buffer interface
```

my guess is there is a need for a bytesToNativeString somewhere

**Comment by aliceinwire** [comment]
also with c['www']['auth'] = util.HTPasswdAuth("password")
with both clear password and hashed password

**Comment by tardyp** [comment]
problem comes from this code in twisted:
```
    def render(self, request):
        """
        Send www-authenticate headers to the client
        """
        def generateWWWAuthenticate(scheme, challenge):
            l = []
            for k,v in challenge.items():
                l.append(networkString("%s=%s" % (k, quoteString(v))))
            return b" ".join([scheme, b", ".join(l)])

        def quoteString(s):
            return '"%s"' % (s.replace('\\', '\\\\').replace('"', '\\"'),)

        request.setResponseCode(401)
        for fact in self._credentialFactories:
            challenge = fact.getChallenge(request)
            request.responseHeaders.addRawHeader(
                b'www-authenticate',
                generateWWWAuthenticate(fact.scheme, challenge))
        if request.method == b'HEAD':
            return b''
```
```fact.getChallenge(request)``` returns a byte string, then the code tries to quote it, but uses native string only

**Comment by Foxboron** [comment]
This issue doesn't seem to be fixed.
```
2017-06-04 22:24:40+0200 [_GenericHTTPChannelProtocol,240,127.0.0.1] HTTPAuthSessionWrapper.getChildWithDefault encountered unexpected error
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/web/_auth/wrapper.py", line 162, in _login
	    d = self._portal.login(credentials, None, IResource)
	  File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/cred/portal.py", line 119, in login
	    return maybeDeferred(self.checkers[i].requestAvatarId, credentials
	  File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/cred/checkers.py", line 97, in requestAvatarId
	    self.users[credentials.username]).addCallback(
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/cred/credentials.py", line 157, in checkPassword
	    calcHA1(algo, self.username, self.realm, password, nonce, cnonce),
	  File "/usr/local/lib/python3.5/dist-packages/Twisted-17.1.0.dev0-py3.5-linux-x86_64.egg/twisted/cred/_digest.py", line 65, in calcHA1
	    m.update(pszPassword)
	builtins.TypeError: Unicode-objects must be encoded before hashing
```
```
authz = util.Authz(
    allowRules=[
        util.AnyControlEndpointMatcher(role="admins"),
        util.StopBuildEndpointMatcher(role="admin"),
        util.RebuildBuildEndpointMatcher(role="admin"),
        util.ForceBuildEndpointMatcher(role="admin"),
    ],
    roleMatchers=[
        util.RolesFromEmails(admins=["admin"])
    ]
)
auth=util.UserPasswordAuth({'admin': 'admin'})

c['www'] = dict(port=8010,
                plugins=dict(waterfall_view={}, console_view={}))

c['www']['auth'] = auth
c['www']['authz'] = authz
```
Installed twisted from master and made sure the above patch was included. Chrome  58.0.3029.110 breaks and throws the above error. Firefox 53.0.3 fails silently it seems.

Running python 3.5.3
```
buildbot (0.9.7)
buildbot-console-view (0.9.7)
buildbot-waterfall-view (0.9.7)
buildbot-worker (0.9.7)
buildbot-www (0.9.7)
Twisted (17.1.0.dev0)
```

**Comment by nickdeveaux** [comment]
I'm seeing this same issue in Twisted 18.7.0 with python3.5:

```
2019-03-26T20:52:41+0000 [twisted.web._auth.wrapper.HTTPAuthSessionWrapper#critical] HTTPAuthSessionWrapper.getChildWithDefault encountered unexpected error
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/dist-packages/twisted/web/_auth/wrapper.py", line 163, in _login
	    d = self._portal.login(credentials, None, IResource)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/cred/portal.py", line 119, in login
	    return maybeDeferred(self.checkers[i].requestAvatarId, credentials
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/cred/checkers.py", line 257, in requestAvatarId
	    return defer.maybeDeferred(c.checkPassword, p
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/cred/credentials.py", line 157, in checkPassword
	    calcHA1(algo, self.username, self.realm, password, nonce, cnonce),
	  File "/usr/local/lib/python3.5/dist-packages/twisted/cred/_digest.py", line 63, in calcHA1
	    m.update(pszRealm)
	builtins.TypeError: Unicode-objects must be encoded before hashing
```

**Comment by nickdeveaux** [comment]
I found that if I edited credentials.py on line 157 to replace `self.realm` with `self.realm.encode()` it fixed the issue.

**Comment by tardyp** [comment]
@nickdeveaux do you have custom realm? Shouldn't you just use a byte string instead of unicode string?

**Comment by nickdeveaux** [comment]
@tardyp I'm using the PublicHTMLRealm code [from the documentation](https://twistedmatrix.com/documents/current/web/howto/web-in-60/http-auth.html) , with the example httpd.password text file: 
jon:Pwd4Steve

**Comment by tardyp** [comment]
why aren't you using the official  HTPasswdAuth?

https://github.com/buildbot/buildbot/blob/9043e016101cf0b04b67396ed7f298b9e2b2c4c4/master/buildbot/www/auth.py#L162

**Comment by nickdeveaux** [comment]
Because I'm using the twisted one, as shown in the documentation tutorial I linked: `from twisted.web.guard import HTTPAuthSessionWrapper`. However, I will propose this as a fix to twisted, as its not relevant to buildbot.
