### ISSUE TITLE
unhashable type: 'MethodicalState' : Buildbot workers failing to start

### ISSUE THREAD

**Issue by mlieberman85** [buildbot/buildbot#3195]
I'm seeing the following exception: 
```Unhandled Error
Traceback (most recent call last):
  File "/home/centos/bb-worker/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/home/centos/bb-worker/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/home/centos/bb-worker/lib/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/home/centos/bb-worker/lib/python2.7/site-packages/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/centos/bb-worker/lib/python2.7/site-packages/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/centos/bb-worker/lib/python2.7/site-packages/twisted/application/service.py", line 413, in loadApplication
    passphrase)
  File "/home/centos/bb-worker/lib/python2.7/site-packages/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "buildbot.tac", line 3, in <module>
    from buildbot_worker.bot import Worker
  File "/home/centos/bb-worker/lib/python2.7/site-packages/buildbot_worker/bot.py", line 20, in <module>
    from buildbot_worker.pb import Worker
  File "/home/centos/bb-worker/lib/python2.7/site-packages/buildbot_worker/pb.py", line 22, in <module>
    from twisted.application import internet
  File "/home/centos/bb-worker/lib/python2.7/site-packages/twisted/application/internet.py", line 542, in <module>
    class _ClientMachine(object):
  File "/home/centos/bb-worker/lib/python2.7/site-packages/twisted/application/internet.py", line 842, in _ClientMachine
    outputs=[_connect])
  File "/home/centos/bb-worker/lib/python2.7/site-packages/automat/_methodical.py", line 62, in upon
    self.machine._oneTransition(self, input, enter, outputs, collector)
  File "/home/centos/bb-worker/lib/python2.7/site-packages/automat/_methodical.py", line 255, in _oneTransition
    tuple(outputTokens))
  File "/home/centos/bb-worker/lib/python2.7/site-packages/automat/_core.py", line 74, in addTransition
    (inState, inputSymbol, outState, tuple(outputSymbols))
exceptions.TypeError: unhashable type: 'MethodicalState'
```

This is on Centos 7 with Python 2.7.5.

Output of Pip freeze:
```appdirs==1.4.3
attrs==17.1.0
Automat==0.5.0
buildbot-worker==0.9.7
constantly==15.1.0
future==0.16.0
incremental==16.10.1
packaging==16.8
pyparsing==2.2.0
six==1.10.0
Twisted==17.1.0
zope.interface==4.4.1
```

I also tried running buildbot worker versions 0.9.4 and 0.9.6. Installing Twisted 16.1.0 on the workers is a workaround.

**Comment by tardyp** [comment]
relevent issue is: https://github.com/glyph/automat/issues/62

Please downgrade attrs to 16.3.0

**Comment by mlieberman85** [comment]
Thanks
