### ISSUE TITLE
Exception thrown by buildbot_net_usage_data.py

### ISSUE THREAD

**Issue by chrisspen** [buildbot/buildbot#3352]
When I try to run Buildbot, master fails to start, and twistd.log shows:

	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 754, in run
	    self.__target(*self.__args, **self.__kwargs)
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
	    task()
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
	    task()
	--- <exception caught here> ---
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/buildbot/buildbot_net_usage_data.py", line 197, in _sendBuildbotNetUsageData
	    res = _sendWithRequests(PHONE_HOME_URL, data)
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/buildbot/buildbot_net_usage_data.py", line 190, in _sendWithRequests
	    r = requests.post(url, json=data)
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/requests/api.py", line 88, in post
	    return request('post', url, data=data, **kwargs)
	  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
	    return session.request(method=method, url=url, **kwargs)
	exceptions.TypeError: request() got an unexpected keyword argument 'json'

My package versions are:

    buildbot==0.9.5
    requests==2.2.1

**Comment by seankelly** [comment]
Quick search indicates the `json` parameter appeared in [this commit](https://github.com/requests/requests/commit/8f17741849edb5e7eba0356f90cb17e43c938a2f), first released in 2.4.2

**Comment by rodrigc** [comment]
Fixed by using requests 2.4.2 or higher
