### ISSUE TITLE
failed to create EC2LatentWorker

### ISSUE THREAD

**Issue by vigsterkr** [buildbot/buildbot#3380]
i've just upgraded to 0.9.8 from 0.8.12 and since then all my latent workers are failing.
here's the stacktrace:
http://buildbot.shogun-toolbox.org:8080/#/builders/16/builds/10/steps/0/logs/err_text

**Comment by seankelly** [comment]
Including traceback here for posterity.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/buildbot/process/build.py", line 320, in startBuild
    ready_or_failure = yield workerforbuilder.prepare(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/buildbot/worker/ec2.py", line 516, in _request_spot_instance
    Name=self.instance_profile_name,
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the RequestSpotInstances operation: Value () for parameter groupId is invalid. The value cannot be empty
```

**Comment by vigsterkr** [comment]
ok so i've debugged this one. this is due the the fact that i had to specify `security_name='sg-10de0577'`  - as it cannot be `latent_buildbot_slave` (see #3382). but if you do that then the `api_params` for the `_make_api_call` will contain something like this:

```
{'SpotPrice': '0.019895', 'LaunchSpecification': {'Placement': {'AvailabilityZone': 'eu-west-1b'}, 'SecurityGroupIds': ['sg-10de0577'], 'ImageId': u'ami-f6def890', 'KeyName': 'latent_buildbot_slave', 'SecurityGroups': ['sg-10de0577'], 'IamInstanceProfile': {}, 'InstanceType': u'm4.large'}}
```

but note that SecurityGroups needs to be the name and not the id, see https://stackoverflow.com/a/35721660

so if i forcefully change the request to be 
```
{'SpotPrice': '0.019895', 'LaunchSpecification': {'Placement': {'AvailabilityZone': 'eu-west-1b'}, 'SecurityGroupIds': ['sg-10de0577'], 'ImageId': u'ami-f6def890', 'KeyName': 'latent_buildbot_slave', 'SecurityGroups': ['latent_buildbot_slave'], 'IamInstanceProfile': {}, 'InstanceType': u'm4.large'}}
```

the error goes away...

i guess from here it should be easy for a developer to figure out where things went wrong in 0.9.x
