### ISSUE TITLE
buildbot_profiler fails with exception 'svmem' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3445]
While running buildbot_profiler, I noticed following exceptions repeatedly in twisted.log:

2017-07-16 15:49:55-0700 [-] Unexpected error in main loop.
2017-07-16 15:49:55-0700 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib64/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 262, in postApplication
	    self.startReactor(None, self.oldstdout, self.oldstderr)
	  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 395, in startReactor
	    self.config, oldstdout, oldstderr, self.profiler, reactor)
	  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 310, in runReactorWithLogging
	    reactor.run()
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1199, in run
	    self.mainLoop()
	--- <exception caught here> ---
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1211, in mainLoop
	    self.doIteration(t)
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/epollreactor.py", line 218, in doPoll
	    l = self._poller.poll(timeout, len(self._selectables))
	  File "/usr/lib/python2.7/site-packages/buildbot_profiler/api.py", line 116, in handler
	    mem=dict(psutil.virtual_memory().__dict__)))
	exceptions.AttributeError: 'svmem' object has no attribute '__dict__'
	
2017-07-16 15:49:55-0700 [_GenericHTTPChannelProtocol,1209,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib64/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 1752, in lineReceived
	    self.allContentReceived()
	  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 1845, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 766, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/usr/lib64/python2.7/site-packages/twisted/web/server.py", line 190, in process
	    self.render(resrc)
	  File "/usr/lib64/python2.7/site-packages/twisted/web/server.py", line 241, in render
	    body = resrc.render(self)
	  File "/usr/lib/python2.7/site-packages/autobahn/twisted/resource.py", line 140, in render
	    protocol.makeConnection(transport)
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/protocol.py", line 494, in makeConnection
	    self.connectionMade()
	  File "/usr/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 94, in connectionMade
	    self._connectionMade()
	  File "/usr/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 2456, in _connectionMade
	    WebSocketProtocol._connectionMade(self)
	  File "/usr/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 960, in _connectionMade
	    self.log.debug("\n{attrs}", attrs=pformat(configAttrLog))
	  File "/usr/lib64/python2.7/pprint.py", line 63, in pformat
	    return PrettyPrinter(indent=indent, width=width, depth=depth).pformat(object)
	  File "/usr/lib64/python2.7/pprint.py", line 122, in pformat
	    self._format(object, sio, 0, 0, {}, 0)
	  File "/usr/lib/python2.7/site-packages/buildbot_profiler/api.py", line 116, in handler
	    mem=dict(psutil.virtual_memory().__dict__)))
	exceptions.AttributeError: 'svmem' object has no attribute '__dict__'

**Comment by aakashja** [comment]
This is on Linux (centos 7).
I do not see this error on similar setup of buildbot, buildbot_profiler running on mac.

**Comment by aakashja** [comment]
Some related info:

>>> dir(psutil.virtual_memory())
['__add__', '__class__', '__contains__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getslice__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_asdict', '_fields', '_make', '_replace', 'active', 'available', 'buffers', 'cached', 'count', 'free', 'inactive', 'index', 'percent', 'shared', 'total', 'used']

>>> type(psutil.virtual_memory())
<class 'psutil._pslinux.svmem'>

[~]$uname -a
Linux machine112 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tardyp** [comment]
could you please give the result of pip freeze?

probably you need to update your psutil package (if you not see this on mac).

**Comment by tardyp** [comment]
Note that I strongly discourage to install buildbot on the system python. You should always use a virtualenv.

**Comment by aakashja** [comment]
psutil==5.2.2  (same on both mac and centOS). 

maybe psutil package is little different on mac vs linux (centOS).

**Comment by tardyp** [comment]
should be fixed by buildbot_profiler 1.1.0
