### ISSUE TITLE
RuntimeError: value for column objects.name is greater than max of 128 characters

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3449]
This happens if an object name is too big:
```
2017-07-17 16:10:24+0100 [-] Got fatal Exception on DB
	Traceback (most recent call last):
	Failure: exceptions.RuntimeError: value for column objects.name is greater than max of 128 characters: MailNotifier_builders_<ALL BUILDER NAMES HERE>passing_failing
	
2017-07-17 16:10:24+0100 [-] while starting BuildMaster
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1357, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/master.py", line 304, in startService
	    yield self.reconfigServiceWithBuildbotConfig(self.config)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/util/service.py", line 53, in reconfigServiceWithBuildbotConfig
	    yield svc.reconfigServiceWithBuildbotConfig(new_config)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/util/service.py", line 474, in reconfigServiceWithBuildbotConfig
	    child.name, class_name)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/db/pool.py", line 183, in __thd
	    rv = callable(arg, *args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/db/state.py", line 49, in thd
	    return self.thdGetObjectId(conn, name, class_name)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/db/state.py", line 55, in thdGetObjectId
	    self.checkLength(objects_tbl.c.name, name)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/db/base.py", line 65, in checkLength
	    % (col, col.type.length, value))
	exceptions.RuntimeError: value for column objects.name is greater than max of 128 characters: MailNotifier_builders_<ALL BUILDER NAMES HERE>passing_failing
	
2017-07-17 16:10:24+0100 [-] BuildMaster startup failed
```

**Comment by mokibit** [comment]
@p12tic, I think this issue can be closed, I can confirm, that it was fixed by https://github.com/buildbot/buildbot/pull/3451.
master.cfg file:
```
c['schedulers'].append(schedulers.ForceScheduler(
                            name=("very-long-name"+"-"*180),
                            builderNames=["run_tests"]))
```
After the change, too long name gets hashed and fits the column name length, not breaking the code.
