### ISSUE TITLE
Invalid Type Byte '\xb5'

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3463]
I noticed following exceptions in twistd.log 
```
2017-07-19 22:02:51-0700 [Broker,0,17.198.216.49] The client selected a protocol the server didn't suggest and doesn't know: disconnecting.
2017-07-19 22:02:51-0700 [Broker,0,17.198.216.49] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
            return self._dataReceived(data)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib64/python2.7/site-packages/twisted/spread/banana.py", line 246, in dataReceived
            raise NotImplementedError(("Invalid Type Byte %r" % (typebyte,)))
        exceptions.NotImplementedError: Invalid Type Byte '\xb5'
...
...

2017-07-19 22:03:03-0700 [-] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x910e368>
2017-07-19 22:04:05-0700 [Broker,6,17.198.216.49] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
            return self._dataReceived(data)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib64/python2.7/site-packages/twisted/spread/banana.py", line 246, in dataReceived
            raise NotImplementedError(("Invalid Type Byte %r" % (typebyte,)))
        exceptions.NotImplementedError: Invalid Type Byte '\xde'
...
...
2017-07-19 22:04:05-0700 [Broker,8,17.198.216.49] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
            return self._dataReceived(data)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib64/python2.7/site-packages/twisted/spread/banana.py", line 246, in dataReceived
            raise NotImplementedError(("Invalid Type Byte %r" % (typebyte,)))
        exceptions.NotImplementedError: Invalid Type Byte '\xff'
```

**Comment by tardyp** [comment]
We would need a little bit more correlation.
This comes from the perspective broker protocol that is used for worker protocol, and for try schedulers. 
The error may mean somebody is using the pb port for something else as expected.
a corruption of a stream is also a possibility, but I doubt it.

We need to understand which condition is triggering those errors in order to help.
Who is connecting? do they have the decent version of twisted?

**Comment by djmitche** [comment]
I'm guessing that someone is making a HTTPS connection to the PB port - either misconfiguration or a portscan.

**Comment by rvanlaar** [comment]
We encountered the same problem. The PB port happened to be open for the world. After these errors it won't pick up new builds.

**Comment by martin-lueders** [comment]
We have the same messaged. The IP from which the connections come is a security scanner of the network we are in. We don't want to block this, as it might reveal useful security issues. The question is, whether there is anything we can do from the buildbot configuration side to avoid these messages cluttering the twistd. log.
