### ISSUE TITLE
exceptions.IndexError: list index out of range

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3464]
I noticed following exception in twistd.log

Seems like it is coming from https://git.io/v7kkL  (buildbot/process/buildstep.py line 463). I wonder how can self.results have a value outside the range of Results (https://git.io/vQShL)

```
2017-07-14 00:26:34-0700 [-] from debounced function:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/buildbot/util/debounce.py", line 89, in stop
            self.invoke()
          File "/usr/lib/python2.7/site-packages/buildbot/util/debounce.py", line 70, in invoke
            d = defer.maybeDeferred(self.function)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 483, in updateSummary
            summary = yield self.getResultSummary()
          File "steps.py", line 731, in getResultSummary
            return super(Build, self).getResultSummary()
          File "/usr/lib/python2.7/site-packages/buildbot/steps/shell.py", line 192, in getResultSummary
            return super(ShellCommand, self).getResultSummary()
          File "/usr/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 463, in getResultSummary
            stepsumm += u' (%s)' % Results[self.results]
        exceptions.IndexError: list index out of range

2017-07-14 00:26:34-0700 [-] releaseLocks(Build(is_trybot=True, merge_archive='archive.tar.gz')): []
2017-07-14 00:26:34-0700 [-] <Build Tech-Production-TryBot number:2 results:success>.buildException
2017-07-14 00:26:34-0700 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/process/build.py", line 536, in stepDone
            summary = yield step.getBuildResultSummary()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 469, in getBuildResultSummary
            summary = yield self.getResultSummary()
          File "steps.py", line 731, in getResultSummary
            return super(Build, self).getResultSummary()
          File "/usr/lib/python2.7/site-packages/buildbot/steps/shell.py", line 192, in getResultSummary
            return super(ShellCommand, self).getResultSummary()
          File "/usr/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 463, in getResultSummary
            stepsumm += u' (%s)' % Results[self.results]
        exceptions.IndexError: list index out of range

2017-07-14 00:26:34-0700 [-]  <Build Tech-Production-TryBot number:2 results:success>: build finished

```

**Comment by tardyp** [comment]
I'd say buildstep.py+463 should use statusToString in order to correctly manage the error.

but also, probably the root cause comes from a custom step which does not use an existing status code.

**Comment by aj062** [comment]
Can a custom evaluateCommand(self, cmd) which might return cmd.rc (and cmd.rc might be large, e.g.: 60) create this issue?
