### ISSUE TITLE
BananaError: Security precaution with 0.9.9-post2 on FreeBSD

### ISSUE THREAD

**Issue by asomers** [buildbot/buildbot#3483]
I'm trying to upgrade FreeBSD's buildbot package to 0.9.9-post2, from 0.9.5.  When I start the pyflakes example project, it appears to work fine; I see log messages about polling the repo and stuff.  But when I try to load the web page in my browser, the twistd.log fills up with this:

```
2017-07-27 23:31:35-0600 [Broker,19,192.168.0.24] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
            return self._dataReceived(data)
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/local/lib/python2.7/site-packages/twisted/spread/banana.py", line 191, in dataReceived
            raise BananaError("Security precaution: more than %d bytes of prefix" % (self.prefixLimit,))
        twisted.spread.banana.BananaError: Security precaution: more than 64 bytes of prefix
```

Any ideas?

**Comment by asomers** [comment]
Ok, it's a PEBKAC.  I was trying to connect to the worker port, not the http port.  A better error message would be nice, but I'm not sure how to add one.

**Comment by seankelly** [comment]
All web hooks should point to the web UI and the WWW port. If you're receiving that error from a web hook, then it's connecting to the PB port and not the WWW port.

**Comment by devrajatverma** [comment]
@seankelly  Thanks

**Comment by devrajatverma** [comment]
@seankelly getting 405 response when receive the hook on web ui

**Comment by seankelly** [comment]
405 is "method not allowed". I'm not seeing anything in Buildbot proper that returns a 405 so you have something configured wrong. I suggest checking the documentation and confirming the configuration in Bitbucket matches what Buildbot expects.
