### ISSUE TITLE
UnicodeEncodeError when sending mails

### ISSUE THREAD

**Issue by chrwen-omicron** [buildbot/buildbot#3499]
Since I've upgraded to 9.10.0, sending mail fails with the following traceback:

```
        Traceback (most recent call last):
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/buildbot/reporters/notifier.py", line 280, in buildMessage
            list(users), patches, logs)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/buildbot/reporters/mail.py", line 270, in sendMessage
            yield self.sendMail(m, all_recipients)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/buildbot/reporters/mail.py", line 334, in sendMail
            requireAuthentication=useAuth)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 2060, in __init__
            SMTPSenderFactory.__init__(self, fromEmail, toEmail, file, deferred, retries, timeout)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1897, in __init__
            _email = _email.encode('ascii')
        exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 8: ordinal not in range(128)
```

I'm using Buildbot 0.9.10 with Twisted 17.5.0 and Python 2.7.12.

**Comment by rodrigc** [comment]
Looks like one of your recipient e-mail addresses as a *ä* character in the user's name, or in the e-maill address itself.
One quick workaround is to use an e-mail address with only ascii characters in it.

**Comment by rodrigc** [comment]
Can you try this patch? 
https://github.com/buildbot/buildbot/pull/3501

**Comment by chrwen-omicron** [comment]
Now I get a different error:

```
        Traceback (most recent call last):
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
            return self._dataReceived(data)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
            self._flushReceiveBIO()
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
            ProtocolWrapper.dataReceived(self, bytes)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
            self.wrappedProtocol.dataReceived(data)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
            why = self.lineReceived(line)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 995, in lineReceived
            why = self._okresponse(self.code, b'\n'.join(self.resp))
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1044, in smtpState_to
            return self.smtpState_toOrData(0, b'')
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1062, in smtpState_toOrData
            self.sendLine(b'RCPT TO:' + quoteaddr(self.lastAddress))
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 179, in quoteaddr
            res = email.utils.parseaddr(addr)
          File "/usr/lib/python2.7/email/utils.py", line 214, in parseaddr
            addrs = _AddressList(addr).addresslist
          File "/usr/lib/python2.7/email/_parseaddr.py", line 457, in __init__
            self.addresslist = self.getaddrlist()
          File "/usr/lib/python2.7/email/_parseaddr.py", line 217, in getaddrlist
            while self.pos < len(self.field):
        exceptions.TypeError: object of type 'module' has no len()
```

**Comment by rodrigc** [comment]
@chrwen-omicron That's a known issue with Twisted: https://stackoverflow.com/questions/44580929/buildbot-mailnotifier-error

Can you run Twisted trunk by doing:

```
python -m pip install --upgrade git+https://github.com/twisted/twisted
```

**Comment by chrwen-omicron** [comment]
Back to the start, this time it seems to be the address:

```
        Traceback (most recent call last):
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
            return self._dataReceived(data)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
            self._flushReceiveBIO()
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
            ProtocolWrapper.dataReceived(self, bytes)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
            self.wrappedProtocol.dataReceived(data)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
            why = self.lineReceived(line)
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 996, in lineReceived
            why = self._okresponse(self.code, b'\n'.join(self.resp))
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 1063, in smtpState_toOrData
            self.sendLine(b'RCPT TO:' + quoteaddr(self.lastAddress))
          File "/home/buibot00/venv/bb_0.9.x/local/lib/python2.7/site-packages/twisted/mail/smtp.py", line 178, in quoteaddr
            addr = addr.decode('ascii')
        exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
```

**Comment by rodrigc** [comment]
@chrwen-omicron can you provide the exact *from address* and *recipients* that you are specifying?  I need this to create a proper test case to test this.

**Comment by chrwen-omicron** [comment]
@rodrigc I can give you a similar example. My configuration gets its changes from a GitLab instance, the Author looks like 'John Doé <john.doe@example.com>' or 'Jöhn Doe <joehn.doe@example.com>'. That's also what I see in the twisted.log.

**Comment by rodrigc** [comment]
For now, if you can remove all non-ASCII characters from your addresses, i.e. just use 'john.doe@example.com' or 'joehn.doe@example.com', that should work around the problem.
This needs to be fixed in Twisted: https://twistedmatrix.com/trac/ticket/9250

**Comment by tardyp** [comment]
maybe we can just fix the mail reporter to automatically convert the email address to contain just the address (not the name, which might have to be encoded)

**Comment by rodrigc** [comment]
I don't think it's worth doing that.  I think it is just better to fix the code in Twisted.

**Comment by rodrigc** [comment]
I have an initial patch here: https://github.com/twisted/twisted/compare/9250-rodrigc-mail
It isn't fully working yet, because on this line:
https://github.com/twisted/twisted/blob/9250-rodrigc-mail/src/twisted/mail/smtp.py#L192

there is a regular expression which restricts the address characters to those specified in RFC 5322's *atext*:
https://tools.ietf.org/html/rfc5322#section-3.2.3 

In RFC 6532, *atext* was extended:
https://tools.ietf.org/html/rfc6532#section-3.2

Any idea how to expand the regex in Twisted to support RFC 6532?  
There is an example here:
https://tools.ietf.org/html/draft-seantek-mail-regexen-00#section-3.1.1

I'm not an expert on regex's, especially with Unicode. :)

**Comment by rodrigc** [comment]
Well, I gave it a shot here:
https://github.com/twisted/twisted/commit/bb595fa4934425c3294bd6a5d82ca1df566c158f
and my unit test passes....

**Comment by rodrigc** [comment]
@chrwen-omicron I made an initial patch to Twisted.  In your buildbot environment, can you install Twisted from my branch:

```
python -m pip install --upgrade git+https://github.com/twisted/twisted@9250-rodrigc-mail
```

and try again?

**Comment by chrwen-omicron** [comment]
Looks good now, at least I don't see any errors in the log and I'm receiving mails.

**Comment by tardyp** [comment]
@rodrigc can you make a PR in twisted with your 9250 fix, and link it to this bb issue?

**Comment by rodrigc** [comment]
@chrwen-omicron Thanks for your patience through all this, and your willingness to test my patches.  I'll try to push this along on the Twisted side.

**Comment by rodrigc** [comment]
@tardyp done.

**Comment by chrwen-omicron** [comment]
@rodrigc Thanks for your quick help!

**Comment by rodrigc** [comment]
@chrwen-omicron well we aren't done yet until the code gets merged in Twisted, and Twisted does a new release with the fix.  Thanks again for your patience!

**Comment by tardyp** [comment]
thanks @rodrigc and @chrwen-omicron for coop. I'm keeping it open until we get the tw release

**Comment by chrwen-omicron** [comment]
my bad, I thought this will be part of a PR where the required twisted version will be updated

**Comment by tardyp** [comment]
We avoid requiring a too new version of twisted, as it is "only" needed for py3 support, this would make packager work harder.

**Comment by rodrigc** [comment]
@tardyp I think you should remove the py3 label from this issue.
@chrwen-omicron reproduced this problem with py2.  This is a general Unicode encode/decode problem that occurs on both py2 and py3.

**Comment by chrwen-omicron** [comment]
I'm facing this problem now again. The server doesn't support SMTPUTF8, so it falls back to ASCII which results in the unhandled exception described above.
Would it make sense to replace all unicode characters for example with ? when falling back to ASCII?

**Comment by marrak** [comment]
Any update on this?
I have the same problem after applying patch:
[ESMTPSender,client] Server does not support SMTPUTF8 option, switching encoding from utf-8 to ascii
Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f4249452390>
Any solution beyond workaround by replacing chracters to ascii?
