### ISSUE TITLE
UnicodeDecodeError while sending email for patches containing non-ASCII characters

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3503]
buildbot is configured to send email which is working fine. Once in a while it fails to send email and has following error in the logs:

2017-08-08 19:46:33-0700 [-] Unhandled error in Deferred:
2017-08-08 19:46:33-0700 [-] Unhandled Error 
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
        return _inlineCallbacks(None, gen, Deferred())
      File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
        result = g.send(result)
      File "/usr/lib/python2.7/site-packages/buildbot/reporters/mail.py", line 262, in sendMessage
        results, builds, patches, logs) 
      File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
        return _inlineCallbacks(None, gen, Deferred())
    --- <exception caught here> ---
      File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
        result = g.send(result)
      File "/usr/lib/python2.7/site-packages/buildbot/reporters/mail.py", line 210, in createEmail
        a = self.patch_to_attachment(patch, i)
      File "/usr/lib/python2.7/site-packages/buildbot/reporters/mail.py", line 170, in patch_to_attachment
        a = MIMEText(patch['body'].encode(ENCODING), _charset=ENCODING)
    exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1997: ordinal not in range(128)

This seems to happen when the patch have non-ascii characters. buildbot should handle the patches with non-ascii characters properly.

**Comment by rodrigc** [comment]
Can you provide a small example patch file which reproduces the problem?

**Comment by aakashja** [comment]
Will do. The patch I noticed had these characters:  … ’ “ ”

**Comment by aakashja** [comment]
Seems similar to: https://github.com/buildbot/buildbot/pull/3501

**Comment by aakashja** [comment]
Also related to https://github.com/buildbot/buildbot/issues/3448

**Comment by rodrigc** [comment]
Can you provide an attachment of the patch which reproduces the problem?
In this case pasting characters into these github comments isn't ideal because github parses the characters.

**Comment by seankelly** [comment]
Related: #3499. That one links to Twisted trac bug and PR to fix.

**Comment by rodrigc** [comment]
@aakashja what mail server are you specifying in your master.cfg?  Is it a local one at your site,
or one provided by an e-mail provider such as GMail, Hotmail, Yahoo, etc.?
