### ISSUE TITLE
buildbot[bundle] does not install grid-view

### ISSUE THREAD

**Issue by pmatos** [buildbot/buildbot#3507]
While testing another issue, I noticed bundle does not install grid view. Interestingly, I haven't had a problem before on python3.

With `python 2.7.11`, install `buildbot[bundle]`:
```
$ pip install buildbot[bundle]==0.9.10
Collecting buildbot[bundle]==0.9.10
  Using cached buildbot-0.9.10-py2.py3-none-any.whl
Collecting Jinja2>=2.1 (from buildbot[bundle]==0.9.10)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting sqlalchemy>=0.8.0 (from buildbot[bundle]==0.9.10)
  Using cached SQLAlchemy-1.1.13.tar.gz
Collecting zope.interface>=4.1.1 (from buildbot[bundle]==0.9.10)
  Using cached zope.interface-4.4.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting autobahn>=0.16.0 (from buildbot[bundle]==0.9.10)
  Using cached autobahn-17.7.1-py2.py3-none-any.whl
Collecting sqlalchemy-migrate>=0.9 (from buildbot[bundle]==0.9.10)
  Using cached sqlalchemy_migrate-0.11.0-py2-none-any.whl
Collecting python-dateutil>=1.5 (from buildbot[bundle]==0.9.10)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=8.0 in ./venv/lib/python2.7/site-packages (from bui
Collecting PyJWT (from buildbot[bundle]==0.9.10)
  Using cached PyJWT-1.5.2-py2.py3-none-any.whl
Collecting txaio>=2.2.2 (from buildbot[bundle]==0.9.10)
  Using cached txaio-2.8.1-py2.py3-none-any.whl
Collecting Twisted>=14.0.1 (from buildbot[bundle]==0.9.10)
Collecting future (from buildbot[bundle]==0.9.10)
Collecting buildbot-waterfall-view==0.9.10; extra == "bundle" (from buildbot[bundle]==0.9.10)
  Using cached buildbot_waterfall_view-0.9.10-py2.py3-none-any.whl
Collecting buildbot-console-view==0.9.10; extra == "bundle" (from buildbot[bundle]==0.9.10)
  Using cached buildbot_console_view-0.9.10-py2.py3-none-any.whl
Collecting buildbot-worker==0.9.10; extra == "bundle" (from buildbot[bundle]==0.9.10)
  Using cached buildbot_worker-0.9.10-py2.py3-none-any.whl
Collecting buildbot-www==0.9.10; extra == "bundle" (from buildbot[bundle]==0.9.10)
  Using cached buildbot_www-0.9.10-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.1->buildbot[bundle]==0.9.10)
Collecting six>=1.10.0 (from autobahn>=0.16.0->buildbot[bundle]==0.9.10)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting sqlparse (from sqlalchemy-migrate>=0.9->buildbot[bundle]==0.9.10)
  Using cached sqlparse-0.2.3-py2.py3-none-any.whl
Collecting decorator (from sqlalchemy-migrate>=0.9->buildbot[bundle]==0.9.10)
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting Tempita>=0.4 (from sqlalchemy-migrate>=0.9->buildbot[bundle]==0.9.10)
Collecting pbr>=1.8 (from sqlalchemy-migrate>=0.9->buildbot[bundle]==0.9.10)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting constantly>=15.1 (from Twisted>=14.0.1->buildbot[bundle]==0.9.10)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from Twisted>=14.0.1->buildbot[bundle]==0.9.10)
  Using cached hyperlink-17.3.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from Twisted>=14.0.1->buildbot[bundle]==0.9.10)
  Using cached Automat-0.6.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from Twisted>=14.0.1->buildbot[bundle]==0.9.10)
  Using cached incremental-17.5.0-py2.py3-none-any.whl
Collecting attrs (from Automat>=0.3.0->Twisted>=14.0.1->buildbot[bundle]==0.9.10)
  Using cached attrs-17.2.0-py2.py3-none-any.whl
Building wheels for collected packages: sqlalchemy
  Running setup.py bdist_wheel for sqlalchemy ... done
  Stored in directory: /home/pmatos/.cache/pip/wheels/f0/50/ca/3cb6e78527eb05e180d19632343ee14
Successfully built sqlalchemy
Installing collected packages: MarkupSafe, Jinja2, sqlalchemy, zope.interface, six, txaio, autita, pbr, sqlalchemy-migrate, python-dateutil, PyJWT, constantly, hyperlink, attrs, Automat, ildbot-waterfall-view, buildbot-console-view, buildbot-worker, buildbot-www, buildbot
Successfully installed Automat-0.6.0 Jinja2-2.9.6 MarkupSafe-1.0 PyJWT-1.5.2 Tempita-0.5.2 Twin-17.7.1 buildbot-0.9.10 buildbot-console-view-0.9.10 buildbot-waterfall-view-0.9.10 buildbot-0 constantly-15.1.0 decorator-4.1.2 future-0.16.0 hyperlink-17.3.0 incremental-17.5.0 pbr-3.1..0 sqlalchemy-1.1.13 sqlalchemy-migrate-0.11.0 sqlparse-0.2.3 txaio-2.8.1 zope.interface-4.4.2
```

Create master:
```
$ buildbot create-master master
mkdir /home/pmatos/tmp/bb-2/master
creating /home/pmatos/tmp/bb-2/master/master.cfg.sample
creating database (sqlite:///state.sqlite)
buildmaster configured in /home/pmatos/tmp/bb-2/master
```

Use sample config
```
$ mv master/master.cfg.sample master/master.cfg
```

Ensure its ok:
```
$ buildbot checkconfig master
/home/pmatos/tmp/bb-2/venv/lib/python2.7/site-packages/buildbot/config.py:101: ConfigWarning: [0.9.0 and later] `buildbotNetUsageData` is not configured and defaults to basic.
This parameter helps the buildbot development team to understand the installation base.
No personal information is collected.
Only installation software version info and plugin usage is sent.
You can `opt-out` by setting this variable to None.
Or `opt-in` for more information by setting it to "full".

  category=ConfigWarning,
Config file is good!
```

Start:
```
$ buildbot start master
Following twistd.log until startup finished..
The buildmaster startup failed. Please see 'twistd.log' for possible reason.
```

Whoops:
```
$ cat master/twistd.log 
2017-08-10 20:09:32+0200 [-] Loading buildbot.tac...
2017-08-10 20:09:33+0200 [-] Loaded.
2017-08-10 20:09:33+0200 [-] twistd 17.5.0 (/home/pmatos/tmp/bb-2/venv/bin/python2.7 2.7.11) starting up.
2017-08-10 20:09:33+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2017-08-10 20:09:33+0200 [-] Starting BuildMaster -- buildbot.version: 0.9.10
2017-08-10 20:09:33+0200 [-] Loading configuration from '/home/pmatos/tmp/bb-2/master/master.cfg'
2017-08-10 20:09:33+0200 [-] /home/pmatos/tmp/bb-2/venv/lib/python2.7/site-packages/buildbot/config.py:101: buildbot.config.ConfigWarning: [0.9.0 and later] `buildbotNetUsageData` is not configured and defaults to basic.
        This parameter helps the buildbot development team to understand the installation base.
        No personal information is collected.
        Only installation software version info and plugin usage is sent.
        You can `opt-out` by setting this variable to None.
        Or `opt-in` for more information by setting it to "full".

2017-08-10 20:09:33+0200 [-] Setting up database with URL 'sqlite:/state.sqlite'
2017-08-10 20:09:33+0200 [-] setting database journal mode to 'wal'
2017-08-10 20:09:33+0200 [-] adding 1 new change_sources, removing 0
2017-08-10 20:09:33+0200 [-] gitpoller: using workdir '/home/pmatos/tmp/bb-2/master/gitpoller-workdir'
2017-08-10 20:09:34+0200 [-] adding 1 new builders, removing 0
2017-08-10 20:09:34+0200 [-] adding 2 new schedulers, removing 0
2017-08-10 20:09:35+0200 [-] initializing www plugin 'grid_view'
2017-08-10 20:09:35+0200 [-] while starting BuildMaster
        Traceback (most recent call last):
          File "/home/pmatos/tmp/bb-2/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/home/pmatos/tmp/bb-2/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/home/pmatos/tmp/bb-2/venv/lib/python2.7/site-packages/buildbot/util/service.py", line 53, in reconfigServiceWithBuildbotConfig
            yield svc.reconfigServiceWithBuildbotConfig(new_config)
          File "/home/pmatos/tmp/bb-2/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/home/pmatos/tmp/bb-2/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/home/pmatos/tmp/bb-2/venv/lib/python2.7/site-packages/buildbot/www/service.py", line 209, in reconfigServiceWithBuildbotConfig
            self.setupSite(new_config)
          File "/home/pmatos/tmp/bb-2/venv/lib/python2.7/site-packages/buildbot/www/service.py", line 274, in setupSite
            "could not find plugin %s; is it installed?" % (key,))
        exceptions.RuntimeError: could not find plugin grid_view; is it installed?

2017-08-10 20:09:35+0200 [-] BuildMaster startup failed
2017-08-10 20:09:35+0200 [-] Initiating clean shutdown
2017-08-10 20:09:35+0200 [-] No running jobs, starting shutdown immediately
2017-08-10 20:09:35+0200 [-] BuildMaster is stopped
2017-08-10 20:09:35+0200 [-] Main loop terminated.
2017-08-10 20:09:35+0200 [-] Server Shut Down.
```

Lets be explicit:
```
$ pip install buildbot-grid-view==0.9.10
Collecting buildbot-grid-view==0.9.10
  Downloading buildbot_grid_view-0.9.10-py2.py3-none-any.whl (644kB)
    100% |████████████████████████████████| 645kB 1.1MB/s 
Installing collected packages: buildbot-grid-view
Successfully installed buildbot-grid-view-0.9.10
```

Try again
```
$ buildbot start master
Following twistd.log until startup finished..
The buildmaster appears to have (re)started correctly.
```

yay!

**Comment by tardyp** [comment]
fixed by https://github.com/buildbot/buildbot/pull/3494
