### ISSUE TITLE
[0.9.10]: SVN.purge fails when modified files contain non-ascii characters

### ISSUE THREAD

**Issue by cmumford** [buildbot/buildbot#3576]
Version info:

* Python version: 2.7.9
* Buildbot version: 0.9.10
* Twisted version: 17.5.0
* Client: macOS Sierra

I have a master configuration with the following:

```python
steps.SVN(name="SVN Source",                                                                                                                  
          repourl="http://the.host.com/svn/repository",                                                            
          mode='full', method='fresh')
```

with a modified file as so:

```xml
<entry
   path="Path/To/Content/Developers/François">
<wc-status
   item="unversioned"
   props="none">
</wc-status>
</entry>
```

Fails as so:

```
Traceback (most recent call last):
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 575, in startStep
    self.results = yield self.run()
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 705, in run
    results = yield self._start_deferred
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/steps/source/svn.py", line 131, in mode_full
    yield self.fresh()
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/build/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot/steps/source/svn.py", line 356, in parseAndRemove
    filename = self.workdir + '/' + str(filename)
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u0327' in position 42: ordinal not in range(128)

```

**Comment by tardyp** [comment]
@cmumford can you please try the fix in #3579 ?

**Comment by cmumford** [comment]
Verified - thanks for the quick fix.

**Comment by seankelly** [comment]
I closed this before the PR was actually merged so reopening.
