### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by pmatos** [buildbot/buildbot#3608]
In bb 0.9.11 I just noticed a new failure which I not encountered before:

```
2017-09-11 13:20:11+0200 [_GenericHTTPChannelProtocol,0,127.0.0.1] while decoding JWT session
        Traceback (most recent call last):
          File "/home/pmatos/.pyenv/versions/3.6.2/envs/gcc-buildbot/lib/python3.6/site-packages/twisted/web/server.py", line 442, in getSession
            session = self.site.getSession(sessionCookie)
          File "/home/pmatos/.pyenv/versions/3.6.2/envs/gcc-buildbot/lib/python3.6/site-packages/buildbot/www/service.py", line 172, in getSession
            return BuildbotSession(self, uid)
          File "/home/pmatos/.pyenv/versions/3.6.2/envs/gcc-buildbot/lib/python3.6/site-packages/buildbot/www/service.py", line 74, in __init__
            self._fromToken(token)
          File "/home/pmatos/.pyenv/versions/3.6.2/envs/gcc-buildbot/lib/python3.6/site-packages/buildbot/www/service.py", line 87, in _fromToken
            log.err(e, "while decoding JWT session")
        --- <exception caught here> ---
          File "/home/pmatos/.pyenv/versions/3.6.2/envs/gcc-buildbot/lib/python3.6/site-packages/buildbot/www/service.py", line 83, in _fromToken
            decoded = jwt.decode(token, self.site.session_secret, algorithms=[SESSION_SECRET_ALGORITHM])
          File "/home/pmatos/.pyenv/versions/3.6.2/envs/gcc-buildbot/lib/python3.6/site-packages/jwt/api_jwt.py", line 78, in decode
            jwt, key=key, algorithms=algorithms, options=options, **kwargs
          File "/home/pmatos/.pyenv/versions/3.6.2/envs/gcc-buildbot/lib/python3.6/site-packages/jwt/api_jws.py", line 140, in decode
            key, algorithms)
          File "/home/pmatos/.pyenv/versions/3.6.2/envs/gcc-buildbot/lib/python3.6/site-packages/jwt/api_jws.py", line 207, in _verify_signature
            raise DecodeError('Signature verification failed')
        jwt.exceptions.DecodeError: Signature verification failed
```

What is this?

**Comment by hir12111** [comment]
I think it's because you restarted Buildbot but your browser kept the same session token (in the cookies).
When Buildbot starts, it creates a new secret so the signature changes and your session is no longer valid (it is not able to decode it)

**Comment by pmatos** [comment]
@hir2111 might be. Haven't seen the issue again. Lets assume that was the case.

@tardyp what do you think? Shall I close this or is it worth some investigation?

**Comment by tardyp** [comment]
The secret for signature is stored in the db. So it get reinitialized only
if you blow up the DB.

**Comment by hir12111** [comment]
Sorry about my mistake, I got that error a long time ago and I thought of that but I was also playing with the db. I guess the easiest way to reproduce it is creating two different buildbot configurations.

**Comment by pmatos** [comment]
@tardyp blowing up the db doesn't sound like a good idea. But then, if that's the case I don't understand what secret is this because then @hir12111 explanation for the issue doesn't make sense anymore. What's this secret?

**Comment by tardyp** [comment]
The Buildbot authentication is now storing the authentication information in a cookie, and attached to your browser. To make sure that the cookie cannot be tempered, it is signed with a secret key that is unique to the Buildbot cluster and stored in the DB. This method is known as JWT (https://jwt.io/).

The error that you are seeing means that there is a browser who sent a JWT cookie, signed with a different key, probably because the DB was reset in between the two connections, or that you started another bot on the same machine.

This error is logged as this might be a sign somebody is doing something nasty. In that failure case Buildbot is just ignoring that JWT and restart the authentication process from scratch.

**Comment by rodrigc** [comment]
I'm seeing the same problem in a  new system I am trying to set up buildbot in.
@tardyp when you mentioned *or that you started another bot on the same machine*, what are you referring to?  Is that starting another buildbot master on the same machine, or buildbot worker?

**Comment by tardyp** [comment]
@rodrigc I tried to improve my comment in order to make it more clear. I am not sure how to improve it further.

**Comment by rodrigc** [comment]
Thanks, your clarification helped, and I now understand

**Comment by WayneKeenan** [comment]
perhaps lessen the noise and instead of a full stack trace just emit a single line warning line in the log?

**Comment by tardyp** [comment]
I am not sure there is a need for such a serious warning, even for prod, as it is much more likely that the cookie expired, than it is a mitm. 
Probably we should differenciate when the warning is because of cookie expiration or because of signature failure.
I agree that the stack trace is not very useful

**Comment by ynezz** [comment]
FYI it's still polluting logs in 3.0.0.

**Comment by tardyp** [comment]
@ynezz what is the occurence rate? For me any large occurence rate which would qualify for "pollution" would be a symptom of a configuration issue.

I think we can accept a patch for a single line warning though

**Comment by lms-jk** [comment]
This issue got duplicated by #6872. Since #6872 is resolved, this issue should probably be closed.

**Comment by ynezz** [comment]
Yep, not seeing this log splat anymore.
