### ISSUE TITLE
py3: buildbot 0.9.11 breaks import plugins 

### ISSUE THREAD

**Issue by pmatos** [buildbot/buildbot#3616]
Apologies for the cryptic title, however couldn't think of a better one.

I have created a standalone file to import from my master.cfg which has a renderer to use to `steps.SetProperties`:
```python
from buildbot.plugins import *

@util.renderer
def fetch_dejagnu_results(builddir):
    return None
```

I want to test this in Python and so I do:
```
$ python lib/dejagnu.py 
Traceback (most recent call last):
  File "lib/dejagnu.py", line 2, in <module>
    from buildbot.plugins import *
  File "/home/pmatos/.pyenv/versions/gcc-buildbot/lib/python3.6/site-packages/buildbot/plugins/__init__.py", line 20, in <module>
    from buildbot import statistics
  File "/home/pmatos/.pyenv/versions/gcc-buildbot/lib/python3.6/site-packages/buildbot/statistics/__init__.py", line 16, in <module>
    from buildbot.statistics.capture import CaptureBuildDuration
  File "/home/pmatos/.pyenv/versions/gcc-buildbot/lib/python3.6/site-packages/buildbot/statistics/capture.py", line 23, in <module>
    from twisted.internet import defer
  File "/home/pmatos/.pyenv/versions/gcc-buildbot/lib/python3.6/site-packages/twisted/internet/defer.py", line 29, in <module>
    from twisted.python.compat import cmp, comparable
  File "/home/pmatos/.pyenv/versions/gcc-buildbot/lib/python3.6/site-packages/twisted/python/__init__.py", line 11, in <module>
    from .compat import unicode
  File "/home/pmatos/.pyenv/versions/gcc-buildbot/lib/python3.6/site-packages/twisted/python/compat.py", line 622, in <module>
    from http import cookiejar as cookielib
  File "/home/pmatos/.pyenv/versions/3.6.2/lib/python3.6/http/cookiejar.py", line 35, in <module>
    import urllib.parse, urllib.request
  File "/home/pmatos/.pyenv/versions/3.6.2/lib/python3.6/urllib/request.py", line 86, in <module>
    import email
  File "/home/pmatos/Projects/gcc-buildbot/lib/email.py", line 3, in <module>
    import smtplib
  File "/home/pmatos/.pyenv/versions/3.6.2/lib/python3.6/smtplib.py", line 47, in <module>
    import email.utils
ModuleNotFoundError: No module named 'email.utils'; 'email' is not a package
```

I really don't understand what's happening but I suspect it has to do with the trickery buildbot employs during `from buildbot.plugins import *`

**Comment by tardyp** [comment]
Hi,
I think, it rather comes from your import PYTHON_PATH

your gcc-buildbot defines an 'email' module, which you probably put on your python path. 
this clashes with python's email module, where smtplib is supposed to fine email.utils.

**Comment by pmatos** [comment]
That is correct and also rather embarrassing. Therefore I am closing this and assuming it never happened.
Once again thanks for your help and sorry for wasting your time.
