### ISSUE TITLE
AttributeError in slave twistd.log: 'str' object has no attribute '__module__'

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3626]
Noticed this exception in twistd.log on slave (running Buildslave version: 0.8.12, twistd v16.4.1). Master running Buildbot 0.9.11.

Can this issue be due to slave running old package (buildslave instead of buildbot-worker) and master running latest Buildbot 0.9?

```
2017-09-16 19:24:53-0700 [Broker,client] SlaveBuilder._ackFailed: sendComplete
2017-09-16 19:24:53-0700 [Broker,client] Unhandled Error
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
        self._runCallbacks()
      File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/Library/Python/2.7/site-packages/buildslave/bot.py", line 227, in commandComplete
        d = self.remoteStep.callRemote("complete", failure)
      File "/Library/Python/2.7/site-packages/twisted/spread/pb.py", line 343, in callRemote
        _name, args, kw)
    --- <exception caught here> ---
      File "/Library/Python/2.7/site-packages/twisted/spread/pb.py", line 858, in _sendMessage
        netArgs = self.serialize(args, perspective=perspective, method=message)
      File "/Library/Python/2.7/site-packages/twisted/spread/pb.py", line 812, in serialize
        return jelly(object, self.security, None, self)
      File "/Library/Python/2.7/site-packages/twisted/spread/jelly.py", line 1129, in jelly
        return _Jellier(taster, persistentStore, invoker).jelly(object)
      File "/Library/Python/2.7/site-packages/twisted/spread/jelly.py", line 530, in jelly
        sxp.extend(self._jellyIterable(tuple_atom, obj))
      File "/Library/Python/2.7/site-packages/twisted/spread/jelly.py", line 583, in _jellyIterable
        yield self.jelly(item)
      File "/Library/Python/2.7/site-packages/twisted/spread/jelly.py", line 470, in jelly
        return obj.jellyFor(self)
      File "/Library/Python/2.7/site-packages/twisted/spread/flavors.py", line 299, in jellyFor
        state = self.getStateToCopyFor(p)
      File "/Library/Python/2.7/site-packages/twisted/spread/flavors.py", line 267, in getStateToCopyFor
        return self.getStateToCopy()
      File "/Library/Python/2.7/site-packages/twisted/spread/pb.py", line 425, in getStateToCopy
        state['traceback'] = self.getTraceback()
      File "/Library/Python/2.7/site-packages/twisted/python/failure.py", line 533, in getTraceback
        self.printTraceback(file=io, elideFrameworkCode=elideFrameworkCode, detail=detail)
      File "/Library/Python/2.7/site-packages/twisted/python/failure.py", line 594, in printTraceback
        w("%s: %s\n" % (reflect.qual(self.type),
      File "/Library/Python/2.7/site-packages/twisted/python/reflect.py", line 359, in qual
        return clazz.__module__ + '.' + clazz.__name__
    exceptions.AttributeError: 'str' object has no attribute '__module__'

2017-09-16 19:30:28-0700 [-] sending app-level keepalive
2017-09-16 19:40:28-0700 [-] sending app-level keepalive
```

**Comment by seankelly** [comment]
Is the master running Python 2.7 too?

**Comment by aakashja** [comment]
Yes.
Master is running: Python: 2.7.5, Twisted: 17.5.0, Buildbot: 0.9.11

**Comment by seankelly** [comment]
0.9.x masters have supported 0.8.x workers but I wonder if that broke in 0.9.11.

**Comment by tardyp** [comment]
It looks like there is a failure to dump the failure...

      File "/Library/Python/2.7/site-packages/buildslave/bot.py", line 227, in commandComplete
        d = self.remoteStep.callRemote("complete", failure)

means that there is a remote command that fails with a failure.

      File "/Library/Python/2.7/site-packages/twisted/spread/pb.py", line 425, in getStateToCopy
        state['traceback'] = self.getTraceback()

means that twisted fails to dump that failure, because the failure.type is a string instead of the expected class type.

You can try to patch /Library/Python/2.7/site-packages/twisted/python/reflect.py to say
```
if isinstance(clazz, str):
     return clazz
```
and the we may see what is the original failure.

Also, I see that you are not using virtualenv. We have often see people having issues by not using virtualenv, by example conflicting python packages or half installed packaged. I really suggest you re-try after installing buildbot slave with virtualenv.

**Comment by p12tic** [comment]
Closing because we haven't seen this bug to repeat and there's not enough information in the bug report to reproduce it.
