### ISSUE TITLE
Exception buildslave.exceptions.AbandonChain

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3632]
Noticed following exception in twistd.log on master (buildbot v0.9.11), (buildslaves running version 0.8.12):

```
2017-09-19 08:50:32-0700 [-] BuildStep.failed; traceback follows
        Traceback (most recent call last): 
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 500, in errback
            self._startRunCallbacks(fail)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 705, in run 
            results = yield self._start_deferred
        buildbot.process.remotecommand.RemoteException: buildslave.exceptions.AbandonChain: -1
        Traceback (most recent call last): 
        Failure: buildslave.exceptions.AbandonChain: -1
```

**Comment by rodrigc** [comment]
That exception means that one of the RunProcess steps failed on your system and returned -1.
It would be useful to know which step failed and how it failed.

**Comment by rodrigc** [comment]
You need to look in the twistd.log on the worker/slave to see what command failed.
