### ISSUE TITLE
GitLabStatusPush Reporter fails to comment

### ISSUE THREAD

**Issue by JonasToth** [buildbot/buildbot#3651]
Hello everybody,

I am currently setting up a buildbot instance an configure it in order to integrate nice with Gitlab. My goal is, to comment on commits when buildbot does its job, `GitlabStatusPush` ftw!

The configuration in that respect is as follows.
```
GitlabReporter = reporters.GitLabStatusPush(token=util.Interpolate('%(secret:gitlab_token)s'), 
                                            context='continuous-integration/buildbot', 
                                            baseURL='https://gitlab.hrz.tu-chemnitz.de')

c['services'] = []
c['services'].append(GitlabReporter)
``` 

I have setup a testproject for experimentation and buildbot tries to do its thing, but i get the following exception (for reporting the begin and end of a build):

```
2017-09-25 11:39:00+0200 [-] while invoking <bound method GitLabStatusPush.buildFinished of <buildbot.reporters.gitlab.GitLabStatusPush object at 0x7f4a682c0dd0>>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
	    _inlineCallbacks(r, g, deferred)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/reporters/http.py", line 84, in getMoreInfoAndSend
	    yield self.send(build)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/reporters/gitlab.py", line 144, in send
	    proj_id = yield self.getProjectId(sourcestamp)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/reporters/gitlab.py", line 113, in getProjectId
	    repo=project_full_name, **proj))
	exceptions.KeyError: 'message'
	
2017-09-25 11:39:00+0200 [-] while invoking <bound method GitLabStatusPush.buildFinished of <buildbot.reporters.gitlab.GitLabStatusPush object at 0x7f4a682c0dd0>>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
	    _inlineCallbacks(r, g, deferred)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/reporters/http.py", line 84, in getMoreInfoAndSend
	    yield self.send(build)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/reporters/gitlab.py", line 144, in send
	    proj_id = yield self.getProjectId(sourcestamp)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/reporters/gitlab.py", line 113, in getProjectId
	    repo=project_full_name, **proj))
	exceptions.KeyError: 'message'
```

I tested the api manually with curl and firefox, and api access works! I could even comment with curl without problems with APIv3 and v4.

Could you help me out on this one?

All the best, Jonas

**Comment by JonasToth** [comment]
It currently looks like the requests to the Gitlab-instance were double encoded, which results in a bad repository name landing at gitlab at has nothing to do with buildbot, but with the server configuration.

I contacted the admin and will update this issue with the link to the solution if possible.

**Comment by JonasToth** [comment]
The problem was indeed the configuration of the webserver.
Please see the following links for guidence if this happens to you as well:

https://docs.gitlab.com/ce/api/commits.html#post-comment-to-commit and https://docs.gitlab.com/ce/api/README.html#namespaced-path-encoding
Here are examples how to test the API with `curl` directly. You need to setup your/a private token!

https://github.com/gitlabhq/gitlabhq/issues/8290 the last for 4 comments(maybe more above) and https://github.com/clns/go-gitlab/commit/d5e2e8d0d0c63eebc7450d4e9a8db59354ce2e5c

That explain the situation for the webserver.
