### ISSUE TITLE
PatchParameter is not playing nice with Triggers

### ISSUE THREAD

**Issue by btaidm** [buildbot/buildbot#3656]
Currently the PatchParameter is not playing nice with Triggers. It is throwing an AssertionError.

It is happening in the `TempSourceStamp` class in buildrequest.py in the assertion in the `asDict` function. I believe it is because the `patch_body` is not a unicode string. I am not sure if it the filefield failing to give unicode or something else.

**Comment by rodrigc** [comment]
Can you post a stack trace from your logs?

**Comment by btaidm** [comment]
I added some additional log outputs to help with debugging.

```
2017-09-27 13:01:17-0400 [-] level: <type 'int'>
2017-09-27 13:01:17-0400 [-] body: <type 'str'>
2017-09-27 13:01:17-0400 [-] subdir: <type 'unicode'>
2017-09-27 13:01:17-0400 [-] author: <type 'unicode'>
2017-09-27 13:01:17-0400 [-] comment: <type 'unicode'>
2017-09-27 13:01:17-0400 [-] BuildStep.failed; traceback follows
        Traceback (most recent call last):
          File "/home/bradt/repos/buildbot_travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/home/bradt/repos/buildbot_travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/home/bradt/repos/buildbot_travis/buildbot_travis/steps/spawner.py", line 56, in run
            rv = yield Trigger.run(self)
          File "/home/bradt/repos/buildbot_travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/home/bradt/repos/buildbot_travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/home/bradt/repos/buildbot_travis/sandbox/lib/python2.7/site-packages/buildbot/steps/trigger.py", line 264, in run
            ss_for_trigger = self.prepareSourcestampListForTrigger()
          File "/home/bradt/repos/buildbot_travis/sandbox/lib/python2.7/site-packages/buildbot/steps/trigger.py", line 172, in prepareSourcestampListForTrigger
            ss_for_trigger[ss.codebase] = ss.asDict()
          File "/home/bradt/repos/buildbot_travis/sandbox/lib/python2.7/site-packages/buildbot/process/buildrequest.py", line 145, in asDict
            ), result
        exceptions.AssertionError: {'codebase': u'BuildbotTesting', 'repository': u'https://gitea.engineering.signatureresearchinc.com/tbradt/buildbot-testing.git', 'patch_comment': u'', 'patch_level': 1, 'project': u'', 'patch_body': 'diff --git a/Makefile b/Makefile\nindex 30fbbb7..9c0c1de 100644\n--- a/Makefile\n+++ b/Makefile\n@@ -5,4 +5,5 @@ default:\n \tsleep 10\n \techo "another new default..."\n \twhoami\n+\t@echo "This is a test"\n \n', 'branch': u'', 'patch_author': u'', 'patch_subdir': u'.', 'revision': u''}
```

**Comment by rodrigc** [comment]
Thanks for that stack trace.  It was very helpful.  Yes you are correct, the **patch_body** is not unicode which is why this is failing.  I see in forcesched.py we have this:

```python
class PatchParameter(NestedParameter):
    """A patch parameter contains pre-configure UI for all the needed components for a sourcestamp patch
    """
    columns = 1

    def __init__(self, **kwargs):
        name = kwargs.pop('name', 'patch')
        default_fields = [
            FileParameter('body'),
            IntParameter('level', default=1),
            StringParameter('author', default=""),
            StringParameter('comment', default=""),
            StringParameter('subdir', default=".")
        ]
```

```
class FileParameter(BaseParameter):
    """A parameter which allows to download a whole file and store it as a property or patch
    """
    type = 'file'
    maxsize = 1024 * 1024 * 10  # 10M
```

So it looks like when the patchparameter is read in, it is not being read in as unicode.

I'm not familiar with the code related to parameters, but it you can help debug
the line where the patch parameter is read, I can help come up with a fix.

**Comment by rodrigc** [comment]
Also, if you have the time to set up a separate virtualenv with buildbot running in a Python 3 environment, it would be good to confirm if the problem occurs on Python 3 or not.
But I'll help fix the problem on Python 2 for sure.

**Comment by btaidm** [comment]
It is also happening in python3, except it is returning bytes. This is points at the file being read as raw binary data that happens to have the form of a string.

```
2017-09-28 09:53:42-0400 [-] level: <class 'int'>
2017-09-28 09:53:42-0400 [-] body: <class 'bytes'>
2017-09-28 09:53:42-0400 [-] subdir: <class 'str'>
2017-09-28 09:53:42-0400 [-] author: <class 'str'>
2017-09-28 09:53:42-0400 [-] comment: <class 'str'>
2017-09-28 09:53:42-0400 [-] BuildStep.failed; traceback follows
        Traceback (most recent call last):
          File "/home/bradt/repos/buildbot_travis/sandbox-py3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/home/bradt/repos/buildbot_travis/sandbox-py3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/home/bradt/repos/buildbot_travis/buildbot_travis/steps/spawner.py", line 56, in run
            rv = yield Trigger.run(self)
          File "/home/bradt/repos/buildbot_travis/sandbox-py3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/home/bradt/repos/buildbot_travis/sandbox-py3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/home/bradt/repos/buildbot_travis/sandbox-py3/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 263, in run
            ss_for_trigger = self.prepareSourcestampListForTrigger()
          File "/home/bradt/repos/buildbot_travis/sandbox-py3/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 172, in prepareSourcestampListForTrigger
            ss_for_trigger[ss.codebase] = ss.asDict()
          File "/home/bradt/repos/buildbot_travis/sandbox-py3/lib/python3.6/site-packages/buildbot/process/buildrequest.py", line 145, in asDict
            ), result
        builtins.AssertionError: {'branch': '', 'revision': '', 'repository': 'https://gitea.engineering.signatureresearchinc.com/tbradt/buildbot-testing.git', 'project': '', 'codebase': 'BuildbotTesting', 'patch_level': 1, 'patch_body': b'diff --git a/Makefile b/Makefile\nindex 30fbbb7..9c0c1de 100644\n--- a/Makefile\n+++ b/Makefile\n@@ -5,4 +5,5 @@ default:\n \tsleep 10\n \techo "another new default..."\n \twhoami\n+\t@echo "This is a test"\n \n', 'patch_subdir': '.', 'patch_author': '', 'patch_comment': ''}
```

**Comment by rodrigc** [comment]
Thanks for doing the additional test and providing the debugging output.

**Comment by rodrigc** [comment]
This is a legitimate problem.  Can you provide an example `master.cfg` and a sequence of steps to reproduce the problem?  I'm not familiar with how to reproduce this, so don't know where to fix this
