### ISSUE TITLE
pkg_resources.DistributionNotFound: sqlalchemy-migrate when creating master

### ISSUE THREAD

**Issue by a-baumfalk** [buildbot/buildbot#3660]
I'm, following the tutorial, step "1.1.3 Creating Master". After the installation has finished successfully, I try to create a master as described in the tutorial, but I get the following error:

(sandbox)buildbot@picasso:~/master$ buildbot create-master master
Traceback (most recent call last):
  File "/home/buildbot/master/sandbox/bin/buildbot", line 11, in <module>
    sys.exit(run())
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/buildbot/scripts/runner.py", line 760, in run
    subcommandFunction = reflect.namedObject(subconfig.subcommandFunction)
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 173, in namedObject
    module = namedModule('.'.join(classSplit[:-1]))
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/twisted/python/reflect.py", line 159, in namedModule
    topLevel = __import__(name)
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/buildbot/scripts/create_master.py", line 30, in <module>
    from buildbot.master import BuildMaster
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/buildbot/master.py", line 43, in <module>
    from buildbot.db import connector as dbconnector
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/buildbot/db/connector.py", line 32, in <module>
    from buildbot.db import enginestrategy
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/buildbot/db/enginestrategy.py", line 32, in <module>
    import migrate
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/migrate/__init__.py", line 14, in <module>
    pkg_resources.Requirement.parse('sqlalchemy-migrate')).version
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 209, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/buildbot/master/sandbox/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: sqlalchemy-migrate

**Comment by rodrigc** [comment]
Did you create a virtualenv and follow all the `pip` commands listed in http://docs.buildbot.net/current/tutorial/firstrun.html#creating-a-master ?

Looks like you might have missed a step because not all the necessary packages were installed.

**Comment by a-baumfalk** [comment]
Yes, I followed all the steps. I have python 2.7.3 and my virtualenv contains:

(sandbox)buildbot@picasso:~/master$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
attrs (17.2.0)
autobahn (17.9.3)
Automat (0.6.0)
buildbot (0.9.11)
buildbot-console-view (0.9.11)
buildbot-grid-view (0.9.11)
buildbot-waterfall-view (0.9.11)
buildbot-worker (0.9.11)
buildbot-www (0.9.11)
constantly (15.1.0)
decorator (4.1.2)
distribute (0.6.24)
future (0.16.0)
hyperlink (17.3.1)
incremental (17.5.0)
Jinja2 (2.9.6)
MarkupSafe (1.0)
pbr (3.1.1)
pip (9.0.1)
PyJWT (1.5.3)
python-dateutil (2.6.1)
setuptools (36.5.0)
six (1.11.0)
SQLAlchemy (1.1.14)
sqlalchemy-migrate (0.11.0)
sqlparse (0.2.4)
Tempita (0.5.2)
Twisted (17.9.0)
txaio (2.8.2)
zope.interface (4.4.3)

**Comment by rodrigc** [comment]
That looks like you have all the necessary packages installed.  Very odd.
It looks like you are hitting a similar problem to: https://stackoverflow.com/questions/42392878/python-unable-to-find-sqlalchemy-migrate-in-docker-image

**Comment by rodrigc** [comment]
Can you try to do the following using the python in your virtualenv?:

```
which python
python -V
python -v $(which buildbot) create-master test-master
```

and see if something is failing to import?

**Comment by tardyp** [comment]
Sometimes, virtualenvs get corrupted, did you try to re-run the install with a clean virtualenv?

**Comment by rodrigc** [comment]
Glad you solved it!  These package dependency problems are hard to figure out!
