### ISSUE TITLE
Can't build docs inside make virtualenv

### ISSUE THREAD

**Issue by Frodox** [buildbot/buildbot#3671]
Looks like something broken just now
```
$ history | tail
1229  2017.10.03 16:28:16  git clone https://github.com/buildbot/buildbot.git
 1230  2017.10.03 16:28:32  cd buildbot/
 1231  2017.10.03 16:28:33  ll
 1232  2017.10.03 16:28:39  make virtualenv 
 1233  2017.10.03 16:29:21  source .venv/bin/activate

$ make docs
make -C master/docs
make[1]: Entering directory `/tmp/buildbot/master/docs'
rm -rf _build/*
if command -v towncrier >/dev/null 2>&1 ;\
then \
cd ../../; towncrier --draft |grep  'No significant changes.' || yes n | towncrier ;\
fi
Loading template...
Finding news fragments...
Rendering news fragments...
Traceback (most recent call last):
  File "/tmp/buildbot/.venv/bin/towncrier", line 11, in <module>
    load_entry_point('towncrier==16.12.0', 'console_scripts', 'towncrier')()
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/towncrier/__init__.py", line 36, in _main
    return __main(draft, directory, project_version, project_date)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/towncrier/__init__.py", line 73, in __main
    fragments = split_fragments(fragments, definitions)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/towncrier/_builder.py", line 74, in split_fragments
    ticket, category = parts
ValueError: too many values to unpack
Loading template...
Finding news fragments...
Rendering news fragments...
Traceback (most recent call last):
  File "/tmp/buildbot/.venv/bin/towncrier", line 11, in <module>
    load_entry_point('towncrier==16.12.0', 'console_scripts', 'towncrier')()
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/towncrier/__init__.py", line 36, in _main
    return __main(draft, directory, project_version, project_date)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/towncrier/__init__.py", line 73, in __main
    fragments = split_fragments(fragments, definitions)
  File "/tmp/buildbot/.venv/lib/python2.7/site-packages/towncrier/_builder.py", line 74, in split_fragments
    ticket, category = parts
ValueError: too many values to unpack
make[1]: *** [towncrier] Error 1
make[1]: Leaving directory `/tmp/buildbot/master/docs'
make: *** [docs] Error 2
```

**Comment by seankelly** [comment]
Looks like a problem in towncrier.

**Comment by seankelly** [comment]
What version do you have installed? It appears to be 16.12.0. The latest is 17.8.0, so could you try something newer?

**Comment by Frodox** [comment]
@seankelly 
yes, it was `Version: 16.12.0`.
I updated it to `17.8.0` and now docs builded fine. How do you think, why do I have `16.12.0` after `make virtualenv` ?

**Comment by seankelly** [comment]
Do you have the full log from running `make`? It might be because @tardyp 's towncrier repository is used:
```
virtualenv: $(VENV_NAME)   # usage: make virtualenv VENV_PY_VERSION=python3.4
	@echo now you can type following command  to activate your virtualenv
	@echo . $(VENV_NAME)/bin/activate
	$(PIP) install -e pkg \
		-e 'master[tls,test,docs]' \
		-e 'worker[test]' \
		buildbot_www packaging \
		'git+https://github.com/tardyp/towncrier'
```

**Comment by Frodox** [comment]
Yes, I have:
```shell
$ make virtualenv
virtualenv -p python .venv
Already using interpreter /usr/bin/python
New python executable in .venv/bin/python
Installing setuptools, pip, wheel...done.
.venv/bin/pip install -U pip setuptools
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Collecting setuptools
  Using cached setuptools-36.5.0-py2.py3-none-any.whl
Installing collected packages: pip, setuptools
  Found existing installation: pip 7.1.0
    Uninstalling pip-7.1.0:
      Successfully uninstalled pip-7.1.0
  Found existing installation: setuptools 18.0.1
    Uninstalling setuptools-18.0.1:
      Successfully uninstalled setuptools-18.0.1
Successfully installed pip-9.0.1 setuptools-36.5.0
now you can type following command to activate your virtualenv
. .venv/bin/activate
.venv/bin/pip install -e pkg \
	-e 'master[tls,test,docs]' \
	-e 'worker[test]' \
	buildbot_www packaging \
	'git+https://github.com/tardyp/towncrier'
Collecting git+https://github.com/tardyp/towncrier
  Cloning https://github.com/tardyp/towncrier to /tmp/pip-bwwbkP-build
Obtaining file:///tmp/buildbot/pkg
Obtaining file:///tmp/buildbot/master
Obtaining file:///tmp/buildbot/worker
Collecting buildbot_www
  Using cached buildbot_www-0.9.11-py2.py3-none-any.whl
Collecting packaging
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting Click (from towncrier==16.12.0)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting incremental (from towncrier==16.12.0)
  Using cached incremental-17.5.0-py2.py3-none-any.whl
Collecting jinja2 (from towncrier==16.12.0)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting toml (from towncrier==16.12.0)
Requirement already satisfied: setuptools>=21.2.1 in ./.venv/lib/python2.7/site-packages (from buildbot-pkg==0.9.12.dev136)
Collecting Twisted>=14.0.1 (from buildbot==0.9.12.dev136)
Collecting zope.interface>=4.1.1 (from buildbot==0.9.12.dev136)
  Using cached zope.interface-4.4.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting future (from buildbot==0.9.12.dev136)
Collecting sqlalchemy>=0.8.0 (from buildbot==0.9.12.dev136)
Collecting sqlalchemy-migrate>=0.9 (from buildbot==0.9.12.dev136)
  Using cached sqlalchemy_migrate-0.11.0-py2-none-any.whl
Collecting python-dateutil>=1.5 (from buildbot==0.9.12.dev136)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting txaio>=2.2.2 (from buildbot==0.9.12.dev136)
  Using cached txaio-2.8.2-py2.py3-none-any.whl
Collecting autobahn>=0.16.0 (from buildbot==0.9.12.dev136)
  Using cached autobahn-17.9.3-py2.py3-none-any.whl
Collecting PyJWT (from buildbot==0.9.12.dev136)
  Using cached PyJWT-1.5.3-py2.py3-none-any.whl
Collecting docutils<0.13.0 (from buildbot==0.9.12.dev136)
Collecting sphinx>1.4.0 (from buildbot==0.9.12.dev136)
  Using cached Sphinx-1.6.4-py2.py3-none-any.whl
Collecting sphinxcontrib-blockdiag (from buildbot==0.9.12.dev136)
  Using cached sphinxcontrib_blockdiag-1.5.5-py2.py3-none-any.whl
Collecting sphinxcontrib-spelling (from buildbot==0.9.12.dev136)
Collecting pyenchant (from buildbot==0.9.12.dev136)
Collecting ramlfications (from buildbot==0.9.12.dev136)
  Using cached ramlfications-0.1.9-py2.py3-none-any.whl
Collecting sphinx-jinja (from buildbot==0.9.12.dev136)
  Using cached sphinx_jinja-0.3.0-py2-none-any.whl
Collecting setuptools_trial (from buildbot==0.9.12.dev136)
  Using cached setuptools_trial-0.6.0-py2-none-any.whl
Collecting isort (from buildbot==0.9.12.dev136)
  Using cached isort-4.2.15-py2.py3-none-any.whl
Collecting pylint<1.7.0 (from buildbot==0.9.12.dev136)
  Using cached pylint-1.6.5-py2.py3-none-any.whl
Collecting flake8~=2.6.0 (from buildbot==0.9.12.dev136)
  Using cached flake8-2.6.2-py2.py3-none-any.whl
Collecting treq (from buildbot==0.9.12.dev136)
  Using cached treq-17.8.0-py2.py3-none-any.whl
Collecting txrequests (from buildbot==0.9.12.dev136)
  Using cached txrequests-0.9.5-py2-none-any.whl
Collecting pyjade (from buildbot==0.9.12.dev136)
Collecting boto3 (from buildbot==0.9.12.dev136)
  Using cached boto3-1.4.7-py2.py3-none-any.whl
Collecting moto (from buildbot==0.9.12.dev136)
  Using cached moto-1.1.21-py2.py3-none-any.whl
Collecting txgithub (from buildbot==0.9.12.dev136)
  Using cached txgithub-15.0.0-py2-none-any.whl
Collecting mock>=2.0.0 (from buildbot==0.9.12.dev136)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting lz4 (from buildbot==0.9.12.dev136)
Collecting pyopenssl>=16.0.0 (from buildbot==0.9.12.dev136)
  Using cached pyOpenSSL-17.3.0-py2.py3-none-any.whl
Collecting service_identity (from buildbot==0.9.12.dev136)
  Using cached service_identity-17.0.0-py2.py3-none-any.whl
Collecting idna>=0.6 (from buildbot==0.9.12.dev136)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting pep8 (from buildbot-worker==0.9.12.dev136)
  Using cached pep8-1.7.0-py2.py3-none-any.whl
Collecting six (from packaging)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pyparsing (from packaging)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->towncrier==16.12.0)
Collecting constantly>=15.1 (from Twisted>=14.0.1->buildbot==0.9.12.dev136)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from Twisted>=14.0.1->buildbot==0.9.12.dev136)
  Using cached hyperlink-17.3.1-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from Twisted>=14.0.1->buildbot==0.9.12.dev136)
  Using cached Automat-0.6.0-py2.py3-none-any.whl
Collecting Tempita>=0.4 (from sqlalchemy-migrate>=0.9->buildbot==0.9.12.dev136)
Collecting decorator (from sqlalchemy-migrate>=0.9->buildbot==0.9.12.dev136)
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting sqlparse (from sqlalchemy-migrate>=0.9->buildbot==0.9.12.dev136)
  Using cached sqlparse-0.2.4-py2.py3-none-any.whl
Collecting pbr>=1.8 (from sqlalchemy-migrate>=0.9->buildbot==0.9.12.dev136)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached alabaster-0.7.10-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached Babel-2.5.1-py2.py3-none-any.whl
Collecting imagesize (from sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached imagesize-0.7.1-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting typing; python_version < "3.5" (from sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached typing-3.6.2-py2-none-any.whl
Collecting requests>=2.0.0 (from sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting sphinxcontrib-websupport (from sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached sphinxcontrib_websupport-1.0.1-py2.py3-none-any.whl
Collecting blockdiag>=1.5.0 (from sphinxcontrib-blockdiag->buildbot==0.9.12.dev136)
  Using cached blockdiag-1.5.3-py2.py3-none-any.whl
Collecting jsonref (from ramlfications->buildbot==0.9.12.dev136)
Collecting termcolor (from ramlfications->buildbot==0.9.12.dev136)
Collecting xmltodict (from ramlfications->buildbot==0.9.12.dev136)
  Using cached xmltodict-0.11.0-py2.py3-none-any.whl
Collecting pyyaml (from ramlfications->buildbot==0.9.12.dev136)
Collecting attrs (from ramlfications->buildbot==0.9.12.dev136)
  Using cached attrs-17.2.0-py2.py3-none-any.whl
Collecting markdown2 (from ramlfications->buildbot==0.9.12.dev136)
Collecting pathlib2; python_version == "2.7" (from setuptools_trial->buildbot==0.9.12.dev136)
  Using cached pathlib2-2.3.0-py2.py3-none-any.whl
Collecting astroid<1.5.0,>=1.4.5 (from pylint<1.7.0->buildbot==0.9.12.dev136)
  Using cached astroid-1.4.9-py2.py3-none-any.whl
Collecting configparser; python_version == "2.7" (from pylint<1.7.0->buildbot==0.9.12.dev136)
Collecting backports.functools-lru-cache; python_version == "2.7" (from pylint<1.7.0->buildbot==0.9.12.dev136)
  Using cached backports.functools_lru_cache-1.4-py2.py3-none-any.whl
Collecting mccabe (from pylint<1.7.0->buildbot==0.9.12.dev136)
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle<2.1,>=2.0 (from flake8~=2.6.0->buildbot==0.9.12.dev136)
  Using cached pycodestyle-2.0.0-py2.py3-none-any.whl
Collecting pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.3,>=0.8.1 (from flake8~=2.6.0->buildbot==0.9.12.dev136)
  Using cached pyflakes-1.2.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3->buildbot==0.9.12.dev136)
  Using cached s3transfer-0.1.11-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->buildbot==0.9.12.dev136)
  Using cached jmespath-0.9.3-py2.py3-none-any.whl
Collecting botocore<1.8.0,>=1.7.0 (from boto3->buildbot==0.9.12.dev136)
  Using cached botocore-1.7.21-py2.py3-none-any.whl
Collecting boto>=2.36.0 (from moto->buildbot==0.9.12.dev136)
  Using cached boto-2.48.0-py2.py3-none-any.whl
Collecting werkzeug (from moto->buildbot==0.9.12.dev136)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting pyaml (from moto->buildbot==0.9.12.dev136)
  Using cached pyaml-17.8.0-py2.py3-none-any.whl
Collecting docker>=2.5.1 (from moto->buildbot==0.9.12.dev136)
  Using cached docker-2.5.1-py2.py3-none-any.whl
Collecting backports.tempfile; python_version < "3.3" (from moto->buildbot==0.9.12.dev136)
  Using cached backports.tempfile-1.0rc1-py2-none-any.whl
Collecting cryptography>=2.0.0 (from moto->buildbot==0.9.12.dev136)
  Using cached cryptography-2.0.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cookies (from moto->buildbot==0.9.12.dev136)
  Using cached cookies-2.2.1-py2.py3-none-any.whl
Collecting pytz (from moto->buildbot==0.9.12.dev136)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->buildbot==0.9.12.dev136)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pyasn1 (from service_identity->buildbot==0.9.12.dev136)
  Using cached pyasn1-0.3.6-py2.py3-none-any.whl
Collecting pyasn1-modules (from service_identity->buildbot==0.9.12.dev136)
  Using cached pyasn1_modules-0.1.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.0.0->sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.0.0->sphinx>1.4.0->buildbot==0.9.12.dev136)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting funcparserlib (from blockdiag>=1.5.0->sphinxcontrib-blockdiag->buildbot==0.9.12.dev136)
Collecting webcolors (from blockdiag>=1.5.0->sphinxcontrib-blockdiag->buildbot==0.9.12.dev136)
Collecting Pillow (from blockdiag>=1.5.0->sphinxcontrib-blockdiag->buildbot==0.9.12.dev136)
  Using cached Pillow-4.3.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7"->setuptools_trial->buildbot==0.9.12.dev136)
Collecting lazy-object-proxy (from astroid<1.5.0,>=1.4.5->pylint<1.7.0->buildbot==0.9.12.dev136)
  Using cached lazy_object_proxy-1.3.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting wrapt (from astroid<1.5.0,>=1.4.5->pylint<1.7.0->buildbot==0.9.12.dev136)
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer<0.2.0,>=0.1.10->boto3->buildbot==0.9.12.dev136)
  Using cached futures-3.1.1-py2-none-any.whl
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker>=2.5.1->moto->buildbot==0.9.12.dev136)
Collecting docker-pycreds>=0.2.1 (from docker>=2.5.1->moto->buildbot==0.9.12.dev136)
  Using cached docker_pycreds-0.2.1-py2.py3-none-any.whl
Collecting ipaddress>=1.0.16; python_version < "3.3" (from docker>=2.5.1->moto->buildbot==0.9.12.dev136)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting websocket-client>=0.32.0 (from docker>=2.5.1->moto->buildbot==0.9.12.dev136)
  Using cached websocket_client-0.44.0-py2.py3-none-any.whl
Collecting backports.weakref (from backports.tempfile; python_version < "3.3"->moto->buildbot==0.9.12.dev136)
  Using cached backports.weakref-1.0.post1-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=2.0.0->moto->buildbot==0.9.12.dev136)
  Using cached asn1crypto-0.23.0-py2.py3-none-any.whl
Collecting cffi>=1.7 (from cryptography>=2.0.0->moto->buildbot==0.9.12.dev136)
  Using cached cffi-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34 (from cryptography>=2.0.0->moto->buildbot==0.9.12.dev136)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting olefile (from Pillow->blockdiag>=1.5.0->sphinxcontrib-blockdiag->buildbot==0.9.12.dev136)
Collecting pycparser (from cffi>=1.7->cryptography>=2.0.0->moto->buildbot==0.9.12.dev136)
Installing collected packages: buildbot-www, six, pyparsing, packaging, Click, incremental, MarkupSafe, jinja2, toml, towncrier, buildbot-pkg, zope.interface, constantly, hyperlink, attrs, Automat, Twisted, future, sqlalchemy, Tempita, decorator, sqlparse, pbr, sqlalchemy-migrate, python-dateutil, txaio, autobahn, PyJWT, docutils, alabaster, snowballstemmer, pytz, babel, imagesize, Pygments, typing, certifi, chardet, idna, urllib3, requests, sphinxcontrib-websupport, sphinx, funcparserlib, webcolors, olefile, Pillow, blockdiag, sphinxcontrib-blockdiag, pyenchant, sphinxcontrib-spelling, jsonref, termcolor, xmltodict, pyyaml, markdown2, ramlfications, sphinx-jinja, scandir, pathlib2, setuptools-trial, isort, lazy-object-proxy, wrapt, astroid, configparser, backports.functools-lru-cache, mccabe, pylint, pycodestyle, pyflakes, flake8, treq, txrequests, pyjade, futures, jmespath, botocore, s3transfer, boto3, funcsigs, mock, boto, werkzeug, pyaml, backports.ssl-match-hostname, docker-pycreds, ipaddress, websocket-client, docker, backports.weakref, backports.tempfile, asn1crypto, pycparser, cffi, enum34, cryptography, cookies, moto, pyopenssl, txgithub, lz4, pyasn1, pyasn1-modules, service-identity, buildbot, pep8, buildbot-worker
  Running setup.py install for towncrier ... done
  Running setup.py develop for buildbot-pkg
  Running setup.py develop for buildbot
  Running setup.py develop for buildbot-worker
Successfully installed Automat-0.6.0 Click-6.7 MarkupSafe-1.0 Pillow-4.3.0 PyJWT-1.5.3 Pygments-2.2.0 Tempita-0.5.2 Twisted-17.9.0 alabaster-0.7.10 asn1crypto-0.23.0 astroid-1.4.9 attrs-17.2.0 autobahn-17.9.3 babel-2.5.1 backports.functools-lru-cache-1.4 backports.ssl-match-hostname-3.5.0.1 backports.tempfile-1.0rc1 backports.weakref-1.0.post1 blockdiag-1.5.3 boto-2.48.0 boto3-1.4.7 botocore-1.7.21 buildbot buildbot-pkg buildbot-worker buildbot-www-0.9.11 certifi-2017.7.27.1 cffi-1.11.0 chardet-3.0.4 configparser-3.5.0 constantly-15.1.0 cookies-2.2.1 cryptography-2.0.3 decorator-4.1.2 docker-2.5.1 docker-pycreds-0.2.1 docutils-0.12 enum34-1.1.6 flake8-2.6.2 funcparserlib-0.3.6 funcsigs-1.0.2 future-0.16.0 futures-3.1.1 hyperlink-17.3.1 idna-2.6 imagesize-0.7.1 incremental-17.5.0 ipaddress-1.0.18 isort-4.2.15 jinja2-2.9.6 jmespath-0.9.3 jsonref-0.1 lazy-object-proxy-1.3.1 lz4-0.10.1 markdown2-2.3.4 mccabe-0.6.1 mock-2.0.0 moto-1.1.21 olefile-0.44 packaging-16.8 pathlib2-2.3.0 pbr-3.1.1 pep8-1.7.0 pyaml-17.8.0 pyasn1-0.3.6 pyasn1-modules-0.1.4 pycodestyle-2.0.0 pycparser-2.18 pyenchant-1.6.11 pyflakes-1.2.3 pyjade-4.0.0 pylint-1.6.5 pyopenssl-17.3.0 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 pyyaml-3.12 ramlfications-0.1.9 requests-2.18.4 s3transfer-0.1.11 scandir-1.6 service-identity-17.0.0 setuptools-trial-0.6.0 six-1.11.0 snowballstemmer-1.2.1 sphinx-1.6.4 sphinx-jinja-0.3.0 sphinxcontrib-blockdiag-1.5.5 sphinxcontrib-spelling-2.3.0 sphinxcontrib-websupport-1.0.1 sqlalchemy-1.1.14 sqlalchemy-migrate-0.11.0 sqlparse-0.2.4 termcolor-1.1.0 toml-0.9.3 towncrier-16.12.0 treq-17.8.0 txaio-2.8.2 txgithub-15.0.0 txrequests-0.9.5 typing-3.6.2 urllib3-1.22 webcolors-1.7 websocket-client-0.44.0 werkzeug-0.12.2 wrapt-1.10.11 xmltodict-0.11.0 zope.interface-4.4.3
```

**Comment by seankelly** [comment]
Yeah, I think it's from the repository. That needs to changed to either be the name or upstream's repository.

**Comment by Frodox** [comment]
@tardyp how should I fix it in upstream?

**Comment by seankelly** [comment]
I got it to work by installing towncrier==17.8.0 in the virtualenv.
