### ISSUE TITLE
buildrequestdistributor 'NoneType' object has no attribute 'config'

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3673]
Noticed this error in twistd.log:

```
2017-10-03 17:03:43-0700 [WampWebSocketClientProtocol,client] while attempting to start builds on None
        Traceback (most recent call last): 
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/process/buildrequestdistributor.py", line 383, in resetPendingBuildersList
            list(existing_pending | new_builders))
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/process/buildrequestdistributor.py", line 453, in _sortBuilders
            sorter = self.master.config.prioritizeBuilders
        exceptions.AttributeError: 'NoneType' object has no attribute 'config'
```

**Comment by tardyp** [comment]
Hi, would be nice to have a little bit more context.
Was it in the middle of a reconfig or a restart?

That could explain that self.master is None while the buildrequestdistributor is being reconfigured or stopped.
