### ISSUE TITLE
Errors with GitHub change hook since 0.9.11

### ISSUE THREAD

**Issue by faudebert** [buildbot/buildbot#3693]
After upgrading from 0.9.10 to 0.9.11 (or 0.9.12), GitHub change hook throws error when parsing an event:
```
2017-10-13 15:21:27+0200 [_GenericHTTPChannelProtocol,1,192.168.1.1] X-GitHub-Event: pull_request
2017-10-13 15:21:27+0200 [_GenericHTTPChannelProtocol,1,192.168.1.1] Processing GitHub PR #312
2017-10-13 15:21:27+0200 [-] http https://api.github.com/repos/myorg/myrepo/commits/c3f57422f0242ceefc7ec2e908e45d7880014770 {'headers': {}}
2017-10-13 15:21:27+0200 [-] ==> 404: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/commits/#get-a-single-commit"}
2017-10-13 15:21:27+0200 [-] adding changes from web hook
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 500, in errback
            self._startRunCallbacks(fail)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1357, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python2.7/dist-packages/buildbot/www/change_hook.py", line 107, in getAndSubmitChanges
            changes, src = yield self.getChanges(request)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python2.7/dist-packages/buildbot/www/change_hook.py", line 168, in getChanges
            changes, src = yield handler.getChanges(request)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python2.7/dist-packages/buildbot/www/hooks/github.py", line 87, in process
            result = yield defer.maybeDeferred(lambda: handler(payload, event_type))
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python2.7/dist-packages/buildbot/www/hooks/github.py", line 167, in handle_pull_request
            head_msg = yield self._get_commit_msg(repo_full_name, head_sha)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/buildbot/www/hooks/github.py", line 218, in _get_commit_msg
            msg = data['commit']['message']
        exceptions.KeyError: 'commit'
```

The repository being accessed is private but using ```curl``` like this on it works properly:
```
curl https://api.github.com/repos/myorg/myrepo/commits/c3f57422f0242ceefc7ec2e908e45d7880014770?access_token=TOKEN
```

The 404 is to be expected on authentication failure as mentioned by [GitHub documentation](https://developer.github.com/v3/#authentication).

For now, no issue so far continuing using 0.9.10.

Thanks for you help,

**Comment by tardyp** [comment]
This is fixed in https://github.com/buildbot/buildbot/pull/3683 which needs unit test updates

**Comment by faudebert** [comment]
Oh great, did not notice the PR, my bad!

Thanks

**Comment by seankelly** [comment]
PR merged so closing this.
