### ISSUE TITLE
HyperLatentWorker checkconfig complains incorrectly

### ISSUE THREAD

**Issue by pmatos** [buildbot/buildbot#3719]
I have a buildbot 0.9.12 and am trying to play with HyperLatentWorker.

I have the following in my config:
```python
c['workers'] = [worker.HyperLatentWorker(name='hyper-latent',
                                         password=None,
                                         hyper_host='LTLatentWorker',
                                         image='ubuntu:latest',
                                         masterFQDN='foo:9990',
                                         hyper_accesskey='asdasd',
                                         hyper_secretkey='4asdasd',
                                         hyper_size='s3',
                                         build_wait_timeout=3)]
```

And yet I get from `checkconfig`:
```
$ buildbot checkconfig master
DEBUG:root:Current directory: /home/buildbot/ltbot/master
error while parsing config file:
Traceback (most recent call last):
  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/buildbot/scripts/checkconfig.py", line 60, in checkconfig
    return _loadConfig(basedir=basedir, configFile=configFile, quiet=quiet)
  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/buildbot/scripts/checkconfig.py", line 30, in _loadConfig
    config.FileLoader(basedir, configFile).loadConfig()
  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/buildbot/config.py", line 181, in loadConfig
    self.basedir, self.configFileName)
--- <exception caught here> ---
  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/buildbot/config.py", line 139, in loadConfigDict
    execfile(filename, localDict)
  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/python/compat.py", line 246, in execfile
    exec(code, globals, locals)
  File "master/master.cfg", line 41, in <module>
    
  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/buildbot/util/service.py", line 178, in __init__
    self.checkConfig(*args, **kwargs)
builtins.TypeError: checkConfig() missing 1 required positional argument: 'name'

Configuration Errors:
  error while parsing config file: checkConfig() missing 1 required positional argument: 'name' (traceback in logfile)
```

Where line 41 of `master.cfg` is `                                         build_wait_timeout=3)]`. However, as you can see I do have `name` defined as a parameter to `HyperLatentWorker`.

**Comment by seankelly** [comment]
Try without the `name` parameter explicitly set. E.g., `worker.HyperLatentWorker('hyper-latent', password=None, ...)`

**Comment by pmatos** [comment]
@seankelly  Doh! It works but why?

**Comment by p12tic** [comment]
The hyper service has shutdown on 15 January. Hyper has been since removed from buildbot.
