### ISSUE TITLE
Hyper usage with buildbot-worker image generates fake docker error

### ISSUE THREAD

**Issue by pmatos** [buildbot/buildbot#3723]
i have the following buildbot latent worker setup:
```
c['workers'] = [worker.HyperLatentWorker('hyper-latent',
                                         password=None,
                                         hyper_host='tcp://eu-central-1.hyper.sh:443',
                                         image='buildbot/buildbot-worker',
                                         masterFQDN='mybuildbot:9990',
                                         hyper_accesskey='sdfsdf',
                                         hyper_secretkey='laskdfaosfj',
                                         hyper_size='s3',
                                         build_wait_timeout=3)]
```

The interesting thing is that this somehow trigger a docker error:
```
2017-10-29 00:32:09+0200 [-] DEBUG:urllib3.connectionpool:https://eu-central-1.hyper.sh:443 "GET /v1.23/containers/json?filters=%7B%22name%22%3A+%5B%22buildboteb0b23-hyper-latent%22%5D%7D&trunc_cmd=0&size=0&limit=-1&all=1 HTTP/1.1" 200 2
2017-10-29 00:32:09+0200 [-] image: buildbot/buildbot-worker
2017-10-29 00:32:09+0200 [-] name: buildboteb0b23-hyper-latent
2017-10-29 00:32:09+0200 [-] DEBUG:urllib3.connectionpool:https://eu-central-1.hyper.sh:443 "POST /v1.23/containers/create?name=buildboteb0b23-hyper-latent HTTP/1.1" 404 47
2017-10-29 00:32:09+0200 [-] while worker_prepare
	Traceback (most recent call last):
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 1442, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	--- <exception caught here> ---
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/buildbot/process/build.py", line 320, in startBuild
	    ready_or_failure = yield workerforbuilder.prepare(self)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/buildbot/worker/hyper.py", line 129, in start_instance
	    yield self.deferToThread(self._thd_start_instance, image, size)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/buildbot/worker/hyper.py", line 163, in _thd_start_instance
	    name=self.getContainerName()
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/docker/api/container.py", line 135, in create_container
	    return self.create_container_from_config(config, name)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/docker/api/container.py", line 146, in create_container_from_config
	    return self._result(res, True)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/docker/client.py", line 178, in _result
	    self._raise_for_status(response)
	  File "/home/buildbot/ltbot/venv/lib/python3.5/site-packages/docker/client.py", line 173, in _raise_for_status
	    raise errors.NotFound(e, response, explanation=explanation)
	docker.errors.NotFound: 404 Client Error: Not Found ("b'No such image: buildbot/buildbot-worker:latest'")
```

Obviously there's something else wrong the fact that `buildbot/buildbot-worker` does not exist. Just in case I actually pulled this image using docker cli but still get the error.

My guess is that something went wrong before due to this:
```
2017-10-29 00:32:09+0200 [-] DEBUG:urllib3.connectionpool:https://eu-central-1.hyper.sh:443 "POST /v1.23/containers/create?name=buildboteb0b23-hyper-latent HTTP/1.1" 404 47
```

In my hyper console I don't see any container and it seems we got back a 404 error, so maybe that's it but I am not comfortable enough with hyper to understand all the terminology.

**Comment by p12tic** [comment]
The hyper service has shutdown on 15 January. Hyper has been since removed from buildbot.
