### ISSUE TITLE
python3 buildbot master sendchange face exception

### ISSUE THREAD

**Issue by congzhangzh** [buildbot/buildbot#3726]
Hi Devs,

buildbot sendchange face exception, under python3

**sendchange like(which work correct under python2)**:

 /home/buildbot/.virtualenvs/python3env/bin/buildbot sendchange ..

exception:
 b'change not sent:\nTraceback (most recent call last):\n  File "/home/buildbot/.virtualenvs/python3env/lib/python3.5/site-packages/buildbot/scripts/sendchange.py", line 54, in sendchange\n    codebase=codebase)\n  File "/home/buildbot/.virtualenvs/python3env/lib/python3.5/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks\n    current.result = callback(current.result, *args, **kw)\n  File "/home/buildbot/.virtualenvs/python3env/lib/python3.5/site-packages/twisted/spread/pb.py", line 1387, in _cbResponse\n    return challenger.callRemote("respond", respond(challenge, password), client)\n  File "/home/buildbot/.virtualenvs/python3env/lib/python3.5/site-packages/twisted/spread/pb.py", line 1257, in respond\n    m.update(password)\nTypeError: Unicode-objects must be encoded before hashing\n'

**Comment by congzhangzh** [comment]
one workaround maybe:
adjust **~/.virtualenvs/python3env/lib/python3.5/site-packages/buildbot/clients/senchange.py:24**

```python
class Sender:

    def __init__(self, master, auth=('change', 'changepw'), encoding='utf8'):
        self.encoding = encoding
        self.username= auth[0].encode(self.encoding)
        self.password =auth[1].encode(self.encoding)
        self.host, self.port = master.split(":")
        self.port = int(self.port)


```

or adjust, **~/.virtualenvs/python3env/lib/python3.5/site-packages/twisted/spread/pb.py:1246, which is better!**

```python
def respond(challenge, password):
    """
    Respond to a challenge.

    This is useful for challenge/response authentication.

    @param challenge: A challenge.
    @param password: A password.
    @return: The password hashed twice.
    """
    m = md5()
    pwdBytes=password if isinstance(password, str) and isinstance(password, bytes) else pwdBytes.encode('ascii')
    m.update(pwdBytes)
    hashedPassword = m.digest()
    m = md5()
    m.update(hashedPassword)
    m.update(challenge)
    doubleHashedPassword = m.digest()
    return doubleHashedPassword

```

**Comment by jdpipe** [comment]
I also saw a similar error when attempting to use svn_buildbot.py (buildbot-contrib).

**Comment by tardyp** [comment]
@rodrigc is this something we should report to twisted?

**Comment by exarkun** [comment]
Twisted might incorporate a change to improve the error reporting in this case but ultimately it seems like Buildbot has the bug.  pb's builtin username/password authentication does not accept unicode passwords but buildbot seems to be supplying one.  Buildbot should change to provide bytes, presumably by encoding the unicode value it is currently supplying.
