### ISSUE TITLE
GitHub step broken with method="full", mode="copy"

### ISSUE THREAD

**Issue by morrone** [buildbot/buildbot#3749]
I am using a buildbot master version 0.9.13 and worker version 0.9.12.

I have am using a steps.GitHub() that looks like this:

```
factory.addStep(steps.GitHub(repourl='http://github.com/morrone/flux-core.git',
                             mode='full', method='copy'))
```

This combination of mode "full" and method "copy" seems to be broken.  For comparison, mode "full" and method "fresh" works just fine.  On the master side, I see this in the logs:

```
2017-11-09 03:34:06+0000 [-] <RemoteShellCommand '['git', '--version']'>: RemoteCommand.run [0]
2017-11-09 03:34:06+0000 [-] command '['git', '--version']' in dir 'build'
2017-11-09 03:34:06+0000 [Broker,0,13.57.33.5] <RemoteShellCommand '['git', '--version']'> rc=0
2017-11-09 03:34:06+0000 [-] <RemoteCommand 'stat' at 140658929127096>: RemoteCommand.run [1]
2017-11-09 03:34:06+0000 [Broker,0,13.57.33.5] <RemoteCommand 'stat' at 140658929127096> rc=2
2017-11-09 03:34:06+0000 [-] <RemoteCommand 'rmdir' at 140658929200600>: RemoteCommand.run [2]
2017-11-09 03:34:06+0000 [Broker,0,13.57.33.5] <RemoteCommand 'rmdir' at 140658929200600> rc=0
2017-11-09 03:34:06+0000 [-] <RemoteCommand 'listdir' at 140658928829552>: RemoteCommand.run [3]
2017-11-09 03:34:06+0000 [Broker,0,13.57.33.5] <RemoteCommand 'listdir' at 140658928829552> rc=2
2017-11-09 03:34:06+0000 [-] No git repo present, making full clone
2017-11-09 03:34:06+0000 [-] <RemoteShellCommand '['git', 'clone', '--no-checkout', 'http://github.com/morrone/flux-core.git', '.']'>: RemoteCommand.run [4]
2017-11-09 03:34:06+0000 [-] command '['git', 'clone', '--no-checkout', 'http://github.com/morrone/flux-core.git', '.']' in dir 'source'
2017-11-09 03:34:10+0000 [Broker,0,13.57.33.5] <RemoteShellCommand '['git', 'clone', '--no-checkout', 'http://github.com/morrone/flux-core.git', '.']'> rc=0
2017-11-09 03:34:10+0000 [-] <RemoteShellCommand '['git', 'fetch', '-t', 'http://github.com/morrone/flux-core.git', 'refs/pull/1/merge']'>: RemoteCommand.run [5]
2017-11-09 03:34:10+0000 [-] command '['git', 'fetch', '-t', 'http://github.com/morrone/flux-core.git', 'refs/pull/1/merge']' in dir 'source'
2017-11-09 03:34:10+0000 [Broker,0,13.57.33.5] <RemoteShellCommand '['git', 'fetch', '-t', 'http://github.com/morrone/flux-core.git', 'refs/pull/1/merge']'> rc=0
2017-11-09 03:34:10+0000 [-] <RemoteShellCommand '['git', 'reset', '--hard', 'FETCH_HEAD', '--']'>: RemoteCommand.run [6]
2017-11-09 03:34:10+0000 [-] command '['git', 'reset', '--hard', 'FETCH_HEAD', '--']' in dir 'source'
2017-11-09 03:34:10+0000 [Broker,0,13.57.33.5] <RemoteShellCommand '['git', 'reset', '--hard', 'FETCH_HEAD', '--']'> rc=0
2017-11-09 03:34:10+0000 [-] <RemoteShellCommand '['git', 'checkout', '-B', 'refs/pull/1/merge']'>: RemoteCommand.run [7]
2017-11-09 03:34:10+0000 [-] command '['git', 'checkout', '-B', 'refs/pull/1/merge']' in dir 'source'
2017-11-09 03:34:10+0000 [Broker,0,13.57.33.5] <RemoteShellCommand '['git', 'checkout', '-B', 'refs/pull/1/merge']'> rc=0
2017-11-09 03:34:10+0000 [-] <RemoteCommand 'cpdir' at 140658938726160>: RemoteCommand.run [8]
2017-11-09 03:34:10+0000 [Broker,0,13.57.33.5] <RemoteCommand 'cpdir' at 140658938726160> rc=-1
2017-11-09 03:34:10+0000 [-] releaseLocks(GitHub(repourl='http://github.com/morrone/flux-core.git', mode='full', method='copy')): []
2017-11-09 03:34:10+0000 [-]  step 'git' complete: failure (['update (failure)'])
2017-11-09 03:34:10+0000 [-]  <Build core_test number:24 results:failure>: build finished
2017-11-09 03:34:10+0000 [-] releaseLocks(<EC2LatentWorker 'CentOS7_0'>): []

```
And on the worker side this is the error with backtrace:
```
2017-11-09 03:34:10+0000 [HangCheckProtocol,client]  startCommand:cpdir [id 8]
2017-11-09 03:34:10+0000 [HangCheckProtocol,client] RunProcess._startCommand
2017-11-09 03:34:10+0000 [HangCheckProtocol,client]  cp -R -P -p -v /home/buildbotworker/worker/core_test/source /home/buildbotworker/worker/core_test/build
2017-11-09 03:34:10+0000 [HangCheckProtocol,client]   in dir /home/buildbotworker/worker/core_test (timeout 1200 secs)
2017-11-09 03:34:10+0000 [HangCheckProtocol,client]   watching logfiles {}
2017-11-09 03:34:10+0000 [HangCheckProtocol,client]   argv: [b'cp', b'-R', b'-P', b'-p', b'-v', b'/home/buildbotworker/worker/core_test/source', b'/home/buildbotworker/worker/core_test/build']
2017-11-09 03:34:10+0000 [HangCheckProtocol,client]  environment:
        {'BASH_FUNC_module()': '() {  eval `/usr/bin/modulecmd bash $*`\n}',
         'HISTCONTROL': 'ignoredups',
         'HISTSIZE': '1000',
         'HOME': '/home/buildbotworker',
         'HOSTNAME': 'ip-172-31-3-252.us-west-1.compute.internal',
         'LANG': 'en_US.UTF-8',
         'LESSOPEN': '||/usr/bin/lesspipe.sh %s',
         'LOADEDMODULES': '',
         'LOGNAME': 'buildbotworker',
         'MAIL': '/var/spool/mail/buildbotworker',
         'MODULEPATH': '/usr/share/Modules/modulefiles:/etc/modulefiles',
         'MODULESHOME': '/usr/share/Modules',
         'PATH': '/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/buildbotworker/.local/bin:/home/buildbotworker/bin',
         'PWD': '/home/buildbotworker/worker/core_test',
         'SHELL': '/bin/bash',
         'SHLVL': '1',
         'USER': 'buildbotworker',
         '_': '/bin/buildbot-worker'}
2017-11-09 03:34:10+0000 [HangCheckProtocol,client]   using PTY: False
2017-11-09 03:34:10+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python3.4/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib64/python3.4/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib64/python3.4/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib64/python3.4/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib64/python3.4/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib64/python3.4/site-packages/twisted/internet/process.py", line 291, in doRead
            return fdesc.readFromFD(self.fd, self.dataReceived)
          File "/usr/lib64/python3.4/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
            callback(output)
          File "/usr/lib64/python3.4/site-packages/twisted/internet/process.py", line 295, in dataReceived
            self.proc.childDataReceived(self.name, data)
          File "/usr/lib64/python3.4/site-packages/twisted/internet/process.py", line 961, in childDataReceived
            self.proto.childDataReceived(name, data)
          File "/usr/lib64/python3.4/site-packages/twisted/internet/protocol.py", line 636, in childDataReceived
            self.outReceived(data)
          File "/usr/lib/python3.4/site-packages/buildbot_worker/runprocess.py", line 216, in outReceived
            data, self.command.builder.unicode_encoding)
          File "/usr/lib/python3.4/site-packages/buildbot_worker/compat.py", line 87, in bytes2unicode
            return text_type(x, encoding, errors)
        builtins.UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 4094-4095: unexpected end of data
        
2017-11-09 03:34:10+0000 [-] command finished with signal 13, exit code None, elapsedTime: 0.067885
```

**Comment by rodrigc** [comment]
@morrone upgrade your worker to 0.9.13.  That code has changed in the worker and you are missing a fix.

**Comment by morrone** [comment]
Awesome!  I agree, this is no longer a problem with the 0.9.13 worker.
