### ISSUE TITLE
Render properties for nightly scheduler

### ISSUE THREAD

**Issue by pmisik** [buildbot/buildbot#3757]
Hi,
I try to create nightly scheduler that’s properties should be rendered this way:

```
@util.renderer
def dailyBuildProps(props):
    p = {
        "retentionPolicy" : 20,
        "forceClean" : True,
    }
    stamp = datetime.datetime.now().strftime("%Y%m%d")
    p["stamp"] = stamp
    p["buildSuffix"] = "_master_{}".format(stamp)
    return p

c['schedulers'].append(schedulers.Nightly(
    name='dailyBuild',
    builderNames=['productBuild'],
    hour=5,
    minute=0,
    properties=dailyBuildProps))
```
Unfortunately it does not work. I receive following traceback.

```
2017-11-13 08:25:57+0100 [-] error while parsing config file:
        Traceback (most recent call last):
          File "/home/bb/sandbox/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/home/bb/sandbox/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/bb/sandbox/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/home/bb/sandbox/lib/python3.5/site-packages/buildbot/config.py", line 181, in loadConfig
            self.basedir, self.configFileName)
        --- <exception caught here> ---
          File "/home/bb/sandbox/lib/python3.5/site-packages/buildbot/config.py", line 139, in loadConfigDict
            execfile(filename, localDict)
          File "/home/bb/sandbox/lib/python3.5/site-packages/twisted/python/compat.py", line 246, in execfile
            exec(code, globals, locals)
          File "/home/bb/master/master.cfg", line 36, in <module>
            builders.setupSchedulers(c)
          File "/home/bb/master/build/builders.py", line 113, in setupSchedulers
            properties=dailyBuildProps))
          File "/home/bb/sandbox/lib/python3.5/site-packages/buildbot/schedulers/timed.py", line 350, in __init__
            **kwargs)
          File "/home/bb/sandbox/lib/python3.5/site-packages/buildbot/schedulers/timed.py", line 290, in __init__
            Timed.__init__(self, name, builderNames, **kwargs)
          File "/home/bb/sandbox/lib/python3.5/site-packages/buildbot/schedulers/timed.py", line 56, in __init__
            base.BaseScheduler.__init__(self, name, builderNames, **kwargs)
          File "/home/bb/sandbox/lib/python3.5/site-packages/buildbot/schedulers/base.py", line 68, in __init__
            self.properties.update(properties, "Scheduler")
          File "/home/bb/sandbox/lib/python3.5/site-packages/buildbot/process/properties.py", line 169, in update
            for k, v in iteritems(dict):
          File "/home/bb/sandbox/lib/python3.5/site-packages/future/utils/__init__.py", line 306, in iteritems
            func = obj.items
        builtins.AttributeError: '_Renderer' object has no attribute 'items'

```
Any idea what I'm doing wrong?

Thank you.
Palo

**Comment by lancelodliu** [comment]
`properties` param for `Scheduler` is not renderable. My suggestion is to use a buildstep to set these properties.
