### ISSUE TITLE
Possible bug in GitHubCommentPush

### ISSUE THREAD

**Issue by adydychk** [buildbot/buildbot#3763]
I tried to use `GithubCommentPush` but it did not work it seems that there is a problem in using Github API by Buildbot.  
Is it a bug or I do something wrong?  
  
How I use `GithubCommentPush`:
```python
reporters.GitHubCommentPush(token=config.GITHUB_TOKEN,
                                               startDescription="Started (comment)",
                                               endDescription="Done (comment)",
                                               verbose=True,
                                               debug=True)]
```

Here is a log with exception:  
```
2017-11-17 12:35:22+0300 [-] Updating github status: repoOwner=..., repoName=...
2017-11-17 12:35:22+0300 [-] Failed to update "pending" for .../... at f83c4d05df77a7da81c52f78354f0dbfccbb87b7, issue None
	Traceback (most recent call last):
	  File "/opt/python36/lib/python3.6/site-packages/buildbot/reporters/http.py", line 84, in getMoreInfoAndSend
	    yield self.send(build)
	  File "/opt/python36/lib/python3.6/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	  File "/opt/python36/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/opt/python36/lib/python3.6/site-packages/buildbot/reporters/github.py", line 182, in send
	    state=state, repoOwner=repoOwner, repoName=repoName, sha=sha, issue=issue))
	--- <exception caught here> ---
	  File "/opt/python36/lib/python3.6/site-packages/buildbot/reporters/github.py", line 170, in send
	    description=description
	  File "/opt/python36/lib/python3.6/site-packages/buildbot/reporters/github.py", line 213, in createStatus
	    '/'.join(['/repos', repo_user, repo_name, 'issues', issue, 'comments']),
	builtins.TypeError: sequence item 4: expected str instance, NoneType found
	
2017-11-17 12:35:22+0300 [Broker,0,127.0.0.1] ping finished: success
```

P.S.
Buildbot team, thanks for your great work! :)

**Comment by tardyp** [comment]
The sequence item 4 is the issue, as computed in following code
```
       branch = props['branch']
        m = re.search(r"refs/pull/([0-9]*)/merge", branch)
        if m:
            issue = m.group(1)
        else:
            issue = None
```
It will be None if the branch is not coming from a merge. It looks like the branch you are trying to build is not coming from a merge request

**Comment by adydychk** [comment]
@tardyp Hm, it seems that you are right... So if I use GithubCommitPush Buildbot scheduler should react only on changes from Pull Requests. Did I understand you correct?

**Comment by tardyp** [comment]
Right. You can configure that by doing a build specific for the pull requests, and by configuring the reporter to react only on that builder's events.

We can also fix the code to silently discard the event if there is no issue to update.

**Comment by adydychk** [comment]
Oh super, thanks for your answer! Also I think that it needs to update the documentation. It needs to clarify that GithubCommentPush works only if changes are taken from `refs/pull/([0-9]*)/merge`.  
Where can I do that? In the source file of GithubCommentPush?

**Comment by tardyp** [comment]
You can fix the code here:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/reporters/github.py#L211

by adding a ```if issue is not None```

You can also fix the documentation here: https://github.com/buildbot/buildbot/blob/master/master/docs/manual/cfg-reporters.rst#L936

thanks for your contribution!

**Comment by WayneKeenan** [comment]
I'm seeing the same error for a branch that is coming from a PR merge.

**Comment by WayneKeenan** [comment]
ok, on re-reading, I actually need to change my GitPoller `branch` to be to `refs/pull/([0-9]*)/merge`   (?)

**Comment by tardyp** [comment]
@WayneKeenan right

**Comment by WayneKeenan** [comment]
I have `GitHubCommentPush` updating my PR on create and merge, however, it's not behaving.

I see start and end comments, as expected,  if I set the following and the build is successful:
```python
startDescription='Build started.(GitHubCommentPush)',
endDescription='Build done. (GitHubCommentPush)',
```

If the build is unsuccessful the `endDescription` is not added.  (I assumed it would be)

If I set the `endDescription` to a function (as per the example in the doc) I never see it called, and thus no comment.

Is there something I am missing?

Thanks
Wayne
