### ISSUE TITLE
Exceptions when using postgresQL with buildbot  0.9.11-dev534

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#3766]
Python version: 3.4.3
Buildbot version: 0.9.11-dev534
Twisted version: 17.5.0

We were having performance reasons so we tried using postgresSQL. Things 'mostly' worked but occasionally we would get failures with the following callstack:

Traceback (most recent call last):
          File "/home/buildmaster/buildbot/sandbox/lib/python3.4/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/home/buildmaster/buildbot/sandbox/lib/python3.4/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
          File "/home/buildmaster/buildbot/sandbox/lib/python3.4/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/buildmaster/buildbot/sandbox/lib/python3.4/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/home/buildmaster/buildbot/sandbox/lib/python3.4/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/home/buildmaster/buildbot/sandbox/lib/python3.4/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/home/buildmaster/buildbot/src/master/buildbot/process/buildstep.py", line 844, in addCompleteLog
            yield _log.finish()
        builtins.AssertionError:

the builtins.AssertionError has nothing after it.

While I don't see anything postgresQL specific, switching back to the sqlite doesn't exhibit this problem.

Any thoughts?

**Comment by tardyp** [comment]
There is an assertion in log.finish which verify that the log is not yet finished, but I don't see why there would be a double finish for that log.

**Comment by tardyp** [comment]
by looking at the custom step that you published on IRC:
```
class ShellCommandWithLogFiles(steps.ShellCommand, CompositeStepMixin):
        def __init__(self, generatedLogFiles={}, **kwargs):
                self.logEnviron = kwargs.get('logEnviron',False) # pull locally for CompositeStepMixin
                steps.ShellCommand.__init__(self, **kwargs)
                if not isinstance(generatedLogFiles,dict):
                        raise RuntimeError("generatedLogFiles must be a dictionary { 'name' : 'filename' } or { 'name' : { 'filename' : filename, 'type' : 'h' }")
                for name, e in generatedLogFiles.items():
                        if isinstance(e,str):
                                generatedLogFiles[name] = { 'filename' : e, 'type' : 's' }
                self.generatedLogFiles = generatedLogFiles
                       
        @defer.inlineCallbacks
        def run(self):
                yield self.rmLogFiles()
                results = yield steps.ShellCommand.run(self)
                for name, options in self.generatedLogFiles.items():
                        hasPath = yield self.pathExists(self.build.path_module.join(self.workdir, options['filename']))
                        if not hasPath:
                                continue
                        content = yield self.getFileContentFromWorker(options['filename'], abandonOnFailure=False)
                        if content:
                                if options.get('type','s') == 'h':
                                        self.addHTMLLog( name, content)
                                else:
                                        self.addCompleteLog( name, content)
                defer.returnValue(results)
 
        @defer.inlineCallbacks
        def rmLogFiles(self):
                all_results = []
                for name, options in self.generatedLogFiles.items():
                        fname = self.build.path_module.join(self.workdir, options['filename'])
                        hasPath = yield self.pathExists(fname)
                        log.msg( ">> hasPath of {} = {}".format(fname, hasPath))
                        if hasPath:
                                res = yield self.runRmFile(fname, abandonOnFailure=False)
                                log.msg( ">> rmFile of {} rc = {}".format(fname, res ))
                                all_results.append(res)
                if results.FAILURE in all_results:
                        result = results.FAILURE
                else:
                        result = results.SUCCESS
                defer.returnValue(result)
class ShellCommandWithLogFiles(steps.ShellCommand, CompositeStepMixin):
        def __init__(self, generatedLogFiles={}, **kwargs):
                self.logEnviron = kwargs.get('logEnviron',False) # pull locally for CompositeStepMixin
                steps.ShellCommand.__init__(self, **kwargs)
                if not isinstance(generatedLogFiles,dict):
                        raise RuntimeError("generatedLogFiles must be a dictionary { 'name' : 'filename' } or { 'name' : { 'filename' : filename, 'type' : 'h' }")
                for name, e in generatedLogFiles.items():
                        if isinstance(e,str):
                                generatedLogFiles[name] = { 'filename' : e, 'type' : 's' }
                self.generatedLogFiles = generatedLogFiles
                       
        @defer.inlineCallbacks
        def run(self):
                yield self.rmLogFiles()
                results = yield steps.ShellCommand.run(self)
                for name, options in self.generatedLogFiles.items():
                        hasPath = yield self.pathExists(self.build.path_module.join(self.workdir, options['filename']))
                        if not hasPath:
                                continue
                        content = yield self.getFileContentFromWorker(options['filename'], abandonOnFailure=False)
                        if content:
                                if options.get('type','s') == 'h':
                                        self.addHTMLLog( name, content)
                                else:
                                        self.addCompleteLog( name, content)
                defer.returnValue(results)
 
        @defer.inlineCallbacks
        def rmLogFiles(self):
                all_results = []
                for name, options in self.generatedLogFiles.items():
                        fname = self.build.path_module.join(self.workdir, options['filename'])
                        hasPath = yield self.pathExists(fname)
                        log.msg( ">> hasPath of {} = {}".format(fname, hasPath))
                        if hasPath:
                                res = yield self.runRmFile(fname, abandonOnFailure=False)
                                log.msg( ">> rmFile of {} rc = {}".format(fname, res ))
                                all_results.append(res)
                if results.FAILURE in all_results:
                        result = results.FAILURE
                else:
                        result = results.SUCCESS
                defer.returnValue(result)
```
I realize that you forgot the yield in   
```self.addCompleteLog( name, content)``` and ```self.addHTMLLog( name, content)```
In the end of a step, buildbot core will automatically finish all unfinished logs.
There is a difference between sqlite and pg, probably because the timings are different.

**Comment by sphet** [comment]
I will check the results with those changes next week. I didn't realize I needed to yield on the two calls. I couldn't find an example in the buildbot code base where they are yielded with the exception of buildstep.py. Why the discrepancy?

**Comment by tardyp** [comment]
You don't have to yield it in the case of an old-style step. old-style step have gory details to allow this. It is indeed unfortunately confusing.
