### ISSUE TITLE
GitPoller fails encoding ascii on a branch name

### ISSUE THREAD

**Issue by pho** [buildbot/buildbot#3769]
Hi, we're getting an error encoding a branch with an `ñ` on its name:

```
2017-11-21 08:08:55+0000 [-] while polling for changes
        Traceback (most recent call last):
          File "/home/buildbot/buildbot-adv/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/home/buildbot/buildbot-adv/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
          File "/home/buildbot/buildbot-adv/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/buildbot/buildbot-adv/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/home/buildbot/buildbot-adv/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/buildbot-adv/env/local/lib/python2.7/site-packages/buildbot/changes/gitpoller.py", line 189, in poll
            path=self.workdir)
          File "/home/buildbot/buildbot-adv/env/local/lib/python2.7/site-packages/buildbot/changes/gitpoller.py", line 350, in _dovccmd
            encodeArg([command] + args),
          File "/home/buildbot/buildbot-adv/env/local/lib/python2.7/site-packages/buildbot/changes/gitpoller.py", line 344, in encodeArg
            return [encodeArg(a) for a in arg]
          File "/home/buildbot/buildbot-adv/env/local/lib/python2.7/site-packages/buildbot/changes/gitpoller.py", line 347, in encodeArg
            return arg.encode("ascii")
        exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 18: ordinal not in range(128)

```

https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/gitpoller.py#L346

**Comment by rodrigc** [comment]
@pho can you try this patch: https://github.com/buildbot/buildbot/pull/3770 ?

**Comment by pho** [comment]
Awesome! Seems to be working nicely

Thank you!

**Comment by rodrigc** [comment]
@pho thanks for the quick feedback.

**Comment by pho** [comment]
Should we close this now? Or wait till your PR gets merged?

**Comment by rodrigc** [comment]
Wait until it is merged.
