### ISSUE TITLE
unicode encoding problem in windows from version 0.9.13 to 0.9.15post1

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3799]
If you try to excute a command containing a `unicode` to a **Windows** worker from a **Windows** master , you will get the error message like:
```python
 error in RunProcess._startCommand
Traceback (most recent call last):
  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 446, in start
    self._startCommand()
  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 572, in _startCommand
    usePTY=self.usePTY)
  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 603, in _spawnProcess
    path, usePTY=usePTY)
  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 619, in _spawnAsBatch
    tf.write(win32_batch_quote(self.command))
  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 70, in win32_batch_quote
    return ' '.join(map(escape_arg, cmd_list))
  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 63, in escape_arg
    arg = bytes2unicode(arg, unicode_encoding)
  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\compat.py", line 87, in bytes2unicode
    return text_type(x, encoding, errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb3 in position 49: invalid start byte
```
I found that in _buildbot-worker/runprocess.py:323_:
```python
        def to_bytes(cmd):
            if isinstance(cmd, (tuple, list)):
                for i, a in enumerate(cmd):
                    if isinstance(a, text_type):
                        cmd[i] = a.encode(self.builder.unicode_encoding)
            elif isinstance(cmd, text_type):
                cmd = cmd.encode(self.builder.unicode_encoding)
            return cmd
```
where `self.builder.unicode_encoding` is set to 'mbcs' which results in a wrong encoded `str` for 
 `text_type` in _compat.py:87_ to encode.

**Comment by pmisik** [comment]
This is probably related to #3797

**Comment by rodrigc** [comment]
@pmisik No you are wrong, it is not related to #3797

**Comment by lancelodliu** [comment]
By the way, 0.9.11 doesn't have this problem in that 0.9.11 because I can send command in gbk encoded str format.

**Comment by lancelodliu** [comment]
0.9.15 still has this problem. 
Unicode command is encoded by `self.builder.unicode_encoding` which is gbk in Windows and the decoded by default value of 'utf-8' in `buildbot_worker\compat.py:87`

**Comment by lancelodliu** [comment]
A reproduceable `master.cfg`:
```python
# -*- python -*-
# ex: set filetype=python:

from buildbot.plugins import *

# This is a sample buildmaster config file. It must be installed as
# 'master.cfg' in your buildmaster's base directory.

# This is the dictionary that the buildmaster pays attention to. We also use
# a shorter alias to save typing.
c = BuildmasterConfig = {}

####### WORKERS

# The 'workers' list defines the set of recognized workers. Each element is
# a Worker object, specifying a unique worker name and password.  The same
# worker name and password must be configured on the worker.
c['workers'] = [worker.LocalWorker("example-worker", "pass")]

# 'protocols' contains information about protocols which master will use for
# communicating with workers. You must define at least 'port' option that workers
# could connect to your master with this protocol.
# 'port' must match the value configured into the workers (with their
# --master option)
c['protocols'] = {'pb': {'port': 9989}}

####### CHANGESOURCES

# the 'change_source' setting tells the buildmaster how it should find out
# about source code changes.  Here we point to the buildbot version of a python hello-world project.

c['change_source'] = []

####### SCHEDULERS

# Configure the Schedulers, which decide how to react to incoming changes.  In this
# case, just kick off a 'runtests' build

c['schedulers'] = []
c['schedulers'].append(schedulers.ForceScheduler(
                            name="force",
                            builderNames=["runtests"]))

####### BUILDERS

# The 'builders' list defines the Builders, which tell Buildbot how to perform a build:
# what steps, and which workers can execute them.  Note that any particular build will
# only take place on one worker.

factory = util.BuildFactory()
# run the tests (note that this will require that 'trial' is installed)
factory.addStep(steps.ShellCommand(command=["echo", "我".decode('utf8')],
                                    logEnviron=False))

c['builders'] = []
c['builders'].append(
    util.BuilderConfig(name="runtests",
      workernames=["example-worker"],
      factory=factory))

####### BUILDBOT SERVICES

# 'services' is a list of BuildbotService items like reporter targets. The
# status of each build will be pushed to these targets. buildbot/reporters/*.py
# has a variety to choose from, like IRC bots.

c['services'] = []

####### PROJECT IDENTITY

# the 'title' string will appear at the top of this buildbot installation's
# home pages (linked to the 'titleURL').

c['title'] = "Hello World CI"
c['titleURL'] = "https://buildbot.github.io/hello-world/"

# the 'buildbotURL' string should point to the location where the buildbot's
# internal web server is visible. This typically uses the port number set in
# the 'www' entry below, but with an externally-visible host name which the
# buildbot cannot figure out without some help.

c['buildbotURL'] = "http://localhost:8010/"

# minimalistic config to activate new web UI
c['www'] = dict(port=8010,
                plugins=dict(waterfall_view={}, console_view={}, grid_view={}))

####### DB URL

c['db'] = {
    # This specifies what database buildbot uses to store its state.  You can leave
    # this at its default for all but the largest installations.
    'db_url' : "sqlite:///state.sqlite",
}

```

**Comment by lancelodliu** [comment]
This bug is caused by the following code in `runprocess.py:58`:
```python
def win32_batch_quote(cmd_list, unicode_encoding='utf-8'):
    # Quote cmd_list to a string that is suitable for inclusion in a
    # Windows batch file. This is not quite the same as quoting it for the
    # shell, as cmd.exe doesn't support the %% escape in interactive mode.
    def escape_arg(arg):
        arg = bytes2unicode(arg, unicode_encoding) # SHOULD BE unicode2bytes
        arg = quoteArguments([arg])
        # escape shell special characters
        arg = re.sub(r'[@()^"<>&|]', r'^\g<0>', arg)
        # prevent variable expansion
        return arg.replace('%', '%%')

    return ' '.join(map(escape_arg, cmd_list))
```
`bytes2unicode` should be replaced by `unicode2bytes` because `tf.write()`(runprocess.py:617) requires native string other than a unicode in Python2. You can try the following code to confirm that:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from tempfile import NamedTemporaryFile
tf = NamedTemporaryFile(mode='w+', dir='.', suffix=".bat",
                                delete=False)
tf.write(u'\u6211')
tf.close()
```
The diff between 0.9.11 and 0.9.15post1 is as below:
![image](https://user-images.githubusercontent.com/19603852/35970731-6a8033da-0d06-11e8-9857-7e0c038298ba.png)

In Python2, `bytes2NativeString` returns `x` directly if `x` is a `str` object while `bytes2unicode` doesn't which causes a `UnicodeDecodeError` because `self.command` consists of `str` objects encoded by `mbcs` in `to_bytes` function.
```python
def bytes2NativeString(x, encoding='utf-8'):
    """
    Convert C{bytes} to a native C{str}.

    On Python 3 and higher, str and bytes
    are not equivalent.  In this case, decode
    the bytes, and return a native string.

    On Python 2 and lower, str and bytes
    are equivalent.  In this case, just
    just return the native string.

    @param x: a string of type C{bytes}
    @param encoding: an optional codec, default: 'utf-8'
    @return: a string of type C{str}
    """
    if isinstance(x, bytes) and str != bytes:
        return x.decode(encoding)
    return x
```
