### ISSUE TITLE
GitHubStatusPush: Exception in re.search when branch is None

### ISSUE THREAD

**Issue by krf** [buildbot/buildbot#3854]
Heya,

`GitHubStatusPush` produces an exception for us, when a particular build was triggered via a nightly scheduler instead of the quick scheduler reacting on pull requests.

Note: In the backtrace there's a 'githubintegration.py' -- which is an *almost* 1:1 copy of github.py from upstream (we needed to patch a few behaviors, thus the copy).

Looks like we should probably just `return` in case branch is `None` in `GitHubStatusPush.send(...)`, too?

```
2017-12-27 06:02:14+0100 [-] while invoking <bound method GitHubStatusPush.buildFinished of <GitHubStatusPush object at 0x7f00bb994450>>
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1357, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
            result = g.send(result)
          File "/home/build/opt/lib/python2.7/site-packages/buildbot-0.9.15.dev11-py2.7.egg/buildbot/reporters/http.py", line 84, in getMoreInfoAndSend
            yield self.send(build)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
            result = g.send(result)
          File "githubintegration.py", line 134, in send
            m = re.search(r"refs/pull/([0-9]*)/merge", branch)
          File "/usr/lib/python2.7/re.py", line 146, in search
            return _compile(pattern, flags).search(string)
        exceptions.TypeError: expected string or buffer
```

**Comment by krf** [comment]
CC'ing @anish @jangmarker

**Comment by tardyp** [comment]
what is this githubintegration.py file? does not look like a file in buildbot codebase.

```
          File "githubintegration.py", line 134, in send
```

**Comment by jangmarker** [comment]
@tardyp githubintegration.py is a nearly 1:1 copy of upstream's github.py.

**Comment by krf** [comment]
Update: We're using github.py from upstream now.

Issue still remains:
```
2018-01-03 01:11:23+0100 [-] while invoking <bound method GitHubStatusPush.buildFinished of <buildbot.reporters.github.GitHubStatusPush object at 0x7fddf4ad8590>>
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1357, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
            result = g.send(result)
          File "/home/build/opt/lib/python2.7/site-packages/buildbot-0.9.15.dev12-py2.7.egg/buildbot/reporters/http.py", line 84, in getMoreInfoAndSend
            yield self.send(build)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
            result = g.send(result)
          File "/home/build/opt/lib/python2.7/site-packages/buildbot-0.9.15.dev12-py2.7.egg/buildbot/reporters/github.py", line 135, in send
            m = re.search(r"refs/pull/([0-9]*)/merge", branch)
          File "/usr/lib/python2.7/re.py", line 146, in search
            return _compile(pattern, flags).search(string)
        exceptions.TypeError: expected string or buffer
```

**Comment by umar456** [comment]
I am also having the same issue. Here is the log:

```
buildbot_1       | 2018-05-10 05:55:40+0000 [-] while invoking <bound method GitHubStatusPush.buildStarted of <buildbot.reporters.github.GitHubStatusPush object at 0x7f1a3b78bf90>>
buildbot_1       | 	Traceback (most recent call last):
buildbot_1       | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
buildbot_1       | 	    _inlineCallbacks(r, g, deferred)
buildbot_1       | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
buildbot_1       | 	    result = g.send(result)
buildbot_1       | 	  File "/usr/lib/python2.7/site-packages/buildbot/reporters/http.py", line 84, in getMoreInfoAndSend
buildbot_1       | 	    yield self.send(build)
buildbot_1       | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
buildbot_1       | 	    return _inlineCallbacks(None, gen, Deferred())
buildbot_1       | 	--- <exception caught here> ---
buildbot_1       | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
buildbot_1       | 	    result = g.send(result)
buildbot_1       | 	  File "/usr/lib/python2.7/site-packages/buildbot/reporters/github.py", line 136, in send
buildbot_1       | 	    m = re.search(r"refs/pull/([0-9]*)/merge", branch)
buildbot_1       | 	  File "/usr/lib/python2.7/re.py", line 146, in search
buildbot_1       | 	    return _compile(pattern, flags).search(string)
buildbot_1       | 	exceptions.TypeError: expected string or buffer
```

This was created in a Docker container using the following Dockerfile:

```
FROM buildbot/buildbot-master:v1.1.1

RUN apk update && \
    apk add apk-tools && \
    apk add gcc musl-dev python-dev cairo && \
    pip install --upgrade pip && \
    pip install --upgrade twisted && \
    pip install treq buildbot-badges

WORKDIR /var/lib/buildbot
CMD ["dumb-init", "/usr/src/buildbot/docker/start_buildbot.sh"]
```

**Comment by rgerhards** [comment]
We are also seeing this issue. I think we are probably doing something wrong. I think it is possible to call a notifier conditionally, but I admit I do not know how. Am I on the right path?

**Comment by rgerhards** [comment]
After some more digging, it looks like I can use the ```builders=[...]``` parameter to list all non-nightly builders that should use the status push. That's a doable workaround, but I admit it's a bit painful: we have many builders that react on pull requests (~50) and some are added and removed regularly. We have a single nightly one, with maybe a handful of more to come. So it would be great if we could say "all builders but xxx" in the ```builders``` parameter.

**Comment by yhager** [comment]
I'm seeing the exact same issue in bb 2.3.1, twisted 19.2.1, python 3.7.
In my case I can't filter out the builders list because I use the same builder for pull requests as well as nightly builds.
