### ISSUE TITLE
UnicodeEncodeError in SVNPoller (0.9.15)

### ISSUE THREAD

**Issue by cmumford** [buildbot/buildbot#3865]
I just upgraded from 0.9.11 to 0.9.15, but this may not be a new issue. The SVN log message in r663 is: "Adding some of François's stuff".

```
2018-01-02 22:50:18+0000 [-] SVNPoller: _process_changes 662 .. 663
2018-01-02 22:50:18+0000 [-] Adding change revision 663
2018-01-02 22:50:18+0000 [-] SVNPoller: Error in  while polling
        Traceback (most recent call last):
          File "/home/chris/continuous-build/buildbot/buildbotvenv/lib/python3.4/site-packages/twisted/internet/_baseprocess.py", line 64, in maybeCallProcessEnded
            proto.processEnded(Failure(reason))
          File "/home/chris/continuous-build/buildbot/buildbotvenv/lib/python3.4/site-packages/twisted/internet/utils.py", line 93, in processEnded
            self.deferred.callback(self.s.getvalue())
          File "/home/chris/continuous-build/buildbot/buildbotvenv/lib/python3.4/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/home/chris/continuous-build/buildbot/buildbotvenv/lib/python3.4/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/home/chris/continuous-build/buildbot/buildbotvenv/lib/python3.4/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/chris/continuous-build/buildbot/buildbotvenv/lib/python3.4/site-packages/buildbot/changes/svnpoller.py", line 360, in create_changes
            path = path.encode("ascii")
        builtins.UnicodeEncodeError: 'ascii' codec can't encode character '\u0327' in position 43: ordinal not in range(128)

2018-01-02 22:51:11+0000 [-] SVNPoller: polling
```

**Comment by cmumford** [comment]
Looks like the cause is the file path not the comment:

```
/UE4/StarryExpanse/Content/Developers/François/
```

**Comment by rodrigc** [comment]
Can you provide the full raw log of r663 in XML format?

something like:

```
svn log --xml -r663
```

**Comment by rodrigc** [comment]
According to http://svnbook.red-bean.com/en/1.7/svn.advanced.l10n.html , Subversion internally  stores paths encoded as UTF-8, so we need to improve the code in buildbot, and maybe
add some tests with some paths which have non-ASCII characters.

**Comment by cmumford** [comment]
I see @tardyp fixed this already. Here's the log, and I'll test it tonight.

```xml
svn log --xml --verbose -r663 file:///path/to/repo
<?xml version="1.0" encoding="UTF-8"?>
<log>
<logentry
   revision="663">
<author>philip</author>
<date>2018-01-02T22:50:09.157379Z</date>
<paths>
<path
   action="A"
   prop-mods="false"
   text-mods="false"
   kind="dir">/UE4/StarryExpanse/Content/Developers/François</path>
<path
   kind="dir"
   action="A"
   prop-mods="false"
   text-mods="false">/UE4/StarryExpanse/Content/Developers/François/Collections</path>
<path
   kind="dir"
   action="A"
   prop-mods="false"
   text-mods="false">/UE4/StarryExpanse/Content/Developers/François/Misc</path>
<path
   action="A"
   prop-mods="true"
   text-mods="true"
   kind="file">/UE4/StarryExpanse/Content/Developers/François/Misc/LUT_Fall.uasset</path>
<path
   prop-mods="false"
   text-mods="false"
   kind="dir"
   action="A">/UE4/StarryExpanse/Content/Developers/François/TestMaps</path>
<path
   action="A"
   prop-mods="true"
   text-mods="true"
   kind="file">/UE4/StarryExpanse/Content/Developers/François/TestMaps/TestGehnLab.umap</path>
</paths>
<msg>Adding some of François's stuff</msg>
</logentry>
</log>
```
