### ISSUE TITLE
'Interpolate' does not support the buffer interface - SMTP password

### ISSUE THREAD

**Issue by trevorhook** [buildbot/buildbot#3870]
> buildbot version = 0.9.14

I'm attempting to set up a Mail Notifier using the file base secrets provider to store the password.

The mail notifier configuration I'm using is
```
mn = reporters.MailNotifier(
   fromaddr="{{redacted}}",
   sendToInterestedUsers=False,
   extraRecipients=[{{redacted}}],
   relayhost="{{redacted}}",
   useSmtps=True,
   smtpPort=465,
   smtpUser="{{redacted}}",
   smtpPassword=util.Interpolate('%(secret:buildbotmail-password)s'),
   mode=('all')
)
c['services'].append(mn)
```

The secrets service provider being used is successfully supplying passwords in other parts of the configuration, specifically in command line ftp operation.

When a job completes I get the following error messages in the twistd.log

```
2018-01-04 07:07:29+0000 [ESMTPSender (TLSMemoryBIOProtocol),client] SMTP Client retrying server. Retry: 1
2018-01-04 07:07:29+0000 [ESMTPSender (TLSMemoryBIOProtocol),client] Unhandled Error
Traceback (most recent call last):
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/python/log.py", line 103, in callWithLogger
return callWithContext({"system": lp}, func, args, **kw)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/python/log.py", line 86, in callWithContext
return context.call({ILogContext: newCtx}, func, args, kw)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/python/context.py", line 122, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, kw)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/python/context.py", line 85, in callWithContext
return func(*args,**kw)
--- <exception caught here> ---
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
why = selectable.doRead()
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/tcp.py", line 205, in doRead
return self._dataReceived(data)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
rval = self.protocol.dataReceived(data)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
self._flushReceiveBIO()
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
ProtocolWrapper.dataReceived(self, bytes)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
self.wrappedProtocol.dataReceived(data)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
why = self.lineReceived(line)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/mail/smtp.py", line 996, in lineReceived
why = self._okresponse(self.code, b'\n'.join(self.resp))
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/mail/smtp.py", line 1588, in smtpState_maybeAuthenticated
self._authResponse(self._authinfo, resp)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/mail/smtp.py", line 1573, in _authResponse
self.sendLine(base64.b64encode(resp))
File "/srv/buildbot2/bb-master/lib/python3.4/base64.py", line 62, in b64encode
encoded = binascii.b2a_base64(s)[:-1]
builtins.TypeError: 'Interpolate' does not support the buffer interface
```

There is then a second block of traceback in the twistd.log for an unhandled error in Deferred:

```
2018-01-04 07:07:29+0000 [-] Unhandled error in Deferred:
2018-01-04 07:07:29+0000 [-] Unhandled Error
Traceback (most recent call last):
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/defer.py", line 500, in errback
self._startRunCallbacks(fail)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
self._runCallbacks()
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/defer.py", line 1442, in gotResult
_inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/buildbot/reporters/notifier.py", line 280, in buildMessage
list(users), patches, logs)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/buildbot/reporters/mail.py", line 271, in sendMessage
yield self.sendMail(m, all_recipients)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
why = selectable.doRead()
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/tcp.py", line 205, in doRead
return self._dataReceived(data)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
rval = self.protocol.dataReceived(data)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
self._flushReceiveBIO()
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
ProtocolWrapper.dataReceived(self, bytes)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
self.wrappedProtocol.dataReceived(data)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
why = self.lineReceived(line)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/mail/smtp.py", line 996, in lineReceived
why = self._okresponse(self.code, b'\n'.join(self.resp))
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/mail/smtp.py", line 1588, in smtpState_maybeAuthenticated
self._authResponse(self._authinfo, resp)
File "/srv/buildbot2/bb-master/lib/python3.4/site-packages/twisted/mail/smtp.py", line 1573, in _authResponse
self.sendLine(base64.b64encode(resp))
File "/srv/buildbot2/bb-master/lib/python3.4/base64.py", line 62, in b64encode
encoded = binascii.b2a_base64(s)[:-1]
builtins.TypeError: 'Interpolate' does not support the buffer interface

2018-01-04 07:07:30+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0xb2bfc630>
```

**Comment by tardyp** [comment]
That is because MailNotifier does not support SecretManager yes. I'll fix that soon
