### ISSUE TITLE
'BitbucketServerStatusPush' object has no attribute '_buildCompleteConsumer'

### ISSUE THREAD

**Issue by kocsenc** [buildbot/buildbot#3943]
I was setting up the `BitbucketServerStatusPush` following the guide [here](http://buildbot.readthedocs.io/en/latest/manual/cfg-reporters.html?highlight=report#bitbucketserverstatuspush).

It had me install `treq` (may be irrelevant) and then whenever I try to run `buildbot start`: 

```
2018-02-08 10:25:40-0800 [-] BuildMaster startup failed
2018-02-08 10:25:40-0800 [-] Initiating clean shutdown
2018-02-08 10:25:40-0800 [-] No running jobs, starting shutdown immediately
2018-02-08 10:25:40-0800 [-] Unhandled error in Deferred:
2018-02-08 10:25:40-0800 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 457, in callback
            self._startRunCallbacks(result)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1355, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/master.py", line 348, in stopService
            yield service.AsyncMultiService.stopService(self)
        twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'BitbucketServerStatusPush' object has no attribute '_buildCompleteConsumer'
        /usr/lib/python2.7/site-packages/buildbot/master.py:348:stopService
        /usr/lib/python2.7/site-packages/buildbot/util/service.py:96:stopService
        /usr/lib64/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
        /usr/lib/python2.7/site-packages/buildbot/util/service.py:96:stopService
        --- <exception caught here> ---
        /usr/lib64/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
        /usr/lib/python2.7/site-packages/buildbot/reporters/http.py:66:stopService
        ]]
        ]]

2018-02-08 10:25:40-0800 [-] Main loop terminated.
2018-02-08 10:25:40-0800 [-] Server Shut Down.
```

### Notes
Commenting out the `BitbucketServerStatusPush` lines from `master.cfg` allows buildbot to start successfully.

### Version

```bash
$ buildbot --version
Buildbot version: 0.9.15
Twisted version: 16.6.0
```

**Comment by kocsenc** [comment]
Just updated `Twisted` and still same error :(

```bash
$ buildbot --version
Buildbot version: 0.9.15
Twisted version: 17.9.0
```

**Comment by kocsenc** [comment]
This was a config error, cannot end in a `/`

**Comment by seankelly** [comment]
Which part cannot end in a `/`?

**Comment by kocsenc** [comment]
@seankelly: the host URL in the ‘master.cfg’ cannot end in a ‘/’.

**Comment by tardyp** [comment]
@kocsenc would you like to make a patch in order to support base_url configuration with trailing / ?
like done here:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/reporters/bitbucket.py#L52

to be ported here:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/reporters/bitbucketserver.py#L50
