### ISSUE TITLE
"Command 'TASKKILL /F /PID 102996 /T' returned non-zero exit status 1" on windows worker 

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3978]
System of worker PC is Win10 64bit and my master version is 0.9.11. Error happens if master is restarted when the worker has a running task.
```python
2018-03-05 19:03:48+0800 [HangCheckProtocol,client] message from master: ping
2018-03-05 19:03:49+0800 [HangCheckProtocol,client] leftover command, dropping it
2018-03-05 19:03:49+0800 [HangCheckProtocol,client] stopCommand: halting current command <buildbot_worker.commands.shell.WorkerShellCommand object at 0x0000000004266940>
2018-03-05 19:03:49+0800 [HangCheckProtocol,client] command interrupted, attempting to kill
2018-03-05 19:03:49+0800 [HangCheckProtocol,client] using TASKKILL PID /F /T to kill pid 102996
2018-03-05 19:03:49+0800 [HangCheckProtocol,client] Peer will receive following PB traceback:
2018-03-05 19:03:49+0800 [HangCheckProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\spread\banana.py", line 173, in gotItem
	    self.callExpressionReceived(item)
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\spread\banana.py", line 136, in callExpressionReceived
	    self.expressionReceived(obj)
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\spread\pb.py", line 575, in expressionReceived
	    method(*sexp[1:])
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\spread\pb.py", line 896, in proto_message
	    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
	--- <exception caught here> ---
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\spread\pb.py", line 913, in _recvMessage
	    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
	  File "d:\buildbot\sandbox\lib\site-packages\twisted\spread\flavors.py", line 120, in remoteMessageReceived
	    state = method(*args, **kw)
	  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\base.py", line 139, in remote_startCommand
	    self.stopCommand()
	  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\base.py", line 174, in stopCommand
	    self.command.doInterrupt()  # shut up! and die!
	  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\commands\base.py", line 192, in doInterrupt
	    self.interrupt()
	  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\commands\shell.py", line 58, in interrupt
	    self.command.kill("command interrupted")
	  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 933, in kill
	    hit = self.sendSig(self.interruptSignal)
	  File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 890, in sendSig
	    "TASKKILL /F /PID %s /T" % self.process.pid)
	  File "c:\python27\Lib\subprocess.py", line 186, in check_call
	    raise CalledProcessError(retcode, cmd)
	subprocess.CalledProcessError: Command 'TASKKILL /F /PID 102996 /T' returned non-zero exit status 1
```

If I restart the build manually, this error still exists.

And the error message printed on worker CMD is:
>The paging file is too small for this operation to complete. 

And the process is not killed:
![image](https://user-images.githubusercontent.com/19603852/36972811-8932cf5a-20ab-11e8-81d3-d33044043b57.png)

However, the machine this worker works on has 64 GB RAM and I don't find any RAM problem.

The only solution I found is to restart the worker which bothers.

**Comment by tardyp** [comment]
This looks like a windows expertise issue, maybe you can ask on windows support forums.

if you manually do:

    TASKKILL /F /PID 102996 /T'

do you have same message?
Can you think of a better command line that we could issue if the former one fail?

**Comment by lancelodliu** [comment]
Running the command manually gave me the same error message. My WMI [seems to be corrupted](https://serverfault.com/questions/733531/wmi-issue-the-paging-file-is-too-small-for-this-operation-to-complete). It seems that one must set the virtual RAM to 8GB to avoid this and maybe it's because the worker has been running for months. This problem didn't show up for the last 2 months.

**Comment by tardyp** [comment]
So we have confirmation Buildbot cannot do much about that. closing. thanks for report, we still have a trace of what is needing:

    winmgmt /verifyrepository
