### ISSUE TITLE
Unicode exception after every build.  1.0.0 and 1.1.0

### ISSUE THREAD

**Issue by kallisti5** [buildbot/buildbot#4003]
After successful builds, every one fails with an exception.  The UI doesn't list any errors, but looking at the logs...

```
buildbot_1     | 2018-03-16 18:31:32+0000 [-] releaseLocks(ShellCommand(haltOnFailure=True, workdir='generated', description=['jam'], descriptionDone=['jam'], timeout=3600, descriptionSuffix=[['@minimum-raw']], env=renderer(<function renderJamEnvironment at 0x7f1c0a899050>), command=renderer(<function renderJamCommand at 0x7f1c0a892f50>), name='jam @minimum-raw')): []
buildbot_1     | 2018-03-16 18:31:32+0000 [-] <Build haiku-master-ppc number:3 results:success>.buildException
buildbot_1     | 2018-03-16 18:31:32+0000 [-] Unhandled Error
buildbot_1     | 	Traceback (most recent call last):
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
buildbot_1     | 	    return _inlineCallbacks(None, gen, Deferred())
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
buildbot_1     | 	    result = g.send(result)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/process/build.py", line 555, in stepDone
buildbot_1     | 	    summary = yield step.getBuildResultSummary()
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
buildbot_1     | 	    return _inlineCallbacks(None, gen, Deferred())
buildbot_1     | 	--- <exception caught here> ---
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
buildbot_1     | 	    result = g.send(result)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 470, in getBuildResultSummary
buildbot_1     | 	    summary = yield self.getResultSummary()
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/steps/shell.py", line 193, in getResultSummary
buildbot_1     | 	    return super(ShellCommand, self).getResultSummary()
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 459, in getResultSummary
buildbot_1     | 	    stepsumm += u' ' + util.join_list(self.descriptionSuffix)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/util/__init__.py", line 428, in join_list
buildbot_1     | 	    return u' '.join(bytes2unicode(s) for s in maybeList)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/util/__init__.py", line 428, in <genexpr>
buildbot_1     | 	    return u' '.join(bytes2unicode(s) for s in maybeList)
buildbot_1     | 	  File "/usr/lib/python2.7/site-packages/buildbot/util/__init__.py", line 228, in bytes2unicode
buildbot_1     | 	    return text_type(x, encoding, errors)
buildbot_1     | 	exceptions.TypeError: coercing to Unicode: need string or buffer, list found
buildbot_1     | 	
```

Same error over and over.

**Comment by kallisti5** [comment]
I did just port our buildbot config from 0.8.x to 1.1.0, so it is possible I made a mistake somewhere... we have a *massive* master.cfg for Haiku.  Given the nature of the error... we might be doing something that doesn't agree with buildbot 1.1.0, however there is nothing obvious I can find from the error.

I went ahead and sanitized it and got it into our new infrastructure git repo. Feel free to poke around.

https://github.com/haiku/infrastructure/blob/master/data/buildbot/master.cfg

**Comment by kallisti5** [comment]
Actually.. this might be on us.

Found an array wrapped in an array (descriptionSuffix below)
Buildbot 0.8.x may just not of cared... but 1.1.0 does!

```python
		filteredJamTargetElements = [
			# Skip everything starting with '-s', in order to
			# simplify the view. Additionally, HTML-escape the
			# text in order to preserve something like
			# <repository>Haiku in HTML views.
			cgi.escape(target) for target in jamTarget.split()
			if not target.startswith('-s')
		]
		factory.addStep(
			ShellCommand(
				command = renderJamCommand,
				description = ['jam'],
				descriptionDone = ['jam'],
				descriptionSuffix = [filteredJamTargetElements],
				name = 'jam ' + ' '.join(filteredJamTargetElements),
				haltOnFailure = True,
				workdir = generatedDir,
				env = renderJamEnvironment,
				timeout = 3600))
```

Testing now.

**Comment by kallisti5** [comment]
Yeah, removing the double array fixed it.  Sorry for spam. Resolved.
