### ISSUE TITLE
How to auto restart master if it is terminated.

### ISSUE THREAD

**Issue by meritozh** [buildbot/buildbot#4005]
Log is:

```
2018-03-16 18:53:24+0800 [_GenericHTTPChannelProtocol,1510,10.200.55.139] X-GitHub-Event: push
2018-03-16 18:53:24+0800 [_GenericHTTPChannelProtocol,1510,10.200.55.139] New revision: 160693d7
2018-03-16 18:53:24+0800 [_GenericHTTPChannelProtocol,1510,10.200.55.139] Received 1 changes from github
2018-03-16 18:53:24+0800 [_GenericHTTPChannelProtocol,1510,10.200.55.139] WARNING: change source is using deprecated self.master.addChange method; this method will disappear in Buildbot-1.0.0
2018-03-16 18:53:24+0800 [-] added change with revision 160693d7874fae174a7079644a960e84dfa6a2ff to database
2018-03-16 18:53:24+0800 [-] injected change Change(revision=u'160693d7874fae174a7079644a960e84dfa6a2ff', who=u'xxx', when=1521197599, category=None, project=u'waimai/nevermore', repository=u'https://github.elenet.me/waimai/nevermore', codebase=u'nevermore')
2018-03-16 18:53:27+0800 [-] Received SIGTERM, shutting down.
```

Backtrace is:

```
2018-03-16 18:53:28+0800 [-] BuildMaster is stopped
2018-03-16 18:53:28+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1117, in _cbDeferred
	    self.callback(self.resultList)
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
	    self._startRunCallbacks(result)
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
	    callable(*args, **kwargs)
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/txrequests/sessions.py", line 46, in <lambda>
	    reactor.addSystemEventTrigger("after", "shutdown", lambda: pool.stop())
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/python/threadpool.py", line 278, in stop
	    self._team.quit()
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/_threads/_team.py", line 226, in quit
	    self._quit.set()
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 35, in set
	    self.check()
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 46, in check
	    raise AlreadyQuit()
	twisted._threads._ithreads.AlreadyQuit: 
	
2018-03-16 18:53:28+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 1117, in _cbDeferred
	    self.callback(self.resultList)
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
	    self._startRunCallbacks(result)
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
	    callable(*args, **kwargs)
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/txrequests/sessions.py", line 46, in <lambda>
	    reactor.addSystemEventTrigger("after", "shutdown", lambda: pool.stop())
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/python/threadpool.py", line 278, in stop
	    self._team.quit()
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/_threads/_team.py", line 226, in quit
	    self._quit.set()
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 35, in set
	    self.check()
	  File "/Users/waimai/BuildBot/bb-travis/sandbox/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 46, in check
	    raise AlreadyQuit()
	twisted._threads._ithreads.AlreadyQuit: 
	
2018-03-16 18:53:28+0800 [-] Main loop terminated.
2018-03-16 18:53:28+0800 [-] Server Shut Down.
```

I don't know what happened. I want the master can be restart automatically if it is terminated. How to do it?

**Comment by adydychk** [comment]
In our team we start Buildbot as systemd service to auto-restart in case of any Buildbot`s termination.

**Comment by seankelly** [comment]
2018-03-16 18:53:27+0800 [-] Received SIGTERM, shutting down.

Buildbot shut down because something told it to.
