### ISSUE TITLE
Latent Docker throwing exceptions

### ISSUE THREAD

**Issue by gregorydlogan** [buildbot/buildbot#4010]
Virtualenv with:
- docker (3.1.4)
- docker-py (1.10.6)
- docker-pycreds (0.2.2)

Worker(s) are remote VMs running Docker, with their Docker socket reverse forwarded via SSH.  Worker definition looks like this:

worker.DockerLatentWorker("docker", password=None,
                docker_host='unix:///opt/buildbot/sockets/builder.sock',
                image='greglogan/ocqa-jessie',
                masterFQDN="http://localhost:9989",
                autopull=True, alwaysPull=True),

Upon build start I get this ugly stack trace:

> 2018-03-21 11:50:08-0600 [-] substantiating worker <LatentWorkerForBuilder builder=u'Develop Build' worker=u'docker' state=DETACHED>
2018-03-21 11:50:08-0600 [-] while worker_prepare
        Traceback (most recent call last):
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
        --- <exception caught here> ---
          File "/opt/buildbot/local/lib/python2.7/site-packages/buildbot/process/build.py", line 336, in startBuild
            ready_or_failure = yield workerforbuilder.prepare(self)
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/opt/buildbot/local/lib/python2.7/site-packages/buildbot/worker/docker.py", line 203, in start_instance
            res = yield threads.deferToThread(self._thd_start_instance, image, dockerfile, volumes)
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
            result = inContext.theWork()
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/opt/buildbot/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/opt/buildbot/local/lib/python2.7/site-packages/buildbot/worker/docker.py", line 217, in _thd_start_instance
            docker_client = self._getDockerClient()
          File "/opt/buildbot/local/lib/python2.7/site-packages/buildbot/worker/docker.py", line 193, in _getDockerClient
            docker_client = client.APIClient(**self.client_args)
          File "/opt/buildbot/local/lib/python2.7/site-packages/docker/api/client.py", line 110, in __init__
            config_dict=self._general_configs
        exceptions.TypeError: load_config() got an unexpected keyword argument 'config_dict'

Appears to be related to https://github.com/docker/docker-py/issues/1916, however I can't seem to find a correct combination of docker bits to get this working.  Any suggestions?

**Comment by gregorydlogan** [comment]
Bah, forgot to mention the worker is Docker version 17.12.1-ce, build 7390fc6, running on Debian 9.

**Comment by gregorydlogan** [comment]
Ah, figured it out.  The correct Docker python package is just 'docker'.  The old, unmaintained 'docker-py' package causes conflicts.  Removing that package resolved this issue.
