### ISSUE TITLE
While running ```make frontend```, getting installation error around Cairo, cairocffi

### ISSUE THREAD

**Issue by uglycoyote** [buildbot/buildbot#4035]
A couple times while trying to ```make frontend``` I have run in to an issue around this Cairo/CairoCFFI business.  This seems to be a new dependency of the ```badges``` module.

Here's the error:

```
Obtaining file:///Users/mike/development/buildbot-work/uglycoyote/buildbot/www/badges
Collecting klein (from buildbot-badges==1.1.2.dev7)
  Using cached klein-17.10.0-py2.py3-none-any.whl
Collecting CairoSVG==1.0.22 (from buildbot-badges==1.1.2.dev7)
  Using cached CairoSVG-1.0.22.tar.gz
Collecting cairocffi (from buildbot-badges==1.1.2.dev7)
  Using cached cairocffi-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'cffi' (maybe misspelled?)
    No local packages or working download links found for cffi>=1.1.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/40/qz_qn8sd1hj_2c6s501t68v00000gn/T/pip-install-HJ_sOl/cairocffi/setup.py", line 44, in <module>
        extras_require={'xcb': ['xcffib>=0.3.2']},
      File "/Users/mike/development/buildbot-work/uglycoyote/buildbot/.venv/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
 ```

**Comment by tardyp** [comment]
it is, you need to install libcffi-dev or similar:

 sudo apt-get install libffi-dev

**Comment by uglycoyote** [comment]
your advice solved the issue for me, though it seems odd to have to install this manually.  

Please feel free to close the issue if it is intended to be installed manually,  or leave the issue open if it seems like an unaddressed issue, where this should be being installed through the ```make frontend``` process in an automated way.
