### ISSUE TITLE
buildbot try client issue on python3

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#4037]
As reported on irc by xpetri:

```
buildbot try --connect=pb --master=127.0.0.1:5555 --username=sampleuser --passwd=simplepass --vc=git
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/twisted/internet/_baseprocess.py", line 64, in maybeCallProcessEnded
    proto.processEnded(Failure(reason))
  File "/usr/lib/python3.6/site-packages/twisted/internet/utils.py", line 163, in processEnded
    self.deferred.callback((out, err, code))
  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 459, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python3.6/site-packages/buildbot/clients/tryclient.py", line 921, in trapSystemExit
    why.trap(SystemExit)
  File "/usr/lib/python3.6/site-packages/twisted/python/failure.py", line 359, in trap
    self.raiseException()
  File "/usr/lib/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python3.6/site-packages/buildbot/clients/tryclient.py", line 382, in parseStatus
    m = re.search(r'^\* (\S+)\s+([0-9a-f]{40})', res, re.MULTILINE)
  File "/usr/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
builtins.TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by rodrigc** [comment]
Twisted's `getProcessOutput`, which is called by `getProcessOutputAndValue` returns `bytes`:

```
def getProcessOutput(executable, args=(), env={}, path=None, reactor=None,
                     errortoo=0):
    """
    Spawn a process and return its output as a deferred returning a L{bytes}.
```

So this entire file needs some spring cleaning to get this to work properly on Py2 and Py3.

**Comment by rodrigc** [comment]
@xpetrl can you try the fix in https://github.com/buildbot/buildbot/pull/4038
by creating a new virtualenv and doing:

python -m pip install "git+https://github.com/rodrigc/buildbot.git@try-py3#egg=pkg&subdirectory=master"

The buildbot version number will be 0.9.0 but that is wrong.  It is the latest stuff with my patch.

**Comment by xpetrl** [comment]
virtualenv python-2.7:

buildbot try --connect=pb --master=127.0.0.1:5555 --username=sampleuser --passwd=samplepass --vc=git
8Unhandled Error
Traceback (most recent call last):
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/twisted/spread/pb.py", line 621, in expressionReceived
    method(*sexp[1:])
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/twisted/spread/pb.py", line 1105, in proto_answer
    d.callback(self.unserialize(netResult))
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
    self._startRunCallbacks(result)
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/buildbot/clients/tryclient.py", line 922, in trapSystemExit
    why.trap(SystemExit)
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/twisted/python/failure.py", line 359, in trap
    self.raiseException()
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/buildbot/clients/tryclient.py", line 689, in _deliverJob_pb
    output("Delivering job; comment=", self.comment)
  File "/home/me/dev/27-bb-client-try/lib/python2.7/site-packages/buildbot/clients/tryclient.py", line 55, in output
    log.msg(u' '.join([bytes2unicode(m) for m in msg]))
exceptions.TypeError: sequence item 1: expected string or Unicode, NoneType found

**Comment by xpetrl** [comment]
virtualenv python-3.6:

buildbot try --connect=pb --master=127.0.0.1:5555 --username=sampleuser --passwd=samplepass --vc=git
Unhandled Error
Traceback (most recent call last):
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/spread/pb.py", line 621, in expressionReceived
    method(*sexp[1:])
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/spread/pb.py", line 1105, in proto_answer
    d.callback(self.unserialize(netResult))
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/internet/defer.py", line 459, in callback
    self._startRunCallbacks(result)
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/buildbot/clients/tryclient.py", line 922, in trapSystemExit
    why.trap(SystemExit)
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/python/failure.py", line 359, in trap
    self.raiseException()
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/spread/pb.py", line 1387, in _cbResponse
    return challenger.callRemote("respond", respond(challenge, password), client)
  File "/home/me/dev/36-bb-client-try/lib/python3.6/site-packages/twisted/spread/pb.py", line 1257, in respond
    m.update(password)
builtins.TypeError: Unicode-objects must be encoded before hashing

**Comment by rodrigc** [comment]
@xpetrl I've updated the branch with help from @tardyp.  Can you try again with a new virtualenv:

```
python -m pip install "git+https://github.com/rodrigc/buildbot.git@try-py3#egg=pkg&subdirectory=master"
```

**Comment by sebhub** [comment]
I tried the buildbot tutorial and ended up with this error in step: 1.3.8. Adding a ‘try’ scheduler.
