### ISSUE TITLE
Maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4042]
Noticed this exception during buildbot start. I am using Buildbot 1.1.1

2018-04-11 21:06:54-0700 [-] Unhandled error in Deferred:
2018-04-11 21:06:54-0700 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1429, in _inlineCallbacks
            deferred.callback(e.value)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/spread/pb.py", line 1117, in _sendFailureOrError
            self._sendFailure(fail, requestID)
          File "/usr/lib64/python2.7/site-packages/twisted/spread/pb.py", line 1129, in _sendFailure
            log.msg("Peer will receive following PB traceback:")
          File "/usr/lib64/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync 
            return function(self, *args, **kwargs)
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 286, in msg
            _publishNew(self._publishPublisher, actualEventDict, textFromEventDict)
          File "/usr/lib64/python2.7/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
            observer(eventDict)
          File "/usr/lib64/python2.7/site-packages/twisted/logger/_observer.py", line 133, in __call__
            brokenObservers.append((observer, Failure()))
        exceptions.RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by aj062** [comment]
Many of the workers are not able to connect to the master, can that be due to this error.

**Comment by aj062** [comment]
Another exception:

```
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1429, in _inlineCallbacks
            deferred.callback(e.value)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/spread/pb.py", line 1117, in _sendFailureOrError
            self._sendFailure(fail, requestID)
          File "/usr/lib64/python2.7/site-packages/twisted/spread/pb.py", line 1129, in _sendFailure
            log.msg("Peer will receive following PB traceback:")
          File "/usr/lib64/python2.7/site-packages/twisted/python/threadable.py", line 53, in sync 
            return function(self, *args, **kwargs)
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 286, in msg
            _publishNew(self._publishPublisher, actualEventDict, textFromEventDict)
          File "/usr/lib64/python2.7/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
            observer(eventDict)
          File "/usr/lib64/python2.7/site-packages/twisted/logger/_observer.py", line 136, in __call__
            errorLogger = self._errorLoggerForObserver(brokenObserver)
          File "/usr/lib64/python2.7/site-packages/twisted/logger/_observer.py", line 156, in _errorLoggerForObserver
            if obs is not observer
          File "/usr/lib64/python2.7/site-packages/twisted/logger/_observer.py", line 81, in __init__
            self.log = Logger(observer=self)
          File "/usr/lib64/python2.7/site-packages/twisted/logger/_logger.py", line 52, in __init__
            namespace = self._namespaceFromCallingContext()
          File "/usr/lib64/python2.7/site-packages/twisted/logger/_logger.py", line 32, in _namespaceFromCallingContext
            return currentframe(2).f_globals["__name__"]
        exceptions.RuntimeError: maximum recursion depth exceeded
```

**Comment by aj062** [comment]
Another one:
```
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/buildbot/pbmanager.py", line 217, in requestAvatarId
            yield self.master.initLock.release()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1640, in release
            d.callback(self)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
            self._startRunCallbacks(result)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1432, in _inlineCallbacks
            deferred.errback()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 500, in errback
            self._startRunCallbacks(fail)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 666, in _runCallbacks
            current.result = failure.Failure(captureVars=self.debug)
          File "/usr/lib64/python2.7/site-packages/twisted/python/failure.py", line 206, in __init__
            if isinstance(exc_value, str) and exc_type is None:
        exceptions.RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by aj062** [comment]
Adding "sys.setrecursionlimit(10000)" in master.cfg helps. Probably this issue is visible only when there are large number of workers configured on a master.

**Comment by tardyp** [comment]
Did you upgrade your twisted as well?
This exception looks in the logging system. Did you change the way the logging is handled?

**Comment by aj062** [comment]
> This exception looks in the logging system. Did you change the way the logging is handled?

No, I didn't touch the Twisted version. It was 17.5.0.

**Comment by aj062** [comment]
As discussed on IRC, all 3 exceptions referred above seems to be while generating error for UnauthorizedLogin()

First two exceptions have this:
```
File "/usr/lib64/python2.7/site-packages/twisted/spread/pb.py", line 1129, in _sendFailure
log.msg("Peer will receive following PB traceback:")
```
This is while generating error message for UnauthorizedLogin() in https://github.com/buildbot/buildbot/blob/master/master/buildbot/pbmanager.py#L215

Third one is in https://github.com/buildbot/buildbot/blob/master/master/buildbot/pbmanager.py#L217 in master.initLock.release()

This code was added in https://git.io/vxjTY

@rjarry any ideas?

**Comment by rjarry** [comment]
Maybe the problem is that only one worker may authenticate at a time. Which causes a too big waiting queue.

My original idea was to forbid the workers to try to connect while the master is still starting up.

Maybe another approach would be better. Only wait for the lock if it is already locked and release it right away:

```diff
diff --git a/master/buildbot/pbmanager.py b/master/buildbot/pbmanager.py
index b649330ec9f7..76748a16da6f 100644
--- a/master/buildbot/pbmanager.py
+++ b/master/buildbot/pbmanager.py
@@ -197,21 +197,24 @@ class Dispatcher(service.AsyncService):
 
     @defer.inlineCallbacks
     def requestAvatarId(self, creds):
+        if self.master.initLock.locked:
+            # wait for the master init to be finished before trying to
+            # authenticate anyone.
+            try:
+                yield self.master.initLock.acquire()
+            finally:
+                yield self.master.initLock.release()
         p = Properties()
         p.master = self.master
         username = bytes2unicode(creds.username)
-        try:
-            yield self.master.initLock.acquire()
-            if username in self.users:
-                password, _ = self.users[username]
-                password = yield p.render(password)
-                matched = yield defer.maybeDeferred(
-                    creds.checkPassword, unicode2bytes(password))
-                if not matched:
-                    log.msg("invalid login from user '{}'".format(username))
-                    raise error.UnauthorizedLogin()
-                defer.returnValue(creds.username)
-            log.msg("invalid login from unknown user '{}'".format(username))
-            raise error.UnauthorizedLogin()
-        finally:
-            yield self.master.initLock.release()
+        if username in self.users:
+            password, _ = self.users[username]
+            password = yield p.render(password)
+            matched = yield defer.maybeDeferred(
+                creds.checkPassword, unicode2bytes(password))
+            if not matched:
+                log.msg("invalid login from user '{}'".format(username))
+                raise error.UnauthorizedLogin()
+            defer.returnValue(creds.username)
+        log.msg("invalid login from unknown user '{}'".format(username))
+        raise error.UnauthorizedLogin()
```
