### ISSUE TITLE
Database error while downgrading buildbot version

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4044]
I was trying to downgrade from Buildbot 1.1.1 to 0.9.12 (because of https://github.com/buildbot/buildbot/issues/4043), However "buildbot start" asked to do "upgrade-master", which failed with the below error:

```
[bash ~]# buildbot upgrade-master /var/buildbot/build-webserver
checking basedir
checking for running master
checking master.cfg
upgrading basedir
Notice: public_html is not used starting from Buildbot 0.9.0
        consider using third party HTTP server for serving static files
/var/buildbot/build-webserver/master.cfg.sample has old/modified contents
 overwriting it with new contents
upgrading database (postgresql://buildbot_admin:xxxx@localhost/buildbot)
Got fatal Exception on DB
Traceback (most recent call last):
Failure: migrate.exceptions.VersionNotFoundError: "Database schema file with version 51 doesn't exist."

problem while upgrading!:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/buildbot/scripts/upgrade_master.py", line 121, in _upgradeMaster
    yield upgradeDatabase(config, master_cfg)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib64/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/site-packages/buildbot/scripts/upgrade_master.py", line 88, in upgradeDatabase
    yield db.model.upgrade()
  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/site-packages/buildbot/db/pool.py", line 184, in __thd
    rv = callable(arg, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/buildbot/db/model.py", line 851, in thd
    upgrade(engine)
  File "/usr/lib/python2.7/site-packages/buildbot/db/model.py", line 811, in upgrade
    changeset = schema.changeset(None)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/schema.py", line 82, in changeset
    changeset = self.repository.changeset(database, start_ver, version)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/repository.py", line 225, in changeset
    changes = [self.version(v).script(database, op) for v in versions]
  File "/usr/lib/python2.7/site-packages/migrate/versioning/repository.py", line 189, in version
    return self.versions.version(*p, **k)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/version.py", line 174, in version
    "exist.") % {'args': VerNum(vernum)})
VersionNotFoundError: "Database schema file with version 51 doesn't exist."

```

**Comment by tardyp** [comment]
Down grading is not supported :-/

You can manually set the version to 50 or 49 by editing the migrate table. You would have to put it back again later when you re-upgrade.

Probablt the best is to restore a backup. Sorry about that.

**Comment by lgraziani1** [comment]
@tardyp how should I change the table?

If I look into it, I get:
```py
>>> cur.execute('select version from migrate_version limit 1')
1L
```

**Comment by lgraziani1** [comment]
For future reference (tested on 0.9.8):
```py
#!/opt/buildbot/.venv/bin/python2.7
import MySQLdb
# initialize MySQLdb.Connection conn
cur = conn.cursor()
cur.execute('update migrate_version set version=49 where repository_id="Buildbot"')
```
