### ISSUE TITLE
Invalid login from unknown user

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4047]
When a bot which is not in buildbot config tries to connect to build-master, build-master has following exception in the logs. This should be handled gracefully and printed nicely rather than an exception (which fills up the logs):

```
2018-04-13 00:50:59-0700 [Broker,996440] invalid login from unknown user 'bot111'
2018-04-13 00:50:59-0700 [Broker,996440] Peer will receive following PB traceback:
2018-04-13 00:50:59-0700 [Broker,996440] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/spread/pb.py", line 1631, in remote_respond
            d = self.portal.login(self, mind, IPerspective)
          File "/usr/lib64/python2.7/site-packages/twisted/cred/portal.py", line 119, in login
            return maybeDeferred(self.checkers[i].requestAvatarId, credentials
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/pbmanager.py", line 215, in requestAvatarId
            raise error.UnauthorizedLogin()
        twisted.cred.error.UnauthorizedLogin:
```

**Comment by chrisspen** [comment]
I received this too after replacing my master with a backup instance. Although the workers were the same and I re-installed my master with the same codebase, it somehow wouldn't respect the worker's logins. How do you resolve this?
