### ISSUE TITLE
'ascii' codec can't encode character u'\u0308'

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4053]
Noticed this error in a svn up step:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1355, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib64/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 577, in startStep
    self.results = yield self.run()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/site-packages/buildbot/process/buildstep.py", line 707, in run
    results = yield self._start_deferred
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/site-packages/buildbot/steps/source/svn.py", line 356, in parseAndRemove
    for filename in self.getUnversionedFiles(stdout, self.keep_on_purge):
  File "/usr/lib/python2.7/site-packages/buildbot/steps/source/svn.py", line 379, in getUnversionedFiles
    result_xml = xml.dom.minidom.parseString(xmlStr)
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1931, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u0308' in position 244: ordinal not in range(128)

**Comment by rodrigc** [comment]
What version of buildbot are you running?
Does your directory have a filename with the 
```
̈
```
character in it?

**Comment by senyai** [comment]
Is this error reproducible in python 3?
