### ISSUE TITLE
"Unauthorized Login" exception in "requestAvatarId" spamming twistd.log

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#4117]
We're seeing the following spam in the twistd.log - every 15 seconds or so. It is a Windows computer that seems to be causing this. Any ideas?

Python version: 3.5.2
Buildbot version: 1.1.1-dev19
Twisted version: 17.9.0

```
2018-05-27 10:42:46-0700 [Broker,32416,10.0.1.173] invalid login from unknown user 'b'COMBUTERNAMEGOESHERE''
2018-05-27 10:42:46-0700 [Broker,32416,10.0.1.173] Peer will receive following PB traceback:
2018-05-27 10:42:46-0700 [Broker,32416,10.0.1.173] Unhandled Error
	Traceback (most recent call last):
	  File "/home/buildmaster/buildbot/sandbox/lib/python3.5/site-packages/twisted/spread/pb.py", line 1631, in remote_respond
	    d = self.portal.login(self, mind, IPerspective)
	  File "/home/buildmaster/buildbot/sandbox/lib/python3.5/site-packages/twisted/cred/portal.py", line 119, in login
	    return maybeDeferred(self.checkers[i].requestAvatarId, credentials
	  File "/home/buildmaster/buildbot/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/buildmaster/buildbot/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	--- <exception caught here> ---
	  File "/home/buildmaster/buildbot/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/buildmaster/buildbot/src/master/buildbot/pbmanager.py", line 215, in requestAvatarId
	    raise error.UnauthorizedLogin()
	twisted.cred.error.UnauthorizedLogin: 

```

We are not using avatars, and we don't require logins (yet).

Seems like the same error as #4047 but it isn't clear to me if the COMPUTERNAME is running a worker (I don't have access to it at the moment, but I would be surprised)

Any thoughts?

**Comment by sphet** [comment]
Duplicate #4047

**Comment by tardyp** [comment]
@sphet don't hesitate to submit a patch which would rate limit those errors.
