### ISSUE TITLE
GitHub Oauth2 login fails

### ISSUE THREAD

**Issue by noc0lour** [buildbot/buildbot#4134]
Traceback from the master instance:
```
bb-master   | 2018-06-05 09:22:53+0000 [-] While rendering resource:
bb-master   |         Traceback (most recent call last):
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1355, in gotResult
bb-master   |             _inlineCallbacks(r, g, deferred)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1345, in _inlineCallbacks
bb-master   |             deferred.errback()
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 498, in errback
bb-master   |             self._startRunCallbacks(fail)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
bb-master   |             self._runCallbacks()
bb-master   |         --- <exception caught here> ---
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
bb-master   |             current.result = callback(current.result, *args, **kw)
bb-master   |           File "/usr/lib/python3.6/site-packages/buildbot/www/resource.py", line 91, in failHttpError
bb-master   |             f.trap(Error)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/python/failure.py", line 342, in trap
bb-master   |             self.raiseException()
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/python/failure.py", line 368, in raiseException
bb-master   |             raise self.value.with_traceback(self.tb)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
bb-master   |             current.result = callback(current.result, *args, **kw)
bb-master   |           File "/usr/lib/python3.6/site-packages/buildbot/www/resource.py", line 84, in failHttpRedirect
bb-master   |             f.trap(Redirect)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/python/failure.py", line 342, in trap
bb-master   |             self.raiseException()
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/python/failure.py", line 368, in raiseException
bb-master   |             raise self.value.with_traceback(self.tb)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
bb-master   |             result = result.throwExceptionIntoGenerator(g)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
bb-master   |             return g.throw(self.type, self.value, self.tb)
bb-master   |           File "/usr/lib/python3.6/site-packages/buildbot/www/oauth2.py", line 63, in renderLogin
bb-master   |             details = yield self.auth.verifyCode(code)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/python/threadpool.py", line 246, in inContext
bb-master   |             result = inContext.theWork()
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
bb-master   |             inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/python/context.py", line 118, in callWithContext
bb-master   |             return self.currentContext().callWithContext(ctx, func, *args, **kw)
bb-master   |           File "/usr/lib/python3.6/site-packages/twisted/python/context.py", line 81, in callWithContext
bb-master   |             return func(*args,**kw)
bb-master   |           File "/usr/lib/python3.6/site-packages/buildbot/www/oauth2.py", line 173, in thd
bb-master   |             return self.getUserInfoFromOAuthClient(session)
bb-master   |           File "/usr/lib/python3.6/site-packages/buildbot/www/oauth2.py", line 276, in getUserInfoFromOAuthClient
bb-master   |             return self.getUserInfoFromOAuthClient_v4(c)
bb-master   |           File "/usr/lib/python3.6/site-packages/buildbot/www/oauth2.py", line 334, in getUserInfoFromOAuthClient_v4
bb-master   |             for node in team_data['teams']['edges']:
bb-master   |         builtins.TypeError: 'NoneType' object is not subscriptable
```

Configuration of GitHub OAuth is:
```
    "auth": util.GitHubAuth(
        $CLIENT_TOKEN,
        $CLIENT_SECRET,
        apiVersion=4,
        getTeamsMembership=True),
``` 

This works for some, but fails for some users. Logging in on `nine.buildbot.net` for the same person works.

I already tried to solve the issue by recreating the oauth_token & secret to have users to grant missing access rights, but something is still wrong.

**Comment by noc0lour** [comment]
This is already fixed by 3f0ca992e423ae25c6b0d7534c2cbfbad1e36b65
