### ISSUE TITLE
Exception: NoneType object has no attribute 'writeSequence'

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4162]
Noticed this exception is master twistd.log:

```
	Traceback (most recent call last):
	  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1432, in _inlineCallbacks
	    deferred.errback()
	  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Library/Python/2.7/site-packages/buildbot/www/resource.py", line 91, in failHttpError
	    f.trap(Error)
	  File "/Library/Python/2.7/site-packages/twisted/python/failure.py", line 359, in trap
	    self.raiseException()
	  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Library/Python/2.7/site-packages/buildbot/www/resource.py", line 84, in failHttpRedirect
	    f.trap(Redirect)
	  File "/Library/Python/2.7/site-packages/twisted/python/failure.py", line 359, in trap
	    self.raiseException()
	  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/Library/Python/2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/Library/Python/2.7/site-packages/buildbot/www/rest.py", line 528, in asyncRender
	    res = yield self.renderRest(request)
	  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/Library/Python/2.7/site-packages/buildbot/www/rest.py", line 453, in renderRest
	    request.write(data)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
	    self.gen.throw(type, value, traceback)
	  File "/Library/Python/2.7/site-packages/buildbot/www/rest.py", line 172, in handleErrors
	    jsonrpccode=JSONRPC_CODES["internal_error"])
	  File "/Library/Python/2.7/site-packages/buildbot/www/rest.py", line 375, in writeError
	    request.write(data)
	  File "/Library/Python/2.7/site-packages/twisted/web/server.py", line 234, in write
	    http.Request.write(self, data)
	  File "/Library/Python/2.7/site-packages/twisted/web/http.py", line 1084, in write
	    self.channel.writeSequence(toChunk(data))
	exceptions.AttributeError: 'NoneType' object has no attribute 'writeSequence'
```

**Comment by seankelly** [comment]
Possible duplicate of #4045.
