### ISSUE TITLE
Can't run the windows worker

### ISSUE THREAD

**Issue by crazybie** [buildbot/buildbot#4192]
The basic example of worker failed to work on windows:

2018-07-04 21:53:57+0800 [Broker,0,127.0.0.1] worker 'example-worker' attaching from IPv4Address(TCP, '127.0.0.1', 64010)
2018-07-04 21:53:57+0800 [Broker,0,127.0.0.1] Failed to communicate with worker 'example-worker'
	'utf8' codec can't decode byte 0xd6 in position 0: invalid continuation byte
2018-07-04 21:53:57+0800 [Broker,0,127.0.0.1] Peer will receive following PB traceback:
2018-07-04 21:53:57+0800 [Broker,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 1442, in gotResult
	    _inlineCallbacks(r, g, deferred)
	--- <exception caught here> ---
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "d:\python27\lib\site-packages\twisted\python\failure.py", line 408, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "d:\python27\lib\site-packages\buildbot\worker\protocols\pb.py", line 77, in _getPerspective
	    accepted = yield workers.newConnection(conn, workerName)
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "d:\python27\lib\site-packages\twisted\python\failure.py", line 408, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "d:\python27\lib\site-packages\buildbot\worker\manager.py", line 132, in newConnection
	    info = yield conn.remoteGetWorkerInfo()
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "d:\python27\lib\site-packages\buildbot\worker\protocols\pb.py", line 204, in remoteGetWorkerInfo
	    defer.returnValue(decode(info))
	  File "d:\python27\lib\site-packages\buildbot\pbutil.py", line 176, in decode
	    return data_type(map(decode, data))
	  File "d:\python27\lib\site-packages\buildbot\pbutil.py", line 176, in decode
	    return data_type(map(decode, data))
	  File "d:\python27\lib\site-packages\buildbot\pbutil.py", line 176, in decode
	    return data_type(map(decode, data))
	  File "d:\python27\lib\site-packages\buildbot\pbutil.py", line 176, in decode
	    return data_type(map(decode, data))
	  File "d:\python27\lib\site-packages\buildbot\pbutil.py", line 172, in decode
	    return bytes2unicode(data, encoding, errors)
	  File "d:\python27\lib\site-packages\buildbot\util\__init__.py", line 228, in bytes2unicode
	    return text_type(x, encoding, errors)
	exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 0: invalid continuation byte
	
installed version:
Buildbot version: 1.2.0
worker version: 1.2.0
Twisted version: 17.9.0

windows code page:
936

**Comment by crazybie** [comment]
I temporarily changed the bytes2unicode to ignore errors, then it works now.

`def bytes2unicode(x, encoding='utf-8', errors='ignore'):
    ....
`

**Comment by lancelodliu** [comment]
My master uses 1.1.0 and Twisted 16.6.0 and workers use 1.1.0 and Twisted 17.9.0. Evertything is good.
But If use both 1.1.0 and 17.9.0/16.6.0, this problem happens again.

**Comment by seankelly** [comment]
@lancelodliu Do you mean 17.9.0 on the master and 16.6.0 on the workers?

**Comment by lancelodliu** [comment]
@seankelly No. 16.6.0 on master and 17.9.0 on workers. But your solution still works.

**Comment by crazybie** [comment]
issue seems be resolved in buildbot 1.3.0.
