### ISSUE TITLE
giturlparse cant't parse an url with a personal token

### ISSUE THREAD

**Issue by pc-tradelab** [buildbot/buildbot#4236]
Hello,

I have a github repo that I want to test. My url has the following form (with a personnal token) :
https://9s20c70cs0a7f7eddscba8f5ad2a81g76656f2ee@github.com/my_org/my_repo.git
(with the token, i can directly use git clone ...)

It works well in the GitPoller, the Builder but not in the GitHubStatusPush because of the function giturlparse that can't parse that kind of url : 

2018-07-26 12:37:12+0000 [-] while invoking <bound method GitHubStatusPush.buildFinished of <buildbot.reporters.github.GitHubStatusPush object at 0x7f7ed8f521d0>>
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/reporters/http.py", line 84, in getMoreInfoAndSend
            yield self.send(build)
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python2.7/site-packages/buildbot/reporters/github.py", line 146, in send
            repoOwner = giturl.owner
        exceptions.AttributeError: 'NoneType' object has no attribute 'owner'

Is it a bug or should I change on my side the github url ?

Thanks in advance !

**Comment by pc-tradelab** [comment]
After new investigations, giturlparse is not the problem. I am using a ForceScheduler. The repo information does not exist in a ForceScheduler . Hence the exception.
