### ISSUE TITLE
TLS error in send email

### ISSUE THREAD

**Issue by qzqsmile** [buildbot/buildbot#4263]
hello,  Recently email moudle is introduced into my project. But it raised a weird error. After searched over the Internet for the soultion, i found a smiliar case in [here](https://stackoverflow.com/questions/24116105/buildbot-from-buildbot-net-icloud-email-not-working-as-status-target/24127889).  But different from this case, i have installed the pyopenssl. So i have no idea how to handle this error message. Can you give me some help? thanks

```
2018-08-16 04:09:45-0400 [ESMTPSender,client] SMTP Client retrying server. Retry: 1
2018-08-16 04:09:45-0400 [ESMTPSender,client] Unhandled Error
        Traceback (most recent call last):
          File "/root/tmp/bb-master/sandbox/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
            return self._dataReceived(data)
          File "/root/tmp/bb-master/sandbox/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/root/tmp/bb-master/sandbox/lib/python3.6/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
            why = self.lineReceived(line)
          File "/root/tmp/bb-master/sandbox/lib/python3.6/site-packages/twisted/mail/smtp.py", line 996, in lineReceived
            why = self._okresponse(self.code, b'\n'.join(self.resp))
        --- <exception caught here> ---
          File "/root/tmp/bb-master/sandbox/lib/python3.6/site-packages/twisted/mail/smtp.py", line 1497, in esmtpState_starttls
            self.transport.startTLS(self.context)
        builtins.AttributeError: 'Client' object has no attribute 'startTLS'
2018-08-16 04:09:45-0400 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe23e9bc630>
```

My Dev Env:
Ubuntu:16.04  Python3.6.6

**Comment by tardyp** [comment]
Hi, I guess we also need the vrsion of twisted. you can get that using the command `pip freeze` from inside your virtualenv.

Also, we don't recommend to run buildbot as root.

**Comment by qzqsmile** [comment]
below is my twisted version. Thanks for your comment, later i will use another user to run buildbot
`Twisted==18.7.0`

**Comment by tardyp** [comment]
I think TLS is disabled here if pyopenssl is not properly installed:

https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/tcp.py#L31

can you try this from your virtualenv:

```
 python -c   'import twisted.internet._newtls'
```

**Comment by qzqsmile** [comment]
`python -c   'import twisted.internet._newtls'`
It works fine. Not any errors tips are raised

**Comment by tardyp** [comment]
You may want to see what is this Client class in the traceback. You would need to edit the smtp.py line 1497 and insert following code:

```
import inspect
print(inspect.getmro(self.transport.__class__))
```
