### ISSUE TITLE
EC2LatentWorker use generates an error

### ISSUE THREAD

**Issue by drmeister** [buildbot/buildbot#4320]
I get this

```
ubuntu@ip-172-31-28-114:~/master$ buildbot reconfig .
sending SIGHUP to process 1645
b'2018-09-12 21:24:44+0000 [-] beginning configuration update'
b"2018-09-12 21:24:44+0000 [-] Loading configuration from '/home/ubuntu/master/master.cfg'"
b'2018-09-12 21:24:44+0000 [-] error while parsing config file:'
b'\tTraceback (most recent call last):'
b'\t  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>'
b'\t    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)'
b'\t  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext'
b'\t    return self.currentContext().callWithContext(ctx, func, *args, **kw)'
b'\t  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext'
b'\t    return func(*args,**kw)'
b'\t  File "/home/ubuntu/.local/lib/python3.5/site-packages/buildbot/config.py", line 182, in loadConfig'
b'\t    self.basedir, self.configFileName)'
b'\t--- <exception caught here> ---'
b'\t  File "/home/ubuntu/.local/lib/python3.5/site-packages/buildbot/config.py", line 140, in loadConfigDict'
b'\t    execfile(filename, localDict)'
b'\t  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/compat.py", line 246, in execfile'
b'\t    exec(code, globals, locals)'
b'\t  File "/home/ubuntu/master/master.cfg", line 24, in <module>'
b'\t    ),'
b'\t  File "/home/ubuntu/.local/lib/python3.5/site-packages/buildbot/worker/ec2.py", line 194, in __init__'
b"\t    region = botocore.session.get_session().get_config_variable('region')"
b"\tbuiltins.NameError: name 'botocore' is not defined"
b'\t'
b"2018-09-12 21:24:44+0000 [-] The python module 'boto3' is needed to use a EC2LatentWorker"
b"2018-09-12 21:24:44+0000 [-] error while parsing config file: name 'botocore' is not defined (traceback in logfile)"
b'2018-09-12 21:24:44+0000 [-] reconfig aborted without making any changes'
Reconfiguration failed. Please inspect the master.cfg file for errors, correct
them, then try 'buildbot reconfig' again.
```

When I set up this:

```
# The 'workers' list defines the set of recognized workers. Each element is
# a Worker object, specifying a unique worker name and password.  The same
# worker name and password must be configured on the worker.
c['workers'] = [
    worker.EC2LatentWorker('bot1','sekrit', 'c4.xlarge',
                           ami='ami-0029aa3b21ee336a0',
                           elastic_ip='52.15.210.174',
                           keypair_name='latent_buildbot_worker',
                           security_name='latent_buildbot_worker',
    ),
#    worker.Worker("clasp-worker", "clasppass"),
#    worker.Worker("fry-worker","pass")
]
```

When I try to edit the ec2.py source file none of my changes appear to have any effect on the outcome.  I then removed the ec2.pyc and ec2.py files and that made no difference either.
It's like there is another version of the file somewhere - but it makes this difficult to debug.

**Comment by drmeister** [comment]
Here is some more context.
I'm on ubuntu linux (stable I think)
Using Python3.5

Here is my master.cfg file:
# Pastebin dZFzLD8G
# -*- python -*-
# ex: set filetype=python:

from buildbot.plugins import *
from boto3 import *


# This is a sample buildmaster config file. It must be installed as
# 'master.cfg' in your buildmaster's base directory.

# This is the dictionary that the buildmaster pays attention to. We also use
# a shorter alias to save typing.
c = BuildmasterConfig = {}

####### WORKERS

# The 'workers' list defines the set of recognized workers. Each element is
# a Worker object, specifying a unique worker name and password.  The same
# worker name and password must be configured on the worker.
c['workers'] = [
    worker.EC2LatentWorker('bot1','sekrit', 'c4.xlarge',
                           ami='ami-0029aa3b21ee336a0',
                           elastic_ip='52.15.210.174',
                           keypair_name='latent_buildbot_worker',
                           security_name='latent_buildbot_worker',
    ),
#    worker.Worker("clasp-worker", "clasppass"),
#    worker.Worker("fry-worker","pass")
]

# 'protocols' contains information about protocols which master will use for
# communicating with workers. You must define at least 'port' option that workers
# could connect to your master with this protocol.
# 'port' must match the value configured into the workers (with their
# --master option)
c['protocols'] = {'pb': {'port': 9989}}

####### CHANGESOURCES

# the 'change_source' setting tells the buildmaster how it should find out
# about source code changes.  Here we point to the buildbot version of a python hello-world project.

c['change_source'] = []
c['change_source'].append(changes.GitPoller(
    'https://github.com/clasp-developers/clasp.git',
    workdir='gitpoller-workdir', branch='testing',
    pollInterval=30))

####### SCHEDULERS

# Configure the Schedulers, which decide how to react to incoming changes.  In this
# case, just kick off a 'clasp' build

c['schedulers'] = []
c['schedulers'].append(schedulers.SingleBranchScheduler(
                            name="all",
                            change_filter=util.ChangeFilter(branch='testing'),
                            treeStableTimer=None,
                            builderNames=["clasp"]))
c['schedulers'].append(schedulers.ForceScheduler(
                            name="force",
                            builderNames=["clasp"]))

####### BUILDERS

# The 'builders' list defines the Builders, which tell Buildbot how to perform a build:
# what steps, and which workers can execute them.  Note that any particular build will
# only take place on one worker.


##### Build clasp

waf_distclean = steps.ShellCommand(name="waf distclean",
                                   command=["./waf", "distclean"],
                                   description="waf distclean",
                                   workdir="/home/admin/worker/build",
                                   haltOnFailure=True)
git_clasp = steps.Git(repourl='https://github.com/clasp-developers/clasp.git', mode='incremental',
                                   workdir="/home/admin/worker/build",
                      haltOnFailure=True)
waf_configure = steps.ShellCommand(name="waf configure",
                                   command=["./waf", "configure"],
                                   description="waf configure",
                                   workdir="/home/admin/worker/build",
                                   haltOnFailure=True)
waf_build_iboehm = steps.ShellCommand(name="waf build_iboehm",
                                      command=["./waf", "build_iboehm"],
                                      description="waf build_iboehm",
                                      workdir="/home/admin/worker/build",
                                      haltOnFailure=True)
waf_build_aboehm = steps.ShellCommand(name="waf build_aboehm",
                                      command=["./waf", "build_aboehm"],
                                      description="waf build_aboehm",
                                      workdir="/home/admin/worker/build",
                                      haltOnFailure=True)
waf_build_bboehm = steps.ShellCommand(name="waf build_bboehm",
                                      command=["./waf", "build_bboehm"],
                                      description="waf build_bboehm",
                                      workdir="/home/admin/worker/build",
                                      haltOnFailure=True)
waf_build_cboehm = steps.ShellCommand(name="waf build_cboehm",
                                      command=["./waf", "build_cboehm"],
                                      description="waf build_cboehm",
                                      workdir="/home/admin/worker/build",
                                      haltOnFailure=True)


factory_clasp = util.BuildFactory()
factory_clasp.addStep(waf_distclean)
factory_clasp.addStep(git_clasp)
factory_clasp.addStep(waf_configure)
factory_clasp.addStep(waf_build_iboehm)
factory_clasp.addStep(waf_build_aboehm)
factory_clasp.addStep(waf_build_bboehm)
factory_clasp.addStep(waf_build_cboehm)

c['builders'] = []
c['builders'].append(
    util.BuilderConfig(name="clasp",
                       workernames=["clasp-worker"],
                       factory=factory_clasp))

####### BUILDBOT SERVICES

# 'services' is a list of BuildbotService items like reporter targets. The
# status of each build will be pushed to these targets. buildbot/reporters/*.py
# has a variety to choose from, like IRC bots.

c['services'] = []

####### PROJECT IDENTITY

# the 'title' string will appear at the top of this buildbot installation's
# home pages (linked to the 'titleURL').

c['title'] = "Hello World CI"
c['titleURL'] = "https://buildbot.github.io/hello-world/"

# the 'buildbotURL' string should point to the location where the buildbot's
# internal web server is visible. This typically uses the port number set in
# the 'www' entry below, but with an externally-visible host name which the
# buildbot cannot figure out without some help.

c['buildbotURL'] = "http://clasp-buildbot.ddns.net:8010/"

# minimalistic config to activate new web UI
c['www'] = dict(port=8010,
                plugins=dict(waterfall_view={}, console_view={}, grid_view={}))

####### DB URL

c['db'] = {
    # This specifies what database buildbot uses to store its state.  You can leave
    # this at its default for all but the largest installations.
    'db_url' : "sqlite:///state.sqlite",
}

**Comment by drmeister** [comment]
Whoah - ok - I screwed up.   I was using 'buildbot reconfig' and that doesn't reload source code.  Once I stopped the master and started it again my changes to ec2.py took effect. I was then quickly able to diagnose the problem(s) and get things up and running.
I have no problems - buildbot is great.  Thank you.
