### ISSUE TITLE
Github WebHook directly crashes buildbot upon reception of a PR

### ISSUE THREAD

**Issue by brkindar** [buildbot/buildbot#4367]
I'm seeing my buildbot crash each time he receives a PR notification from GitHub.

Hook is defined as : 
c['www'] = dict(port=8010,
                plugins=dict(waterfall_view={}, console_view={}, grid_view={}),
                change_hook_dialects={'github':{
                    'secret': someStringSecret}})

I get in the logs :
2018-10-19 10:48:01+0200 [_GenericHTTPChannelProtocol,8,_someIP_] Payload: {'action': 'opened', 'number': 1, 'pull_request': {'url': (lots of stuff I'd rather not post here)...}}
2018-10-19 10:48:01+0200 [_GenericHTTPChannelProtocol,8,_someIP_] X-GitHub-Event: pull_request
2018-10-19 10:48:01+0200 [_GenericHTTPChannelProtocol,8,_someIP_] Processing GitHub PR #1

This is reproducible on two different repositories.
I'd expect at least a message in the log before crashing, now I don't know what to do to get more information.

**Comment by brkindar** [comment]
This occurs on an enterprise GitHub repository.
I've verified that the token and the endpoint are correctly specified.

**Comment by brkindar** [comment]
Apparently the http request performed returns a "We didn't receive a proper request from your browser".

**Comment by brkindar** [comment]
Manually it looks like the request is well formed and returns a correct output.

**Comment by brkindar** [comment]
My guess is that :
	res = yield http.get(url)
is not doing what it is expected to do. Any help on this would be appreciated to fix it.

**Comment by tardyp** [comment]
hi @brkindar which http.get do you think is not working?

**Comment by tardyp** [comment]
hi @brkindar which http.get do you think is not working?

**Comment by brkindar** [comment]
Hi @tardyp, actually I'm not even sure the http.get request is not working. I'm printf debugging so it's really hard to understand what's going on.
The last thing that I get when I force debug=True in getService is :
2018-10-22 09:52:59+0200 [-] http https://api.github.myenterprise.com/repos/myName/myRepo/commits/c54942f0565be39e5c578977d7ac3dea4d1cacd6 {'headers': {'User-Agent': 'Buildbot', 'Authorization': 'token myHexaToken'}}


So I guess this is the issue in txrequests ?



Is there a howto for debugging efficiently ?

**Comment by tardyp** [comment]
Hi @brkindar looks like due to https://blog.github.com/2018-10-21-october21-incident-report/
you last comment was lost.
Can you repost it with some detail on where in the code you think there is an issue (where do you put your prints)

**Comment by tardyp** [comment]
ah. The post magically reappeared..

**Comment by brkindar** [comment]
Looks like Github is back to normal.

**Comment by brkindar** [comment]
Hi Pierre, actually I'm not even sure the http.get request is not working.
I'm printf debugging so it's really hard to understand what's going on.
The last thing that I get when I force debug=True in getService is :

2018-10-22 09:52:59+0200 [-] http
https://api.github.myenterprise.com/repos/myName/myRepo/commits/c54942f0565be39e5c578977d7ac3dea4d1cacd6
{'headers': {'User-Agent': 'Buildbot', 'Authorization': 'token
myHexaToken'}}


So I guess this is the issue in txrequests ?


Is there a howto for debugging efficiently ?

**Comment by brkindar** [comment]
I've tried replacing the webhook payload of my failing PR into the unit test buildbot/test/unit/test_www_hooks_github.py to see if there is something that rings a bell.

There are a few (supposedly expected) errors, but more interestingly there is a FAIL:

```
  TestChangeHookConfiguredWithGitChangeCustomPullrequestRef
    test_git_pull_request_with_custom_ref ...                            [FAIL]
                          [ERROR]

```

```
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/bkindarji/Perso/buildbot/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/bkindarji/Perso/buildbot/master/buildbot/test/unit/test_www_hooks_github.py", line 1190, in test_git_pull_request_with_custom_ref
    self.assertEqual(len(self.changeHook.master.addedChanges), 1)
  File "/Users/bkindarji/Perso/buildbot/.venv/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 0 != 1

```

**Comment by brkindar** [comment]
I've given up the unit test way, seems too complicated to rewrite everything to reproduce whereas I have a direct way of reproducing on my machine.

The master runs on a mac (High Sierra); strangely when I run it on another machine I don't have the issue.

**Comment by brkindar** [comment]
In the good scenario:
```
* Preparing request to http://localhost:8010/change_hook/github
* Using libcurl/7.54.0 LibreSSL/2.6.4 zlib/1.2.11 nghttp2/1.24.1
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8010 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8010 (#10)
> POST /change_hook/github HTTP/1.1
> Host: localhost:8010
> User-Agent: insomnia/6.0.2
> X-GitHub-Event: pull_request
> Content-Type: application/json
> Accept: */*
> Content-Length: 25027
| (24.4 KB hidden)
* upload completely sent off: 25027 out of 25027 bytes
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Wed, 24 Oct 2018 08:50:49 GMT
< Content-Type: text/html
< Server: TwistedWeb/18.9.0

* Received 24 B chunk
* Connection #10 to host localhost left intact
```

In the bad machine scenario:
```
* Preparing request to http://mymachine.com:8010/change_hook/github
* Using libcurl/7.54.0 LibreSSL/2.6.4 zlib/1.2.11 nghttp2/1.24.1
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Connection 10 seems to be dead!
* Closing connection 10
*   Trying myIP...
* TCP_NODELAY set
* Connected to mymachine.com (myIP) port 8010 (#11)
> POST /change_hook/github HTTP/1.1
> Host: mymachine.com:8010
> User-Agent: insomnia/6.0.2
> X-GitHub-Event: pull_request
> Content-Type: application/json
> Accept: */*
> Content-Length: 25027
| (24.4 KB hidden)
* upload completely sent off: 25027 out of 25027 bytes
* Empty reply from server
* Connection #11 to host mymachine.com left intact
```

**Comment by brkindar** [comment]
Finally, running buildbot from the virtualenv instead of the installed buildbot using pip makes it work without any issue on the other machine.

So I guess there is something rotten in this python installation ?

**Comment by brkindar** [comment]
Files do not really differ between master and 1.5 except for #4316 so perhaps this is related ?
