### ISSUE TITLE
buildbot.test.integration.interop.test_transfer.TransferStepsMasterPb.test_transfer is flaky on Windows

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#4407]
https://ci.appveyor.com/project/djmitche/buildbot/builds/20090290/job/8bnsx9sh621jpnwd
https://ci.appveyor.com/project/djmitche/buildbot/builds/20044022/job/4i1b47hop0ogisy2

**Comment by p12tic** [comment]
Will disable in https://github.com/buildbot/buildbot/pull/4405.

**Comment by yan12125** [comment]
This test is flaky on Linux, too. A test failure from Arch Linux: https://tests.reproducible-builds.org/archlinux/community/buildbot/build2.log

This log file will be overwritten during the next Arch Linux package test, so I paste relevant lines here:
```
[ERROR]
Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: <buildbot.test.integration.interop.test_transfer.TransferStepsMasterPb testMethod=test_transfer> (test_transfer) still running at 5.0 secs

buildbot.test.integration.interop.test_transfer.TransferStepsMasterPb.test_transfer
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/twisted/trial/util.py", line 276, in _runSequentially
    thing = yield d
  File "/usr/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/tmp/buildbot-archlinuxrb-build-EeIrmqxN/buildbot/trunk/src/tmp_install/usr/lib/python3.7/site-packages/buildbot/test/util/integration.py", line 201, in dump
    raise self.failureException(dump.getvalue())
twisted.trial.unittest.FailTest: FAILED! dumping build db for debug
*** BUILD 1 *** ==> building (not finished)
    *** STEP worker_preparation *** ==> worker ready (success)
    *** STEP string_download *** ==> downloading to file1.txt (success)
    *** STEP string_download_1 *** ==> downloading to file2.txt (success)
    *** STEP download *** ==> running (not finished)


buildbot.test.integration.interop.test_transfer.TransferStepsMasterPb.test_transfer
-------------------------------------------------------------------------------
```
