### ISSUE TITLE
customMergeRequests() takes exactly 3 arguments 

### ISSUE THREAD

**Issue by ostermannc** [buildbot/buildbot#4459]
Hello,

I am using master version 1.6.0 and I got following error.

My main concern is that cronScheduler are some how stuck after few days (I have some nightly build).
By going through the log I found the following issue.

Can it be related ?

```
2018-11-27 13:51:37+0100 [-] while firing stable timer
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in errback
	    self._startRunCallbacks(fail)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/schedulers/basic.py", line 207, in stableTimerFired
	    changeids=changeids)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/schedulers/base.py", line 344, in addBuildsetForChanges
	    properties=properties, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/schedulers/base.py", line 405, in addBuildsetForSourceStamps
	    external_idstring=external_idstring, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/data/buildsets.py", line 161, in addBuildset
	    yield BuildRequestCollapser(self.master, list(itervalues(brids))).collapse()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/process/buildrequest.py", line 88, in collapse
	    canCollapse = yield collapseRequestsFn(self.master, bldr, br, unclaim_br)
	exceptions.TypeError: customMergeRequests() takes exactly 3 arguments (4 given)

```

**Comment by tardyp** [comment]
yes, it looks like your ```customMergeRequests``` method has to many arguments. Can you share it?

**Comment by ostermannc** [comment]
oh sorry it was in my code...

In fact API has evolved from 0.8.2, the function now takes one more argument *master*.
I use it to decide to collapseRequest or not.

Just ignore this item.
Thank you
