### ISSUE TITLE
resetQuarantine 

### ISSUE THREAD

**Issue by ostermannc** [buildbot/buildbot#4460]
HI,
I have detected an error in my master log.
Since you kindly ask to file a bug. I proceed.

BR
Christophe

`
2018-11-29 05:00:03+0100 [-] from finishing a build; this is a serious error - please file a bug at http://buildbot.net
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/process/build.py", line 680, in buildFinished
	    self.workerforbuilder.worker.resetQuarantine()
	exceptions.AttributeError: 'NoneType' object has no attribute 'resetQuarantine'
`

**Comment by tardyp** [comment]
Hi @ostermannc Do you have more information on what is the context of the error?

Does this happen often?
Is this always for the same builder?
What kind of worker do you use?

Regards

**Comment by ostermannc** [comment]
Hello,

Yes it happens quite often. Mostly every days on one of my worker(I have 8 workers).
My master version 1.6.0  runs in a docker container (docker runs on ubuntu).  But all my slaves are under windows 10.
This error is raised in a very specific build: it reboots the slave.
I do that every morning on all my slave with *shutdown.exe -r -t 0 -f* 
This approach was working fine since years with buildbot 0.8.2. I have decided to move forward to upgrade to latest buildbot release. (Half of my slaves (8) are still on another master with 0.8.2, I will move everything when it will be stable again with 1.6.0) 

Is there a cleaner way to reboot slaves ?

**Comment by tardyp** [comment]
So this looks like a race condition with the build finishing and the worker disconnecting.

can you try and change code with something like following in build.py line 680?

```
if self.workerforbuilder.worker is not None:
    self.workerforbuilder.worker.resetQuarantine()
```

**Comment by tardyp** [comment]
Thanks, if this works, would you like to send a PR for this fix?

**Comment by ostermannc** [comment]
I have created a PR but it somehow fail... can you have a look ? https://github.com/buildbot/buildbot/pull/4468
