### ISSUE TITLE
buildstep returned int result

### ISSUE THREAD

**Issue by angeloudy** [buildbot/buildbot#4462]
I added a custom build step.
```
class SquishGetVersion(Squish):
    name = 'Get version from squish'
    description = ['Communicating with squish']
    descriptionDone = ['Set']

    def __init__(self, project, **kwargs):
        Squish.__init__(self, project, **kwargs)

    def run(self):
        version = self.get_version(self.project)
        self.property = "releaseVersion"
        self.value = version[0]
        properties = self.build.getProperties()
        properties.setProperty(self.property, self.value, self.name, runtime=True)

        return defer.succeed(results.SUCCESS)

```
It worked OK. But recently the build stucks and never finishes even though it finishes all steps.

errors from twisted.log:

```
2018-12-04 15:40:35+1100 [-] from finishing a build; this is a serious error - please file a bug at http://buildbot.net
    Traceback (most recent call last):
      File "/var/buildbot/master_lib.py", line 63, in allStepsDone
        return self.buildFinished(text, self.results)
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
        return _cancellableInlineCallbacks(gen)
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
        _inlineCallbacks(None, g, status)
      File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
        result = g.send(result)
    --- <exception caught here> ---
      File "/usr/local/lib/python3.6/site-packages/buildbot/process/build.py", line 671, in buildFinished
        bytes2unicode(" ".join(text)))
    builtins.TypeError: sequence item 0: expected str instance, int found

```

I added some debug in `AllStepDone` method, `log.info(f"build results: {self.results}")`
and found that results was 0, instead of one of `SUCCESS, WARNINGS, FAILURE, SKIPPED, EXCEPTION, RETRY, CANCELLED `

**Comment by angeloudy** [comment]
This was because I put a `int` in the result text in my customised `allStepDone` method. Closing task
