### ISSUE TITLE
expected a bytes-like object, str found in Rest api

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#4477]
Following stack trace happens with metabuildbot on python3

```
2018-12-15 22:08:08+0000 [_GenericHTTPChannelProtocol,48,192.168.80.239] while handling API request
        Traceback (most recent call last):
          File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/home/bbuser/buildbot/master/buildbot/www/rest.py", line 453, in renderRest
            request.write(data)
          File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
            self.gen.throw(type, value, traceback)
        --- <exception caught here> ---
          File "/usr/home/bbuser/buildbot/master/buildbot/www/rest.py", line 141, in handleErrors
            yield
          File "/usr/home/bbuser/buildbot/master/buildbot/www/rest.py", line 378, in renderRest
            ep, kwargs = yield self.getEndpoint(request, bytes2NativeString(request.method), {})
        builtins.TypeError: sequence item 0: expected a bytes-like object, str found
```

**Comment by tardyp** [comment]
@rodrigc any idea?

**Comment by rodrigc** [comment]
Offhand I don't know.  For this kind of thing, it would help to be able to reproduce the problem and use
pudb or pdb to set a breakpoint to inspect the data.  That's how I debugged several other www related bytes/str issues on Py3

**Comment by tardyp** [comment]
fixed by https://github.com/buildbot/buildbot_travis/pull/93
