### ISSUE TITLE
When downloading stdio log: {"error": "MemoryError()"}

### ISSUE THREAD

**Issue by alorbach** [buildbot/buildbot#4484]
I have a very large stdio (3GB) logfile I want to download 

However seems like the download function is not piping the logfile through but loading it fully into local memory. This causes download to fail with this error: 
{"error": "MemoryError()"}

Can something done to optimize this process?

**Comment by alorbach** [comment]
2018-12-31 13:14:56+0100 [-] closing log <buildbot.process.buildstep.SyncLogFileWrapper object at 0x7ff4c8674290>
2018-12-31 13:15:04+0100 [-] Got fatal Exception on DB
	Traceback (most recent call last):
	Failure: exceptions.MemoryError: 
	
2018-12-31 13:15:04+0100 [-] while handling API request
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/www/rest.py", line 453, in renderRest
	    request.write(data)
	  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
	    self.gen.throw(type, value, traceback)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/www/rest.py", line 141, in handleErrors
	    yield
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/www/rest.py", line 381, in renderRest
	    data = yield ep.get(rspec, kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/data/logchunks.py", line 118, in get
	    logid, 0, lastline)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/db/pool.py", line 184, in __thd
	    rv = callable(arg, *args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/buildbot/db/logs.py", line 143, in thdGetLogLines
	    return u'\n'.join(rv) + u'\n' if rv else u''
	exceptions.MemoryError:

**Comment by alorbach** [comment]
function "getLogLines" in logs.py tries to load the full logfile into memory causing the whole buildbot master to fail with MemoryError when the Logfile is to large.

**Comment by alorbach** [comment]
Related to #4505
