### ISSUE TITLE
buildbot.test failing due to missing file?

### ISSUE THREAD

**Issue by sfantao** [buildbot/buildbot#4588]
I am trying the latest buildbot release. I installed in Python 3.7.0 environment:
```
$ python --version
Python 3.7.0
```
as 
```
$ pip install 'buildbot[bundle]'
```
When I tried to run the tests I get:
```
$ PYTHONPATH=. trial buildbot.test
buildbot
  test ...                                                              [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/clusters-testing/sandbox/lib/python3.7/site-packages/twisted/trial/runner.py", line 804, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File "/home/clusters-testing/sandbox/lib/python3.7/site-packages/twisted/trial/runner.py", line 746, in findByName
    recurse=recurse)
  File "/home/clusters-testing/sandbox/lib/python3.7/site-packages/twisted/trial/runner.py", line 765, in loadAnything
    if isPackage(obj):
  File "/home/clusters-testing/sandbox/lib/python3.7/site-packages/twisted/trial/runner.py", line 54, in isPackage
    basename = os.path.splitext(os.path.basename(module.__file__))[0]
  File "/home/clusters-testing/sandbox/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
builtins.TypeError: expected str, bytes or os.PathLike object, not NoneType

buildbot.test
-------------------------------------------------------------------------------
Ran 1 tests in 0.025s

FAILED (errors=1)
```
Looks like the `buildbot.test` object (here `module`) does not have a file name associated. 

Any hint on what might be causing the issue?

Many thanks!

**Comment by tardyp** [comment]
Hello,
The wheel packages do not ship with the test packages.

```
pip install --no-binary wheel buildbot
```

If you want to run the tests for contributing, you bette look at our quickstart:
http://docs.buildbot.net/current/developer/quickstart.html

**Comment by sfantao** [comment]
@tardyp, thanks for the quick response!

If I do:
```
$ pip install --no-binary ':all:' wheel buildbot                                                                    
```
then I can spin the tests.
