### ISSUE TITLE
Commit hook fails after recent upgrade

### ISSUE THREAD

**Issue by kayhayen** [buildbot/buildbot#4632]
Python version: 3.5.3
Buildbot version: 2.0.1
Twisted version: 18.9.0

My change source is like this:

```
#!/bin/bash

while read oldrev newrev refname
do
   echo $oldrev $newrev $refname | python /home/git/git_buildbot.py --project=private -m localhost:9999 -u hayen -a not_my_password
done
```

This gives however:

```
019-03-04 17:19:46+0100 [Broker,16,127.0.0.1] <bound method ChangePerspective.perspective_addChange of <bui
ldbot.changes.pb.ChangePerspective object at 0xb3e537d0>> didn't accept ({b'src': 'git', b'project': 'privat
e', b'comments': 'Release work\n', 'files': [], b'branch': 'master', b'revision': '3cfb1380e7bdd829e55a9bed2
fb1e1b86422ab12', b'files': ['Developer_Manual.rst', 'tests/optimizations/Subscripts.py', 'tests/type_infere
nce/Test4.py'], b'who': 'Kay Hayen <kay.hayen@gmail.com>'},) and {}
2019-03-04 17:19:46+0100 [Broker,16,127.0.0.1] Peer will receive following PB traceback:
2019-03-04 17:19:46+0100 [Broker,16,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/home/nuitka-buildmaster/sandbox/lib/python3.5/site-packages/twisted/spread/banana.py", line
 173, in gotItem
            self.callExpressionReceived(item)
          File "/home/nuitka-buildmaster/sandbox/lib/python3.5/site-packages/twi
sted/spread/banana.py", line 136, in callExpressionReceived
            self.expressionReceived(obj)
          File "/home/nuitka-buildmaster/sandbox/lib/python3.5/site-packages/twisted/spread/pb.py", line 621, in expressionReceived
            method(*sexp[1:])
          File "/home/nuitka-buildmaster/sandbox/lib/python3.5/site-packages/twisted/spread/pb.py", line 1025, in proto_message
            self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
        --- <exception caught here> ---
          File "/home/nuitka-buildmaster/sandbox/lib/python3.5/site-packages/twisted/spread/pb.py", line 1054, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "/home/nuitka-buildmaster/sandbox/lib/python3.5/site-packages/twisted/spread/pb.py", line 245, in perspectiveMessageReceived
            state = method(*args, **kw)
          File "/home/nuitka-buildmaster/sandbox/lib/python3.5/site-packages/buildbot/changes/pb.py", line 90, in perspective_addChange
            d = self.master.data.updates.addChange(**changedict)
        builtins.TypeError: unwindGenerator() keywords must be strings
```

Did the format change or is this a Buildbot bug of some sorts?

**Comment by seankelly** [comment]
What was your previous version of Buildbot and the Python version used?

**Comment by kayhayen** [comment]
@seankelly it's hard to say now, I started pre-0.9 with Buildbot, have been in the later for a long time, I got the script from then, and lets say bi-weekly I update to the latest version. I think I can say it for sure from the logs what I last ran and believe it was still working:

> 2019-02-24 19:37:18+0100 [-] Starting BuildMaster -- buildbot.version: 1.8.0
> 2019-02-28 08:49:41+0100 [-] Starting BuildMaster -- buildbot.version: 2.0.1

The 1.8 was the last to work with my commit hook, 2.0.1 is the only version I used since, and it doesn't work anymore.

**Comment by kayhayen** [comment]
@seankelly As for Python used, right, I recall being annoyed at a forced update of the Python version used for Buildbot master, I was using Python 2.7.13 or so. This is a Debian stable machine, but Buildbot is run in a virtualenv.

Maybe the Python used for git_buildbot.py and buildbot-master need to match, is that what you are suspecting?

Yours,
Kay
