### ISSUE TITLE
bytes2unicode tries to convert types other than bytes

### ISSUE THREAD

**Issue by vibbo** [buildbot/buildbot#4636]
Hi,
as far as I can tell, force scheduler WebUI is not showing validation errors properly. It ends up with generic error: "internal error - see logs" in UI and
``builtins.TypeError: coercing to str: need a bytes-like object, dict found``
in twistd.log
This originates in https://github.com/buildbot/buildbot/blob/0727f2c585a6e9cce4e841c8cb955a747ab8e93b/master/buildbot/www/rest.py#L217
when msg is a dict with errors for force fields (as it should).

Solution could be in fixing function bytes2unicode:
https://github.com/vibbo/buildbot/commit/e802c0db3aadc7cceefc0aa082dcaea632b17a09
But I am not sure, whether this can have hidden unintended consequences.

**Comment by tardyp** [comment]
This is not normal to have msg being a dict at that point. Do you have a full stack trace?

**Comment by vibbo** [comment]
> 2019-03-07 14:09:33+0100 [-] While rendering resource:
	Traceback (most recent call last):
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1464, in _inlineCallbacks
	    status.deferred.errback()
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 501, in errback
	    self._startRunCallbacks(fail)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/buildbot/www/resource.py", line 96, in failHttpError
	    f.trap(Error)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/python/failure.py", line 439, in trap
	    self.raiseException()
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/python/failure.py", line 467, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/buildbot/www/resource.py", line 89, in failHttpRedirect
	    f.trap(Redirect)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/python/failure.py", line 439, in trap
	    self.raiseException()
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/python/failure.py", line 467, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/buildbot/www/rest.py", line 522, in asyncRender
	    res = yield self.renderJsonRpc(request)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/buildbot/www/rest.py", line 251, in renderJsonRpc
	    request.write(data)
	  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
	    self.gen.throw(type, value, traceback)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/buildbot/www/rest.py", line 155, in handleErrors
	    writeError(msg, errcode=400, jsonrpccode=e.jsonrpccode)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/buildbot/www/rest.py", line 217, in writeError
	    msg = bytes2unicode(msg)
	  File "/home/vibbo/bbm/sandbox/lib/python3.5/site-packages/buildbot/util/__init__.py", line 227, in bytes2unicode
	    return text_type(x, encoding, errors)
	builtins.TypeError: coercing to str: need a bytes-like object, dict found

If I am not mistaken, it all originates here, as validation errors are collected into dict: https://github.com/buildbot/buildbot/blob/0727f2c585a6e9cce4e841c8cb955a747ab8e93b/master/buildbot/schedulers/forcesched.py#L42-L45
Then passed further as following: https://github.com/buildbot/buildbot/blob/0727f2c585a6e9cce4e841c8cb955a747ab8e93b/master/buildbot/data/forceschedulers.py#L67-L68
And end up here: https://github.com/buildbot/buildbot/blob/0727f2c585a6e9cce4e841c8cb955a747ab8e93b/master/buildbot/www/rest.py#L217

This functionality used to work, back when bytes2NativeString was used there. https://github.com/buildbot/buildbot/commit/1739bed5646304c655991689405e68d917529f3a#diff-ce137e0a239224f9564dcc03ca0b1f06L230

**Comment by vibbo** [comment]
Web UI is expecting this: https://github.com/buildbot/buildbot/blob/0727f2c585a6e9cce4e841c8cb955a747ab8e93b/www/base/src/app/builders/buildrequest/forcedialog/forcedialog.controller.coffee#L46-L51

**Comment by tardyp** [comment]
then we should rather fix here: https://github.com/buildbot/buildbot/blob/0727f2c585a6e9cce4e841c8cb955a747ab8e93b/master/buildbot/www/rest.py#L217

and test for dictionary type

**Comment by seankelly** [comment]
Fixed in #4641.
