### ISSUE TITLE
Worker build failed : (docker, python3.5)

### ISSUE THREAD

**Issue by nakyong** [buildbot/buildbot#4676]
Hello,
I'm trying to run buildbot with docker.
I used docker file at docker hub (buildbot-master:2.0.0) and buildbot-worker.(changed pip ->pip3)
I copied buildbot.tac in this repository under docker/buildbot.tac.

When i ran docker-compose (which is included at buildbot-docker-example-config)

It gave error like below

worker_1    | Unhandled Error
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 674, in run
worker_1    |     runApp(config)
worker_1    |   File "/usr/local/lib/python3.5/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
worker_1    |     runner.run()
worker_1    |   File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 381, in run
worker_1    |     self.application = self.createOrGetApplication()
worker_1    |   File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 453, in createOrGetApplication
worker_1    |     application = getApplication(self.config, passphrase)
worker_1    | --- <exception caught here> ---
worker_1    |   File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 464, in getApplication
worker_1    |     application = service.loadApplication(filename, style, passphrase)
worker_1    |   File "/usr/local/lib/python3.5/dist-packages/twisted/application/service.py", line 416, in loadApplication
worker_1    |     application = sob.loadValueFromFile(filename, 'application')
worker_1    |   File "/usr/local/lib/python3.5/dist-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
worker_1    |     eval(codeObj, d, d)
worker_1    |   File "buildbot.tac", line 9, in <module>
worker_1    |     from buildbot_worker.bot import Worker
worker_1    | builtins.ImportError: No module named 'buildbot_worker'
worker_1    | 
worker_1    | 
worker_1    | Failed to load application: No module named 'buildbot_worker'
worker_1    | 

Could anybody help me?
If more information needed, please tell me.

**Comment by nakyong** [comment]
When build Dockerfile on my environment, i should copy all under /buildbot/woker/docker and setup.py.
After copy and build, it worked well.
Thanks for help:)
