### ISSUE TITLE
Buildbot upload step hangs in case of no space left on device

### ISSUE THREAD

**Issue by marrak** [buildbot/buildbot#4680]
We have Buildbot step:
`f_buildPosixTests.addStep(
  steps.DirectoryUpload(
    name='reports & trends results upload',
    workersrc='EDS/results',
    masterdest='/var/www/html/VK/9.2/',
    compress='gz',
    alwaysRun=True,
    doStepIf=lambda step: step.build.getProperty('emptyResultsDir') == str(0),
    hideStepIf=lambda results, s: results not in (FAILURE, EXCEPTION, RETRY)
  )
)
`
Last night we got exception which hangs all workers on this step due to lack of space:

`2019-03-26 07:06:22+0100 [-] DirectoryUpload started, from worker 'EDS/results/' to master '/var/www/html/VK/9.2/'
2019-03-26 07:06:22+0100 [-] <RemoteCommand 'uploadDirectory' at 139690896745472>: RemoteCommand.run [4525]
2019-03-26 07:06:30+0100 [Broker,3,192.168.58.34] Peer will receive following PB traceback:
2019-03-26 07:06:30+0100 [Broker,3,192.168.58.34] Unhandled Error
        Traceback (most recent call last):
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/site-packages/twisted/spread/banana.py", line 173, in gotItem
            self.callExpressionReceived(item)
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/site-packages/twisted/spread/banana.py", line 136, in callExpressionReceived
            self.expressionReceived(obj)
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/site-packages/twisted/spread/pb.py", line 621, in expressionReceived
            method(*sexp[1:])
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/site-packages/twisted/spread/pb.py", line 1025, in proto_message
            self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
        --- <exception caught here> ---
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/site-packages/twisted/spread/pb.py", line 1054, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/site-packages/twisted/spread/flavors.py", line 125, in remoteMessageReceived
            state = method(*args, **kw)
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/site-packages/buildbot/process/remotetransfer.py", line 133, in remote_unpack
            archive.extractall(path=self.destroot)
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/tarfile.py", line 2007, in extractall
            numeric_owner=numeric_owner)
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/tarfile.py", line 2049, in extract
            numeric_owner=numeric_owner)
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/tarfile.py", line 2121, in _extract_member
            self.makedir(tarinfo, targetpath)
          File "/home/buildmaster/buildbot-work/env/lib/python3.6/tarfile.py", line 2150, in makedir
            os.mkdir(targetpath, 0o700)
        builtins.OSError: [Errno 28] No space left on device: '/var/www/html/VK/9.2/RHEL6-x86_64/1224'

2019-03-26 07:06:32+0100 [Broker,3,192.168.58.34] <RemoteCommand 'uploadDirectory' at 139690896745472> rc=1
`
Could you fix it to throw error and continue work?

**Comment by tardyp** [comment]
Looks like if you are out of space in the master, a lot of thing will start failing. So I don't see much point in catching No space left exceptions each time we do a write.

**Comment by marrak** [comment]
No, it's out of space on partition where results of tests are kept, space on master is ok.
Master works well, but uploading step hangs during downloading data from slaves workdir to master data partition.

**Comment by YngveNPettersen** [comment]
We just had a case of this happening (in v3.7).

The MultipleFileUpload command filled up the filesystem of /tmp on the manager host with a single 2GB temporary file, and threw the exception below.

Afterwards. the status was as follows:

- The temporary file that caused the error remained on the drive until manually deleted
- The task that caused the remained active, it was not stopped with an error (or exception); and it did not stop due to a timeout either.
- When this state was detected several hours later, using the "stop" action on the task did not work
- The only way to stop the task was to stop the worker process on the worker (which may involve rebooting the worker host)
- at which time the task was retried

Subsequently this became the status of about a dozen tasks, that got this exception (because the first failing task did not remove the temporary file), and was unstoppable except by restarting the worker process on the affected workers.

(We are going to do something about the tmp drive size, but we could have hit this in some scenarios anyway, unless we had an absurdly big /tmp drive)

IMO Buildbot should have:

1. The exception should have triggered a failure/exception state in the running task, causing it to end
2.  Deleted the temporary file it was writing while cleaning up the task
3. Started the next task for the builder and worker

The exception:
```
2024-09-21 05:48:17+0000 [Broker (TLSMemoryBIOProtocol),9,<snip>] Peer will receive following PB traceback:
2024-09-21 05:48:17+0000 [Broker (TLSMemoryBIOProtocol),9,<snip>] Unhandled Error
        Traceback (most recent call last):
          File "sandbox/lib/python3.10/site-packages/twisted/spread/banana.py", line 176, in gotItem
            self.callExpressionReceived(item)
          File "sandbox/lib/python3.10/site-packages/twisted/spread/banana.py", line 137, in callExpressionReceived
            self.expressionReceived(obj)
          File "sandbox/lib/python3.10/site-packages/twisted/spread/pb.py", line 607, in expressionReceived
            method(*sexp[1:])
          File "sandbox/lib/python3.10/site-packages/twisted/spread/pb.py", line 999, in proto_message
            self._recvMessage(
        --- <exception caught here> ---
          File "sandbox/lib/python3.10/site-packages/twisted/spread/pb.py", line 1053, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "sandbox/lib/python3.10/site-packages/twisted/spread/flavors.py", line 131, in remoteMessageReceived
            state = method(*args, **kw)
          File "sandbox/lib/python3.10/site-packages/buildbot/process/remotetransfer.py", line 64, in remote_write
            self.fp.write(data)
        builtins.OSError: [Errno 28] No space left on device

2024-09-21 05:48:18+0000 [Broker (TLSMemoryBIOProtocol),9,<snip>] <RemoteCommand 'uploadDirectory' at 140232254216016> rc=0
```
