### ISSUE TITLE
addURL can't handle non-ascii characters

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4717]
addURL can't handle non-ascii characters

Following command reproduces the issue:
`self.addURL('\xe2\x8c', '')
`
result:
```
2019-04-11 07:41:13-0400 [-] from an asynchronous method executed in an old-style step 
        Traceback (most recent call last):
          File "steps.py", line 333, in _mystep
            self.addURL('\xe2\x8c', '')
          File "/Library/Python/2.7/site-packages/buildbot/process/buildstep.py", line 122, in wrap 
            d = fn(self, *args, **kwargs)
          File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/Library/Python/2.7/site-packages/buildbot/process/buildstep.py", line 892, in addURL
            yield self.master.data.updates.addStepURL(self.stepid, text_type(name), text_type(url))
        exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

```

**Comment by senyai** [comment]
It must be python 2.7 issue
