### ISSUE TITLE
UserPasswordAuth and secrets broken.

### ISSUE THREAD

**Issue by vext01** [buildbot/buildbot#4725]
UserPasswordAuth doesn't work with the secrets manager.

```
c['www']['auth'] = util.UserPasswordAuth([('bb', util.Secret('www'))])
```

Buildbot will start, but when you try and log in it will crash:
```
2019-04-17 15:50:56+0100 [-] HTTPAuthSessionWrapper.getChildWithDefault encountered unexpected error
        Traceback (most recent call last):
          File "/opt/buildbot/lib/python3.5/site-packages/twisted/web/_auth/wrapper.py", line 163, in _login
            d = self._portal.login(credentials, None, IResource)
          File "/opt/buildbot/lib/python3.5/site-packages/twisted/cred/portal.py", line 119, in login
            return maybeDeferred(self.checkers[i].requestAvatarId, credentials
          File "/opt/buildbot/lib/python3.5/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "/opt/buildbot/lib/python3.5/site-packages/twisted/cred/checkers.py", line 97, in requestAvatarId
            self.users[credentials.username]).addCallback(
        --- <exception caught here> ---
          File "/opt/buildbot/lib/python3.5/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "/opt/buildbot/lib/python3.5/site-packages/twisted/cred/credentials.py", line 157, in checkPassword
            calcHA1(algo, self.username, self.realm, password, nonce, cnonce),
          File "/opt/buildbot/lib/python3.5/site-packages/twisted/cred/_digest.py", line 65, in calcHA1
            m.update(pszPassword)
        builtins.TypeError: object supporting the buffer API required
```

And the user sees this in the web browser:
---
![image](https://user-images.githubusercontent.com/604955/56297753-d9ab9e80-6128-11e9-8901-d2796674bac4.png)
---

Versions:
```
$ buildbot --version
Buildbot version: 1.5.0
Twisted version: 18.9.0
```

**Comment by p12tic** [comment]
Thanks for the report. Did your approach ever work in older buildbot version? I.e. is this a regression? To me it looks like it's just another area where we don't support secrets yet.

**Comment by vext01** [comment]
Hi,

I'm not sure if it's a regression. This is the first buildbot install ive
ever done.

Cheers

**Comment by vext01** [comment]
In the meantime, you can just read the password in from file like this:
```
#c['www']['auth'] = util.UserPasswordAuth([('bb', util.Secret('www'))])
with open("/path/to/master/secrets_dir/www") as fh:
    www_pass = fh.read().strip()
c['www']['auth'] = util.UserPasswordAuth([('bb', www_pass)])
```

It's not ideal, I know...

**Comment by vext01** [comment]
Can someone help me make the failing test for this? I'm unfamiliar with the codebase, and struggling to get it right.

So far I have:
```
class UserPasswordAuthFromSecret(TestReactorMixin, www.WwwTestMixin, unittest.TestCase):    
    def setUp(self):                                                                                
        self.setUpTestReactor()                                                     
        self.master = fakemaster.make_master(self)                                    
        auth = UserPasswordAuth([('theuser', Secret('fake'))])                      
        auth.reconfigAuth(self.master, self.master.config)                          
                                                                                    
    def test_passwordStringToBytes(self):                                           
        correct_login = {b"user_string": b"theuser",                            
                         b"user_bytes": b"thepassword"}                         
        self.auth = auth.UserPasswordAuth([('theuser', Secret('fake'))])        
        self.assertEqual(self.auth.checkers[0].users, correct_login)
```

which gives:
```
[ERROR]
Traceback (most recent call last):
  File "/home/vext01/source/buildbot/master/buildbot/test/unit/test_www_auth.py", line 207, in setUp
    auth = UserPasswordAuth([('theuser', Secret('fake'))])
  File "/home/vext01/source/buildbot/.venv/lib/python3.7/site-packages/twisted/trial/_asynctest.py", line 56, in __init__
    super(TestCase, self).__init__(methodName)
  File "/home/vext01/source/buildbot/.venv/lib/python3.7/site-packages/twisted/trial/_synctest.py", line 945, in __init__
    super(SynchronousTestCase, self).__init__(methodName)
  File "/usr/lib/python3.7/unittest/case.py", line 407, in __init__
    testMethod = getattr(self, methodName)
builtins.TypeError: getattr(): attribute name must be string

buildbot.test.unit.test_www_auth.UserPasswordAuthFromSecret.test_passwordStringToBytes
```

i.e. not the right kind of failure.
