### ISSUE TITLE
Logs secrets cleanup issue with binary secrets

### ISSUE THREAD

**Issue by faudebert** [buildbot/buildbot#4730]
I'm using a custom class inheriting from `HashiCorpVaultSecretProvider` which handles binary secrets retrieval (ex. Java Key Store for Android app).
Vault itself does not allow storing binary secrets thus, such secrets are converted to base64 and their name are prefixed by `b64_` before being stored into Vault.
Then, if a key name is prefixed by `b64_`, my custom `HashiCorpVaultSecretProvider` decodes its value before using it during the build thanks to `DownloadSecretsToWorker`.
Until recently, this was working without any issue but I now have the following error with buildbot-2.2.0:

```
2019-04-24 12:57:05+0200 [-] from debounced function:
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/dist-packages/buildbot/util/debounce.py", line 68, in invoke
	    d = defer.maybeDeferred(self.function)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/local/lib/python3.5/dist-packages/buildbot/process/buildstep.py", line 488, in updateSummary
	    stepResult)
	  File "/usr/local/lib/python3.5/dist-packages/buildbot/process/properties.py", line 217, in cleanupTextFromSecrets
	    text = text.replace(k, v)
	builtins.TypeError: Can't convert 'bytes' object to str implicitly
```

This seems related to logs secrets cleanup which assumes all secrets are `str`:
```python
    def cleanupTextFromSecrets(self, text):
        # Better be correct and inefficient than efficient and wrong
        for k, v in self._used_secrets.items():
            text = text.replace(k, v)
        return text
```

In this specific case, `k` is a `bytes` type so I changed the previous code like this (i.e. only replacing text if secret value is `str`):
```python
    def cleanupTextFromSecrets(self, text):
        # Better be correct and inefficient than efficient and wrong
        for k, v in self._used_secrets.items():
            if isinstance(k, str):
                text = text.replace(k, v)
        return text
```

Do you have any suggestion allowing me to fix that without editing master code or, better, a clean way to do it for `master` so I can try to make a PR (if that's an easy one...).

**Comment by p12tic** [comment]
I think using bytes for secrets is a valid use case, but it looks like the code has not been written with both bytes and str in mind, so adding proper support may be a complex task.

For a workaround, why is editing master code an inappropriate solution for you? You could create a patch file and apply it to the master source after each time you install master.

**Comment by faudebert** [comment]
I couldn't more agree: I'm fine patching master code for now but as you wrote, it's not that maintainable in the long run.

Thanks for your answer and let me know if I can be of any help.
