### ISSUE TITLE
Exceptions when adding new workers to builder using sighup; -> worker does not get jobs from builder

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbot/buildbot#4757]
Buildbot 2.2.0

I added new workers to some of our builders. The builders were already active in the system and used for other builders. They were added to the new builders due a short term need for more workers for those builders, and doing a full restart for the master is out of the question in this scenario.

When running sighup, I frequently got the exception below for various builders

When the sighup operation did succeed, only one of the three workers accepted scheduled builds from the builder they had been added to; and that was AFAICT a build on the builder that did not trigger any exceptions. I tried removing one of the workers from the builder, sighup, readding it, and sighup; got exceptions, then succeeded, but builds does not start.

Please note that this is not the first case we have had of exceptions breaking stuff during sighup, see https://github.com/buildbot/buildbot/issues/4673 and https://github.com/buildbot/buildbot/issues/4715 for the others.

```
2019-05-07 10:51:03+0000 [Broker (TLSMemoryBIOProtocol),19,1.2.3.4] during reconfig:
        Traceback (most recent call last):
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
            _inlineCallbacks(r, g, status)
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
        --- <exception caught here> ---
          File "sandbox/lib/python3.6/site-packages/buildbot/master.py", line 393, in doReconfig
            yield self.reconfigServiceWithBuildbotConfig(new_config)
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "sandbox/lib/python3.6/site-packages/buildbot/util/service.py", line 49, in reconfigServiceWithBuildbotConfig
            yield svc.reconfigServiceWithBuildbotConfig(new_config)
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/measured_service.py", line 31, in reconfigServiceWithBuildbotConfig
            yield super(MeasuredBuildbotServiceManager, self).reconfigServiceWithBuildbotConfig(new_config)
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "sandbox/lib/python3.6/site-packages/buildbot/util/service.py", line 520, in reconfigServiceWithBuildbotConfig
            yield svc.reconfigServiceWithSibling(config_sibling)
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "sandbox/lib/python3.6/site-packages/buildbot/worker/base.py", line 302, in reconfigServiceWithSibling
            yield self.updateWorker()
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "sandbox/lib/python3.6/site-packages/buildbot/worker/base.py", line 509, in sendBuilderList
            d1 = self.attachBuilder(b)
          File "sandbox/lib/python3.6/site-packages/buildbot/worker/base.py", line 514, in attachBuilder
            return builder.attached(self, self.worker_commands)
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1421, in _inlineCallbacks
            status.deferred.callback(getattr(e, "value", None))
          File "sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 459, in callback
            assert not isinstance(result, Deferred)
        builtins.AssertionError:
```

**Comment by p12tic** [comment]
Fixed in #5029.
