### ISSUE TITLE
remote_getWorkerInfo in 

### ISSUE THREAD

**Issue by winterz** [buildbot/buildbot#4758]
I installed a new windows build worker today.
I got the following error in build_worker\base.py (see below the --transcript--)

So I hacked base.py, line 324 to this:
                    with open(filename, "r", errors="ignore") as fin:
(i.e. I added the errors="ignore")
now it works.  Can you fix this properly?
-Allen

-- transcript starts here --

c:\Buildbot>c:\Python37\Scripts\buildbot-worker --verbose start
2019-05-07 15:06:48-0700 [-] Log opened.
2019-05-07 15:06:48-0700 [-] Loading buildbot.tac...
2019-05-07 15:06:48-0700 [-] Loaded.
2019-05-07 15:06:48-0700 [-] Warning: primary log target selected twice at <c:\python37\lib\site-packages\twisted\application\app.py:213> - previously selected at <c:\python37\lib\site-packages\twisted\python\log.py:214>.  Remove one of the calls to beginLoggingTo.
2019-05-07 15:06:48-0700 [-] twistd 19.2.0 (c:\python37\python.exe 3.7.3) starting up.
2019-05-07 15:06:48-0700 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2019-05-07 15:06:48-0700 [-] Starting Worker -- version: 2019.05.07
2019-05-07 15:06:48-0700 [-] recording hostname in twistd.hostname
2019-05-07 15:06:48-0700 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x0000019FAE8E8BA8>
2019-05-07 15:06:48-0700 [Broker,client] message from master: attached
2019-05-07 15:06:48-0700 [Broker,client] Peer will receive following PB traceback:
2019-05-07 15:06:48-0700 [Broker,client] Unhandled Error
        Traceback (most recent call last):
          File "c:\python37\lib\site-packages\twisted\spread\banana.py", line 173, in gotItem
            self.callExpressionReceived(item)
          File "c:\python37\lib\site-packages\twisted\spread\banana.py", line 136, in callExpressionReceived
            self.expressionReceived(obj)
          File "c:\python37\lib\site-packages\twisted\spread\pb.py", line 621, in expressionReceived
            method(*sexp[1:])
          File "c:\python37\lib\site-packages\twisted\spread\pb.py", line 1025, in proto_message
            self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
        --- <exception caught here> ---
          File "c:\python37\lib\site-packages\twisted\spread\pb.py", line 1054, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "c:\python37\lib\site-packages\twisted\spread\flavors.py", line 125, in remoteMessageReceived
            state = method(*args, **kw)
          File "c:\python37\lib\site-packages\buildbot_worker\base.py", line 324, in remote_getWorkerInfo
            files[f] = fin.read()
          File "c:\python37\lib\encodings\cp1252.py", line 23, in decode
            return codecs.charmap_decode(input,self.errors,decoding_table)[0]
        builtins.UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 594: character maps to <undefined>

2019-05-07 15:06:48-0700 [Broker,client] ReconnectingPBClientFactory.failedToGetPerspective
2019-05-07 15:06:48-0700 [Broker,client] While trying to connect:
        Traceback from remote host -- twisted.spread.pb.RemoteError: 'charmap' codec can't decode byte 0x81 in position 594: character maps to <undefined>

2019-05-07 15:06:48-0700 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x0000019FAE8E8BA8>
2019-05-07 15:06:48-0700 [-] Main loop terminated.
2019-05-07 15:06:48-0700 [-] Server Shut Down.
2019-05-07 15:06:48-0700 [-] Server Shut Down.

**Comment by seankelly** [comment]
Appears to be an encoding issue with a file in the `info` directory. If you're not setting an encoding then perhaps Windows-1252 was picked as a default. Try setting an encoding.

**Comment by p12tic** [comment]
I think it still makes sense to not crash and instead report the error as warning in the worker logs.

**Comment by winterz** [comment]
I don't see anything out of the ordinary:

```
c:\Buildbot\info>type admin
Buildmaster <buildmaster@foo.com>
```

```
c:\Buildbot\info>type host
Microsoft Windows [Version 10.0.17134.706]
```

could the editor backup files (ie. the tilde files) be causing some problem?
```
c:\Buildbot\info>dir
 Volume in drive C has no label.
 Volume Serial Number is 1EA0-B306

 Directory of c:\Buildbot\info

05/07/2019  09:14 AM    <DIR>          .
05/07/2019  09:14 AM    <DIR>          ..
05/07/2019  09:07 AM             1,514 .admin.un~
05/07/2019  09:14 AM               523 .host.un~
05/07/2019  09:07 AM                36 admin
05/07/2019  09:05 AM                39 admin~
05/07/2019  09:14 AM                44 host
05/07/2019  09:12 AM                46 host~
               6 File(s)          2,202 bytes
               2 Dir(s)  144,546,971,648 bytes free
```

**Comment by seankelly** [comment]
I think all files are opened. There's no check to exclude files after the `os.listdir`.

https://github.com/buildbot/buildbot/blob/414574c423242714482be5c7496ddb8ca8eab0be/worker/buildbot_worker/base.py#L320
