### ISSUE TITLE
buildbot_pkg do not build buildbot_travis anymore

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#4778]
We need to make sure that buildbot_pkg is still able to build guanlecoja based plugins.

**Comment by tardyp** [comment]
```
Obtaining file:///usr/home/bbuser/buildbot_travis
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    running build_js
    Running command: yarn run yarn-update-local
    yarn run v1.9.4
    error Command "yarn-update-local" not found.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/home/bbuser/buildbot_travis/setup.py", line 54, in <module>
        'future'
      File "/usr/home/bbuser/buildbot/pkg/buildbot_pkg.py", line 264, in setup_www_plugin
        **kw)
      File "/home/bbuser/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/home/bbuser/buildbot/pkg/buildbot_pkg.py", line 251, in run
        self.run_command('build_js')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/home/bbuser/buildbot/pkg/buildbot_pkg.py", line 225, in run
        subprocess.check_call(command, shell=shell)
      File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['yarn', 'run', 'yarn-update-local']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /usr/home/bbuser/buildbot_travis/
```

**Comment by rajdeepbharati** [comment]
I am getting the same error with https://github.com/rajdeepbharati/buildbot-vue-plugin

```
Obtaining file:///Users/rajdeep/bvp
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    running build_js
    warning ../package.json: No license field
    Running command: yarn run yarn-update-local
    yarn run v1.16.0
    warning ../package.json: No license field
    error Command "yarn-update-local" not found.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/rajdeep/bvp/setup.py", line 46, in <module>
        """,
      File "/Users/rajdeep/clonedbb/pkg/buildbot_pkg.py", line 264, in setup_www_plugin
        **kw)
      File "/Users/rajdeep/clonedbb/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/rajdeep/clonedbb/pkg/buildbot_pkg.py", line 251, in run
        self.run_command('build_js')
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/rajdeep/clonedbb/pkg/buildbot_pkg.py", line 225, in run
        subprocess.check_call(command, shell=shell)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['yarn', 'run', 'yarn-update-local']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /Users/rajdeep/bvp/
```

**Comment by rajdeepbharati** [comment]
I guess one possible solution would be to add this kind of script: https://github.com/buildbot/buildbot/blob/master/www/base/package.json#L11 with every plugin's package.json. But it will have to refer to the buildbot source directory

**Comment by rajdeepbharati** [comment]
I added this line `"yarn-update-local": "yarn add ../clonedbb/www/data_module ../clonedbb/www/guanlecoja-ui && yarn add --dev ../clonedbb/www/build_common"` as a script in my plugin's `package.json` and it's working. However, it is referring to an external directory (buildbot source)

**Comment by tardyp** [comment]
We should rather fix the pkg script to not do yarn-update-local.

yarn-update-local should be done only manually when developing dependencies or in the CI.

**Comment by rajdeepbharati** [comment]
Do you mean simply removing this line?
https://github.com/buildbot/buildbot/blob/master/pkg/buildbot_pkg.py#L211

**Comment by p12tic** [comment]
@tardyp: I think we should still keep the `yarn run yarn-update-local` behavior for plugins that contain that script rule. Otherwise it will lead to very unpleasant surprises when developing locally, as node_modules directory is not tracked by git and not cleaned either, so the plugins that are referenced from relative filesystem path will quickly go out of date.
