### ISSUE TITLE
Latent Docker worker does not clean up containers

### ISSUE THREAD

**Issue by gregorydlogan** [buildbot/buildbot#4782]
I have a 2.3.0 install which is failing to instanciate workers (likely an issue on my end), but more importantly it's failing to clean up the containers when it's done with them.  Successful builds *do* clean up appropriately, so there's a missed cleanup check on a failed startup. 
 Example log of an attempted startup:

```none
2019-05-22 18:40:54+0000 [-] <Build Pull Request Database Tests number:None results:success>.startBuild
2019-05-22 18:40:54+0000 [-] acquireLocks(worker <DockerLatentWorker 'oc-com-worker'>, locks [(<MasterLock(oc-com-worker1.rrz.uni-koeln.de, 1)>, <buildbot.locks.LockAccess object at 0x7f8fbece9710>)])
2019-05-22 18:40:54+0000 [-] substantiating worker <LatentWorkerForBuilder builder='Pull Request Build' worker='oc-com-worker' state=DETACHED>
2019-05-22 18:40:54+0000 [-] Image 'oc-com-worker_140255358260952_image' not found, building it from scratch
2019-05-22 18:40:54+0000 [-] acquireLocks(worker <DockerLatentWorker 'oc-com-presentation'>, locks [(<MasterLock(oc-com-presentation.rrz.uni-koeln.de, 1)>, <buildbot.locks.LockAccess object at 0x7f8fbece95c0>)])
2019-05-22 18:40:54+0000 [-] substantiating worker <LatentWorkerForBuilder builder='Pull Request Build' worker='oc-com-presentation' state=DETACHED>
2019-05-22 18:40:54+0000 [-] Image 'oc-com-presentation_140255358260728_image' not found, building it from scratch
2019-05-22 18:40:54+0000 [-] Step 1/5 : FROM greglogan/ocqa-deb9-worker-base:v2.3.0
2019-05-22 18:40:54+0000 [-]  ---> f0ad73c14a88
2019-05-22 18:40:54+0000 [-] Step 2/5 : RUN groupadd -g 1004 builder &&     useradd -m -u 1004 -g 1004 -s /bin/bash -d /builder builder &&     mkdir /builder/.ssh &&     chown -R builder:builder /builder
2019-05-22 18:40:54+0000 [-]  ---> Running in 74a9f09bc02d
2019-05-22 18:40:55+0000 [-] Step 1/5 : FROM greglogan/ocqa-cent7-worker-base:v2.3.0
2019-05-22 18:40:55+0000 [-]  ---> f7c86f42129b
2019-05-22 18:40:55+0000 [-] Step 2/5 : RUN groupadd -g 1004 builder &&     useradd -m -u 1004 -g 1004 -s /bin/bash -d /builder builder &&     mkdir /builder/.ssh &&     chown -R builder:builder /builder
2019-05-22 18:40:55+0000 [-]  ---> Running in 9a453ba965eb
2019-05-22 18:40:55+0000 [-] acquireLocks(worker <DockerLatentWorker 'ci-opencast-org'>, locks [(<MasterLock(ci.opencast.org, 1)>, <buildbot.locks.LockAccess object at 0x7f8fbece94a8>)])
2019-05-22 18:40:55+0000 [-] substantiating worker <LatentWorkerForBuilder builder='Pull Request Database Tests' worker='ci-opencast-org' state=DETACHED>
2019-05-22 18:40:55+0000 [-] [91museradd: warning: the home directory already exists.
2019-05-22 18:40:55+0000 [-] Not copying any file from skel directory into it.
2019-05-22 18:40:55+0000 [-] [0m
2019-05-22 18:40:55+0000 [-] Image 'ci-opencast-org_140255358260448_image' not found, building it from scratch
2019-05-22 18:40:55+0000 [-] Step 1/5 : FROM greglogan/ocqa-cent7-worker-base:v2.3.0
2019-05-22 18:40:55+0000 [-]  ---> f7c86f42129b
2019-05-22 18:40:55+0000 [-] Step 2/5 : RUN groupadd -g 1004 builder &&     useradd -m -u 1004 -g 1004 -s /bin/bash -d /builder builder &&     mkdir /builder/.ssh &&     chown -R builder:builder /builder
2019-05-22 18:40:55+0000 [-]  ---> Running in bb047d88b9d0
2019-05-22 18:40:55+0000 [-] [91museradd: warning: the home directory already exists.
2019-05-22 18:40:55+0000 [-] Not copying any file from skel directory into it.
2019-05-22 18:40:55+0000 [-] [0m
2019-05-22 18:40:55+0000 [-]  ---> 7123c7672dc8
2019-05-22 18:40:55+0000 [-] Step 3/5 : USER builder
2019-05-22 18:40:55+0000 [-]  ---> Running in d59b193960d6
2019-05-22 18:40:55+0000 [-]  ---> f4cfedb4809c
2019-05-22 18:40:55+0000 [-] Step 4/5 : WORKDIR /builder
2019-05-22 18:40:55+0000 [-]  ---> Running in a8e404f88c99
2019-05-22 18:40:55+0000 [-]  ---> cbaface871de
2019-05-22 18:40:55+0000 [-] Step 5/5 : CMD ["/usr/local/bin/dumb-init", "twistd", "--pidfile=", "-ny", "buildbot.tac"]
2019-05-22 18:40:55+0000 [-]  ---> 2f209219b99c
2019-05-22 18:40:55+0000 [-] Step 3/5 : USER builder
2019-05-22 18:40:55+0000 [-]  ---> Running in 8746f1e135f0
2019-05-22 18:40:55+0000 [-]  ---> Running in 57c6e6fa8a96
2019-05-22 18:40:56+0000 [-]  ---> 8c0f2dd45039
2019-05-22 18:40:56+0000 [-] Step 4/5 : WORKDIR /builder
2019-05-22 18:40:56+0000 [-]  ---> 3f26c06d7219
2019-05-22 18:40:56+0000 [-] Successfully built 3f26c06d7219
2019-05-22 18:40:56+0000 [-] Successfully tagged oc-com-worker_140255358260952_image:latest
2019-05-22 18:40:56+0000 [-]  ---> Running in ed533f6b6bf8
2019-05-22 18:40:56+0000 [-]  ---> e6793dd8e710
2019-05-22 18:40:56+0000 [-] Step 5/5 : CMD ["/usr/local/bin/dumb-init", "twistd", "--pidfile=", "-ny", "buildbot.tac"]
2019-05-22 18:40:56+0000 [-] Container created, Id: 501117...
2019-05-22 18:40:56+0000 [-]  ---> Running in 2ad5b9468b43
2019-05-22 18:40:56+0000 [-]  ---> 4be108a5f63d
2019-05-22 18:40:56+0000 [-] Successfully built 4be108a5f63d
2019-05-22 18:40:56+0000 [-] Successfully tagged oc-com-presentation_140255358260728_image:latest
2019-05-22 18:40:56+0000 [-] Container created, Id: b59dae...
2019-05-22 18:40:56+0000 [-] Container started
2019-05-22 18:40:56+0000 [-] [91museradd: warning: the home directory already exists.
2019-05-22 18:40:56+0000 [-] Not copying any file from skel directory into it.
2019-05-22 18:40:56+0000 [-] [0m
2019-05-22 18:40:56+0000 [-] Container started
2019-05-22 18:40:56+0000 [-] docker VM 501117: b'2019-05-22 18:40:56+0000 [-] Loading buildbot.tac...'
2019-05-22 18:40:56+0000 [-] docker VM 501117: b'2019-05-22 18:40:56+0000 [-] Loaded.'
2019-05-22 18:40:56+0000 [-] docker VM 501117: b'2019-05-22 18:40:56+0000 [-] twistd 19.2.0 (/usr/bin/python3 3.5.3) starting up.'
2019-05-22 18:40:56+0000 [-] docker VM 501117: b'2019-05-22 18:40:56+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.'
2019-05-22 18:40:56+0000 [-] docker VM 501117: b'2019-05-22 18:40:56+0000 [-] Starting Worker -- version: 2019.05.16'
2019-05-22 18:40:56+0000 [-] docker VM 501117: b'2019-05-22 18:40:56+0000 [-] recording hostname in twistd.hostname'
2019-05-22 18:40:56+0000 [-] docker VM 501117: b'2019-05-22 18:40:56+0000 [-] failed - ignoring'
2019-05-22 18:40:56+0000 [-] docker VM 501117: b'2019-05-22 18:40:56+0000 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x7f8951fd5f28>'
2019-05-22 18:40:56+0000 [Broker,0,127.0.0.1] worker 'oc-com-worker' attaching from IPv4Address(type='TCP', host='127.0.0.1', port=54736)
2019-05-22 18:40:56+0000 [Broker,0,127.0.0.1] Got workerinfo from 'oc-com-worker'
2019-05-22 18:40:56+0000 [-] docker VM 501117: b'2019-05-22 18:40:56+0000 [Broker,client] message from master: attached'
2019-05-22 18:40:56+0000 [-]  ---> cd426adba309
2019-05-22 18:40:56+0000 [-] Step 3/5 : USER builder
2019-05-22 18:40:56+0000 [-]  ---> Running in 659b39758123
2019-05-22 18:40:57+0000 [-] bot attached
2019-05-22 18:40:57+0000 [-]  ---> d3a4eb26fd22
2019-05-22 18:40:57+0000 [-] Step 4/5 : WORKDIR /builder
2019-05-22 18:40:57+0000 [-]  ---> Running in 4c00d146946a
2019-05-22 18:40:57+0000 [Broker,0,127.0.0.1] Firing oc-com-worker substantiation deferred with failure
2019-05-22 18:40:57+0000 [Broker,0,127.0.0.1] while worker_prepare
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
	    self._startRunCallbacks(fail)
	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	--- <exception caught here> ---
	  File "/usr/lib/python3.6/site-packages/buildbot/process/build.py", line 340, in startBuild
	    ready_or_failure = yield workerforbuilder.prepare(self)
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/base.py", line 441, in attached
	    yield self.updateWorker()
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/base.py", line 525, in sendBuilderList
	    slist = yield self.conn.remoteSetBuilderList(builders=blist)
	  File "/usr/lib/python3.6/site-packages/twisted/spread/pb.py", line 513, in throwExceptionIntoGenerator
	    return g.throw(RemoteError(self.type, self.value, self.traceback))
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/protocols/pb.py", line 239, in remoteSetBuilderList
	    builders = yield self.mind.callRemote('setBuilderList', builders)
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/latent.py", line 305, in attached
	    yield super().attached(bot)
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/base.py", line 441, in attached
	    yield self.updateWorker()
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/base.py", line 525, in sendBuilderList
	    slist = yield self.conn.remoteSetBuilderList(builders=blist)
	  File "/usr/lib/python3.6/site-packages/twisted/spread/pb.py", line 513, in throwExceptionIntoGenerator
	    return g.throw(RemoteError(self.type, self.value, self.traceback))
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/protocols/pb.py", line 239, in remoteSetBuilderList
	    builders = yield self.mind.callRemote('setBuilderList', builders)
	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/base.py", line 441, in attached
	    yield self.updateWorker()
	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/base.py", line 525, in sendBuilderList
	    slist = yield self.conn.remoteSetBuilderList(builders=blist)
	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/lib/python3.6/site-packages/twisted/spread/pb.py", line 513, in throwExceptionIntoGenerator
	    return g.throw(RemoteError(self.type, self.value, self.traceback))
	  File "/usr/lib/python3.6/site-packages/buildbot/worker/protocols/pb.py", line 239, in remoteSetBuilderList
	    builders = yield self.mind.callRemote('setBuilderList', builders)
	twisted.spread.pb.RemoteError: [Errno 13] Permission denied: '/builds/6_x_Reports'
	
2019-05-22 18:40:57+0000 [Broker,0,127.0.0.1] oc-com-worker has been put in quarantine for 10s
2019-05-22 18:40:57+0000 [-]  ---> 455db9f885bd
2019-05-22 18:40:57+0000 [-] Step 5/5 : CMD ["/usr/local/bin/dumb-init", "twistd", "--pidfile=", "-ny", "buildbot.tac"]
2019-05-22 18:40:57+0000 [-]  ---> Running in 1a428bf184a3
2019-05-22 18:40:57+0000 [-] docker VM b59dae: b'2019-05-22 18:40:56+0000 [-] Loading buildbot.tac...\n2019-05-22 18:40:57+0000 [-] Loaded.'
2019-05-22 18:40:57+0000 [Broker,0,127.0.0.1] insubstantiating worker <DockerLatentWorker 'oc-com-worker'>
2019-05-22 18:40:57+0000 [Broker,0,127.0.0.1] No substantiation deferred for oc-com-worker
2019-05-22 18:40:57+0000 [Broker,0,127.0.0.1] Stopping container 501117...
2019-05-22 18:40:57+0000 [-] docker VM b59dae: b'2019-05-22 18:40:57+0000 [-] twistd 19.2.0 (/usr/bin/python3.6 3.6.8) starting up.'
2019-05-22 18:40:57+0000 [-] docker VM b59dae: b'2019-05-22 18:40:57+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.'
2019-05-22 18:40:57+0000 [-] docker VM b59dae: b'2019-05-22 18:40:57+0000 [-] Starting Worker -- version: 2019.05.16'
2019-05-22 18:40:57+0000 [-] docker VM b59dae: b'2019-05-22 18:40:57+0000 [-] recording hostname in twistd.hostname'
2019-05-22 18:40:57+0000 [-] docker VM b59dae: b'2019-05-22 18:40:57+0000 [-] failed - ignoring'
2019-05-22 18:40:57+0000 [-] docker VM b59dae: b'2019-05-22 18:40:57+0000 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x7f91b4077748>'
2019-05-22 18:40:57+0000 [-]  ---> 6883447ba06c
2019-05-22 18:40:57+0000 [-] Successfully built 6883447ba06c
2019-05-22 18:40:57+0000 [Broker,0,127.0.0.1] Worker.detached(oc-com-worker)
2019-05-22 18:40:57+0000 [Broker,0,127.0.0.1] releaseLocks(<DockerLatentWorker 'oc-com-worker'>): [(<MasterLock(oc-com-worker1.rrz.uni-koeln.de, 1)>, <buildbot.locks.LockAccess object at 0x7f8fbece9710>)]
2019-05-22 18:40:57+0000 [-] Successfully tagged ci-opencast-org_140255358260448_image:latest
2019-05-22 18:40:57+0000 [Broker,1,127.0.0.1] worker 'oc-com-presentation' attaching from IPv4Address(type='TCP', host='127.0.0.1', port=54894)
2019-05-22 18:40:57+0000 [-] docker VM b59dae: b'2019-05-22 18:40:57+0000 [Broker,client] message from master: attached'
2019-05-22 18:40:57+0000 [Broker,1,127.0.0.1] Got workerinfo from 'oc-com-presentation'
2019-05-22 18:40:57+0000 [-] Container created, Id: a12fd9...
2019-05-22 18:40:57+0000 [-] bot attached
2019-05-22 18:40:57+0000 [-] docker VM b59dae: b'2019-05-22 18:40:57+0000 [Broker,client] Peer will receive following PB traceback:'
2019-05-22 18:40:57+0000 [Broker,1,127.0.0.1] Firing oc-com-presentation substantiation deferred with failure
```

Workers are defined like this:

```python
worker.DockerLatentWorker("ci-opencast-org", password=None,
                docker_host='tcp://localhost:2375',
                dockerfile=selectWorkerDockerfile,
                volumes=['/opt/buildbot/ssh:/builder/.ssh', '/opt/buildbot/m2:/builder/m2', '/opt/buildbot/builds:/builds', '/var/www/buildbot:/var/www/buildbot', '/opt/buildbot/buildbot-config:/var/lib/buildbot:ro'],
                masterFQDN="localhost:9989",
                hostconfig={ "network_mode": "host" }, #Host mode needed to use the ssh-forwarded tunnel
                followStartupLogs=True,
                locks=[locks["ci.opencast.org"].access('exclusive')]),
```

**Comment by gregorydlogan** [comment]
Further investigation: What I'm actually seeing is the container that Buildbot is building the image in.  It builds the image:
```none
docker ps -a
...
ce23d8fe33cb        6c2dca05d064      "/bin/sh -c '#(nop) …"   8 seconds ago...
```
saves it:
```none
docker images
<none>                  <none>              6c2dca05d064        About a minute ago   1.93GB
```
then runs it:
```none
efd8cdf368f2        builder03_139985493847848_image    "/usr/local/bin/dumb…"   8 seconds ago       Up 8 seconds           buildbot-builder03-0a0bf3
```

The container used by the worker for the tests is correctly removed, but the container used to *build* the image which the container uses for the tests is *not removed*.  Clear as mud? :)
