### ISSUE TITLE
Cannot connect to SMTP server

### ISSUE THREAD

**Issue by angeloudy** [buildbot/buildbot#4815]
My buildbot cannot send email since I upgraded it to 2.3.x

Getting the following error
```
82412 2019-06-07 16:48:02+1000 [-] sending mail (599 bytes) to ['tao@ish.com.au']
82413 2019-06-07 16:48:02+1000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x811c7f4a8>
82414 2019-06-07 16:48:02+1000 [ESMTPSender,client] SMTP Client retrying server. Retry: 5
82415 2019-06-07 16:48:02+1000 [ESMTPSender,client] SMTP Client retrying server. Retry: 4
82416 2019-06-07 16:48:02+1000 [ESMTPSender,client] SMTP Client retrying server. Retry: 3
82417 2019-06-07 16:48:02+1000 [ESMTPSender,client] SMTP Client retrying server. Retry: 2
82418 2019-06-07 16:48:02+1000 [ESMTPSender,client] SMTP Client retrying server. Retry: 1
82419 2019-06-07 16:48:02+1000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x811c7f4a8>
82420 2019-06-07 16:48:02+1000 [-] Unhandled error in Deferred:
82421 2019-06-07 16:48:02+1000 [-] Unhandled Error
82422     Traceback (most recent call last):
82423     --- <exception caught here> ---
82424       File "/usr/local/lib/python3.6/site-packages/buildbot/reporters/notifier.py", line 280, in buildMessage
82425         list(users), patches, logs)
82426       File "/usr/local/lib/python3.6/site-packages/buildbot/reporters/mail.py", line 268, in sendMessage
82427         yield self.sendMail(m, all_recipients)
82428     twisted.mail._except.SMTPConnectError: Unable to connect to server.
82429
```
My twisted installation is `twisted-18.9.0_1`

Is there a way I can debug into this?

**Comment by p12tic** [comment]
Thanks for the bug report!

Which version have you updated from? 2.2.0? It's really strange because nothing SMTP-related changed between 2.2.0 and 2.3.0. I suspend that it could be a dependency issue.

Could you maybe help by bisecting? There has been only 21 PR between v2.2.0 and v2.3.0, so you would only need to do 5 tests to pin-point the issue to a specific PR.

The process to create and install packages to a virtualenv is as follows:
```
rm -rf dist
make tarballs
pip install dist/buildbot-2*.$suffix
pip install dist/buildbot?pkg*.$suffix
pip install dist/*.$suffix
```

Make sure you're cleaning your virtualenv after each test, I have been burned by unclean bisecting many times.

The list of PRs is as follows:
```
git log --first-parent v2.2.0..v2.3.0 --format=oneline
22e9a0aca52a7345b40aec157673bc3e524de94b (tag: v2.3.0) Merge pull request #4755 from p12tic/release
9b8e01aa3950cfbdb8e3998fd0ce8ce6476da325 Merge pull request #4752 from p12tic/fix-smoke-tests
c20a39257c319e241d0276117f2d1b147eb6a48b Merge pull request #4753 from p12tic/www-remove-npm-support
b7f6c2e5c81f187a3a4d33653f855f6f39ee96aa Merge pull request #4754 from p12tic/www-coffeescript-removal-release-note
f769aa64e543e1fd6342e3f6b56285f6193cd6af Merge pull request #4748 from vbraun/vbraun/test-invalid-utf8
a108c3eec75b7dbec6c59d6929c2bbc5c9ddd086 Merge pull request #4742 from buildbot/pyup-scheduled-update-2019-04-29
bcf21933bac82424a21076ae0cb796da9da8e7bc Merge pull request #4747 from p12tic/fix-smoke-tests
8041e0347d3a2e3b8d1e2babcb342468781759d5 Merge pull request #4736 from p12tic/www-guanlecoja-ui
b9e155c0f8dbb2ad384338bad98c98ba01c2bc08 Merge pull request #4737 from p12tic/www-fix-coffeescript-returns
5df3cfae6d760557d99156633c32b1822a1e130c Merge pull request #4738 from p12tic/www-spacing
5711c7b4daa317f59cc57492f4a49395a0ca002b Merge pull request #4691 from p12tic/latent-machine
38de359f9027402f366363e890903bf6c9de8d16 Merge pull request #4713 from rjarry/migration-error
ec4d982346b8a99a7991c4658322c7698d9eee1f Merge pull request #4727 from buildbot/pyup-scheduled-update-2019-04-22
54a1ca9e947136a824c77657af37e9f70bc9f656 Merge pull request #4720 from p12tic/decaffeinate
7c2524ee8ca8488e0f524612d343f53acb7ab203 Merge pull request #4732 from p12tic/fix-smoke-tests
280b3c0ac868cd434ef069065c8b4b75e9de9cc4 Merge pull request #4724 from p12tic/latent-worker-misc
6335a978fef3ee71a3fdd7033a3fb846a9f7e02f Merge pull request #4723 from buildbot/pyup-scheduled-update-2019-04-15
6793de49ba86c90d94016e7ed7d728940907e0d5 Merge pull request #4708 from p12tic/latent-worker-misc
4cd80e355acdacd8ba86411774a4bd009668ebf6 Merge pull request #4719 from PodnimatelPingvinov/git-submodules-fix
f42dcd771712499460d0919cbbc223d5d9f22988 Merge pull request #4714 from chapipo/fix/GitPush-buildstep-missing-setup
5f8d824fdcb083761bd21a4235d6c91ae509ad18 Merge pull request #4707 from tardyp/release
```

**Comment by angeloudy** [comment]
I found the cause for my problem. 
It was our firewall rejecting connection from buildbot, which is weird because I have no problem connect from buildbot master to the SMTP server by hand. 
After I switched to a different SMTP server, buildbot worked fine sending emails.

Still, it would be nice for buildbot to give more detailed errors than `Unable to connect to server`.

**Comment by tardyp** [comment]
"Unable to connect to server". is to me the only thing that buildbot knows.
It tried open a tcp connection, and it didn't work. So this is indeed
usually either your smtp server which is down, or a firewall blocking the
tcp packets

Pierre
