### ISSUE TITLE
Server does not detect failed build

### ISSUE THREAD

**Issue by vbraun** [buildbot/buildbot#4821]
I'm having issues where, if the worker build fails, the server state is not updated accordingly and remains at the building / yellow badge state.

The server log when the build failure arrives:
~~~~
2019-06-09 10:47:40+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33258)
2019-06-09 10:48:18+0000 [Broker,7,91.64.96.41] <RemoteShellCommand '['make', '-j8', '-k', 'start']'> rc=2
2019-06-09 10:49:47+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33268)
2019-06-09 10:49:47+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33262)
2019-06-09 10:49:47+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33278)
2019-06-09 10:49:47+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33272)
2019-06-09 10:49:47+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33270)
2019-06-09 10:49:49+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33274)
~~~~

Then I tried to press the "Stop" button on the build page:
~~~~
2019-06-09 10:56:40+0000 [-]  <Build  fast Volker KvmMac (OSX 10.14) full number:1 results:success>: stopping build: no reason 6
2019-06-09 10:56:40+0000 [-] RemoteCommand.interrupt <RemoteShellCommand '['make', '-j8', '-k', 'start']'> no reason
2019-06-09 10:56:40+0000 [-]  but this RemoteCommand is already inactive
~~~~

Then I stopped the worker:
~~~~
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41] <Build  fast Volker KvmMac (OSX 10.14) full number:1 results:cancelled>.lostRemote
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41]  stopping currentStep Compile(command=['make', '-j8', '-k', 'start'], env={'SAGE_CHECK_PACKAGES': '!python2,!python3,!sagetex,!m4ri,!m4rie
,!cython,!openblas,!zeromq,!curl,!yasm,!arb,!cvxopt,!eclib,!networkx,!gd,!r', 'SAGE_SERVER': 'http://sagepad.org/', 'SAGE_PARALLEL_SPKG_BUILD': 'yes', 'SAGE_CRASH_LOGS': Interpolate('%(p
rop:builddir)s/crashlogs'), 'SAGE_CHECK': 'yes', 'MAKE': 'make -j8', 'DOT_SAGE': Interpolate('%(prop:builddir)s/dot_sage')}, timeout=86400, haltOnFailure=True, warningPattern='^Error: ',
 logfiles={'arb': 'logs/buildbot/arb.log', 'boehm_gc': 'logs/buildbot/boehm_gc.log', 'boost': 'logs/buildbot/boost_cropped.log', 'bzip2': 'logs/buildbot/bzip2.log', 'cddlib': 'logs/build
bot/cddlib.log', 'cephes': 'logs/buildbot/cephes.log', 'cliquer': 'logs/buildbot/cliquer.log', 'conway': 'logs/buildbot/conway_polynomials.log', 'csage': 'logs/buildbot/csage.log', 'curl
': 'logs/buildbot/curl.log', 'cvxopt': 'logs/buildbot/cvxopt.log', 'cython': 'logs/buildbot/cython.log', 'docutils': 'logs/buildbot/docutils.log', 'ecl': 'logs/buildbot/ecl.log', 'eclib'
: 'logs/buildbot/eclib.log', 'ecm': 'logs/buildbot/ecm.log', 'ell_curves': 'logs/buildbot/elliptic_curves.log', 'flint': 'logs/buildbot/flint.log', 'flintqs': 'logs/buildbot/flintqs.log'
, 'freetype': 'logs/buildbot/freetype.log', 'gap': 'logs/buildbot/gap.log', 'gcc': 'logs/buildbot/gcc.log', 'gd': 'logs/buildbot/gd.log', 'gdmodule': 'logs/buildbot/gdmodule.log', 'g2red
': 'logs/buildbot/genus2reduction.log', 'gf2x': 'logs/buildbot/gf2x.log', 'gfan': 'logs/buildbot/gfan.log', 'giac': 'logs/buildbot/giac.log', 'git': 'logs/buildbot/git.log', 'givaro': 'l
ogs/buildbot/givaro.log', 'glpk': 'logs/buildbot/glpk.log', 'graphs': 'logs/buildbot/graphs.log', 'gsl': 'logs/buildbot/gsl.log', 'iconv': 'logs/buildbot/iconv.log', 'iml': 'logs/buildbo
t/iml.log', 'ipython': 'logs/buildbot/ipython.log', 'jinja2': 'logs/buildbot/jinja2.log', 'jmol': 'logs/buildbot/jmol.log', 'lcalc': 'logs/buildbot/lcalc.log', 'libfplll': 'logs/buildbot
/libfplll.log', 'libgap': 'logs/buildbot/libgap.log', 'm4ri': 'logs/buildbot/m4ri.log', 'm4rie': 'logs/buildbot/m4rie.log', 'libpng': 'logs/buildbot/libpng.log', 'linbox': 'logs/buildbot
/linbox.log', 'matplotlib': 'logs/buildbot/matplotlib.log', 'maxima': 'logs/buildbot/maxima.log', 'mpc': 'logs/buildbot/mpc.log', 'mpfi': 'logs/buildbot/mpfi.log', 'mpfr': 'logs/buildbot
/mpfr.log', 'mpir': 'logs/buildbot/mpir.log', 'mpmath': 'logs/buildbot/mpmath.log', 'ncurses': 'logs/buildbot/ncurses.log', 'networkx': 'logs/buildbot/networkx.log', 'ntl': 'logs/buildbo
t/ntl.log', 'numpy': 'logs/buildbot/numpy.log', 'openblas': 'logs/buildbot/openblas.log', 'palp': 'logs/buildbot/palp.log', 'pari': 'logs/buildbot/pari.log', 'galdata': 'logs/buildbot/pa
ri_galdata.log', 'seadata': 'logs/buildbot/pari_seadata_small.log', 'patch': 'logs/buildbot/patch.log', 'pexpect': 'logs/buildbot/pexpect.log', 'pillow': 'logs/buildbot/pillow.log', 'pkg
conf': 'logs/buildbot/pkgconf.log', 'pkgconfig': 'logs/buildbot/pkgconfig.log', 'polybori': 'logs/buildbot/polybori.log', 'polytopes': 'logs/buildbot/polytopes_db.log', 'ppl': 'logs/buil
dbot/ppl.log', 'pplpy': 'logs/buildbot/pplpy.log', 'pycrypto': 'logs/buildbot/pycrypto.log', 'pygments': 'logs/buildbot/pygments.log', 'pynac': 'logs/buildbot/pynac.log', 'python2': 'log
s/buildbot/python2.log', 'python3': 'logs/buildbot/python3.log', 'r-project': 'logs/buildbot/r.log', 'ratpoints': 'logs/buildbot/ratpoints.log', 'readline': 'logs/buildbot/readline.log',
 'rubiks': 'logs/buildbot/rubiks.log', 'sage': 'logs/buildbot/sage.log', 'sagelib': 'logs/buildbot/sagelib.log', 'sagenb': 'logs/buildbot/sagenb.log', 'sagetex': 'logs/buildbot/sagetex.l
og', 'scipy': 'logs/buildbot/scipy.log', 'scons': 'logs/buildbot/scons.log', 'setuptools': 'logs/buildbot/setuptools.log', 'singular': 'logs/buildbot/singular.log', 'six': 'logs/buildbot
/six.log', 'sphinx': 'logs/buildbot/sphinx.log', 'sqlalchemy': 'logs/buildbot/sqlalchemy.log', 'sqlite': 'logs/buildbot/sqlite.log', 'symmetrica': 'logs/buildbot/symmetrica.log', 'sympow
': 'logs/buildbot/sympow.log', 'sympy': 'logs/buildbot/sympy.log', 'tachyon': 'logs/buildbot/tachyon.log', 'tornado': 'logs/buildbot/tornado.log', 'zlib': 'logs/buildbot/zlib.log', 'zn_p
oly': 'logs/buildbot/zn_poly.log', 'zeromq': 'logs/buildbot/zeromq.log', 'pyzmq': 'logs/buildbot/pyzmq.log'}, lazylogfiles=True)
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41] RemoteCommand.interrupt <RemoteShellCommand '['make', '-j8', '-k', 'start']'> [Failure instance: Traceback (failure with no frames): <clas
s 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
        ]
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41]  but this RemoteCommand is already inactive
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41] Worker.detached(volker-kvm-osx)
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41] releaseLocks(<Worker 'volker-kvm-osx'>): []
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41] Worker volker-kvm-osx detached from  fast Volker KvmMac (OSX 10.14) incremental
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41] Worker volker-kvm-osx detached from  fast Volker KvmMac (OSX 10.14) full
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41] Worker volker-kvm-osx detached from Zpkg  fast Volker KvmMac (OSX 10.14) pkg-binary
2019-06-09 10:58:03+0000 [Broker,7,91.64.96.41] Got fatal Exception on DB
        Traceback (most recent call last):
          File "/usr/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/usr/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/usr/local/lib/python3.6/site-packages/buildbot/db/pool.py", line 209, in __thd
            log.err(e, 'Got fatal Exception on DB')
        --- <exception caught here> ---
          File "/usr/local/lib/python3.6/site-packages/buildbot/db/pool.py", line 182, in __thd
            rv = callable(arg, *args, **kwargs)
          File "/usr/local/lib/python3.6/site-packages/buildbot/db/logs.py", line 156, in thdAddLog
            "log with slug '%r' already exists in this step" % (slug,))
        builtins.KeyError: "log with slug ''cancelled'' already exists in this step"
~~~~

Then I restarted the worker:
~~~~
2019-06-09 10:59:07+0000 [Broker,26,91.64.96.41] worker 'volker-kvm-osx' attaching from IPv4Address(TCP, '91.64.96.41', 50678)
2019-06-09 10:59:07+0000 [Broker,26,91.64.96.41] Got workerinfo from 'volker-kvm-osx'
2019-06-09 10:59:07+0000 [-] bot attached
2019-06-09 10:59:07+0000 [Broker,26,91.64.96.41] Worker volker-kvm-osx attached to  fast Volker KvmMac (OSX 10.14) incremental
2019-06-09 10:59:07+0000 [Broker,26,91.64.96.41] Worker volker-kvm-osx attached to  fast Volker KvmMac (OSX 10.14) full
2019-06-09 10:59:07+0000 [Broker,26,91.64.96.41] Worker volker-kvm-osx attached to Zpkg  fast Volker KvmMac (OSX 10.14) pkg-binary
2019-06-09 10:59:19+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33346)
2019-06-09 10:59:21+0000 [-]  <Build  fast Volker KvmMac (OSX 10.14) full number:1 results:retry>: stopping build: no reason 6
2019-06-09 10:59:21+0000 [-] RemoteCommand.interrupt <RemoteShellCommand '['make', '-j8', '-k', 'start']'> no reason
2019-06-09 10:59:21+0000 [-]  but this RemoteCommand is already inactive
2019-06-09 10:59:21+0000 [-] Got fatal Exception on DB
        Traceback (most recent call last):
          File "/usr/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/usr/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/usr/local/lib/python3.6/site-packages/buildbot/db/pool.py", line 209, in __thd
            log.err(e, 'Got fatal Exception on DB')
        --- <exception caught here> ---
          File "/usr/local/lib/python3.6/site-packages/buildbot/db/pool.py", line 182, in __thd
            rv = callable(arg, *args, **kwargs)
          File "/usr/local/lib/python3.6/site-packages/buildbot/db/logs.py", line 156, in thdAddLog
            "log with slug '%r' already exists in this step" % (slug,))
        builtins.KeyError: "log with slug ''cancelled'' already exists in this step"
        
2019-06-09 10:59:21+0000 [-] Got fatal Exception on DB
        Traceback (most recent call last):
          File "/usr/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/usr/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/usr/local/lib/python3.6/site-packages/buildbot/db/pool.py", line 209, in __thd
            log.err(e, 'Got fatal Exception on DB')
        --- <exception caught here> ---
          File "/usr/local/lib/python3.6/site-packages/buildbot/db/pool.py", line 182, in __thd
            rv = callable(arg, *args, **kwargs)
          File "/usr/local/lib/python3.6/site-packages/buildbot/db/logs.py", line 156, in thdAddLog
            "log with slug '%r' already exists in this step" % (slug,))
        builtins.KeyError: "log with slug ''cancelled_2'' already exists in this step"
        
2019-06-09 11:00:13+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33360)
2019-06-09 11:00:13+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33364)
2019-06-09 11:00:17+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33358)
2019-06-09 11:00:17+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33362)
2019-06-09 11:00:21+0000 [-] Timing out client: IPv4Address(TCP, '91.64.96.41', 33344)
~~~~

The buildbot server still displays building / yellow badge...

**Comment by p12tic** [comment]
Thanks for the bug report with the logs. I've seen this issue sometimes, though very rarely too. There's no workaround currently known unfortunately...

**Comment by krzk** [comment]
I think I hit this or something similar very often - 20% of builds.

Master and worker: v2.8.4
Worker scheduling a ssh command under QEMU, the commands succeeds after 15 seconds but master shows still the command (and build) running. Stopping build does not work.

Master logs:
```
2020-11-06 11:46:11+0100 [-] ShellCommand.startCommand(cmd=<RemoteShellCommand '['ssh', '-o CheckHostIP=no', '-o', 'StrictHostKeyChecking=no', 'root@192.168.7.2', '/usr/lib/syscommon/test/test_syscommon']'>)
2020-11-06 11:46:11+0100 [-]   cmd.args = {'workdir': 'build', 'env': None, 'want_stdout': 1, 'want_stderr': 1, 'logfiles': {'qemu console': 'build/qemu-console.log'}, 'timeout': 1200, 'maxT
ime': None, 'sigtermTime': None, 'usePTY': None, 'logEnviron': True, 'initial_stdin': None}
2020-11-06 11:46:11+0100 [-] <RemoteShellCommand '['ssh', '-o CheckHostIP=no', '-o', 'StrictHostKeyChecking=no', 'root@192.168.7.2', '/usr/lib/syscommon/test/test_syscommon']'>: RemoteCommand.run [1898]
2020-11-06 11:46:11+0100 [-] command '['ssh', '-o CheckHostIP=no', '-o', 'StrictHostKeyChecking=no', 'root@192.168.7.2', '/usr/lib/syscommon/test/test_syscommon']' in dir 'build'
2020-11-06 11:46:11+0100 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f291c2f99e8>
2020-11-06 11:46:25+0100 [Broker,7,192.168.201.117] <RemoteShellCommand '['ssh', '-o CheckHostIP=no', '-o', 'StrictHostKeyChecking=no', 'root@192.168.7.2', '/usr/lib/syscommon/test/test_syscommon']'> rc=0

....

2020-11-06 12:13:51+0100 [_GenericHTTPChannelProtocol,119,192.168.3.100]  <Build yocto_gprpalm_eagle_vf50_devtool number:7 results:success>: stopping build: no reason 6
2020-11-06 12:13:51+0100 [_GenericHTTPChannelProtocol,119,192.168.3.100] RemoteCommand.interrupt <RemoteShellCommand '['ssh', '-o CheckHostIP=no', '-o', 'StrictHostKeyChecking=no', 'root@192.168.7.2', '/usr/lib/syscommon/test/test_syscommon']'> no reason
2020-11-06 12:13:51+0100 [_GenericHTTPChannelProtocol,119,192.168.3.100]  but this RemoteCommand is already inactive
```

Worker logs:
```
2020-11-06 11:46:11+0100 [Broker,client]  startCommand:shell [id 1898]
2020-11-06 11:46:11+0100 [Broker,client] LogFileWatcher created to watch /home/buildbot/worker/builddir_yocto_eagle_devtool/build/build/qemu-console.log
2020-11-06 11:46:11+0100 [Broker,client] RunProcess._startCommand
2020-11-06 11:46:11+0100 [Broker,client]  ssh '-o CheckHostIP=no' -o StrictHostKeyChecking=no root@192.168.
7.2 /usr/lib/syscommon/test/test_syscommon
2020-11-06 11:46:11+0100 [Broker,client]   in dir /home/buildbot/worker/builddir_yocto_eagle_devtool/build (timeout 1200 secs)
2020-11-06 11:46:11+0100 [Broker,client]   watching logfiles {'qemu console': 'build/qemu-console.log'}
2020-11-06 11:46:11+0100 [Broker,client]   argv: [b'ssh', b'-o CheckHostIP=no', b'-o', b'StrictHostKeyChecking=no', b'root@192.168.7.2', b'/usr/lib/syscommon/test/test_syscommon']
2020-11-06 11:46:11+0100 [Broker,client]  environment:
         '_': '/home/buildbot/sandbox/bin/buildbot-worker'}
2020-11-06 11:46:11+0100 [Broker,client]   using PTY: False
2020-11-06 11:46:26+0100 [-] command finished with signal None, exit code 0, elapsedTime: 14.796226
2020-11-06 11:46:26+0100 [-] WorkerForBuilder.commandComplete <buildbot_worker.commands.shell.WorkerShellCommand object at 0x7fc0dce1d1d0>
2020-11-06 11:49:05+0100 [-] sending app-level keepalive
2020-11-06 11:49:05+0100 [Broker,client] Master replied to keepalive, everything's fine
2020-11-06 11:59:05+0100 [-] sending app-level keepalive
2020-11-06 11:59:05+0100 [Broker,client] Master replied to keepalive, everything's fine
2020-11-06 12:09:05+0100 [-] sending app-level keepalive
2020-11-06 12:09:05+0100 [Broker,client] Master replied to keepalive, everything's fine
```

Issue is extremely annoying. The only solution for me is to restart the worker (also with killing QEMU process). It is always the same command which halts the Buildbot workflow. The command produces around 3000-4000 lines and should finish within 20 seconds. The QEMU process is started by worker before, not in this command. Command only executes ssh connection to the system running in QEMU.

**Comment by p12tic** [comment]
This may have been fixed by c3fc07a86646fb6799f7edadf654943443641957 which landed to 3.0.0.
