### ISSUE TITLE
Bitbucket Cloud web hook returns 500

### ISSUE THREAD

**Issue by tzaeru** [buildbot/buildbot#4873]
Started three weeks ago (missed it due to vacations), my guess is that Bitbucket changed something. Error log looks like this:

```
2019-07-02 14:33:40+0300 [_GenericHTTPChannelProtocol,13,18.234.32.226] adding changes from web hook
        Traceback (most recent call last):
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/buildbot/www/change_hook.py", line 106, in getAndSubmitChanges
            changes, src = yield self.getChanges(request)
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/buildbot/www/change_hook.py", line 106, in getAndSubmitChanges
            changes, src = yield self.getChanges(request)
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/buildbot/www/change_hook.py", line 167, in getChanges
            changes, src = yield handler.getChanges(request)
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/buildbot/www/hooks/bitbucketcloud.py", line 163, in getChanges
            return self.process(request)
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/buildbot/www/hooks/bitbucketcloud.py", line 54, in process
            return handler(payload)
          File "/home/buildbot/sandbox/lib/python3.5/site-packages/buildbot/www/hooks/bitbucketcloud.py", line 97, in handle_repo_push
            payload['actor']['username']),
        builtins.KeyError: 'username'
```

Last line reveals the culprit.

**Comment by p12tic** [comment]
I'm wondering if the Bitbucket API has changed.

**Comment by kravietz** [comment]
It did [Bitbucket Cloud REST APIs are changing to improve user privacy](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/) (12 April 2019)

**Comment by kravietz** [comment]
Here's a patch against [bitbucketcloud.py](https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/hooks/bitbucketcloud.py) that gave me a working Bitbucket hooks. Two changes:
* replace the `username` property with `nickname` (per the above privacy changes in API)
* per [Bitbucket documentation](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-entity_repositoryRepository) the `project` property in `repository` is not guaranteed to be always present which was also crashing my Buildbot
```
--- bitbucketcloud.py	2019-08-01 13:45:47.525672898 +0000
+++ ./lib/python3.6/site-packages/buildbot/www/hooks/bitbucketcloud.py	2019-08-01 13:02:29.471261055 +0000
@@ -70,7 +70,10 @@
 
     def handle_repo_push(self, payload):
         changes = []
+        if payload['repository'].get('project'):
         project = payload['repository']['project']['name']
+        else:
+            project = 'none'
         repo_url = payload['repository']['links']['self']['href']
         web_url = payload['repository']['links']['html']['href']
 
@@ -94,7 +97,7 @@
                 'revlink': '{}/commits/{}'.format(web_url, commit_hash),
                 'repository': repo_url,
                 'author': '{} <{}>'.format(payload['actor']['display_name'],
-                                           payload['actor']['username']),
+                                           payload['actor']['nickname']),
                 'comments': 'Bitbucket Cloud commit {}'.format(commit_hash),
                 'branch': branch,
                 'project': project,
@@ -139,6 +142,10 @@
     def handle_pullrequest(self, payload, refname, category):
         pr_number = int(payload['pullrequest']['id'])
         repo_url = payload['repository']['links']['self']['href']
+        if payload['repository'].get('project'):
+            project = payload['repository']['project']['name']
+        else:
+            project = 'none'
         change = {
             'revision': payload['pullrequest']['fromRef']['commit']['hash'],
             'revlink': payload['pullrequest']['link'],
@@ -147,7 +154,7 @@
                                        payload['actor']['username']),
             'comments': 'Bitbucket Cloud Pull Request #{}'.format(pr_number),
             'branch': refname,
-            'project': payload['repository']['project']['name'],
+            'project': project,
             'category': category,
             'properties': {'pullrequesturl': payload['pullrequest']['link']}
         }
```

**Comment by tardyp** [comment]
Hi,
Could you please submit a proper pull request?

Buildbot is 100% maintained by volunteers. 
We rely on the bitbucket community to update plugins like bitbucketcloud hook.

Thank you for your understanding.

**Comment by kravietz** [comment]
@tardyp Done https://github.com/buildbot/buildbot/pull/4934
