### ISSUE TITLE
GitHubPullrequestPoller error

### ISSUE THREAD

**Issue by rajdeepbharati** [buildbot/buildbot#4878]
```
2019-07-03 23:41:31+0530 [-] GitHubPullrequestPoller: polling GitHub repository rajdeepbharati/macports-ports, branches: ['master']
2019-07-03 23:41:31+0530 [-] while polling for changes
	Traceback (most recent call last):
	  File "/Users/rajdeep/goodbb/.venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/Users/rajdeep/goodbb/master/buildbot/changes/github.py", line 295, in poll
	    yield self._processChanges(result)
	  File "/Users/rajdeep/goodbb/.venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/Users/rajdeep/goodbb/.venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "/Users/rajdeep/goodbb/master/buildbot/changes/github.py", line 295, in poll
	    yield self._processChanges(result)
	  File "/Users/rajdeep/goodbb/.venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/Users/rajdeep/goodbb/master/buildbot/changes/github.py", line 218, in _processChanges
	    base_branch = pr['base']['ref']
	builtins.TypeError: string indices must be integers
```

**Comment by phillxnet** [comment]
I am also seeing this, slight line number changes but looks like the same thing:
venv and buildbot install via pip.
buildbot==2.3.1
```
2019-07-28 20:31:13+0100 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] while polling for changes
        Traceback (most recent call last):
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/buildbot/changes/github.py", line 272, in poll
            yield self._processChanges(result)
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/buildbot/changes/github.py", line 272, in poll
            yield self._processChanges(result)
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/buildbot/changes/github.py", line 200, in _processChanges
            base_branch = pr['base']['ref']
        builtins.TypeError: string indices must be integers
```
Anyone have any pointers on where to look.
@rajdeepbharati  did you make any progress with this one?

**Comment by phillxnet** [comment]
On a potentially related note I'm using treq via:
```
pip install treq
```

**Comment by phillxnet** [comment]
Tried installing txrequests as well, which I think is defaulted to in code, if also installed:
```
pip install txrequests
```
and no change:
```
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/buildbot/changes/github.py", line 200, in _processChanges
            base_branch = pr['base']['ref']
        builtins.TypeError: string indices must be integers

```
Any pointers on what I might be doing wrong here?

**Comment by rajdeepbharati** [comment]
@phillxnet Does it work on older versions of buildbot? (2.3.0, 2.2, 2.1, 2.0, 1.x)

**Comment by phillxnet** [comment]
@rajdeepbharati Thanks for the response. I've only tried the default pip installed (latest) version of 2.3.1 so far. I'll try when I next get time and report back with my findings, unless someone else beats me to it of course. Did you end up downgrading yourself? And with any success?

**Comment by rajdeepbharati** [comment]
No, I have only reproduced the issue on master and 2.3.1 (I will test it on lower versions and try to fix this)

**Comment by phillxnet** [comment]
@rajdeepbharati That would be much appreciated, thanks. I'm currently exploring a potential issue in docs re vaultToken retrieval from file suggested code and once I've sorted that and opened an appropriate issue with any findings I can work my way back to this issue so any progress would be great. I can't yet contribute on the code side but hope to in the future as I've seen some vault anomalies / assumptions from what little I've looked at that code.

**Comment by aliceinwire** [comment]
same for me.

**Comment by rajdeepbharati** [comment]
I seem to get this error even on 2.0.1

**Comment by rajdeepbharati** [comment]
I think I found the issue:
IMO it was due to invalid (or the token didn't have all required permissions) github api token (and this case isn't handled properly in buildbot).
See https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/github.py#L210
Here, when I log the value and type of `github_result` and `pr`, I get the following:
```
2019-12-06 20:31:11+0530 [-] ghres: {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'} <class 'dict'>
2019-12-06 20:31:11+0530 [-] prtype: message <class 'str'>
```
Ideally, the `type(pr)` should be dict, not string. Also, the `type(github_result)` should be list, not dict.

By using a different token, I am not getting this error anymore (and the expected data types are coming).
ping: @tardyp
