### ISSUE TITLE
How to use GitHubCommentPush in BuildBot?

### ISSUE THREAD

**Issue by EndrII** [buildbot/buildbot#4898]
I'm trying to add an automatic feedback from BuildBot to a github pull request using [GitHubCommentPush](http://docs.buildbot.net/current/manual/configuration/reporters.html#githubcommentpush)

But I constantly get an error:

``` log
2019-07-18 09: 04: 56 + 0000 [-] Timing out client: IPv4Address (type = 'TCP', host = '86 .57.157.184 ', port = 42090)
2019-07-18 09: 04: 56 + 0000 [-] Timing out client: IPv4Address (type = 'TCP', host = '86 .57.245.94 ', port = 42086)
2019-07-18 09: 04: 56 + 0000 [-] Timing out client: IPv4Address (type = 'TCP', host = '86 .57.157.184 ', port = 42092)
2019-07-18 09: 04: 56 + 0000 [-] while invoking <bound method HttpStatusPushBase.buildStarted of <buildbot.reporters.github.GitHubCommentPush object at 0x7f4ae512aa20 >>
        Traceback (most recent call last):
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send (result)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/reporters/http.py", line 80, in getMoreInfoAndSend
            yield self.send (build)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks (gen)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks (None, g, status)
        --- <exception caught here> ---
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/reporters/http.py", line 80, in getMoreInfoAndSend
            yield self.send (build)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send (result)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/reporters/github.py", line 177, in send
            content = yield response.content ()
        builtins.UnboundLocalError: local variable 'response' referenced before assignment

```

Apparently my GitHub token is not a valid .

I have no idea what kind of token the buildbot wants.

* I tried to create OAuth Apps (but did not publish it in the GitHub Marketplace) and use the Client Secret of the created application as a token.

* I tried to create GitHub Apps in the same way as above, I used Client Secret as a token.

* I tried to create a Personal access token.

None of these points helped me.

Can anyone explain how this should work?

Here is the code for how I connect the service.
``` python
        self.masterConf ['services'] = []
        self.masterConf ['secretsProviders'] = [
            secrets.SecretInAFile (dirname = "/path/to/buildBotSecret")
        ]

        gc = reporters.GitHubCommentPush (token = util.Secret("gitHub"),
                                         startDescription = 'Build started.',
                                         endDescription = 'Build done.')

        self.masterConf ['services']. append (gc)
```

**Comment by EndrII** [comment]
it is duplicate of [stackoverflow](https://stackoverflow.com/questions/57092357/how-to-use-githubcommentpush-in-buildbot)

**Comment by EndrII** [comment]
Noticed something else. perhaps this is due to the current problem
When use **util.Interpolate('SIGN_PATH="%(secret:SIGPATH)s"')**
Then at the output you get not the contents of the file but an invalid line **\<SIGPATH\>**

**Comment by EndrII** [comment]
@p12tic really need help

**Comment by tardyp** [comment]
I commented on the SO question, and provided a patch to better handle error in the Github Reporter

**Comment by EndrII** [comment]
@tardyp thanks 
when to wait for release with this fix?

**Comment by tardyp** [comment]
@EndrII we are in a phase of the project, where we can't release yet, because there are known regressions.
We don't have ETA.
So you should probable apply the patch locally

**Comment by EndrII** [comment]
Okay thanks. 
i close this issue because bug is fixed

**Comment by EndrII** [comment]
After update buildbot to 2.4.0 i have new error message 
```
2019-08-18 17:17:12+0000 [-] starting build <Build Tester number:None results:success> using worker <WorkerForBuilder builder='Tester' worker='Tester' state=AVAILABLE>
2019-08-18 17:17:12+0000 [-] <Build Tester number:None results:success>.startBuild
2019-08-18 17:17:16+0000 [-] acquireLocks(worker <Worker 'Tester'>, locks [])
2019-08-18 17:17:16+0000 [-] Failed to update "pending" for QuasarApp/Qt-Secret at 94406c23dee6153a88ab5ddaa46f6c8de6c6bf7f, context "", issue None. http n/a, n/a
        Traceback (most recent call last):
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/reporters/github.py", line 190, in send
            code=code, content=content))
        --- <exception caught here> ---
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/reporters/github.py", line 165, in send
            description=description
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/reporters/github.py", line 221, in createStatus
            '/'.join(['/repos', repo_user, repo_name, 'issues', issue, 'comments']),
        builtins.TypeError: sequence item 4: expected str instance, NoneType found

```

How to fix it ?

**Comment by tardyp** [comment]
as per code:
https://github.com/buildbot/buildbot/blob/e8b3696a23335236b69e5ebaa7d7976c5d994f2a/master/buildbot/reporters/github.py#L132

branch should be in the form "refs/pull/([0-9]*)/merge, or the reporter will not work.

I think it should be good to fix the code to check for null issue first.

**Comment by EndrII** [comment]
okey, url of my pr is _https://github.com/QuasarApp/Qt-Secret/pull/40_ how to add _merge_
so, what is /merge in  _refs/pull/([0-9]*)/merge_ ?
it is a name of pull request or what?

**Comment by p12tic** [comment]
In your case the branch name will be `refs/pull/40/merge`.

**Comment by EndrII** [comment]
ok, i renamed my pr into merge, but it is still not working.
