### ISSUE TITLE
gitpoller is crashed

### ISSUE THREAD

**Issue by EndrII** [buildbot/buildbot#4912]
``` log 
2019-07-23 11:19:08+0000 [-] trying to poll branch refs/heads/master of git@github.com:QuasarApp/Qt-Secret.git
        Traceback (most recent call last):
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
            _inlineCallbacks(r, g, status)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
        --- <exception caught here> ---
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/changes/gitpoller.py", line 226, in poll
            yield self._process_changes(revs[branch], branch)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/changes/gitpoller.py", line 323, in _process_changes
            results = yield self._dovccmd('log', revListArgs, path=self.workdir)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/changes/gitpoller.py", line 404, in _dovccmd
            stdout = yield self._dovccmdImpl(command, args, path, None)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/andrei/bot/sandbox/lib/python3.6/site-packages/buildbot/changes/gitpoller.py", line 435, in _dovccmdImpl
            full_args, path, self.repourl, code, stderr))
        buildbot.changes.gitpoller.GitError: command ['log', '--format=%H', 'c95ef0d02693d2f241407a8e212de44505d7b2d2', '^06c7ebeae91f0d4253f50d27084ed6254cfc4375', '^183278a5caa2d18d1acb0acfb5747b77c5f02427', $


2019-07-23 11:19:11+0000 [-] gitpoller: processing changes from "git@github.com:QuasarApp/Hanoi-Towers.git"
2019-07-23 11:19:12+0000 [-] gitpoller: processing changes from "https://github.com/usermeme/chat-vironit.git"
``` 

**How to fix it error ?**

**Comment by rajdeepbharati** [comment]
@EndrII Are you using multiple gitpollers?

**Comment by EndrII** [comment]
yes 
```
        self.masterConf['change_source'] = [
            changes.GitPoller(
                repourl = 'git@github.com:QuasarApp/Snake.git',
                project = 'Snake',
                branches = True, # получаем изменения со всех веток
                pollInterval = 60
            ),
            changes.GitPoller(
                repourl = 'git@github.com:QuasarApp/Console-QtDeployer.git',
                project = 'CQtDeployer',
                branches = True, # получаем изменения со всех веток
                pollInterval = 61
            ),
            changes.GitPoller(
                repourl = 'git@github.com:QuasarApp/Qt-Secret.git',
                project = 'Qt-Secret',
                branches = True, # получаем изменения со всех веток
                pollInterval = 62
            ),
            changes.GitPoller(
                repourl = 'git@github.com:QuasarApp/Hanoi-Towers.git',
                project = 'Hanoi-Towers',
                branches = True, # получаем изменения со всех веток
                pollInterval = 63
            ),
            changes.GitPoller(
                repourl = 'https://github.com/usermeme/chat-vironit.git',
                project = 'Chat',
                branch = 'master',
                pollInterval = 64
            )
        ]
```
but before everything worked well, and even now it works but not at all repasitories

**Comment by rajdeepbharati** [comment]
I'm not sure about the problem here but you could also use multiple codebases: http://docs.buildbot.net/current/manual/concepts.html#multiple-codebase-builds

**Comment by EndrII** [comment]
okay, i check it later

**Comment by EndrII** [comment]
@rajdeepbharati  unfortunately it does not suit me multiple codebases, I need to fix the work gitpuller.

**Comment by EndrII** [comment]
This bug is dublicate of #4211

**Comment by EndrII** [comment]
### Temp solution 
Need to run git with the flag --ignore-missing

1. create wraper script for run gin gitBin.sh
2. set permision for exucutable of gitBin.sh  (chmod +x  gitBin.sh) or (chmod 777  gitBin.sh) 
3. set the path to gitBin.sh  in gitbin for gitPuller.

```python
changes.GitPoller(
    repourl = 'git@github.com:QuasarApp/Qt-Secret.git',
    project = 'qmake-Qt-Secret',
    gitbin = os.path.dirname(os.path.realpath(__file__)) + "/git/gitBin.sh", # path to gitBin.sh 
    branches = True,
    pollInterval = 62
),
```

### gitBin.sh
```sh
#!/bin/bash

[ "${1}" = "log" ] && { shift && git log --ignore-missing "${@}"; } || git "${@}"

```
