### ISSUE TITLE
[buildbot-worker] git clean may fail on windows with 'warning: failed to remove ***: Directory not empty'

### ISSUE THREAD

**Issue by ciarancourtney** [buildbot/buildbot#4916]
Similar to gitlab-runner [issue 3185](https://gitlab.com/gitlab-org/gitlab-runner/issues/3185)

I occasionally see this on a Windows 7 worker:

````
Removing venv/Include
Removing venv/pyvenv.cfg
Removing venv/Scripts
warning: failed to remove venv/Lib/site-packages/botocore/data/elastictranscoder: Directory not empty
warning: failed to remove venv/Lib/site-packages/botocore/data/pinpoint: Directory not empty
warning: failed to remove venv/Lib/site-packages/buildbot/db/migrate/versions: Directory not empty
warning: failed to remove venv/Lib/site-packages/celery/bin: Directory not empty
warning: failed to remove venv/Lib/site-packages/celery/contrib: Directory not empty
warning: failed to remove venv/Lib/site-packages/django/views/generic: Directory not empty
warning: failed to remove venv/Lib/site-packages/pip/_vendor: Directory not empty
warning: failed to remove venv/Lib/site-packages/pytz/zoneinfo: Directory not empty
warning: failed to remove venv/Lib/site-packages/sqlalchemy/dialects/sqlite: Directory not empty
warning: failed to remove venv/Lib/site-packages/twisted/conch/openssh_compat: Directory not empty
warning: failed to remove venv/Lib/site-packages/werkzeug: Directory not empty
warning: failed to remove venv/Lib/site-packages/win32/Demos/win32wnet: Directory not empty
warning: failed to remove venv/Lib/site-packages/win32com/makegw: Directory not empty
warning: failed to remove venv/Lib/site-packages/_pytest/assertion: Directory not empty
program finished with exit code 1
elapsedTime=58.609303
exception from rmdirRecursive
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\twisted\_threads\_threadworker.py", line 46, in work
    task()
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\twisted\_threads\_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\buildbot_worker\commands\utils.py", line 98, in rmdirRecursive
    rmdirRecursive(full_name)
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\buildbot_worker\commands\utils.py", line 98, in rmdirRecursive
    rmdirRecursive(full_name)
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\buildbot_worker\commands\utils.py", line 98, in rmdirRecursive
    rmdirRecursive(full_name)
  File "c:\users\default\buildbot-worker\venv\lib\site-packages\buildbot_worker\commands\utils.py", line 103, in rmdirRecursive
    os.rmdir(dir)
builtins.OSError: [WinError 145] The directory is not empty: 'C:\\Users\\default\\buildbot-worker\\app_proj\\build\\services\\'
program finished with exit code -1
````

My git step:

````python
factory.addStep(Git(
        repourl=repourl,
        mode='full',
        method='fresh',
        progress=False,
        retry=(30, 3),
        retryFetch=True,
        clobberOnFailure=True,
        timeout=1800,
    ))
````

Worker version:

    worker version: 2019.05.17
    Twisted version: 18.9.0

I don't have any process with open files in the working directory (that I know of) or any AV running.

As with the gitlab-runner issue, this seems like a windows 7 issue (not just git as rmdirRecursive fails too), if they come up with a workaround we can probably follow suit.

Related https://github.com/buildbot/buildbot/pull/540 (incl old trac issue in final comment)

**Comment by ciarancourtney** [comment]
Potential workaround https://stackoverflow.com/questions/22948189/batch-getting-the-directory-is-not-empty-on-rmdir-command
