### ISSUE TITLE
DirectoryUpload hangs if directory does not exist.

### ISSUE THREAD

**Issue by pepsiman** [buildbot/buildbot#4918]
I've recently upgraded from buildbot 0.8.8 to buildbot 2.3.1.

In 0.8.8, if a DirectoryUpload step tries to upload a directory that does not exist, the step is marked as exception and the build completes.

In 2.3.1, if a DirectoryUpload step tries to upload a directory that does not exist, the step does not finish and cannot be cancelled.

An exception is logged in the worker's log:
```
2019-07-24 17:09:26+0100 [Broker,client]  startCommand:uploadDirectory [id 5705]
2019-07-24 17:09:27+0100 [Broker,client] WorkerForBuilder.commandFailed <buildbot_worker.commands.transfer.WorkerDirectoryUploadCommand object at 0x7faf129f24a8>
2019-07-24 17:09:27+0100 [Broker,client] Unhandled Error
        Traceback (most recent call last):
          File "lib/python3.4/site-packages/twisted/spread/pb.py", line 1054, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "lib/python3.4/site-packages/twisted/spread/flavors.py", line 125, in remoteMessageReceived
            state = method(*args, **kw)
          File "lib/python3.4/site-packages/buildbot_worker/base.py", line 153, in remote_startCommand
            d = self.command.doStart()
          File "lib/python3.4/site-packages/buildbot_worker/commands/base.py", line 160, in doStart
            d = defer.maybeDeferred(self.start)
        --- <exception caught here> ---
          File "lib/python3.4/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
            result = f(*args, **kw)
          File "lib/python3.4/site-packages/buildbot_worker/commands/transfer.py", line 227, in start
            archive.add(self.path, '')
          File "lib64/python3.4/tarfile.py", line 1913, in add
            tarinfo = self.gettarinfo(name, arcname)
          File "lib64/python3.4/tarfile.py", line 1785, in gettarinfo
            statres = os.lstat(name)
        builtins.FileNotFoundError: [Errno 2] No such file or directory: '/export/buildbot/worker/foo/results'
```

Nothing is logged in the master's log.

Expected behaviour:
The step is marked as failed.

**Comment by 99rgosse** [comment]
I've got the same behavior with RemoteUnpack, when the directory exists and no filename is provided:

> 2020-04-15 16:37:09+0200 [Broker,1,10.64.65.145] Unhandled Error                                                         
>         Traceback (most recent call last):                                                                               
>           File "/usr/local/lib/python3.7/dist-packages/twisted/spread/banana.py", line 173, in gotItem                   
>             self.callExpressionReceived(item)                                                                            
>           File "/usr/local/lib/python3.7/dist-packages/twisted/spread/banana.py", line 136, in callExpressionReceived    
>             self.expressionReceived(obj)                                                                                 
>           File "/usr/local/lib/python3.7/dist-packages/twisted/spread/pb.py", line 621, in expressionReceived            
>             method(*sexp[1:])                                                                                            
>           File "/usr/local/lib/python3.7/dist-packages/twisted/spread/pb.py", line 1025, in proto_message                
>             self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)       
>         --- <exception caught here> ---                                                                                  
>           File "/usr/local/lib/python3.7/dist-packages/twisted/spread/pb.py", line 1054, in _recvMessage                 
>             netResult = object.remoteMessageReceived(self, message, netArgs, netKw)                                      
>           File "/usr/local/lib/python3.7/dist-packages/twisted/spread/flavors.py", line 125, in remoteMessageReceived    
>             state = method(*args, **kw)                                                                                  
>           File "/usr/local/lib/python3.7/dist-packages/buildbot/process/remotetransfer.py", line 131, in remote_unpack   
>             archive.extractall(path=self.destroot)                                                                       
>           File "/usr/lib/python3.7/tarfile.py", line 2002, in extractall                                                 
>             numeric_owner=numeric_owner)                                                                                 
>           File "/usr/lib/python3.7/tarfile.py", line 2044, in extract                                                    
>             numeric_owner=numeric_owner)                                                                                 
>           File "/usr/lib/python3.7/tarfile.py", line 2114, in _extract_member                                            
>             self.makefile(tarinfo, targetpath)                                                                           
>           File "/usr/lib/python3.7/tarfile.py", line 2155, in makefile                                                   
>             with bltn_open(targetpath, "wb") as target:                                                                  
>         builtins.IsADirectoryError: [Errno 21] Is a directory: 'public_html/artifacts/docs/developers/html/_static'

I would like to help with this, but I'm not sure how : 
Could I just add a simple workaround into remotetransfer.py and transfer.py with an 
"assert" and some os.path.exists(path) and if os.path.isdir(path) and raise an error or is this not so easy ?
