### ISSUE TITLE
buildrequests.NotClaimedError on tag_push in multiple repositories

### ISSUE THREAD

**Issue by cko-bz** [buildbot/buildbot#5055]
I have schedulers that handle tag_pushes on two of our repositories to package them.

Three for each repository to package for different systems (Linux, Win32 and Win64).
The repos are part of the same codebase, i.e. one depends on the other.
I tag both of them at the same time when we have a new version to trigger the packaging, that results in multiple `buildrequests.NotClaimedError` exceptions on the master (see log below).

Sometimes the Schedulers for one repo are triggered and their builds start as excepected, sometimes none of them start. I never saw a case where all 6 of them worked.

Any Ideas what I am doing wrong?

```
19-10-22` 07:13:01+0000 [_GenericHTTPChannelProtocol,4389,172.18.0.3] New revision: 46f12bc9
2019-10-22 07:13:01+0000 [_GenericHTTPChannelProtocol,4389,172.18.0.3] Received 1 changes from tag_push gitlab event
2019-10-22 07:13:01+0000 [-] added change with revision 46f12bc905468dd86d250ea8c5d249591d4ccb85 to database
2019-10-22 07:13:01+0000 [-] injected change 511
2019-10-22 07:13:03+0000 [_GenericHTTPChannelProtocol,4390,172.18.0.3] New revision: ec49e44b
2019-10-22 07:13:03+0000 [_GenericHTTPChannelProtocol,4390,172.18.0.3] Received 1 changes from tag_push gitlab event
2019-10-22 07:13:03+0000 [-] added change with revision ec49e44bd4b84097c1b0723282129989455bd5d8 to database
2019-10-22 07:13:03+0000 [-] injected change 512
2019-10-22 07:13:05+0000 [_GenericHTTPChannelProtocol,4406,172.18.0.3] New revision: 2b2741da
2019-10-22 07:13:05+0000 [_GenericHTTPChannelProtocol,4406,172.18.0.3] Received 1 changes from tag_push gitlab event
2019-10-22 07:13:05+0000 [-] added change with revision 2b2741da37c052b362fdb7aae04434276eadd2b5 to database
2019-10-22 07:13:05+0000 [-] injected change 513
2019-10-22 07:13:06+0000 [_GenericHTTPChannelProtocol,4436,172.18.0.3] New revision: cc3b4b02
2019-10-22 07:13:06+0000 [_GenericHTTPChannelProtocol,4436,172.18.0.3] Received 1 changes from tag_push gitlab event
2019-10-22 07:13:06+0000 [-] added change with revision cc3b4b02768682a175995225fee07ca25634ecd5 to database
2019-10-22 07:13:06+0000 [-] injected change 514
2019-10-22 07:13:31+0000 [-] tried to complete 6 buildrequests, but only completed 3
2019-10-22 07:13:31+0000 [-] Got fatal Exception on DB
        Traceback (most recent call last):
          File "/home/buildbot/buildbot/bb_master_sandbox/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/home/buildbot/buildbot/bb_master_sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/buildbot/buildbot/bb_master_sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/home/buildbot/buildbot/bb_master_sandbox/lib/python3.6/site-packages/buildbot/db/pool.py", line 209, in __thd
            log.err(e, 'Got fatal Exception on DB')
        --- <exception caught here> ---
          File "/home/buildbot/buildbot/bb_master_sandbox/lib/python3.6/site-packages/buildbot/db/pool.py", line 182, in __thd
            rv = callable(arg, *args, **kwargs)
          File "/home/buildbot/buildbot/bb_master_sandbox/lib/python3.6/site-packages/buildbot/db/buildrequests.py", line 222, in thd
            raise NotClaimedError
        buildbot.db.buildrequests.NotClaimedError: 
```

Versions:
```
Python version: 3.6.8
Buildbot version: 2.4.1
Twisted version: 19.7.0
```

**Comment by cko-bz** [comment]
Apologies in advance for the code, I'm still in the process of understanding BuildBot properly.
The setup for the scheduler looks roughly like this:
```
all_repositories = {
    r'git@repo1': 'library',
    r'git@repo2': 'editor',
    r'git@repo3': '3rdparty',
}

def codebaseGenerator(chdict):
    return all_repositories[chdict['repository']]

codebases_to_package = ['library', 'editor']
systems_to_build = ['linux', 'win64', 'win32']

for project in codebases_to_package:
  tagBuilderNames = []
  for system in systems_to_build:
    tagBuilderNames.append(project + '-' + system + '-' + 'tagged')

    c['schedulers'].append(
    schedulers.SingleBranchScheduler(
      name=project + '-' + system + "-tag-scheduler",
      change_filter=util.ChangeFilter(codebase=project, category="tag_push"),
      treeStableTimer=30,
      builderNames=tagBuilderNames,
      codebases = ['library', 'editor', '3rdparty'],
      properties = {'project': project, 'build_type': 'tagged', 'branch': util.Interpolate('%(src:' + project + ':branch)s') }
    ))

    if 'linux' in system:
          worker = ['linux-worker']
    else:
          worker = ['windows-worker-1', 'windows-worker-2']
    c['builders'].append(
            util.BuilderConfig(
                name = project + '-' + system + '-' + 'tagged',
                workernames = worker,
                factory=createDefaultFactory(project_to_repo_mapping[project]),
                collapseRequests=True,
                tags=[project, 'tagged', system],
                properties={'system': system }
            ))
```
So that generates a `tagged` scheduler for each OS and each repo to package.
`library-linux-tag-scheduler`, `editor-linux-tag-scheduler`, `library-win32-tag-scheduler` and so on. Six in total.
I have three workers, one linux and two windows.
The codebase is configured to use the pushed tag on every codebase. 

Hope that helps

**Comment by cko-bz** [comment]
I figured it out myself. 
For some reason I created a scheduler for each target system and attached all builders to each Scheduler, hence it resulted in multiple build requests for each builder with the same settings.

I changed it so that each project has only has one scheduler that triggers the builders for all systems, i.e. how it should have been in the first place..

Now it works like a charm.
