### ISSUE TITLE
www crash with filenot found error

### ISSUE THREAD

**Issue by hurricanechristian** [buildbot/buildbot#5107]
When running we frequently get the gui fallover with the following stack. On buildbot 2.2 it would mean a restart, on 2.5 sending a kill -HUP seems to bring the gui back. 

```
2019-12-13 22:01:23+0000 [buildbot.www.service.BuildbotSite] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib64/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/tcp.py", line 1434, in doRead
	    skt, protocol, addr, self, s, self.reactor)
	  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/tcp.py", line 828, in __init__
	    self.startReading()
	  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/abstract.py", line 435, in startReading
	    self.reactor.addReader(self)
	  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/epollreactor.py", line 110, in addReader
	    EPOLLIN, EPOLLOUT)
	  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/epollreactor.py", line 94, in _add
	    self._poller.modify(fd, flags)
	builtins.FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by hurricanechristian** [comment]
Some more information about this - at the time of the crash, there is an large subversion task running on one of the builders - the local svn checkout is corrupted, and buildbot decides to clean it but spewing out lots of xml output. This causes another builder, which makes an api call via a script to fall over - and then eventually the www front end falls over. Fixing the checkout on the builder outside of buildbot - and then restarting seems to make the above crash go away.

**Comment by glyph** [comment]
This is the same traceback as #8306 and given that the www frontend is implicated, possibly the same bug as well.

**Comment by oliver-joos** [comment]
@glyph just helped greatly to analyze this bug, see https://github.com/twisted/twisted/issues/11625#issuecomment-5376237380 and later

Apart from the FileNotFoundError in the description of this issue, I also see an AttributeError in `twistd.log` which might be related:

```
2026-09-01 15:48:35+0200 [-] while handling API request
        Traceback (most recent call last):
          File "/home/buildbot/bots/KNX_Vision-env/lib/python3.12/site-packages/buildbot/www/rest.py", line 165, in handleErrors
            yield
          File "/home/buildbot/bots/KNX_Vision-env/lib/python3.12/site-packages/buildbot/www/rest.py", line 419, in renderRest
            yield threads.deferToThread(V2RootResource._write_json_data, request, encoder, data)
          File "/home/buildbot/bots/KNX_Vision-env/lib/python3.12/site-packages/twisted/python/threadpool.py", line 269, in inContext
            result = inContext.theWork()  # type: ignore[attr-defined]
          File "/home/buildbot/bots/KNX_Vision-env/lib/python3.12/site-packages/twisted/python/threadpool.py", line 285, in <lambda>
            inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
          File "/home/buildbot/bots/KNX_Vision-env/lib/python3.12/site-packages/twisted/python/context.py", line 117, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/buildbot/bots/KNX_Vision-env/lib/python3.12/site-packages/twisted/python/context.py", line 82, in callWithContext
            return func(*args, **kw)
          File "/home/buildbot/bots/KNX_Vision-env/lib/python3.12/site-packages/buildbot/www/rest.py", line 513, in _write_json_data
            request.write(unicode2bytes(chunk))
          File "/home/buildbot/bots/KNX_Vision-env/lib/python3.12/site-packages/twisted/web/server.py", line 267, in write
            _HTTPRequest.write(self, data)
          File "/home/buildbot/bots/KNX_Vision-env/lib/python3.12/site-packages/twisted/web/http.py", line 1327, in write
            self.channel.writeSequence(toChunk(data))
        builtins.AttributeError: 'NoneType' object has no attribute 'writeSequence'

```

I tried to drill further down this tracback. I inserted an `if request.channel.writeSequence is None:`. But this does not help to foresee/prevent the AttributeError:

```
    @staticmethod
    def _write_json_data(
        request: server.Request,
        encoder: json.encoder.JSONEncoder,
        data: Any,
    ) -> None:
        content_length = 0
        for chunk in encoder.iterencode(data):
            if _is_request_finished(request):
                return
            content_length += len(unicode2bytes(chunk))
        request.setHeader(b"content-length", unicode2bytes(str(content_length)))

        if request.method != b"HEAD":
            for chunk in encoder.iterencode(data):
                if _is_request_finished(request):
                    return

                # ----- INSERTED ------------------------------------------
                if request.channel.writeSequence is None:
                    log.err(_why='request.channel.writeSequence is None')
                    request.finish()
                    return
                # ----- INSERTED ------------------------------------------

                request.write(unicode2bytes(chunk))
```

**Comment by glyph** [comment]
Trying to figure out where the problematic code is, I found this change, which appears to fix it: 

https://github.com/buildbot/buildbot/commit/0a6cd7fca0438cbb5d672bf881e019adced6902a

**Comment by glyph** [comment]
This is a duplicate of #9065 and was probably fixed by #9143 .

**Comment by oliver-joos** [comment]
**Looks GREAT!** After updating `rest.py`, my manual test (pressing page refresh button in Chromium every 200-500ms) does not trigger `FileNotFoundError` anymore! This is without patching Twisted module.

I will update our 6 Buildbot instances ASAP, and I’ll get back if the issue occurs again.

**Comment by oliver-joos** [comment]
As stated in https://github.com/twisted/twisted/issues/11625#issuecomment-5712513814 the commit https://github.com/buildbot/buildbot/commit/0a6cd7fca0438cbb5d672bf881e019adced6902a seems to fix this issue!

Thanks to @tdesveaux for the commit! I hope it gets merged anytime soon.
