### ISSUE TITLE
test: buildbot.test.unit.test_db_logs.TestRealDB.test_deleteOldLogChunks_basic is flaky

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#5147]
E.g. https://buildbot.buildbot.net/#/builders/58/builds/195

```===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/buildbot/buildbot-job/build/master/buildbot/db/pool.py", line 190, in __thd
    rv = callable(arg, *args, **kwargs)
  File "/buildbot/buildbot-job/build/master/buildbot/db/logs.py", line 215, in thdappendLog
    return self.thdAppendLog(conn, logid, content)
  File "/buildbot/buildbot-job/build/master/buildbot/db/logs.py", line 201, in thdAppendLog
    res = conn.execute(q)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    ret = self._execute_context(
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1252, in _execute_context
    self._handle_dbapi_exception(
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    self.dialect.do_execute(
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: logs
[SQL: SELECT logs.num_lines 
FROM logs 
WHERE logs.id = ?]
[parameters: (67,)]
(Background on this error at: http://sqlalche.me/e/e3q8)
buildbot.test.unit.test_db_logs.TestRealDB.test_deleteOldLogChunks_basic```

**Comment by rjarry** [comment]
Could this be fixed by commit 81d693a8e973b51552cd23bfa695c4b2b0a30f2c ?

**Comment by GretaCB** [comment]
Seeing similar error earlier today:
```
6618 2020-08-27 06:06:08-0500 [Broker,43,10.1.130.10] Got fatal OperationalError on DB
 6619     Traceback (most recent call last):
 6620       File "trunk/.venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
 6621         inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
 6622       File "trunk/.venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
 6623         return self.currentContext().callWithContext(ctx, func, *args, **kw)
 6624       File "trunk/.venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
 6625         return func(*args,**kw)
 6626       File "trunk/.venv/lib/python3.5/site-packages/buildbot/db/pool.py", line 187, in __thd
 6627         log.err(e, 'Got fatal OperationalError on DB')
 6628     --- <exception caught here> ---
 6629       File "trunk/.venv/lib/python3.5/site-packages/buildbot/db/pool.py", line 182, in __thd
 6630         rv = callable(arg, *args, **kwargs)
 6631       File "trunk/.venv/lib/python3.5/site-packages/buildbot/db/logs.py", line 216, in thdappendLog
 6632         return self.thdAppendLog(conn, logid, content)
 6633       File "trunk/.venv/lib/python3.5/site-packages/buildbot/db/logs.py", line 202, in thdAppendLog
 6634         res = conn.execute(q)
 6635       File "trunk/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 982, in execute
 6636         return meth(self, multiparams, params)
 6637       File "trunk/.venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
 6638         return connection._execute_clauseelement(self, multiparams, params)
 6639       File "trunk/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
 6640         distilled_params,
 6641       File "trunk/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
 6642         e, statement, parameters, cursor, context
 6643       File "trunk/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
 6644         util.raise_from_cause(sqlalchemy_exception, exc_info)
 6645       File "trunk/.venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
 6646         reraise(type(exception), exception, tb=exc_tb, cause=cause)
 6647       File "trunk/.venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
 6648         raise value.with_traceback(tb)
 6649       File "trunk/.venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
 6650         cursor, statement, parameters, context
 6651       File "trunk/.venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
 6652         cursor.execute(statement, parameters)
 6653     sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
 6654     server closed the connection unexpectedly
 6655         This probably means the server terminated abnormally
 6656         before or while processing the request.
 6657 
 6658     [SQL: SELECT logs.num_lines
 6659     FROM logs
 6660     WHERE logs.id = %(id_1)s]
 6661     [parameters: {'id_1': 13068915}]
 6662     (Background on this error at: http://sqlalche.me/e/e3q8)
 6663 
 6664 2020-08-27 06:06:08-0500 [-] Unhandled error in Deferred:
 6665 2020-08-27 06:06:08-0500 [-] Unhandled Error
```
Using following versions:
```
Buildbot version: 2.4.1
Twisted version: 20.3.0
```

**Comment by tardyp** [comment]
hi @GretaCB it looks like there was a reboot of your postgres server.
relevent lines are:

```
 6653     sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
 6654     server closed the connection unexpectedly
 6655         This probably means the server terminated abnormally
 6656         before or while processing the request.
```
(unrelated to this issue)

**Comment by p12tic** [comment]
Looks like this test was never disabled and we didn't see similar issues again.
