### ISSUE TITLE
buildbot-worker doesn't support ipv6 address for master connection

### ISSUE THREAD

**Issue by jocelynj** [buildbot/buildbot#5155]
I'm trying the following command line:
```shell
/usr/bin/buildbot-worker create-worker . "[2001\:\:324]:9989" test toto
```
But it gives the following error:
```
Traceback (most recent call last):
  File "/usr/bin/buildbot-worker", line 11, in <module>
    load_entry_point('buildbot-worker==2.0.1.post2', 'console_scripts', 'buildbot-worker')()
  File "/usr/lib/python3/dist-packages/buildbot_worker/scripts/runner.py", line 238, in run
    config.parseOptions()
  File "/usr/lib/python3/dist-packages/twisted/python/usage.py", line 267, in parseOptions
    self.subOptions.parseOptions(rest)
  File "/usr/lib/python3/dist-packages/twisted/python/usage.py", line 273, in parseOptions
    self.parseArgs(*args)
  File "/usr/lib/python3/dist-packages/buildbot_worker/scripts/runner.py", line 183, in parseArgs
    self['host'], self['port'] = self.validateMasterArgument(master)
  File "/usr/lib/python3/dist-packages/buildbot_worker/scripts/runner.py", line 161, in validateMasterArgument
    master, port = master_arg.split(":")
ValueError: too many values to unpack (expected 2)
```

Is Ipv6 address supposed to be supported?

**Comment by p12tic** [comment]
I think the fact that this does not work is a bug either way :) Thanks for the issue.

**Comment by jocelynj** [comment]
In addition, I've found that using a DNS entry with only an ipv6 address prevent buildbot to connect to master. twist.log contains the following message:
```
2020-01-13 21:03:47+0000 [-] Connecting example.org:9989
2020-01-13 21:03:47+0000 [-] Connection example.org:9989 failed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: example.org.
```
It worked after modifying buildbot.tac to use a ipv6 address.
