### ISSUE TITLE
reporters.GitHubCommentPush is not working

### ISSUE THREAD

**Issue by vvscloud** [buildbot/buildbot#5157]
reporters.GitHubCommentPush is failing with the message: (we are using an enterprise github server).

Failed to update "failure" for <Project> at <commit-sha-id>, context "", issue None.
	Traceback (most recent call last):
	Failure: exceptions.TypeError: sequence item 4: expected string, NoneType found

I am using token to authenticate with github.
Please help

**Comment by rajdeepbharati** [comment]
I think issue should be of type string, while here it is getting None. I tried to reproduce this issue, and got a similar message:
```
Failed to update "pending" for rajdeepbharati/macports-ports at a2c289a350856932a31c8bc703f6f23685b66088, context "", issue None. http n/a, n/a
	Traceback (most recent call last):
	  File "/Users/rajdeep/buildbot/.venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/Users/rajdeep/buildbot/.venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	  File "/Users/rajdeep/buildbot/.venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/Users/rajdeep/buildbot/master/buildbot/reporters/github.py", line 190, in send
	    code=code, content=content))
	--- <exception caught here> ---
	  File "/Users/rajdeep/buildbot/master/buildbot/reporters/github.py", line 165, in send
	    description=description
	  File "/Users/rajdeep/buildbot/master/buildbot/reporters/github.py", line 221, in createStatus
	    '/'.join(['/repos', repo_user, repo_name, 'issues', issue, 'comments']),
	builtins.TypeError: sequence item 4: expected str instance, NoneType found
```
