### ISSUE TITLE
prepareSourcestampListForTrigger fails when sourcestamp contains a patch_body

### ISSUE THREAD

**Issue by ehohenstein-imvu** [buildbot/buildbot#5165]
Our Buildbot configuration has a builder that will trigger another builder but this fails when we use the Buildbot try command to submit a build with a patch. The patch file is binary but the `prepareSourcestampListForTrigger()` function in `master/buildbot/steps/trigger.py` calls `asDict()` on the buildrequest instance and that fails an assertion that all of the fields in the buildrequest have values that are of type string, int, or None. The assertion fails because the patch_body field is binary (as I think it probably should be).

Here is a stack trace in case that helps:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/cit/.local/lib/python3.6/site-packages/buildbot/process/buildstep.py", line 567, in startStep
    self.results = yield self.run()
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/cit/.local/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 257, in run
    ss_for_trigger = self.prepareSourcestampListForTrigger()
  File "/home/cit/.local/lib/python3.6/site-packages/buildbot/steps/trigger.py", line 167, in prepareSourcestampListForTrigger
    ss_for_trigger[ss.codebase] = ss.asDict()
  File "/home/cit/.local/lib/python3.6/site-packages/buildbot/process/buildrequest.py", line 137, in asDict
    ), result
builtins.AssertionError: {'branch': None, 'revision': '8a3fad6b5f844704f678af71d10fdc822ff11641', 'repository': 'ssh://some-private-git-host/infra/bb-test.git', 'project': '', 'codebase': '', 'patch_level': 1, 'patch_body': b':100755 100755 1465b4e... 0000000... M\ttest\n\ndiff --git a/test b/test\nindex 1465b4e..c8548bb 100755\n--- a/test\n+++ b/test\n@@ -4,5 +4,5 @@ echo "This is a fake test to be run by a test buildbot"\n \n echo "Still not actually running any tests"\n \n-echo "NO TESTS PASSED!!!"\n+echo "NO TESTS PASSED, BUT ALL TESTS PASSED!!!"\n \n', 'patch_subdir': '', 'patch_author': 'ehohenstein', 'patch_comment': 'ehohenstein'}
```

Also, here is a patch (based on v2.6.0) with the fix that I am suggesting, though I'm not familiar enough with Buildbot code to know if this is really the right fix for this problem:

```
diff --git a/master/buildbot/process/buildrequest.py b/master/buildbot/process/buildrequest.py
index be37254..45201e0 100644
--- a/master/buildbot/process/buildrequest.py
+++ b/master/buildbot/process/buildrequest.py
@@ -132,7 +132,7 @@ class TempSourceStamp:
             result['patch_%s' % attr] = patch.get(attr)

         assert all(
-            isinstance(val, (str, int, type(None)))
+            isinstance(val, (str, int, type(None), bytes))
             for attr, val in result.items()
         ), result
         return result
```

**Comment by p12tic** [comment]
Thanks for the bug report, indeed it looks like the behavior should be as you propose. I need to dig a little bit to see if there are any gotchas.

**Comment by ehohenstein-imvu** [comment]
For what it's worth, I've tested this fix and found it to work as expected with our buildbot configuration, though what I actually tested was an *equivalent* change using python3 and buildbot v1.2.0.

**Comment by aj062** [comment]
This should be fixed by https://github.com/buildbot/buildbot/pull/5827
