### ISSUE TITLE
Gerrit Change Event Monitor: assertion error: codebase cannot be None

### ISSUE THREAD

**Issue by 0x8000-0000** [buildbot/buildbot#5190]
I am getting this stacktrace in the log, with Buildbot 2.6.0 . I do not see this problem with Buildbot 2.5.1 .

2020-02-05 09:11:59-0500 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/changes/gerritchangesource.py", line 180, in addChange
            self.master.db.sourcestamps.findOrCreateId(**stampdict))
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/changes/gerritchangesource.py", line 343, in outReceived
            yield self.change_source.lineReceived(line)
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/changes/gerritchangesource.py", line 253, in addChangeFromEvent
            'properties': properties})
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/changes/gerritchangesource.py", line 180, in addChange
            self.master.db.sourcestamps.findOrCreateId(**stampdict))
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/db/sourcestamps.py", line 58, in findOrCreateId
            assert codebase is not None, "codebase cannot be None"
        builtins.AssertionError: codebase cannot be None

**Comment by 0x8000-0000** [comment]
Potential changes in a98079481870d19edd5eb9b2883db0c1ef6086fe ?

**Comment by 0x8000-0000** [comment]
Adding line 177 in buildbot/changes/gerritchangesource.py seems to work around the problem.

168     @defer.inlineCallbacks
169     def addChange(self, chdict):
170         stampdict = {
171             "branch": chdict["branch"],
172             "revision": chdict["revision"],
173             "patch_author": chdict["author"],
174             "patch_comment": chdict["comments"],
175             "repository": chdict["repository"],
176             "project": chdict["project"],
177             "codebase": '',
178         }

**Comment by meffie** [comment]
We are in the process of moving to a new buildbot master for the OpenAFS project, and I've hit this problem as well, on v2.8.0. I made the same workaround patch for now to avoid the exception.
