### ISSUE TITLE
github oauth2 broken

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#5196]
```
2020-02-12 09:34:05+0000 [-] While rendering resource:
	Traceback (most recent call last):
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1464, in _inlineCallbacks
	    status.deferred.errback()
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
	    self._startRunCallbacks(fail)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/resource.py", line 96, in failHttpError
	    f.trap(Error)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 439, in trap
	    self.raiseException()
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 467, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/resource.py", line 89, in failHttpRedirect
	    f.trap(Redirect)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 439, in trap
	    self.raiseException()
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 467, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 58, in renderLogin
	    details = yield self.auth.verifyCode(code)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 169, in verifyCode
	    result = yield threads.deferToThread(thd, client_id, client_secret)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 163, in thd
	    session = self.createSessionFromToken(content)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 289, in createSessionFromToken
	    s.headers = {'Authorization': 'token ' + token['access_token']}
	builtins.KeyError: 'access_token'
```

**Comment by tardyp** [comment]
```
2020-02-12 09:44:46+0000 [-] /home/bbuser/venv/lib/python3.6/site-packages/urllib3/connectionpool.py:847: urllib3.exceptions.InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2020-02-12 09:44:47+0000 [-] While rendering resource:
	Traceback (most recent call last):
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1464, in _inlineCallbacks
	    status.deferred.errback()
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
	    self._startRunCallbacks(fail)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/resource.py", line 96, in failHttpError
	    f.trap(Error)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 439, in trap
	    self.raiseException()
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 467, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/resource.py", line 89, in failHttpRedirect
	    f.trap(Redirect)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 439, in trap
	    self.raiseException()
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 467, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 58, in renderLogin
	    details = yield self.auth.verifyCode(code)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 169, in verifyCode
	    result = yield threads.deferToThread(thd, client_id, client_secret)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/bbuser/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 164, in thd
	    return self.getUserInfoFromOAuthClient(session)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 271, in getUserInfoFromOAuthClient
	    return self.getUserInfoFromOAuthClient_v3(c)
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 275, in getUserInfoFromOAuthClient_v3
	    user = self.get(c, '/user')
	  File "/usr/home/bbuser/buildbot/master/buildbot/www/oauth2.py", line 131, in get
	    return ret.json()
	  File "/home/bbuser/venv/lib/python3.6/site-packages/requests/models.py", line 897, in json
	    return complexjson.loads(self.text, **kwargs)
	  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
	    return _default_decoder.decode(s)
	  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
	    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
	    raise JSONDecodeError("Expecting value", s, err.value) from None
	json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by tardyp** [comment]
```
2020-02-12 09:46:29+0000 [-] b'Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.\r\n'
```

**Comment by p12tic** [comment]
@tardyp: See #5195, it fixes this exact issue.
