### ISSUE TITLE
module 'buildbot.process.properties' has no attribute 'CommandlineUserManager'

### ISSUE THREAD

**Issue by Sebastian2205** [buildbot/buildbot#5209]
**I have a problem with the following Code:**

from buildbot.plugins import util
c['user_managers'] = []
c['user_managers'].append(util.CommandlineUserManager(username="user",
                                                      passwd="userpw",
                                                      port=9990))

**Error:**
Traceback (most recent call last):
          File "/home/buildbot20/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/home/buildbot20/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/buildbot20/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/home/buildbot20/buildbot/sandbox/lib/python3.6/site-packages/buildbot/config.py", line 170, in loadConfig
            self.basedir, self.configFileName)
        --- <exception caught here> ---
          File "/home/buildbot20/buildbot/sandbox/lib/python3.6/site-packages/buildbot/config.py", line 128, in loadConfigDict
            execfile(filename, localDict)
          File "/home/buildbot20/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/compat.py", line 247, in execfile
            exec(code, globals, locals)
          File "/home/buildbot20/buildbot/bbmaster/master/master.cfg", line 44, in <module>
            c['user_managers'].append(util.CommandlineUserManager(username="seb",
          File "/home/buildbot20/buildbot/sandbox/lib/python3.6/site-packages/buildbot/plugins/db.py", line 275, in __getattr__
            raise AttributeError(str(err))
        builtins.AttributeError: Unable to load buildbot.util:CommandlineUserManager: module 'buildbot.process.properties' has no attribute 'CommandlineUserManager'

**Comment by p12tic** [comment]
This has been fixed in c6d3163a77198694ec424d777a7109435a8d02d6 that landed in v3.0.1.
