### ISSUE TITLE
Tests are freezing/hanging on debian unstable

### ISSUE THREAD

**Issue by rjarry** [buildbot/buildbot#5224]
The tests are completely freezing with version 2.7.0 on debian unstable until the build is interrupted with ctrl-c.

I can reproduce the problem systematically:

```
~$ git clone https://salsa.debian.org/python-team/applications/buildbot/
...
~$ cd buildbot
~$ gbp buildpackage
...
I: pybuild base:217: PYTHONPATH=pkg:/<<PKGBUILDDIR>>/debian/tmp//usr/lib/python3.8/dist-packages PATH=$PATH:/<<PKGBUILDDIR>>/debian/tmp/usr/bin trial3 -xe buildbot.test buildbot_worker.test
buildbot.test.integration.interop.test_commandmixin
  CommandMixinMaster
    test_commandmixin ...                                                  [OK]
  CommandMixinMasterPB
    test_commandmixin ... Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.8/dist-packages/buildbot/test/integration/interop/test_commandmixin.py", line 31, in test_commandmixin
    yield self.setupConfig(masterConfig())
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.8/dist-packages/buildbot/test/util/integration.py", line 197, in setupConfig
    yield self.w.setServiceParent(m)
  File "/usr/lib/python3/dist-packages/twisted/application/service.py", line 193, in setServiceParent
    self.parent.addService(self)
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.8/dist-packages/buildbot/util/service.py", line 117, in addService
    return service.startService()
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.8/dist-packages/buildbot_worker/pb.py", line 236, in startService
    WorkerBase.startService(self)
  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.8/dist-packages/buildbot_worker/base.py", line 418, in startService
    service.MultiService.startService(self)
  File "/usr/lib/python3/dist-packages/twisted/application/service.py", line 288, in startService
    service.startService()
  File "/usr/lib/python3/dist-packages/twisted/application/internet.py", line 1132, in startService
    self._machine.start()
  File "/usr/lib/python3/dist-packages/automat/_methodical.py", line 126, in __get__
    def doInput(*args, **kwargs):
  File "/usr/lib/python3/dist-packages/automat/_introspection.py", line 39, in decorator
    return copyfunction(decorated,
  File "/usr/lib/python3/dist-packages/automat/_introspection.py", line 31, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
  File "/usr/lib/python3/dist-packages/automat/_introspection.py", line 19, in copycode
    return code(*values)
builtins.TypeError: an integer is required (got type bytes)
[ERROR]
<<<<<<<<<<<<<<<<<<< HANGS FOREVER >>>>>>>>>>>>>>>>>>>>>>>>>
```

**Comment by rjarry** [comment]
Here are some über debug traces with trial --spew just before it freezes:

```
...
method callback of twisted.internet.defer.DeferredList at 140455535262784
method _startRunCallbacks of twisted.internet.defer.DeferredList at 140455535262784
method _runCallbacks of twisted.internet.defer.DeferredList at 140455535262784
function _parseDListResult in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1147
function <listcomp> in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1151
function gotResult in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1469
function _inlineCallbacks in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1383
method stopService of buildbot.schedulers.manager.SchedulerManager at 140455535219712
method callback of twisted.internet.defer.Deferred at 140455535260624
method _startRunCallbacks of twisted.internet.defer.Deferred at 140455535260624
method _runCallbacks of twisted.internet.defer.Deferred at 140455535260624
method _cbDeferred of twisted.internet.defer.DeferredList at 140455535707856
method callback of twisted.internet.defer.Deferred at 140455534870592
method _startRunCallbacks of twisted.internet.defer.Deferred at 140455534870592
method _runCallbacks of twisted.internet.defer.Deferred at 140455534870592
function gotResult in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1469
function _inlineCallbacks in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1383
method do of buildbot.db.pool.DBThreadPool at 140455535254064
method callback of twisted.internet.defer.Deferred at 140455535275648
method _startRunCallbacks of twisted.internet.defer.Deferred at 140455535275648
method _runCallbacks of twisted.internet.defer.Deferred at 140455535275648
function gotResult in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1469
function _inlineCallbacks in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1383
method stopService of buildbot.worker.base.Worker at 140455535181728
method disconnect of buildbot.worker.base.Worker at 140455535181728
function succeed in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 71
method __init__ of twisted.internet.defer.Deferred at 140455535254976
method callback of twisted.internet.defer.Deferred at 140455535254976
method _startRunCallbacks of twisted.internet.defer.Deferred at 140455535254976
method _runCallbacks of twisted.internet.defer.Deferred at 140455535254976
method addBoth of twisted.internet.defer.Deferred at 140455535254976
method addCallbacks of twisted.internet.defer.Deferred at 140455535254976
method _runCallbacks of twisted.internet.defer.Deferred at 140455535254976
function gotResult in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1469
method stopService of buildbot.worker.base.Worker at 140455535181728
method waitForCompleteShutdown of buildbot.worker.base.Worker at 140455535181728
function unwindGenerator in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1601
function _cancellableInlineCallbacks in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1496
method __init__ of twisted.internet.defer.Deferred at 140455535741008
method __init__ of twisted.internet.defer._CancellationStatus at 140455536171424
function _inlineCallbacks in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1383
method _waitForCompleteShutdownImpl of buildbot.worker.base.Worker at 140455535181728
method callback of twisted.internet.defer.Deferred at 140455535741008
method _startRunCallbacks of twisted.internet.defer.Deferred at 140455535741008
method _runCallbacks of twisted.internet.defer.Deferred at 140455535741008
method addBoth of twisted.internet.defer.Deferred at 140455535741008
method addCallbacks of twisted.internet.defer.Deferred at 140455535741008
method _runCallbacks of twisted.internet.defer.Deferred at 140455535741008
function gotResult in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1469
method stopService of buildbot.worker.base.Worker at 140455535181728
function unwindGenerator in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1601
function _cancellableInlineCallbacks in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1496
method __init__ of twisted.internet.defer.Deferred at 140455535747184
method __init__ of twisted.internet.defer._CancellationStatus at 140455535747952
function _inlineCallbacks in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1383
method stopService of buildbot.worker.base.Worker at 140455535181728
method stopService of buildbot.worker.base.Worker at 140455535181728
method stopService of buildbot.worker.base.Worker at 140455535181728
method stopService of buildbot.worker.base.Worker at 140455535181728
method __iter__ of buildbot.worker.base.Worker at 140455535181728
function gatherResults in /usr/lib/python3/dist-packages/twisted/internet/defer.py, line 1155
method __init__ of twisted.internet.defer.DeferredList at 140455535275456
method __init__ of twisted.internet.defer.DeferredList at 140455535275456
<<<<<<<<<<<<<<<<<<< HANGS FOREVER >>>>>>>>>>>>>>>>>>>>>>>>>
```

**Comment by rjarry** [comment]
It looks like it was due to an obscure problem with python3-defaults in debian. It seems to work now. Sorry about the noise.
