### ISSUE TITLE
Badges plugin with Buildbot run with docker

### ISSUE THREAD

**Issue by lquinet** [buildbot/buildbot#5259]
Hi,

I'm trying to use the badges plugin with buildbot run with docker. I am not sure how to install the plugin, but there is an error when I install the plugin on the master container via `pip3 install buildbot-badges` . I am using the official docker image of buildbot-master: `buildbot/buildbot-master:master` .

Here is the error:
```sh

Sending build context to Docker daemon  6.144kB
Step 1/3 : FROM buildbot/buildbot-master:master
 ---> 9e0a772632ab
Step 2/3 : RUN pip3 install buildbot-badges
 ---> Running in f83826da5058
Collecting buildbot-badges
  Downloading buildbot_badges-2.7.0-py3-none-any.whl (6.4 kB)
Collecting CairoSVG
  Downloading CairoSVG-2.4.2-py3-none-any.whl (50 kB)
Collecting cairocffi
  Downloading cairocffi-1.1.0.tar.gz (68 kB)
Requirement already satisfied: Jinja2 in /usr/lib/python3.6/site-packages (from buildbot-badges) (2.11.1)
Collecting klein
  Downloading klein-19.6.0-py2.py3-none-any.whl (117 kB)
Collecting defusedxml
  Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting cssselect2
  Downloading cssselect2-0.3.0-py3-none-any.whl (31 kB)
Collecting pillow
  Downloading Pillow-7.1.1.tar.gz (38.9 MB)
Collecting tinycss2
  Downloading tinycss2-1.0.2-py3-none-any.whl (61 kB)
Requirement already satisfied: cffi>=1.1.0 in /usr/lib/python3.6/site-packages (from cairocffi->buildbot-badges) (1.14.0)
Requirement already satisfied: setuptools>=39.2.0 in /usr/lib/python3.6/site-packages (from cairocffi->buildbot-badges) (46.1.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.6/site-packages (from Jinja2->buildbot-badges) (1.1.1)
Collecting typing
  Downloading typing-3.7.4.1-py3-none-any.whl (25 kB)
Collecting Werkzeug
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Requirement already satisfied: attrs in /usr/lib/python3.6/site-packages (from klein->buildbot-badges) (19.3.0)
Requirement already satisfied: Twisted>=15.5 in /usr/lib/python3.6/site-packages (from klein->buildbot-badges) (20.3.0)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from klein->buildbot-badges) (1.14.0)
Requirement already satisfied: hyperlink in /usr/lib/python3.6/site-packages (from klein->buildbot-badges) (19.0.0)
Requirement already satisfied: incremental in /usr/lib/python3.6/site-packages (from klein->buildbot-badges) (17.5.0)
Collecting Tubes
  Downloading Tubes-0.2.0-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: zope.interface in /usr/lib/python3.6/site-packages (from klein->buildbot-badges) (5.0.2)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: pycparser in /usr/lib/python3.6/site-packages (from cffi>=1.1.0->cairocffi->buildbot-badges) (2.20)
Requirement already satisfied: Automat>=0.3.0 in /usr/lib/python3.6/site-packages (from Twisted>=15.5->klein->buildbot-badges) (20.2.0)
Requirement already satisfied: PyHamcrest!=1.10.0,>=1.9.0 in /usr/lib/python3.6/site-packages (from Twisted>=15.5->klein->buildbot-badges) (2.0.2)
Requirement already satisfied: constantly>=15.1 in /usr/lib/python3.6/site-packages (from Twisted>=15.5->klein->buildbot-badges) (15.1.0)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.6/site-packages (from hyperlink->klein->buildbot-badges) (2.9)
Collecting characteristic
  Downloading characteristic-14.3.0-py2.py3-none-any.whl (15 kB)
Building wheels for collected packages: cairocffi, pillow
  Building wheel for cairocffi (setup.py): started
  Building wheel for cairocffi (setup.py): finished with status 'done'
  Created wheel for cairocffi: filename=cairocffi-1.1.0-py3-none-any.whl size=88588 sha256=84fa16ea5761dc1725846f3401fe727d7608d0424749d1c0d98d3186b08f8b7b
  Stored in directory: /root/.cache/pip/wheels/bd/b2/c1/d88d84a95f5dbbaea6361c304a3c76500f88a886ee148de78f
  Building wheel for pillow (setup.py): started
  Building wheel for pillow (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r55suqe4/pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r55suqe4/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1jurlwlx
       cwd: /tmp/pip-install-r55suqe4/pillow/
  Complete output (172 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/_version.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/features.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  writing top-level names to src/Pillow.egg-info/top_level.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'azure-pipelines.yml'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.azure-pipelines'
  no previously-included directories found matching '.ci'
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/tmp/pip-install-r55suqe4/pillow/setup.py", line 899, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW),
    File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-install-r55suqe4/pillow/setup.py", line 694, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: zlib
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-r55suqe4/pillow/setup.py", line 914, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  ----------------------------------------
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
Successfully built cairocffi
Failed to build pillow
Installing collected packages: cairocffi, defusedxml, webencodings, tinycss2, cssselect2, pillow, CairoSVG, typing, Werkzeug, characteristic, Tubes, klein, buildbot-badges
    Running setup.py install for pillow: started
    Running setup.py install for pillow: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r55suqe4/pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r55suqe4/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8nwx6dr3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.6m/pillow
         cwd: /tmp/pip-install-r55suqe4/pillow/
    Complete output (174 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/_version.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/features.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.ci'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-install-r55suqe4/pillow/setup.py", line 899, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW),
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-install-r55suqe4/pillow/setup.py", line 694, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-r55suqe4/pillow/setup.py", line 914, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r55suqe4/pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r55suqe4/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8nwx6dr3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.6m/pillow Check the logs for full command output.
The command '/bin/sh -c pip3 install buildbot-badges' returned a non-zero code: 1


```

**Comment by lquinet** [comment]
**Issue fixed**: I had to install all the following dependencies to be able to install buildbot-badges and use it without error in the master container.

**DEPENDENCIES**: `apk add build-base python3-dev jpeg-dev zlib-dev cairo cairo-dev`

So if you want to use the badges plugin with buildbot run with docker you have to create your own master docker image. The minimum Dockerfile looks like this:

```Dockerfile
# based on alpine:3.7
FROM buildbot/buildbot-master:master

# install pillow dependencies
RUN apk add build-base python3-dev jpeg-dev zlib-dev cairo cairo-dev

# install pip dependencies
RUN pip3 install buildbot-badges

CMD ["dumb-init", "/usr/src/buildbot/docker/start_buildbot.sh"]
```

If I can suggest something to the Buildbot developpers, **it would be great if they could already integrate this plugin in the  official docker image of buildbot-master**, with all required dependencies.

**Comment by p12tic** [comment]
I think it makes sense to keep this issue open. The docker image should be integrated well.
