### ISSUE TITLE
GitHubStatusPush Error when using '/' character in the name of the project change source

### ISSUE THREAD

**Issue by lquinet** [buildbot/buildbot#5266]
Hi,

I notice an error related with GitHubStatusPush when we use  '/' character in the name of the project change source. I used the url of the repo as the name of the project to be used for the GitPoller:

```python
 c['change_source'].append(
        changes.GitPoller(
            repourl="https://github.com/lquinet/meta-fullmetalupdate.git",
            project="https://github.com/lquinet/meta-fullmetalupdate.git",
            workdir='gitpoller-workdir', 
            branches=True,
            pollInterval=60
        )
```

The problem occurs when buildbot try to push the status to GitHub. I suppose it tries to split, with '/', the project name to get repoOwner and repoName but it get more values than expected as there was already some '/' in the project name.

Here is the error:

```sh
buildbot_1  | 2020-04-23 14:24:46+0000 [-] while invoking <bound method HttpStatusPushBase.buildFinished of <buildbot.reporters.github.GitHubStatusPush object at 0x7fc14616b518>>
buildbot_1  | 	Traceback (most recent call last):
buildbot_1  | 	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
buildbot_1  | 	    result = g.send(result)
buildbot_1  | 	  File "/usr/lib/python3.6/site-packages/buildbot/reporters/http.py", line 80, in getMoreInfoAndSend
buildbot_1  | 	    yield self.send(build)
buildbot_1  | 	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
buildbot_1  | 	    return _cancellableInlineCallbacks(gen)
buildbot_1  | 	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
buildbot_1  | 	    _inlineCallbacks(None, g, status)
buildbot_1  | 	--- <exception caught here> ---
buildbot_1  | 	  File "/usr/lib/python3.6/site-packages/buildbot/reporters/http.py", line 80, in getMoreInfoAndSend
buildbot_1  | 	    yield self.send(build)
buildbot_1  | 	  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
buildbot_1  | 	    result = g.send(result)
buildbot_1  | 	  File "/usr/lib/python3.6/site-packages/buildbot/reporters/github.py", line 140, in send
buildbot_1  | 	    repoOwner, repoName = project.split('/')
buildbot_1  | 	builtins.ValueError: too many values to unpack (expected 2)

```

**Comment by tardyp** [comment]
hello, nice findings!

 looks like it is easily resolvable with a simple rstrip('/') at init.

Would you like to contribute a pull request?
