### ISSUE TITLE
TLSRequiredError when trying to send mail from office365 address

### ISSUE THREAD

**Issue by lquinet** [buildbot/buildbot#5267]
Hi,

I don't manage to use the mail notifier with a office365 address. I have an error saying that the Server does not support secure communication via TLS / SSL'. I checked with master/contrib/check_smtp.py and it seems to works.

The mail notifier is configured as follow:
```python
mn = reporters.MailNotifier(fromaddr="lquinet@witekio.com",
                            sendToInterestedUsers=False,
                            extraRecipients=["loicquinet@outlook.com"],
                            useTls=True, relayhost="smtp.office365.com",
                            smtpPort=587, smtpUser="lquinet@witekio.com",
                            smtpPassword=os.environ.get("SMTP_PWD", "password"))
```

Here is the detailed error:

```sh
buildbot_1  | 2020-04-24 13:18:40+0000 [-] Unhandled error in Deferred:
buildbot_1  | 2020-04-24 13:18:40+0000 [-] Unhandled Error
buildbot_1  | 	Traceback (most recent call last):
buildbot_1  | 	--- <exception caught here> ---
buildbot_1  | 	  File "/usr/lib/python3.6/site-packages/buildbot/reporters/notifier.py", line 279, in buildMessage
buildbot_1  | 	    list(users), patches, logs)
buildbot_1  | 	  File "/usr/lib/python3.6/site-packages/buildbot/reporters/mail.py", line 273, in sendMessage
buildbot_1  | 	    yield self.sendMail(m, all_recipients)
buildbot_1  | 	twisted.mail._except.TLSRequiredError: 502 b'Server does not support secure communication via TLS / SSL'
buildbot_1  | 	<<< 250-8BITMIME
buildbot_1  | 	<<< 250-BINARYMIME
buildbot_1  | 	<<< 250-CHUNKING
buildbot_1  | 	<<< 250 SMTPUTF8
```

**Comment by tardyp** [comment]
Hi, there is useTls, and useSmtps option.

The first one starts a tls encryption after a first plain text exchange, and the second is smtp over tls (so tls negociation is before smtp)
probably office365 tls uses the second option.

**Comment by lquinet** [comment]
Hi tardyp,

I found the error. My parameters were right, but actually there was a problem with the openssl package in the buildbot master container. I noticed that when I tested the useSmtps option in MailNotifier. I had the following error:

```sh
buildbot_1  | checking basedir
buildbot_1  | checking for running master
buildbot_1  | checking master.cfg
buildbot_1  | Errors loading configuration:
buildbot_1  |   TLS dependencies required for MailNotifier are not installed : Error relocating /usr/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: RSA_get0_crt_params: symbol not found
buildbot_1  |  pip install 'buildbot[tls]'
buildbot_1  | Can't upgrade master yet. Waiting for database ready?
```

I fixed the error by reinstalling pyopenssl and cryptography in the buildbot master container. Here is the minimum dockerfile for generating the new buildbot-master docker image:

```dockerfile
# based on alpine:3.7
FROM buildbot/buildbot-master:master

# install openssl dependencies
RUN apk add build-base libffi-dev python3-dev openssl-dev 

RUN pip3 uninstall -y pyopenssl
RUN pip3 uninstall -y cryptography
RUN pip3 install pyopenssl

CMD ["dumb-init", "/usr/src/buildbot/docker/start_buildbot.sh"]
```

Tell me if I have to open a separate issue for that (btw the issue #5259 is also related to a missing package in the buidbot master docker image)

**Comment by tenta4** [comment]
Without packages versions your post makes no sense

**Comment by doberkofler** [comment]
> Hi tardyp,
> 
> I found the error. My parameters were right, but actually there was a **problem with the openssl package in the buildbot master container**. I noticed that when I tested the useSmtps option in MailNotifier. I had the following error:
> 
> ```shell
> buildbot_1  | checking basedir
> buildbot_1  | checking for running master
> buildbot_1  | checking master.cfg
> buildbot_1  | Errors loading configuration:
> buildbot_1  |   TLS dependencies required for MailNotifier are not installed : Error relocating /usr/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: RSA_get0_crt_params: symbol not found
> buildbot_1  |  pip install 'buildbot[tls]'
> buildbot_1  | Can't upgrade master yet. Waiting for database ready?
> ```
> 
> I fixed the error by reinstalling pyopenssl and cryptography in the buildbot master container. Here is the minimum dockerfile for generating the new buildbot-master docker image:
> 
> ```dockerfile
> # based on alpine:3.7
> FROM buildbot/buildbot-master:master
> 
> # install openssl dependencies
> RUN apk add build-base libffi-dev python3-dev openssl-dev 
> 
> RUN pip3 uninstall -y pyopenssl
> RUN pip3 uninstall -y cryptography
> RUN pip3 install pyopenssl
> 
> CMD ["dumb-init", "/usr/src/buildbot/docker/start_buildbot.sh"]
> ```
> 
> Tell me if I have to open a separate issue for that (btw the issue #5259 is also related to a missing package in the buidbot master docker image)

I have tried this workaround but was not successful

**Comment by muks** [comment]
See the latest comments on #5943 for a patch to test.
