### ISSUE TITLE
Cannot update property value (SQL error)

### ISSUE THREAD

**Issue by krzk** [buildbot/buildbot#5338]
Hi,

I try to overwrite the property value with something like:
```
steps.SetPropertyFromCommand(some_command, property='my-long-property-name-it-is-really-long-but-not-too-much'), haltOnFailure=True)
steps.SetProperty(property='my-long-property-name-it-is-really-long-but-not-too-much'),
    value='new value', haltOnFailure=True)
```

The build fails with exception:
```
2020-06-08 17:32:55+0200 [-]  step 'setproperty_11' complete: success (None)
2020-06-08 17:32:55+0200 [-] Got fatal Exception on DB
	Traceback (most recent call last):
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/db/pool.py", line 217, in __thd
	    log.err(e, 'Got fatal Exception on DB')
	--- <exception caught here> ---
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/db/pool.py", line 190, in __thd
	    rv = callable(arg, *args, **kwargs)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/db/steps.py", line 110, in thd
	    r = conn.execute(self.db.model.steps.insert(), insert_row)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
	    return meth(self, multiparams, params)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
	    return connection._execute_clauseelement(self, multiparams, params)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
	    distilled_params,
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
	    e, statement, parameters, cursor, context
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
	    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
	    raise exception
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
	    cursor, statement, parameters, context
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
	    cursor.execute(statement, parameters)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
	    res = self._query(query)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
	    db.query(q)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
	    _mysql.connection.query(self, query)
	sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry '93562-SetProperty_1' for key 'steps_name'")
	[SQL: INSERT INTO steps (number, name, buildid, started_at, complete_at, state_string, urls_json) VALUES (%s, %s, %s, %s, %s, %s, %s)]
	[parameters: (21, 'SetProperty_1', 93562, None, None, 'pending', '[]')]
	(Background on this error at: http://sqlalche.me/e/gkpj)
	
2020-06-08 17:32:56+0200 [-] <Build yocto_libsyscommon_devtool number:869 results:success>.buildException
2020-06-08 17:32:56+0200 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
	    self._startRunCallbacks(fail)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	--- <exception caught here> ---
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/process/buildstep.py", line 517, in startStep
	    yield self.addStep()
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/process/buildstep.py", line 510, in addStep
	    name=util.bytes2unicode(self.name))
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/data/steps.py", line 132, in addStep
	    buildid=buildid, name=name, state_string='pending')
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/db/pool.py", line 229, in do
	    args, kwargs)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/db/pool.py", line 190, in __thd
	    rv = callable(arg, *args, **kwargs)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/buildbot/db/steps.py", line 110, in thd
	    r = conn.execute(self.db.model.steps.insert(), insert_row)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
	    return meth(self, multiparams, params)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
	    return connection._execute_clauseelement(self, multiparams, params)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
	    distilled_params,
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
	    e, statement, parameters, cursor, context
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
	    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
	    raise exception
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
	    cursor, statement, parameters, context
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
	    cursor.execute(statement, parameters)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
	    res = self._query(query)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
	    db.query(q)
	  File "/home/buildbot/sandbox/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
	    _mysql.connection.query(self, query)
	sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry '93562-SetProperty_1' for key 'steps_name'")
	[SQL: INSERT INTO steps (number, name, buildid, started_at, complete_at, state_string, urls_json) VALUES (%s, %s, %s, %s, %s, %s, %s)]
	[parameters: (21, 'SetProperty_1', 93562, None, None, 'pending', '[]')]
	(Background on this error at: http://sqlalche.me/e/gkpj)
	
2020-06-08 17:32:56+0200 [-]  <Build yocto_libsyscommon_devtool number:869 results:success>: build finished
```
Python version: 3.6.8
Buildbot version: 2.8.1
Twisted version: 20.3.0
DB: MariaDB, 10.3.17

Expectations:
To be able to overwrite the property with new value.

Best regards,
Krzysztof

**Comment by tardyp** [comment]
Hi,
It looks like the name of your step is duplicate.

```(1062, "Duplicate entry '93562-SetProperty_1' for key 'steps_name'")```

I have changed behavior in step name deduplication recently, but I don't see why that code should not work.

https://github.com/tardyp/buildbot/commit/ba124ccdf67de559553109bb6af9effb539a22a2
You can add some prints around and inside setUniqueStepName to find out why bb cannot deduplicate step name in your case.

Is this a regression with 2.8.0+?

Quick workaround to unblock you is to explicitly set a name for your steps.

**Comment by p12tic** [comment]
This happens because Buildbot does not know that MySQL is case insensitive and tries to create new property name that only differs by case. We should upgrade the DB schema on MySQL to specify case sensitive collation.
