### ISSUE TITLE
builtins.KeyError: 'data' When log in using Github oauth

### ISSUE THREAD

**Issue by yinyangsx** [buildbot/buildbot#5389]
I met this error when log in using Github oath.

My Buildbot's configuration as below,
util.GitHubAuth(GITHUB['ci'], GITHUB['cs'], apiVersion=4, getTeamsMembership=True)

My Buildbot's version is 
Buildbot version: 2.5.0
Twisted version: 19.10.0

2020-06-29 16:40:35+0300 [-] /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: urllib3.exceptions.InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2020-06-29 16:40:35+0300 [-] /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: urllib3.exceptions.InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2020-06-29 16:40:35+0300 [-] While rendering resource:
        Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
            _inlineCallbacks(r, g, status)
          File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1464, in _inlineCallbacks
            status.deferred.errback()
          File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 501, in errback
            self._startRunCallbacks(fail)
          File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/local/lib/python3.6/dist-packages/buildbot/www/resource.py", line 96, in failHttpError
            f.trap(Error)
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 460, in trap
            self.raiseException()
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 488, in raiseException
            raise self.value.with_traceback(self.tb)
          File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/local/lib/python3.6/dist-packages/buildbot/www/resource.py", line 89, in failHttpRedirect
            f.trap(Redirect)
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 460, in trap
            self.raiseException()
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 488, in raiseException
            raise self.value.with_traceback(self.tb)
          File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python3.6/dist-packages/buildbot/www/oauth2.py", line 58, in renderLogin
            details = yield self.auth.verifyCode(code)
          File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python3.6/dist-packages/buildbot/www/oauth2.py", line 169, in verifyCode
            result = yield threads.deferToThread(thd, client_id, client_secret)
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 250, in inContext
            result = inContext.theWork()
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/usr/local/lib/python3.6/dist-packages/buildbot/www/oauth2.py", line 164, in thd 
            return self.getUserInfoFromOAuthClient(session)
          File "/usr/local/lib/python3.6/dist-packages/buildbot/www/oauth2.py", line 272, in getUserInfoFromOAuthClient
            return self.getUserInfoFromOAuthClient_v4(c)
          File "/usr/local/lib/python3.6/dist-packages/buildbot/www/oauth2.py", line 329, in getUserInfoFromOAuthClient_v4
            for org, team_data in data['data'].items():
        builtins.KeyError: 'data'

**Comment by yinyangsx** [comment]
I have found the root cause. BB will get error if my account has an organization named "01org", error logs as below.

2020-07-06 14:06:58+0000 [-] query getOrgTeamMembership {
2020-07-06 14:06:58+0000 [-]   otcshare: organization(login: "otcshare") {
2020-07-06 14:06:58+0000 [-]     teams(first: 100 userLogins: ["erichkeane"]) {
2020-07-06 14:06:58+0000 [-]       edges {
2020-07-06 14:06:58+0000 [-]         node {
2020-07-06 14:06:58+0000 [-]           name,
2020-07-06 14:06:58+0000 [-]           slug
2020-07-06 14:06:58+0000 [-]         }
2020-07-06 14:06:58+0000 [-]       }
2020-07-06 14:06:58+0000 [-]     }
2020-07-06 14:06:58+0000 [-]   }
2020-07-06 14:06:58+0000 [-]   **01org**: organization(login: "01org") {
2020-07-06 14:06:58+0000 [-]     teams(first: 100 userLogins: ["erichkeane"]) {
2020-07-06 14:06:58+0000 [-]       edges {
2020-07-06 14:06:58+0000 [-]         node {
2020-07-06 14:06:58+0000 [-]           name,
2020-07-06 14:06:58+0000 [-]           slug
2020-07-06 14:06:58+0000 [-]         }
2020-07-06 14:06:58+0000 [-]       }
2020-07-06 14:06:58+0000 [-]     }
2020-07-06 14:06:58+0000 [-]   }
2020-07-06 14:06:58+0000 [-]   PDXCPP: organization(login: "PDXCPP") {
2020-07-06 14:06:58+0000 [-]     teams(first: 100 userLogins: ["erichkeane"]) {
2020-07-06 14:06:58+0000 [-]       edges {
2020-07-06 14:06:58+0000 [-]         node {
2020-07-06 14:06:58+0000 [-]           name,
2020-07-06 14:06:58+0000 [-]           slug
2020-07-06 14:06:58+0000 [-]         }
2020-07-06 14:06:58+0000 [-]       }
2020-07-06 14:06:58+0000 [-]     }
2020-07-06 14:06:58+0000 [-]   }
2020-07-06 14:06:58+0000 [-] }
2020-07-06 14:06:58+0000 [-] GitHubAuth GraphQL Response: {'errors': [{'message': '**Parse error on "01"** (FLOAT) at [13, 3]', 'locations': [{'line': 13, 'column': 3}]}]}

There is a simple way to fix this issue.

        if self.getTeamsMembership:
            orgs_name_slug_mapping = {
+              '_' + self._orgname_slug_sub_re.sub('_', n): n
-               self._orgname_slug_sub_re.sub('_', n): n
                for n in user_info['groups']}
