### ISSUE TITLE
GitHub will discontinue the OAuth Authorizations API

### ISSUE THREAD

**Issue by ryandesign** [buildbot/buildbot#5414]
I'm trying to configure buildbot 2.8.2 for the first time. I would like users to be able to log in to my buildbot with their GitHub account.

I found this documentation on GitHubAuth: http://docs.buildbot.net/current/manual/configuration/www.html#authentication-plugins

It says:

> This class implements an authentication with GitHub single sign-on.

The word "GitHub" is a link to http://developer.github.com/v3/oauth_authorizations/

On that page, there is an orange banner that says:

> Deprecation Notice: GitHub will discontinue the OAuth Authorizations API, which is used by integrations to create personal access tokens and OAuth tokens, and you must now create these tokens using our web application flow. The OAuth Authorizations API will be removed on November, 13, 2020. For more information, including scheduled brownouts, see the blog post.

Does GitHubAuth support this new "web application flow"? Could the documentation please be updated, at least by replacing the link with wherever the new GitHub documentation is?

**Comment by tardyp** [comment]
It looks like indeed the github link moved to:

https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow

Buildbot supported the oauth2 authentication flow, which is called web app flow in github.

**Comment by ryandesign** [comment]
I'm finding this extremely confusing. GitHub documentation is full of unfamiliar terminology. I appear to have to create either a "GitHub App" or an "OAuth App" in my GitHub account. GitHub has a guide for [migrating OAuth Apps to GitHub Apps](https://developer.github.com/apps/migrating-oauth-apps-to-github-apps/), which makes me think I should be creating a GitHub App. But the setup screen is huge and I don't know which of the dozens of permissions I'm supposed to give it. It seems to me that I should be able to go to the [GitHub Marketplace, type "buildbot"](https://github.com/marketplace?query=buildbot), and install a pre-made app that has all the right settings.

**Comment by ryandesign** [comment]
> install a pre-made app

Maybe this isn't possible right now. The app's authorization callback URL and webhook URL are hardcoded in the app's settings and aren't configurable on a per-app-installation basis. So GitHub Apps are great for web services like Travis CI but not for self-hosted software like buildbot. Maybe I'll ask GitHub if they can add this feature.

It looks like the permission one needs to enable in a GitHub App in order to receive webhook notifications for commits is called "Checks". Does buildbot know how to respond to "[check_suite](https://developer.github.com/v3/checks/suites/)" notifications?

**Comment by ryandesign** [comment]
I tried configuring my buildbot with the client id and client secret of my new GitHub App. I clicked Login with GitHub, GitHub presented its permission screen, I accepted, and it redirected back to my buildbot, which said:

```
internal error - see logs
```

The log says:

```
2020-07-21 13:26:38+0000 [-] /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py:979: urllib3.exceptions.InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2020-07-21 13:26:38+0000 [-] /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py:979: urllib3.exceptions.InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2020-07-21 13:26:38+0000 [-] While rendering resource:
	Traceback (most recent call last):
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 1464, in _inlineCallbacks
	    status.deferred.errback()
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 501, in errback
	    self._startRunCallbacks(fail)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/buildbot/www/resource.py", line 96, in failHttpError
	    f.trap(Error)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/failure.py", line 460, in trap
	    self.raiseException()
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/failure.py", line 488, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/buildbot/www/resource.py", line 89, in failHttpRedirect
	    f.trap(Redirect)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/failure.py", line 460, in trap
	    self.raiseException()
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/failure.py", line 488, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/buildbot/www/oauth2.py", line 59, in renderLogin
	    details = yield self.auth.verifyCode(code)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/buildbot/www/oauth2.py", line 170, in verifyCode
	    result = yield threads.deferToThread(thd, client_id, client_secret)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/buildbot/www/oauth2.py", line 165, in thd
	    return self.getUserInfoFromOAuthClient(session)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/buildbot/www/oauth2.py", line 272, in getUserInfoFromOAuthClient
	    return self.getUserInfoFromOAuthClient_v3(c)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/buildbot/www/oauth2.py", line 279, in getUserInfoFromOAuthClient_v3
	    if email.get('primary', False):
	builtins.AttributeError: 'str' object has no attribute 'get'
```

**Comment by ryandesign** [comment]
Searching around for "Buildbot" and "GitHub App", I found these [Buildbot meeting notes](https://supybot.buildbot.net/meetings/buildbot/2017/buildbot.2017-07-25-16.00.log.html) from 3 years ago talking about it, so it's not a new thing, so I'm surprised it doesn't work. Incidentally, that host's ssl certificate has expired; you should renew it.

**Comment by ryandesign** [comment]
> ```
> 	    if email.get('primary', False):
> 	builtins.AttributeError: 'str' object has no attribute 'get'
> ```

Aha—if I grant the app read-only permission to user email information, then authentication works.

**Comment by ryandesign** [comment]
> It looks like the permission one needs to enable in a GitHub App in order to receive webhook notifications for commits is called "Checks". Does buildbot know how to respond to "[check_suite](https://developer.github.com/v3/checks/suites/)" notifications?

I've now found the part in the [Buildbot documentation](https://docs.buildbot.net/latest/manual/configuration/wwwhooks.html?highlight=handle_blah#github-hook) where it says "The default class handles ping, push and pull_request events only. If you’d like to handle other events [...] you’d need to subclass GitHubEventHandler". So I started to subclass it to investigate check_suite events, but I realized they are very different from push events. For example a push event can list multiple commits that were pushed, and Buildbot imports each of them, whereas a check_suite event only gives the "head_commit". This is probably where I have to stop working on it, but it would still be good for Buildbot to support check suites and check runs (at least for pull requests), since that seems to be the way GitHub wants CI systems to interact with it now.

I then found the part of the [GitHub API documentation](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#push) which says that the push event is available to "GitHub Apps with the contents permission". I had already tried enabling the contents permission before and it hadn't done anything, but now I realized that when the contents permission is enabled, a "Push" checkbox shows up when you scroll down to the Events section. Checking that box, and saving the settings, and going back to your app installation to accept the changed permissions, finally makes the app send push events which Buildbot then happily accepts. Hopefully we can add something to the Buildbot documentation that fully explains how to create and set up a GitHub App for Buildbot, and how to configure Buildbot to use it.

GitHub Apps also send [installation events](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#installation) when they are installed, when permissions change, when new permissions are accepted, and who knows what else. Buildbot probably doesn't care about those, but it would be good to add a handler that just ignores those events, so that they don't show up with an error in the list of events sent in the GitHub App.

**Comment by rajdeepbharati** [comment]
> It looks like the permission one needs to enable in a GitHub App in order to receive webhook notifications for commits is called "Checks". Does buildbot know how to respond to "check_suite" notifications?

Isn't that an optional permission?

**Comment by ryandesign** [comment]
> Isn't that an optional permission?

Yes. When I wrote that, check_suite was the only way that I was aware of for a GitHub App to send information about commits via web hooks. As I wrote above, I have now figured out how to get it to send push events instead.

**Comment by tardyp** [comment]
So shall we close this issue?

**Comment by p12tic** [comment]
I think this is serious documentation issue with our documentation if @ryandesign had to spend several days configuring github for Buildbot.
