### ISSUE TITLE
command 'buildbot try' doesn't work with p4

### ISSUE THREAD

**Issue by GaryFunKing** [buildbot/buildbot#5444]
Hi,

I am currently trying to use the 'buildbot try' command line.
I use the pb connect methode and our vc is perforce.
I found a first bug in tryclient.py in the readPatch function of PerforceExtractor.
At line 270 : 
`for line in res.split("\n"):`
res is a byte type and not a string type.
I made a quick fix like this : 
```
resAsString = res.decode("utf-8")
        for line in resAsString.split("\n"):
```
with this the job is correctly send to the master, but then I have this error on the master : 
```

2020-08-05 16:32:41+0200 [-] <Build ASFNoUpload number:None results:success>.startBuild
2020-08-05 16:32:41+0200 [-] from a running build; this is a serious error - please file a bug at http://buildbot.net
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 460, in callback
            self._startRunCallbacks(result)
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
            _inlineCallbacks(r, g, status)
        --- <exception caught here> ---
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/.local/lib/python3.7/site-packages/buildbot/process/build.py", line 318, in startBuild
            self.setupOwnProperties()
          File "/home/buildbot/.local/lib/python3.7/site-packages/buildbot/process/build.py", line 241, in setupOwnProperties
            props.setProperty("revision", source.revision, "Build")
          File "/home/buildbot/.local/lib/python3.7/site-packages/buildbot/process/properties.py", line 194, in setProperty
            json.dumps(value)  # Let the exception propagate ...
          File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
            return _default_encoder.encode(obj)
          File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
            chunks = self.iterencode(o, _one_shot=True)
          File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
            return _iterencode(o, 0)
          File "/usr/lib/python3.7/json/encoder.py", line 179, in default
            raise TypeError(f'Object of type {o.__class__.__name__} '
        builtins.TypeError: Object of type bytes is not JSON serializable
```
It look like another type error.
This error is really troublesome because it create a build who never finish is worker_preparation step.
I can't stop it, and I can't restart the master. The only way to stop the build is to reboot the master computer.

For information, the command line I use is : 
buildbot try --connect=pb --master=XXX.XXX.XXX.X:XXXX --username=myName --passwd=myPassword --vc=p4 --builder=myBuilder --branch=dev

**Comment by terencehonles** [comment]
This is likely the Py3 issue #4488
