### ISSUE TITLE
Reconfigurion is failing with exceptions

### ISSUE THREAD

**Issue by sri-codefresh** [buildbot/buildbot#5464]
buildbot master has started to run multiple builds.
And these builds are using Master locks for exclusive Compilation.

During this phase, buildbot reconfig has executed.

Then, we are getting following error.

2020-08-17 15:03:06+0200 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/h/svcbbemi/bb_venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/h/svcbbemi/bb_venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	  File "/h/svcbbemi/bb_venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/h/svcbbemi/bb_venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	--- <exception caught here> ---
	  File "/h/svcbbemi/bb_venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/h/svcbbemi/buildbot/master/buildbot/process/buildstep.py", line 524, in startStep
	    self.locks = yield botmaster.getLockFromLockAccesses(self.locks, self.build.config_version)
	builtins.AttributeError: 'NoneType' object has no attribute 'getLockFromLockAccesses'

Any hints are helpful to debug this issue further

**Comment by p12tic** [comment]
Thanks a lot for the bug report, I roughly see where the problem lies.

**Comment by p12tic** [comment]
This bug has likely been fixed in #5798. Please reopen or maybe create a separate bug if any error like this repeats.
