### ISSUE TITLE
DockerLatentWorker throwing error in ShellCommand

### ISSUE THREAD

**Issue by tgckpg** [buildbot/buildbot#5581]
As discussed from the [mailing list](https://lists.buildbot.net/pipermail/users/2020-October/002063.html), filing an issue here.

## Description
I'm trying to setup a windows worker with `DockerLatentWorker` ( Which is running windows container ). After the container has been started and successfully connected, it fails on `git --version`. After some digging, I've discovered that not only git, it just failed on any command.

I've tested the docker client by going into the master's python shell.
* I can run commands within the containers without a problem ( using `client.exec_run` ).

## Environment
* buildbot-master is running on k8s pod which k8s is running on debian 10. Using images from docker hub.
* A patch in #5580 is applied before this issue
* A DockerLatentWorker is defined a Windows VM runing docker in Windows Container mode

## Full Log
```
$ kubectl logs buildbot-9c69bcf57-5wfcm master
/usr/lib/python3.8/site-packages/buildbot/status/build.py:25: DeprecatedApiWarning: [0.9.0 and later] buildbot.status.build has been deprecated, consume the buildbot.data APIs
  warn_deprecated(
/usr/lib/python3.8/site-packages/buildbot/status/buildrequest.py:25: DeprecatedApiWarning: [0.9.0 and later] buildbot.status.buildrequest has been deprecated, consume the buildbot.data APIs
  warn_deprecated(
/usr/lib/python3.8/site-packages/buildbot/status/event.py:23: DeprecatedApiWarning: [0.9.0 and later] buildbot.status.event has been deprecated, consume the buildbot.data APIs
  warn_deprecated(
/usr/lib/python3.8/site-packages/buildbot/status/builder.py:46: DeprecatedApiWarning: [0.9.0 and later] buildbot.status.worker has been deprecated, consume the buildbot.data APIs
  warn_deprecated(
/usr/lib/python3.8/site-packages/buildbot/status/buildset.py:25: DeprecatedApiWarning: [0.9.0 and later] buildbot.status.buildset has been deprecated, consume the buildbot.data APIs
  warn_deprecated(
/usr/lib/python3.8/site-packages/buildbot/status/master.py:35: DeprecatedApiWarning: [0.9.0 and later] buildbot.status.master has been deprecated, consume the buildbot.data APIs
  warn_deprecated(
/usr/lib/python3.8/site-packages/buildbot/status/worker.py:27: DeprecatedApiWarning: [0.9.0 and later] buildbot.status.worker has been deprecated, consume the buildbot.data APIs
  warn_deprecated(
/usr/lib/python3.8/site-packages/buildbot/config.py:395: ConfigWarning: `buildbotNetUsageData` is not configured and defaults to basic.
This parameter helps the buildbot development team to understand the installation base.
No personal information is collected.
Only installation software version info and plugin usage is sent.
You can `opt-out` by setting this variable to None.
Or `opt-in` for more information by setting it to "full".

  warnings.warn(
checking basedir
checking for running master
checking master.cfg
upgrading basedir
creating /var/lib/buildbot/master.cfg.sample
upgrading database (sqlite:/state.sqlite)
Warning: Stopping this process might cause data loss
upgrade complete
2020-10-14 13:21:22+0000 [-] Loading /var/lib/buildbot/buildbot.tac...
2020-10-14 13:21:23+0000 [-] Loaded.
2020-10-14 13:21:23+0000 [-] twistd 20.3.0 (/usr/bin/python3.8 3.8.2) starting up.
2020-10-14 13:21:23+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2020-10-14 13:21:23+0000 [-] Starting BuildMaster -- buildbot.version: 2020.09.21
2020-10-14 13:21:23+0000 [-] Loading configuration from '/var/lib/buildbot/master.cfg'
2020-10-14 13:21:23+0000 [-] /usr/lib/python3.8/site-packages/buildbot/config.py:395: buildbot.warnings.ConfigWarning: `buildbotNetUsageData` is not configured and defaults to basic.
        This parameter helps the buildbot development team to understand the installation base.
        No personal information is collected.
        Only installation software version info and plugin usage is sent.
        You can `opt-out` by setting this variable to None.
        Or `opt-in` for more information by setting it to "full".

2020-10-14 13:21:23+0000 [-] Setting up database with URL 'sqlite:/state.sqlite'
2020-10-14 13:21:23+0000 [-] setting database journal mode to 'wal'
2020-10-14 13:21:23+0000 [-] adding 1 new change_sources, removing 0
2020-10-14 13:21:23+0000 [-] PBServerFactory starting on 12002
2020-10-14 13:21:23+0000 [-] Starting factory <twisted.spread.pb.PBServerFactory object at 0x7f78c78d2670>
2020-10-14 13:21:23+0000 [-] adding 2 new builders, removing 0
2020-10-14 13:21:24+0000 [-] adding 2 new schedulers, removing 0
2020-10-14 13:21:24+0000 [-] NOTE: www plugin 'waterfall_view' is installed but not configured
2020-10-14 13:21:24+0000 [-] NOTE: www plugin 'grid_view' is installed but not configured
2020-10-14 13:21:24+0000 [-] NOTE: www plugin 'console_view' is installed but not configured
2020-10-14 13:21:24+0000 [-] NOTE: www plugin 'waterfall_view' is installed but not configured
2020-10-14 13:21:24+0000 [-] NOTE: www plugin 'grid_view' is installed but not configured
2020-10-14 13:21:24+0000 [-] NOTE: www plugin 'console_view' is installed but not configured
2020-10-14 13:21:24+0000 [-] BuildbotSite starting on 80
2020-10-14 13:21:24+0000 [-] Starting factory <buildbot.www.service.BuildbotSite object at 0x7f78c78b13d0>
2020-10-14 13:21:24+0000 [-] adding 2 new workers, removing 0
2020-10-14 13:21:24+0000 [-] PBServerFactory starting on 12001
2020-10-14 13:21:24+0000 [-] Starting factory <twisted.spread.pb.PBServerFactory object at 0x7f78c783e820>
2020-10-14 13:21:24+0000 [-] Latent worker debian-10-slim attached to myprojectdeb-linux
2020-10-14 13:21:25+0000 [-] Latent worker nano2004-netcore-3_1 attached to myproject-win
2020-10-14 13:21:25+0000 [-] BuildMaster is running
2020-10-14 13:21:25+0000 [-] buildbotNetUsageData: sending {'installid': '94783f17c7a87fcb5712d028a58fe1bcd0a5c30a', 'versions': {'Python': '3.8.2', 'Buildbot': '2020.09.21', 'Twisted': '20.3
.0'}, 'platform': {'platform': 'Linux-4.19.0-10-amd64-x86_64-with', 'system': 'Linux', 'machine': 'x86_64', 'processor': '', 'python_implementation': 'CPython', 'version': '#1 SMP Debian 4.19
.132-1', 'distro': 'alpine:3.11.6'}, 'plugins': {'buildbot/worker/docker/DockerLatentWorker': 2, 'buildbot/config/BuilderConfig': 2, 'buildbot/schedulers/basic/SingleBranchScheduler': 2, 'bui
ldbot/changes/pb/PBChangeSource': 1, 'buildbot/steps/shell/ShellCommand': 4, 'buildbot/steps/source/git/Git': 2}, 'db': 'sqlite', 'mq': 'simple', 'www_plugins': []}
2020-10-14 13:21:26+0000 [-] buildbotNetUsageData: buildbot.net said: ok
2020-10-14 13:22:36+0000 [Broker,0,10.0.7.1] perspective_addChange called
2020-10-14 13:22:36+0000 [-] added change with revision 63f5098f51f71371ff633be9b2064ec41555c5b5 to database
2020-10-14 13:22:36+0000 [-] added buildset 1 to database
2020-10-14 13:22:36+0000 [-] starting build <Build myproject-win number:None results:success> using worker <LatentWorkerForBuilder builder='myproject-win' worker='nano2004-netcore-3_1' state=AVAI
LABLE>
2020-10-14 13:22:36+0000 [-] <Build myproject-win number:None results:success>.startBuild
2020-10-14 13:22:37+0000 [-] acquireLocks(worker <DockerLatentWorker 'nano2004-netcore-3_1'>, locks [])
2020-10-14 13:22:37+0000 [-] substantiating worker <LatentWorkerForBuilder builder='myproject-win' worker='nano2004-netcore-3_1' state=DETACHED>
2020-10-14 13:22:37+0000 [-] Image 'nano2004-netcore-3_1_140156726302272_image' not found, building it from scratch
2020-10-14 13:22:38+0000 [-] Step 1/28 : FROM mcr.microsoft.com/windows/servercore:2004 as INSTALLER
2020-10-14 13:22:38+0000 [-]  ---> e157581737ec
2020-10-14 13:22:38+0000 [-] Step 2/28 : SHELL [ "powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';" ]
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 420532ada2f8
2020-10-14 13:22:38+0000 [-] Step 3/28 : RUN Invoke-WebRequest -Uri https://curl.haxx.se/windows/dl-7.72.0_5/curl-7.72.0_5-win64-mingw.zip -outfile /curl.zip;     Expand-Archive /curl.zip -De
stinationPath /;     Move-Item curl-7.72.0-win64-mingw curl
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 8d4d96d3ff0f
2020-10-14 13:22:38+0000 [-] Step 4/28 : RUN Invoke-WebRequest -Uri https://github.com/git-for-windows/git/releases/download/v2.28.0.windows.1/MinGit-2.28.0-64-bit.zip -outfile /MinGit.zip;
   Expand-Archive /MinGit.zip -DestinationPath /MinGit;
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 7d864fce84f5
2020-10-14 13:22:38+0000 [-] Step 5/28 : RUN Invoke-WebRequest -Uri https://github.com/PowerShell/Win32-OpenSSH/releases/download/v8.1.0.0p1-Beta/OpenSSH-Win64.zip -outfile /openssh.zip;
Expand-Archive /openssh.zip -DestinationPath /;
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 6b377d2832ca
2020-10-14 13:22:38+0000 [-] Step 6/28 : RUN [REDACTED]
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 8d864ab6ae66
2020-10-14 13:22:38+0000 [-] Step 7/28 : RUN Invoke-WebRequest https://aka.ms/vs/16/release/vs_buildtools.exe -outfile /vs_buildtools.exe
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 5cf9ef70080c
2020-10-14 13:22:38+0000 [-] Step 8/28 : RUN /vs_buildtools.exe --quiet --wait --norestart --nocache     --installPath C:\BuildTools     --add Microsoft.VisualStudio.Component.VC.Tools.x86.x6
4     --add Microsoft.VisualStudio.Component.VC.v141.x86.x64
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> a639791b4d48
2020-10-14 13:22:38+0000 [-] Step 9/28 : RUN /vs_buildtools.exe --quiet --wait --norestart --nocache     --installPath C:\BuildTools     --add Microsoft.VisualStudio.Component.Windows10SDK.18
362
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> c336f6f39d0b
2020-10-14 13:22:38+0000 [-] Step 10/28 : ENV PYTHON_VERSION 3.8.6
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> ad9229749ff3
2020-10-14 13:22:38+0000 [-] Step 11/28 : ENV PYTHON_RELEASE 3.8.6
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 9773c84d187a
2020-10-14 13:22:38+0000 [-] Step 12/28 : RUN $url = ('https://www.python.org/ftp/python/{0}/python-{1}-amd64.exe' -f $env:PYTHON_RELEASE, $env:PYTHON_VERSION);        Write-Host ('Downloadin
g {0} ...' -f $url);    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;        Invoke-WebRequest -Uri $url -OutFile 'python.exe';      Write-Host 'Installing
...';   Start-Process python.exe -Wait          -ArgumentList @(                        '/quiet',                       'InstallAllUsers=1',                    'TargetDir=C:\Python',
                'PrependPath=1',                        'Shortcuts=0',                  'Include_doc=0',                        'Include_pip=0',                        'Include_test=0'
                );      $env:PATH = [Environment]::GetEnvironmentVariable('PATH', [EnvironmentVariableTarget]::Machine);        Write-Host 'Verifying install ...';     Write-Host '  python --
version'; python --version;     Write-Host 'Removing ...';      Remove-Item python.exe -Force;  Write-Host 'Complete.'
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 912651f7edc6
2020-10-14 13:22:38+0000 [-] Step 13/28 : ENV PYTHON_PIP_VERSION 20.2.3
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 370c95608fdd
2020-10-14 13:22:38+0000 [-] Step 14/28 : ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 0f28fb4abde8
2020-10-14 13:22:38+0000 [-] Step 15/28 : ENV PYTHON_GET_PIP_SHA256 6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 9ecb8bfde9f7
2020-10-14 13:22:38+0000 [-] Step 16/28 : RUN Write-Host ('Downloading get-pip.py ({0}) ...' -f $env:PYTHON_GET_PIP_URL);       [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProt
ocolType]::Tls12;       Invoke-WebRequest -Uri $env:PYTHON_GET_PIP_URL -OutFile 'get-pip.py';   Write-Host ('Verifying sha256 ({0}) ...' -f $env:PYTHON_GET_PIP_SHA256);        if ((Get-FileHa
sh 'get-pip.py' -Algorithm sha256).Hash -ne $env:PYTHON_GET_PIP_SHA256) {               Write-Host 'FAILED!';           exit 1;         };      Write-Host ('Installing pip=={0} ...' -f $env:P
YTHON_PIP_VERSION);     python get-pip.py               --disable-pip-version-check             --no-cache-dir          ('pip=={0}' -f $env:PYTHON_PIP_VERSION)         ;       Remove-Item get
-pip.py -Force;         Write-Host 'Verifying pip install ...';         pip --version;  Write-Host 'Complete.'
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 98020bf1cb1f
2020-10-14 13:22:38+0000 [-] Step 17/28 : RUN pip install buildbot-worker
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> d95298870b0e
2020-10-14 13:22:38+0000 [-] Step 18/28 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-2004
2020-10-14 13:22:38+0000 [-]  ---> e43265109b05
2020-10-14 13:22:38+0000 [-] Step 19/28 : SHELL [ "pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';" ]
2020-10-14 13:22:38+0000 [-]  ---> Using cache
2020-10-14 13:22:38+0000 [-]  ---> 0a7ee4577d65
2020-10-14 13:22:38+0000 [-] Step 20/28 : COPY --from=INSTALLER [ "C:/MinGit", "C:/git" ]
2020-10-14 13:22:39+0000 [-]  ---> Using cache
2020-10-14 13:22:39+0000 [-]  ---> 1213125588be
2020-10-14 13:22:39+0000 [-] Step 21/28 : COPY --from=INSTALLER [ "C:/OpenSSH-Win64", "C:/openssh" ]
2020-10-14 13:22:39+0000 [-]  ---> Using cache
2020-10-14 13:22:39+0000 [-]  ---> 99eb8e3c7dc5
2020-10-14 13:22:39+0000 [-] Step 22/28 : COPY --from=INSTALLER [ "C:/Python", "C:/Python" ]
2020-10-14 13:22:39+0000 [-]  ---> Using cache
2020-10-14 13:22:40+0000 [-]  ---> 6192e3414209
2020-10-14 13:22:40+0000 [-] Step 23/28 : RUN New-Item -Path $HOME/.ssh/ -ItemType "Directory"
2020-10-14 13:22:40+0000 [-]  ---> Using cache
2020-10-14 13:22:40+0000 [-]  ---> 6d1dfaf2c181
2020-10-14 13:22:40+0000 [-] Step 24/28 : COPY --from=INSTALLER [ "C:/known_hosts", "C:/Users/ContainerUser/.ssh/known_hosts" ]
2020-10-14 13:22:40+0000 [-]  ---> Using cache
2020-10-14 13:22:40+0000 [-]  ---> 70e1de2bcd90
2020-10-14 13:22:40+0000 [-] Step 25/28 : COPY --from=INSTALLER [ "C:/clone_key", "C:/Users/ContainerUser/.ssh/id_rsa" ]
2020-10-14 13:22:40+0000 [-]  ---> Using cache
2020-10-14 13:22:40+0000 [-]  ---> e164aeae1ce5
2020-10-14 13:22:40+0000 [-] Step 26/28 : WORKDIR C:/Users/ContainerUser
2020-10-14 13:22:40+0000 [-]  ---> Using cache
2020-10-14 13:22:40+0000 [-]  ---> 98825afb5e04
2020-10-14 13:22:40+0000 [-] Step 27/28 : RUN setx Path "$Env:Path`;C:\git\cmd`;C:\openssh`;C:\Python`;C:\Python\Scripts";     setx GIT_SSH "C:\openssh\ssh.exe";     echo 'buildbot-worker cre
ate-worker . \"${Env:BUILDMASTER}:${Env:BUILDMASTER_PORT}\" \"$Env:WORKERNAME\" \"$Env:WORKERPASS\";' >> start.ps1;     echo 'Start-Process buildbot-worker -Wait -ArgumentList \"start\",\"--n
odaemon\",\".\"' >> start.ps1;
2020-10-14 13:22:40+0000 [-]  ---> Using cache
2020-10-14 13:22:40+0000 [-]  ---> 36b8fd361026
2020-10-14 13:22:40+0000 [-] Step 28/28 : ENTRYPOINT [ "pwsh", "start.ps1" ]
2020-10-14 13:22:41+0000 [-]  ---> Running in 5d807531f500
2020-10-14 13:22:41+0000 [-]  ---> 206f274e4ab7
2020-10-14 13:22:41+0000 [-] Successfully built 206f274e4ab7
2020-10-14 13:22:41+0000 [-] Successfully tagged nano2004-netcore-3_1_140156726302272_image:latest
2020-10-14 13:22:42+0000 [-] Container created, Id: e0e848...
2020-10-14 13:22:46+0000 [-] Container started
2020-10-14 13:22:57+0000 [Broker,0,10.0.7.1] worker 'nano2004-netcore-3_1' attaching from IPv4Address(type='TCP', host='10.0.7.1', port=8308)
2020-10-14 13:22:57+0000 [Broker,0,10.0.7.1] Got workerinfo from 'nano2004-netcore-3_1'
2020-10-14 13:22:57+0000 [-] bot attached
2020-10-14 13:22:57+0000 [Broker,0,10.0.7.1] Worker nano2004-netcore-3_1 attached to myproject-win
2020-10-14 13:22:57+0000 [Broker,0,10.0.7.1] Worker nano2004-netcore-3_1 substantiated \o/
2020-10-14 13:22:57+0000 [Broker,0,10.0.7.1] Firing nano2004-netcore-3_1 substantiation deferred with success
2020-10-14 13:22:57+0000 [-] starting build <Build myproject-win number:1 results:success>.. pinging the worker <LatentWorkerForBuilder builder='myproject-win' worker='nano2004-netcore-3_1' state
=BUILDING>
2020-10-14 13:22:57+0000 [-] sending ping
2020-10-14 13:22:57+0000 [Broker,0,10.0.7.1] ping finished: success
2020-10-14 13:22:57+0000 [-] ShellCommand.startCommand(cmd=<RemoteShellCommand '['pwsh', '/?']'>)
2020-10-14 13:22:57+0000 [-]   cmd.args = {'workdir': 'build', 'env': None, 'want_stdout': 1, 'want_stderr': 1, 'logfiles': {}, 'timeout': 1200, 'maxTime': None, 'sigtermTime': None, 'usePTY'
: None, 'logEnviron': True, 'initial_stdin': None}
2020-10-14 13:22:57+0000 [-] <RemoteShellCommand '['pwsh', '/?']'>: RemoteCommand.run [0]
2020-10-14 13:22:57+0000 [-] command '['pwsh', '/?']' in dir 'build'
2020-10-14 13:22:58+0000 [-] BuildStep.failed; traceback follows
        Traceback (most recent call last):
          File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 501, in errback
            self._startRunCallbacks(fail)
          File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1475, in gotResult
            _inlineCallbacks(r, g, status)
        --- <exception caught here> ---
          File "/usr/lib/python3.8/site-packages/buildbot/process/buildstep.py", line 573, in startStep
            self.results = yield self.run()
          File "/usr/lib/python3.8/site-packages/buildbot/process/buildstep.py", line 732, in run
            results = yield self._start_deferred
          File "/usr/lib/python3.8/site-packages/buildbot/process/buildstep.py", line 925, in runCommand
            res = yield command.run(self, self.remote, self.build.builder.name)
          File "/usr/lib/python3.8/site-packages/buildbot/process/remotecommand.py", line 146, in _finished
            yield self.remoteComplete(failure)
          File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/usr/lib/python3.8/site-packages/buildbot/process/buildstep.py", line 732, in run
            results = yield self._start_deferred
          File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/lib/python3.8/site-packages/buildbot/process/buildstep.py", line 925, in runCommand
            res = yield command.run(self, self.remote, self.build.builder.name)
          File "/usr/lib/python3.8/site-packages/buildbot/process/remotecommand.py", line 146, in _finished
            yield self.remoteComplete(failure)
        buildbot.process.remotecommand.RemoteException: b'buildbot_worker.exceptions.AbandonChain': -1
        Traceback (most recent call last):
        Failure: buildbot_worker.exceptions.AbandonChain: -1


2020-10-14 13:23:00+0000 [-] releaseLocks(ShellCommand(command=['pwsh', '/?'])): []
2020-10-14 13:23:00+0000 [-]  step 'shell' complete: exception (["'pwsh /?' (exception)"])
2020-10-14 13:23:00+0000 [-]  <Build myproject-win number:1 results:exception>: build finished
2020-10-14 13:23:00+0000 [-] nano2004-netcore-3_1 has been put in quarantine for 10s
2020-10-14 13:23:00+0000 [-] releaseLocks(<DockerLatentWorker 'nano2004-netcore-3_1'>): []
2020-10-14 13:23:00+0000 [-] disconnecting old worker nano2004-netcore-3_1 now
2020-10-14 13:23:00+0000 [-] waiting for worker to finish disconnecting
2020-10-14 13:23:00+0000 [-] insubstantiating worker <DockerLatentWorker 'nano2004-netcore-3_1'>
2020-10-14 13:23:00+0000 [Broker,0,10.0.7.1] Worker.detached(nano2004-netcore-3_1)
2020-10-14 13:23:00+0000 [Broker,0,10.0.7.1] releaseLocks(<DockerLatentWorker 'nano2004-netcore-3_1'>): []
2020-10-14 13:23:00+0000 [-] Stopping container e0e848...
```

## Resources
dockerfile for nano2004-netcore-3_1
```dockerfile
FROM mcr.microsoft.com/windows/servercore:2004 as INSTALLER
SHELL [ "powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';" ]

RUN Invoke-WebRequest -Uri https://curl.haxx.se/windows/dl-7.72.0_5/curl-7.72.0_5-win64-mingw.zip -outfile /curl.zip; \
    Expand-Archive /curl.zip -DestinationPath /; \
    Move-Item curl-7.72.0-win64-mingw curl

RUN Invoke-WebRequest -Uri https://github.com/git-for-windows/git/releases/download/v2.28.0.windows.1/MinGit-2.28.0-64-bit.zip -outfile /MinGit.zip; \
    Expand-Archive /MinGit.zip -DestinationPath /MinGit;

RUN Invoke-WebRequest -Uri https://github.com/PowerShell/Win32-OpenSSH/releases/download/v8.1.0.0p1-Beta/OpenSSH-Win64.zip -outfile /openssh.zip; \
    Expand-Archive /openssh.zip -DestinationPath /;

# RUN {CURL_LINE_WIN}/known_hosts -o known_hosts; \
#    {CURL_LINE_WIN}/clone_key -o clone_key

RUN Invoke-WebRequest https://aka.ms/vs/16/release/vs_buildtools.exe -outfile /vs_buildtools.exe
RUN /vs_buildtools.exe --quiet --wait --norestart --nocache \
    --installPath C:\BuildTools \
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
    --add Microsoft.VisualStudio.Component.VC.v141.x86.x64

RUN /vs_buildtools.exe --quiet --wait --norestart --nocache \
    --installPath C:\BuildTools \
    --add Microsoft.VisualStudio.Component.Windows10SDK.18362

ENV PYTHON_VERSION 3.8.6
ENV PYTHON_RELEASE 3.8.6

RUN $url = ('https://www.python.org/ftp/python/{0}/python-{1}-amd64.exe' -f $env:PYTHON_RELEASE, $env:PYTHON_VERSION); \
	Write-Host ('Downloading {0} ...' -f $url); \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Uri $url -OutFile 'python.exe'; \
	Write-Host 'Installing ...'; \
	Start-Process python.exe -Wait \
		-ArgumentList @( \
			'/quiet', \
			'InstallAllUsers=1', \
			'TargetDir=C:\Python', \
			'PrependPath=1', \
			'Shortcuts=0', \
			'Include_doc=0', \
			'Include_pip=0', \
			'Include_test=0' \
		); \
	$env:PATH = [Environment]::GetEnvironmentVariable('PATH', [EnvironmentVariableTarget]::Machine); \
	Write-Host 'Verifying install ...'; \
	Write-Host '  python --version'; python --version; \
	Write-Host 'Removing ...'; \
	Remove-Item python.exe -Force; \
	Write-Host 'Complete.'

# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
ENV PYTHON_PIP_VERSION 20.2.3
# https://github.com/pypa/get-pip
ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py
ENV PYTHON_GET_PIP_SHA256 6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c

RUN Write-Host ('Downloading get-pip.py ({0}) ...' -f $env:PYTHON_GET_PIP_URL); \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Uri $env:PYTHON_GET_PIP_URL -OutFile 'get-pip.py'; \
	Write-Host ('Verifying sha256 ({0}) ...' -f $env:PYTHON_GET_PIP_SHA256); \
	if ((Get-FileHash 'get-pip.py' -Algorithm sha256).Hash -ne $env:PYTHON_GET_PIP_SHA256) { \
		Write-Host 'FAILED!'; \
		exit 1; \
	}; \
	Write-Host ('Installing pip=={0} ...' -f $env:PYTHON_PIP_VERSION); \
	python get-pip.py \
		--disable-pip-version-check \
		--no-cache-dir \
		('pip=={0}' -f $env:PYTHON_PIP_VERSION) \
	; \
	Remove-Item get-pip.py -Force; \
	Write-Host 'Verifying pip install ...'; \
	pip --version; \
	Write-Host 'Complete.'

RUN pip install buildbot-worker

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-2004
SHELL [ "pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';" ]

COPY --from=INSTALLER [ "C:/MinGit", "C:/git" ]
COPY --from=INSTALLER [ "C:/OpenSSH-Win64", "C:/openssh" ]
COPY --from=INSTALLER [ "C:/Python", "C:/Python" ]

RUN New-Item -Path $HOME/.ssh/ -ItemType "Directory"
# COPY --from=INSTALLER [ "C:/known_hosts", "C:/Users/ContainerUser/.ssh/known_hosts" ]
# COPY --from=INSTALLER [ "C:/clone_key", "C:/Users/ContainerUser/.ssh/id_rsa" ]

WORKDIR C:/Users/ContainerUser

RUN setx Path "$Env:Path`;C:\git\cmd`;C:\openssh`;C:\Python`;C:\Python\Scripts"; \
    setx GIT_SSH "C:\openssh\ssh.exe"; \
    echo 'buildbot-worker create-worker . \"${Env:BUILDMASTER}:${Env:BUILDMASTER_PORT}\" \"$Env:WORKERNAME\" \"$Env:WORKERPASS\";' >> start.ps1; \
    echo 'Start-Process buildbot-worker -Wait -ArgumentList \"start\",\"--nodaemon\",\".\"' >> start.ps1;

ENTRYPOINT [ "pwsh", "start.ps1" ]
```

**Comment by tgckpg** [comment]
Fixed it.
* Need to use servercore instead of nanoserver.
* `pip install pywin32`

### Diagnostics
* twisted requires `pywin32` to be installed. ( `pip install pywin32` )
* twisted cannot be run on nanoserver since it imports win32api via pywin32

### Stack trace
```
Traceback (most recent call last):
  File "c:\\python\\lib\\site-packages\\buildbot_worker\\runprocess.py", line 453, in start
    self._startCommand()
  File "c:\\python\\lib\\site-packages\\buildbot_worker\\runprocess.py", line 577, in _startCommand
    self.process = self._spawnProcess(
  File "c:\\python\\lib\\site-packages\\buildbot_worker\\runprocess.py", line 611, in _spawnProcess
    return self._spawnAsBatch(processProtocol, executable, args, env,
  File "c:\\python\\lib\\site-packages\\buildbot_worker\\runprocess.py", line 649, in _spawnAsBatch
    return reactor.spawnProcess(processProtocol, executable, argv, env,
  File "c:\\python\\lib\\site-packages\\twisted\\internet\\posixbase.py", line 355, in spawnProcess
    raise NotImplementedError(
NotImplementedError: spawnProcess not available since pywin32 is not installed.
[SOME_BINARY_DATA]
Traceback (most recent call last):
Failure: buildbot_worker.exceptions.AbandonChain: -1
[SOME_BINARY_DATA]
```
After installing `pywin32`
```
Traceback (most recent call last):
  File "c:\\python\\lib\\site-packages\\buildbot_worker\\runprocess.py", line 453, in start
    self._startCommand()
  File "c:\\python\\lib\\site-packages\\buildbot_worker\\runprocess.py", line 577, in _startCommand
    self.process = self._spawnProcess(
  File "c:\\python\\lib\\site-packages\\buildbot_worker\\runprocess.py", line 611, in _spawnProcess
    return self._spawnAsBatch(processProtocol, executable, args, env,
  File "c:\\python\\lib\\site-packages\\buildbot_worker\\runprocess.py", line 649, in _spawnAsBatch
    return reactor.spawnProcess(processProtocol, executable, argv, env,
  File "c:\\python\\lib\\site-packages\\twisted\\internet\\posixbase.py", line 352, in spawnProcess
    fromtwisted.internet._dumbwin32proc import Process
  File "c:\\python\\lib\\site-packages\\twisted\\internet\\_dumbwin32proc.py", line 15, in <module>
    import win32api
ImportError: DLL load failed while importing win32api: The specified procedure could not be found.
[SOME_BINARY_DATA]
Traceback (most recent call last):
Failure: buildbot_worker.exceptions.AbandonChain: -1
[SOME_BINARY_DATA]
```

**Comment by p12tic** [comment]
@tgckpg Thanks a lot for posting your findings. I've improved the way the worker reports errors in #5603 so that it would easier to figure out the reason for the failure next time.
