### ISSUE TITLE
Exception after aborting a Build job

### ISSUE THREAD

**Issue by kfriedberger** [buildbot/buildbot#5655]
We are using Builbot 2.8.4 and found a few exceptions.

#### Our setting:
We have about 20 parallel buildjobs on one master with one worker. Each job consists of the same sequence of 10 steps.
One step (step 4 of 10) uses a common/global workerlock to limit a ressource-expensive execution within this step to only 8 parallel running steps. Other steps simply wait until the workerlock is available. That works as expected.

#### When the exception occurs:
We recently had a few long running (very slow, but finally finishing) expensive steps (i.e., the lock-limited step from above) and we needed to abort several of the parallel steps that were waiting for the workerlock. Aborting worked well and the jobs terminates instantly.
We also had to terminate several (about 50?) pending build requests and cancelled them via the webinterface. Cancellation works well and the pending requests disappeared from the list.
We let the already running buildjobs run further and waited for their results.
And those buildjobs crashed when the expensive step finished some hours later.

Most of those (very slow) jobs, that were running when we aborted or cancelled the other jobs, failed with the following exception, directly after executing the lock-limited step, i.e., the build jobs did not execute the remaining steps:
<pre>
2020-12-02 08:22:15+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/local/lib/python3.6/dist-packages/buildbot/process/buildstep.py", line 625, in startStep
	    self.releaseLocks()
	  File "/usr/local/lib/python3.6/dist-packages/buildbot/process/buildstep.py", line 776, in releaseLocks
	    assert self.stopped
	builtins.AssertionError:
</pre>

**Comment by p12tic** [comment]
@kfriedberger Thanks a lot for the bug report.

**Comment by kfriedberger** [comment]
I hope, the description is good enough for finding the bug.
If was really annoying to first cleanup all pending build requests and then see the already running one fail. :-)
If there are any questions, I will try to help.
