### ISSUE TITLE
Exception sometimes thrown by steps.MsBuild14

### ISSUE THREAD

**Issue by jodogne** [buildbot/buildbot#5698]
Hello,

Since my upgrade to BuildBot 1.9.2, if using the `MsBuild14` step to build a Visual Studio 2015 solution, I sometimes (not always) obtain the following trace in the `twistd.log`:

```
2020-12-15 10:53:20+0100 [-] when trying to finish a log
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 501, in errback
	    self._startRunCallbacks(fail)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python3.5/dist-packages/buildbot/process/log.py", line 203, in finish
	    yield super().finish()
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/local/lib/python3.5/dist-packages/buildbot/process/log.py", line 115, in finish
	    self._had_errors = len(self.subPoint.pop_exceptions()) > 0
	builtins.TypeError: object of type 'NoneType' has no len()
	
2020-12-15 10:53:20+0100 [-] releaseLocks(MsBuild14(env={'PreferredToolArchitecture': 'x64'}, workdir='build/Build', projectfile='OrthancMySQL.sln', config='Release', platform='x64')): []
2020-12-15 10:53:20+0100 [-]  step 'compile' complete: exception (['built solution for Release|x64'])
2020-12-15 10:53:20+0100 [-]  <Build DB mainline - MySQL - VC2015-64 Release number:699 results:exception>: build finished
```

The build is then aborted and tagged with the `EXCEPTION` tag.  When I look at the `stdio` stream from Visual Studio, the build is reported as a success, and the binaries are properly generated:

```
    2551 Warning(s)
    0 Error(s)
Time Elapsed 00:07:53.31
program finished with exit code 0
elapsedTime=475.270000
```

This issue might be related to a large number of warnings being generated by Visual Studio, which seems to take long time to be parsed from `stdio` to `warnings` (this parsing seems to last more than 1 minute, which I find highly suspicious), although I am unsure about this. This issue didn't occur on releases 1.8.x of BuildBot.

Thanks in advance for your help, and thanks for your hard work on BuildBot!

**Comment by p12tic** [comment]
Thanks a lot for the bug report. It seems that it's an issue with general Buildbot logs infrastructure as the error is not coming from the step itself.

**Comment by senyai** [comment]
Are you sure? I think this particular error is caused by oversight in 571a54916f commit. It's `self._got_exceptions = []` in `__init__`, but `self._got_exceptions = None` in `pop_exceptions` method. I wanted to write a fix, but have no idea how to write a test for this issue.

**Comment by jodogne** [comment]
Hello, thanks for your feedback. I see that BuildBot to 1.9.4 is now released. I'm giving another try with this new version in order to see whether this makes the issue vanish on my setup, and I'll keep you updated.

**Comment by jodogne** [comment]
I confirm that the same issue is still present after upgrading to 1.9.4:
```
2020-12-28 01:37:46+0100 [Broker,3,185.35.172.226] <RemoteShellCommand ''"%VCENV_BAT%" x86 && msbuild "OrthancMySQL.sln" /p:Configuration="Release" /p:Platform="x64" /maxcpucount /t:Rebuild''> rc=0
2020-12-28 01:41:23+0100 [-] when trying to finish a log
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 501, in errback
	    self._startRunCallbacks(fail)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python3.5/dist-packages/buildbot/process/log.py", line 203, in finish
	    yield super().finish()
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/local/lib/python3.5/dist-packages/buildbot/process/log.py", line 115, in finish
	    self._had_errors = len(self.subPoint.pop_exceptions()) > 0
	builtins.TypeError: object of type 'NoneType' has no len()
	
2020-12-28 01:41:24+0100 [-] releaseLocks(MsBuild14(platform='x64', projectfile='OrthancMySQL.sln', env={'PreferredToolArchitecture': 'x64'}, workdir='build/Build', config='Release')): []
2020-12-28 01:41:24+0100 [-]  step 'compile' complete: exception (['built solution for Release|x64'])
2020-12-28 01:41:24+0100 [-]  <Build DB mainline - MySQL - VC2015-64 Release number:719 results:exception>: build finished
```
Note that I use other types of builders (gcc, clang, OS X, Visual Studio 2008), but this problem only occurs with `steps.MsBuild14`.

**Comment by senyai** [comment]
Got the same error in 3.1.0. @p12tic are you sure that `_got_exceptions` https://github.com/buildbot/buildbot/blob/571a54916ff186afa345d501a5ab9e66b2ffb439/master/buildbot/util/subscription.py#L63 should become `None`, and not `[]`?

**Comment by Gugli** [comment]
Additionally : I reproduce these exceptions multiple times a day, and it's easy for me to test any patch, or log anything in my instance, but I'm not familiar enough with python and buildbot to solve that bug alone.

**Comment by p12tic** [comment]
The new log message has much more information. @Gugli could you try https://github.com/buildbot/buildbot/pull/6274 ? Thanks!

**Comment by p12tic** [comment]
@senyai: Addressed in #6275.

**Comment by Gugli** [comment]
> 
> 
> The new log message has much more information. @Gugli could you try #6274 ? Thanks!

I've updated vstudio.py on the master, restarted buildbot, and I tried to restart a dozen of varied builds. So far no error.

I'll keep the new code running, and I'll keep you informed if the error comes back during the week (I'll have more "natural-looking" builds during weekdays). But to me it seems the bug is fixed :)

Thanks for the quick fix !

**Comment by YngveNPettersen** [comment]
FYI, I am seeing the Log.finish "Did you maybe forget to yield the method?" exception in 3.7.0 when called from BuildStep.addCompleteLog , and I just confirmed that we also got the exception in v3.3.0. AFAIK the log names are unique for each added.
