### ISSUE TITLE
Error with tuplematch when using GitHubStatusPush

### ISSUE THREAD

**Issue by umar456** [buildbot/buildbot#5764]
I am getting the following error when the status is updated on a GitHub commit using GitHubStatusPush

```
buildbot_1           | 2021-01-21 13:30:37+0000 [WampWebSocketClientProtocol,client] Got exception when handling reporter events
buildbot_1           | 	Traceback (most recent call last):
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
buildbot_1           | 	    return _cancellableInlineCallbacks(gen)
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
buildbot_1           | 	    _inlineCallbacks(None, g, status)
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
buildbot_1           | 	    result = g.send(result)
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/buildbot/reporters/base.py", line 182, in _got_event
buildbot_1           | 	    log.err(e, 'Got exception when handling reporter events')
buildbot_1           | 	--- <exception caught here> ---
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/buildbot/reporters/base.py", line 174, in _got_event
buildbot_1           | 	    if self._does_generator_want_key(g, key):
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/buildbot/reporters/base.py", line 165, in _does_generator_want_key
buildbot_1           | 	    if util.tuplematch.matchTuple(key, filter):
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/twisted/python/deprecate.py", line 512, in __getattribute__
buildbot_1           | 	    value = getattr(state._module, name)
buildbot_1           | 	builtins.AttributeError: module 'buildbot.util' has no attribute 'tuplematch'
```
This is using the official v2.10 docker image from dockerhub.

**Comment by p12tic** [comment]
Fixed in #5765.
