### ISSUE TITLE
_matches_any_tag missing from BuildStartEndStatusGenerator

### ISSUE THREAD

**Issue by umar456** [buildbot/buildbot#5766]
The [_matches_any_tag function](https://github.com/buildbot/buildbot/blob/e630745771a8bd03a2084d03ea8e43547d3dff4b/master/buildbot/reporters/generators/build.py#L82) is missing from the BuildStartEndStatusGenerator. This causes failures when you try to filter the builders using the tag with GitHubStatusPush and this generator.

```
buildbot_1           | 2021-01-21 13:51:23+0000 [-] Got exception when handling reporter events
buildbot_1           | 	Traceback (most recent call last):
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1475, in gotResult
buildbot_1           | 	    _inlineCallbacks(r, g, status)
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
buildbot_1           | 	    result = result.throwExceptionIntoGenerator(g)
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
buildbot_1           | 	    return g.throw(self.type, self.value, self.tb)
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/buildbot/reporters/base.py", line 183, in _got_event
buildbot_1           | 	    log.err(e, 'Got exception when handling reporter events')
buildbot_1           | 	--- <exception caught here> ---
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/buildbot/reporters/base.py", line 176, in _got_event
buildbot_1           | 	    report = yield g.generate(self.master, self, key, msg)
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
buildbot_1           | 	    result = g.send(result)
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/buildbot/reporters/generators/build.py", line 119, in generate
buildbot_1           | 	    if not self.is_message_needed_by_props(build):
buildbot_1           | 	  File "/usr/lib/python3.8/site-packages/buildbot/reporters/generators/utils.py", line 104, in is_message_needed_by_props
buildbot_1           | 	    if self.tags is not None and not self._matches_any_tag(builder['tags']):
buildbot_1           | 	builtins.AttributeError: 'BuildStartEndStatusGenerator' object has no attribute '_matches_any_tag'

```

This output is from the official docker v2.10

**Comment by p12tic** [comment]
Thanks for the bug report! This will be fixed in #5771.
