### ISSUE TITLE
LogObserver triggers StopIteration exceptions

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbot/buildbot#5770]
We have a steps.ShellCommandNewStyle subclass that adds logobserver.LineConsumerLogObserver objects for stdio and stderr in order to process output from our tests, and to create attachment logs for the step to make the information more easily accessible.

However, in a large number of cases after the recent upgrade to v2.10, build steps have failed with "Exception", which also terminates the rest of the testrun. Inspecting logs show that the exception was StopIteration, in at least several cases raised from LineConsumerLogObserver.headerLineReceived().

AFAICT the reason is that LogObserver.gotData() will call self.finishReceived() when the input data is a "None" object, but there are still data pending, and when they get added (primary suspects are the "program finished with exit code" and "elapsedTime" lines at the end of the run's log) the generator created by LineConsumerLogObserver have been closed, resulting in a StopIteration exception being thrown.

AFAICT this also happened in v2.7, but it was not treated as a fatal error for the run at that time, this have apparently changed since then.

I have so far not been able to determine why a "None" object is passed in to gotData(), and where it comes from.

**Comment by tardyp** [comment]
Hi Yngve,

With all due respect, I would appreciate a bit more structure in this bug report. In here, we can clearly see confusion, and "thinking out loud" expression. This would help us to help you if we could have in the first place:

- actual exception trace before 2.7 and after 2.10
- cleaned up custom shell command code that we can review

It is much easier for us to reason on actual code and error log rather than on english text.

thanks!

**Comment by YngveNPettersen** [comment]
Hmmm .... Actually ....  checking for the exceptions a different way (from the start of the log file, not the end) I discovered that the processing function on my side was throwing an exception (too many parameters into a called function, due to extra field separation characters in to log output and a bug in the processing. Ooops!).

However, that **still** leaves a problem with gotData()  (or its callers), because it continues feeding data into a log processor that have indicated something went wrong and has not been handled. It should stop feeding data immediately if there is an exception.

AFAICT the StopIteration exception is repeated multiple time for the same log (which, in combination with lots of activity logged for the other builders, is probably why I did not see the real exception when looking at the **last** exception, assuming that there would be only a single exception for the log file and step).  This is also a further indication that gotData() (or its callers) continues to funnel data into a processor function that is no longer running, thus triggering further exceptions, unrelated to the original failure.

It might be an idea to add a log section to the step about which exceptions were logged when marking the step as failing due to an exception. That would make it more obvious what happened and what went wrong, and it is done for certain other serverside exceptions.

The 2.10 callstack is below. I no longer have the 2.7 logs (the oldest log is from two days after the upgrade), but the look of the log was the same IIRC (only difference is that the class inherited from the old ShellCommand class in the 2.,7 version).

```
2021-01-23 00:35:24+0000 [Broker (TLSMemoryBIOProtocol),1.2.3.4] while invoking callback <bound method LogObserver.gotData of <buildbot.process.logobserver.LineConsumerLogObserver object at 0x7fab843a07f0>> to <SubscriptionPoint ''stdio' log'>
        Traceback (most recent call last):
          File "sandbox/lib/python3.6/site-packages/buildbot/process/log.py", line 187, in addStdout
            return self._getLbf('o').append(text)
          File "sandbox/lib/python3.6/site-packages/buildbot/util/lineboundaries.py", line 73, in append
            return self.callback(text)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/log.py", line 176, in wholeLines
            self.subPoint.deliver(stream, lines)
          File "sandbox/lib/python3.6/site-packages/buildbot/util/subscription.py", line 51, in deliver
            self._notify_delivery_exception(e, sub)
        --- <exception caught here> ---
          File "sandbox/lib/python3.6/site-packages/buildbot/util/subscription.py", line 44, in deliver
            d = sub.callback(*args, **kwargs)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/logobserver.py", line 35, in gotData
            self.outReceived(data)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/logobserver.py", line 78, in outReceived
            self._lineReceived(data, self.stdoutDelimiter, self.outLineReceived)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/logobserver.py", line 75, in _lineReceived
            funcReceived(line)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/logobserver.py", line 117, in outLineReceived
            self.feed(('o', line))
        builtins.StopIteration:

```

The relevant lines for the original exception that ended the processing function is:

```
2021-01-23 17:03:47+0000 [Broker (TLSMemoryBIOProtocol),1.2.3.4] while invoking callback <bound method LogObserver.gotData of <buildbot.process.logobserver.LineConsumerLogObserver object at 0x7fab3a193780>> to <SubscriptionPoint ''stdio' log'>
        Traceback (most recent call last):
          File "sandbox/lib/python3.6/site-packages/buildbot/process/log.py", line 187, in addStdout
            return self._getLbf('o').append(text)
          File "sandbox/lib/python3.6/site-packages/buildbot/util/lineboundaries.py", line 73, in append
            return self.callback(text)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/log.py", line 176, in wholeLines
            self.subPoint.deliver(stream, lines)
          File "sandbox/lib/python3.6/site-packages/buildbot/util/subscription.py", line 51, in deliver
            self._notify_delivery_exception(e, sub)
        --- <exception caught here> ---
          File "lib/python3.6/site-packages/buildbot/util/subscription.py", line 44, in deliver
            d = sub.callback(*args, **kwargs)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/logobserver.py", line 35, in gotData
            self.outReceived(data)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/logobserver.py", line 78, in outReceived
            self._lineReceived(data, self.stdoutDelimiter, self.outLineReceived)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/logobserver.py", line 75, in _lineReceived
            funcReceived(line)
          File "sandbox/lib/python3.6/site-packages/buildbot/process/logobserver.py", line 117, in outLineReceived
            self.feed(('o', line))
# Internal callstack, exception infor

```

**Comment by tardyp** [comment]
So to summarise, if a LineConsumerLogObserver function crash at some point of the observation, the subsequent logline pushes will also except, because the generator is already exited.

I am not sure exactly what to do in this case.

- We could ignore the exception or just log it, and don't make the step fail.
- We could make the step except with clearer info that the generator is buggy


Perhaps you can change the implementation around here:

https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/logobserver.py#L114

to call tryfeed() instead of feed()

```python
def tryfeed(self, f):
    if self.is_broken:
         return
    try:
        self.feed(f)
    except Exception e:
        self.is_broken = True
        self.step.addLogWithException(e, "logconsumer_exception")
```

**Comment by YngveNPettersen** [comment]
In this particular case, the fix in our code was rather easy, and was deployed a few minutes ago.

My suggestion would be to use the second option, reporting a step exception with call stack information as part of the reported info. Just to be on the safe side, this should be used for all LogObserver classes, not just LineConsumerLogObserver.

**Comment by tardyp** [comment]
only LineConsumerLogObserver uses the generator trickm so only that one has this issue.

**Comment by YngveNPettersen** [comment]
Yes, but other non-generator observers/consumers could also throw exceptions, so the base class should consider one that do throw an exception as broken, and report the exception in the step logs.

**Comment by p12tic** [comment]
Indeed, we should improve exception handling with better error messages. Anything that leads to less user time wasted on issues like this is good.
