### ISSUE TITLE
gitpoller: exceptions must be classes or instances deriving from BaseException, not type

### ISSUE THREAD

**Issue by aliceinwire** [buildbot/buildbot#5794]
```
buildbot_1               | 2021-02-13 09:28:45+0000 [-] trying to poll branch refs/heads/4.1 of https://github.com/GKernelCI/linux-patches.git
buildbot_1               |      Traceback (most recent call last):
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
buildbot_1               |          current.result = callback(current.result, *args, **kw)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1475, in gotResult
buildbot_1               |          _inlineCallbacks(r, g, status)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
buildbot_1               |          result = result.throwExceptionIntoGenerator(g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |      --- <exception caught here> ---
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 220, in poll
buildbot_1               |          yield self._process_changes(revs[branch], branch)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
buildbot_1               |          result = result.throwExceptionIntoGenerator(g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 311, in _process_changes
buildbot_1               |          results = yield self._dovccmd('log', revListArgs, path=self.workdir)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
buildbot_1               |          result = result.throwExceptionIntoGenerator(g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 405, in _dovccmd
buildbot_1               |          stdout = yield self._dovccmdImpl(command, args, path, None)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
buildbot_1               |          result = result.throwExceptionIntoGenerator(g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |      builtins.TypeError: exceptions must be classes or instances deriving from BaseException, not type
```

**Comment by aliceinwire** [comment]
gitpoller crash with GitHubPullRequestPoller enabled
```
+sources.append(changes.GitHubPullrequestPoller(
+    owner='gentoo',
+    branches=None,
+    category='gentoo-pull',
+    repo='gentoo'))
```

**Comment by p12tic** [comment]
@aliceinwire Thanks a lot for the bug report. I've looked into the code and didn't see any obvious issues so far. This will need deeper investigation.

**Comment by aliceinwire** [comment]
we are still getting this errors
```
buildbot_1               | 2021-05-28 12:21:32+0000 [-] while processing changes for a911184b29e564f14aed7c54bc633f8c5a6294c8 refs/heads/master
buildbot_1               |      Traceback (most recent call last):
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 517, in errback
buildbot_1               |          self._startRunCallbacks(fail)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 580, in _startRunCallbacks
buildbot_1               |          self._runCallbacks()
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 662, in _runCallbacks
buildbot_1               |          current.result = callback(current.result, *args, **kw)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1514, in gotResult
buildbot_1               |          current_context.run(_inlineCallbacks, r, g, status)
buildbot_1               |      --- <exception caught here> ---
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
buildbot_1               |          result = current_context.run(result.throwExceptionIntoGenerator, g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 405, in _dovccmd
buildbot_1               |          stdout = yield self._dovccmdImpl(command, args, path, None)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
buildbot_1               |          result = current_context.run(result.throwExceptionIntoGenerator, g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |      builtins.TypeError: exceptions must be classes or instances deriving from BaseException, not type
buildbot_1               | 
buildbot_1               | 2021-05-28 12:21:32+0000 [-] trying to poll branch refs/heads/master of https://github.com/gentoo/gentoo.git
buildbot_1               |      Traceback (most recent call last):
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 662, in _runCallbacks
buildbot_1               |          current.result = callback(current.result, *args, **kw)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1514, in gotResult
buildbot_1               |          current_context.run(_inlineCallbacks, r, g, status)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
buildbot_1               |          result = current_context.run(result.throwExceptionIntoGenerator, g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |      --- <exception caught here> ---
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 220, in poll
buildbot_1               |          yield self._process_changes(revs[branch], branch)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
buildbot_1               |          result = current_context.run(g.send, result)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 356, in _process_changes
buildbot_1               |          failures[0].raiseException()
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 475, in raiseException
buildbot_1               |          raise self.value.with_traceback(self.tb)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
buildbot_1               |          result = current_context.run(result.throwExceptionIntoGenerator, g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 405, in _dovccmd
buildbot_1               |          stdout = yield self._dovccmdImpl(command, args, path, None)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
buildbot_1               |          result = current_context.run(result.throwExceptionIntoGenerator, g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |      builtins.TypeError: exceptions must be classes or instances deriving from BaseException, not type
```

**Comment by aliceinwire** [comment]
the code is here: https://github.com/GKernelCI/GBuildbot

**Comment by aliceinwire** [comment]
@p12tic we are having problems where the gitpoller is usually crashing and I have to restart buildbot master manually

**Comment by p12tic** [comment]
@aliceinwire I will look into this this weekend.

**Comment by aliceinwire** [comment]
@p12tic thanks you! 
With the current deferred gitpoller I currently don't see this error anymore.

**Comment by p12tic** [comment]
@aliceinwire Turns out this is bug in Twisted's `getProcessOutputAndValue` function that we were using (I filed this as https://twistedmatrix.com/trac/ticket/10207). The new gitpoller implementation no longer uses `getProcessOutputAndValue` so we can call this bug fixed.

**Comment by aliceinwire** [comment]
@p12tic thanks you!

**Comment by aliceinwire** [comment]
closing this issue as solved from buildbot side
