### ISSUE TITLE
Failed to update "pending"

### ISSUE THREAD

**Issue by aliceinwire** [buildbot/buildbot#5818]
```
buildbot_1               | 2021-02-28 17:05:54+0000 [-] Failed to update "pending" for GKernelCI/linux-patches at a36c86ff7da449dcc400901d3e361d4042fd9f7e, context "buildbot/4.9:amd64", issue None. http 404, b'{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-commit-status"}'
buildbot_1               |      Traceback (most recent call last):
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
buildbot_1               |          current.result = callback(current.result, *args, **kw)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1475, in gotResult
buildbot_1               |          _inlineCallbacks(r, g, status)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
buildbot_1               |          result = g.send(result)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/reporters/github.py", line 277, in _send_impl
buildbot_1               |          log.err(
buildbot_1               |      --- <exception caught here> ---
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/reporters/github.py", line 263, in _send_impl
buildbot_1               |          raise Exception()
buildbot_1               |      builtins.Exception: 
```

**Comment by senyai** [comment]
Was an issue at GKernelCI/linux-patches created and then deleted?

**Comment by aliceinwire** [comment]
https://github.com/GKernelCI/linux-patches I don't think so. but we force pushed some tags.

**Comment by senyai** [comment]
I see now. Buildbot tried to fetch commit a36c86ff7da449dcc400901d3e361d4042fd9f7e that is no longer there. That exception can be ignored in that case. Should we use `log.msg` instead of `log.err` in 404 case?

**Comment by senyai** [comment]
Maybe it should stay `log.err` because we try to update the status.

**Comment by aliceinwire** [comment]
yes but it broke the puller in some cases. Definitely should not give error but work with the problem. like doing a clean fetch.

**Comment by aliceinwire** [comment]
```
 2021-03-03 12:10:26+0000 [-] Failed to update "pending" for GKernelCI/linux-patches at 5a353c5e6247e4d48b8679c204cbf331b072fa44, context "buildbot/4.4:arm64", issue None. http 404, b'{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-commit-status"}'
      Traceback (most recent call last):
        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
          current.result = callback(current.result, *args, **kw)
        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1475, in gotResult
          _inlineCallbacks(r, g, status)
        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
          result = g.send(result)
        File "/usr/lib/python3.8/site-packages/buildbot/reporters/github.py", line 277, in _send_impl
          log.err(
      --- <exception caught here> ---
        File "/usr/lib/python3.8/site-packages/buildbot/reporters/github.py", line 263, in _send_impl
          raise Exception()
      builtins.Exception: 

```
