### ISSUE TITLE
Lost connections not detected in some cases

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbot/buildbot#5832]
Recently we had a situation where the SSL certificate for the worker-manager TLS connections expired. Until the manager and each workers had been provided with the new (self-signed) certificate (could probably fix that), the workers could not connect to the manager.

However, somehow this created some kind of state in the manager's display of workers and their connected state indicated that the workers were still connected, even after restarting the workers, a manager restart, even a reboot of the manager machine. Some of the worker connected indications stayed in "connected" state for several days, despite those workers not being able to connect.

I don't really know how to reproduce this issue. It is possible that it will always happen if the certificate expires.

It seems to me that the "connected" flag (showing a green circle around the "master" number in the worker info, or the worker number in the builder page) is persistent across a restart of the manager. I have seen suggestions that this is the case when restarting the manager under normal circumstances, but the recovery is usually so quick that I am not sure I have seen what I think I saw.

For some reason, it looks like the connected flag is not reset in some cases just after a restart, at least until the the worker actually connects.

My guess is that the flag is not reset on start, and since no worker is connecting for that name, there is no status update. as the worker never connected, there is also no polling of the connected status. This can probably be fixed by resetting the flag as the worker is being added to the list of workers and associated with a builder and/or a master. The default state of a worker on start should be "Disconnected", no matter what the database says.

The worker flag I actually **would** prefer could be persistent, is the "Paused" flag. In some situations it is not desirable that the manager starts passing out jobs immediately, e.g. when it is necessary to check or the manager's or a worker's state before allowing it to start working. For example, the manager restart may be just the first of several restarts if it turns out that the update didn't accomplish quite what one wanted. When the workers are running jobs that can take 3-4 hours each, keeping the workers paused is important in such a situation.

**Comment by ynezz** [comment]
FYI we've switched to 3.0.0 yesterday and seeing probably similar issue, where workers get stuck in the worker_preparation step for several hours https://buildbot.openwrt.org/master/images/#/builders/53/builds/2 and https://buildbot.openwrt.org/master/images/#/builders/47/builds/2 and even explicit `Stop` of the build doesn't work - this is noop, nothing happens.

![image](https://user-images.githubusercontent.com/43848/111060070-9e43b700-849a-11eb-899b-4c1167070bf0.png)

**Comment by p12tic** [comment]
@ynezz Would it be possible for me to get access to the master logs when this happens?

**Comment by ynezz** [comment]
> Would it be possible for me to get access to the master logs when this happens?

Sure, can you provide some grep command?

**Comment by ynezz** [comment]
```Python
2021-03-13 07:26:15+0000 [-] [Contact] Builder bcm27xx/bcm2710 started
2021-03-13 07:26:16+0000 [-] False
2021-03-13 07:26:16+0000 [-] from a running build; this is a serious error - please file a bug at http://buildbot.net
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
	    result = current_context.run(g.send, result)
	  File "/usr/local/lib/python3.7/dist-packages/buildbot/process/build.py", line 355, in startBuild
	    yield self.buildPreparationFailure(ready_or_failure, "worker_prepare")
	  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1656, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1571, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.7/dist-packages/buildbot/process/build.py", line 355, in startBuild
	    yield self.buildPreparationFailure(ready_or_failure, "worker_prepare")
	  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
	    result = current_context.run(g.send, result)
	  File "/usr/local/lib/python3.7/dist-packages/buildbot/process/build.py", line 428, in buildPreparationFailure
	    self.workerforbuilder.worker.putInQuarantine()
	builtins.AttributeError: 'NoneType' object has no attribute 'putInQuarantine'
	
2021-03-13 07:26:17+0000 [-] [Contact] Builder bcm27xx/bcm2711 started
2021-03-13 07:26:17+0000 [-] False
2021-03-13 07:26:17+0000 [-] from a running build; this is a serious error - please file a bug at http://buildbot.net
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
	    result = current_context.run(g.send, result)
	  File "/usr/local/lib/python3.7/dist-packages/buildbot/process/build.py", line 355, in startBuild
	    yield self.buildPreparationFailure(ready_or_failure, "worker_prepare")
	  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1656, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1571, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.7/dist-packages/buildbot/process/build.py", line 355, in startBuild
	    yield self.buildPreparationFailure(ready_or_failure, "worker_prepare")
	  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
	    result = current_context.run(g.send, result)
	  File "/usr/local/lib/python3.7/dist-packages/buildbot/process/build.py", line 428, in buildPreparationFailure
	    self.workerforbuilder.worker.putInQuarantine()
	builtins.AttributeError: 'NoneType' object has no attribute 'putInQuarantine'
```

**Comment by p12tic** [comment]
Thanks I think this is enough for now.

**Comment by ynezz** [comment]
FYI, updated to 3.2.0 today and seeing workers still in [connected state](https://buildbot.openwrt.org/master/images/#/workers) even they got disconnected 6 days ago.

![image](https://user-images.githubusercontent.com/43848/123629271-60ce2400-d814-11eb-8da6-647e353fef93.png)

```
2021-06-22 17:49:21+0000 [Broker (TLSMemoryBIOProtocol),62,xxx.193.126.200] Worker.detached(fsf-dock-16)
2021-06-22 17:49:21+0000 [Broker (TLSMemoryBIOProtocol),62,xxx.193.126.200] RemoteCommand.disconnect: lost worker

2021-06-22 17:51:16+0000 [Broker (TLSMemoryBIOProtocol),61,xxx.193.126.200] Worker.detached(fsf-dock-15)
2021-06-22 17:51:16+0000 [Broker (TLSMemoryBIOProtocol),61,xxx.193.126.200] RemoteCommand.disconnect: lost worker

2021-06-22 17:51:18+0000 [Broker (TLSMemoryBIOProtocol),60,xxx.193.126.200] Worker.detached(fsf-dock-05)
2021-06-22 17:51:18+0000 [Broker (TLSMemoryBIOProtocol),60,xxx.193.126.200] RemoteCommand.disconnect: lost worker
```

**Comment by YngveNPettersen** [comment]
We just had a major issue with the manager machine, and had to reboot it. Afterwards, it seems like most of the workers have not come back online and reconnected to the manager (only the Macs and one Windows machine that was being rebooted around the time the manager was rebooted).

However, the workers are all showing a green circle for their status, which means it is literally impossible from the Builds and worker views to tell if the worker is online, or not.

**Comment by YngveNPettersen** [comment]
Even an hour after restart, none of the workers that had not gotten reconnected within minutes of the restart had reconnected.

The relevant part of the log on one of the workers looks like this
```
2021-07-27 08:17:53+0000 [-] sending app-level keepalive
2021-07-27 08:17:53+0000 [Broker (TLSMemoryBIOProtocol),client] Master replied to keepalive, everything's fine
2021-07-27 08:20:46+0000 [Broker (TLSMemoryBIOProtocol),client] message from master: keepalive
2021-07-27 08:27:53+0000 [-] sending app-level keepalive
```

The last line was just before the recovery operations started, and about 35 minutes before the last restart of the manager.

None of those workers reconnected before they were restarted manually about an hour after the manager restart. In that period there were no further log output on the workers I checked (the keep-alive setting is 600 seconds).

It looks like the worker does not retry a keep-alive if it does not get a response from the manager, even if that takes longer than the keep-alive period.

I do not know what happened to the worker connections to the manager, whether they were closed when the manager rebooted or not. The shutdown part of the log show this for one of the workers (with several more repetitions):

```
2021-07-27 10:03:08+0000 [-] Received SIGTERM, shutting down.
2021-07-27 10:03:08+0000 [Broker (TLSMemoryBIOProtocol),client] connection already shut down when attempting keepalive
2021-07-27 10:03:08+0000 [Broker (TLSMemoryBIOProtocol),client] sending app-level keepalive
2021-07-27 10:03:08+0000 [Broker (TLSMemoryBIOProtocol),client] connection already shut down when attempting keepalive
2021-07-27 10:03:08+0000 [Broker (TLSMemoryBIOProtocol),client] sending app-level keepalive
```

IMO the worker should time out a connection that does not get a keep-alive response and try to reconnect. It seems that is not happening for some reason.

For reference, the buildbot version is 3.1.1
