### ISSUE TITLE
gitpoller: git init --bare fails with EISDIR: workdir is a directory

### ISSUE THREAD

**Issue by freqlabs** [buildbot/buildbot#5846]
software | version
---------------- | ------
Buildbot | 2.10.0
Twisted | 20.3.0
Python | Python 3.7.9
FreeBSD | 14.0-CURRENT

Gitpoller is nonfunctional, filling the log with this traceback:
```
2021-03-03 12:33:51-0500 [-] while polling for changes
        Traceback (most recent call last):
          File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 501, in errback
            self._startRunCallbacks(fail)
          File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
            _inlineCallbacks(r, g, status)
        --- <exception caught here> ---
          File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python3.7/site-packages/buildbot/changes/gitpoller.py", line 189, in poll
            yield self._dovccmd('init', ['--bare', self.workdir])
          File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python3.7/site-packages/buildbot/changes/gitpoller.py", line 409, in _dovccmd
            stdout = yield self._dovccmdImpl(command, args, path, None)
          File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python3.7/site-packages/buildbot/changes/gitpoller.py", line 442, in _dovccmdImpl
            ).format(full_args, path, self.repourl, code, stderr))
        builtins.OSError: command ['init', '--bare', '/var/buildbot-master/gitpoller-work'] in None on repourl git://github.com/zfsonfreebsd/ZoF.git failed with exit code 1: /var/buildbot-master/gitpoller-work/: Is a directory
```

I blindly tried removing the directory before attempting git init in the poll function, but the same error persists:
```diff
@@ -15,6 +15,7 @@

 import os
 import re
+import shutil
 import stat
 from urllib.parse import quote as urlquote

@@ -180,6 +181,9 @@
     @defer.inlineCallbacks
     def poll(self):
         yield self._checkGitFeatures()
+
+        if os.path.exists(self.workdir):
+            shutil.rmtree(self.workdir)

         try:
             yield self._dovccmd('init', ['--bare', self.workdir]) 
```

**Comment by freqlabs** [comment]
```
# git init --bare gitpoller-work
/var/buildbot-master/gitpoller-work/: Is a directory
# ls -la gitpoller-work
total 18
drwx------  2 buildbot-master  buildbot-master   2 Mar  3 13:11 .
drwxr-xr-x  3 buildbot-master  buildbot-master  31 Mar  3 13:11 ..
```
Perhaps this is really a permissions issue? `git init --bare` normally works fine on an empty directory...

**Comment by freqlabs** [comment]
```
buildbot-master@epyc1:~ $ git init --bare gitpoller-work/
/var/buildbot-master/gitpoller-work/: Is a directory
buildbot-master@epyc1:~ $ id
uid=1003(buildbot-master) gid=1004(buildbot-master) groups=1004(buildbot-master),1003(libvirt)
buildbot-master@epyc1:~ $ chmod 777 gitpoller-work/
buildbot-master@epyc1:~ $ git init --bare gitpoller-work/
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /var/buildbot-master/gitpoller-work/
```

**Comment by freqlabs** [comment]
I doubt this is buildbot's fault.

**Comment by freqlabs** [comment]
For anyone else who may run into this, I had to change umask in buildbot.tac from `None` to `0o22`. I'm sure I'd had that configured correctly before but at some point must have lost it somehow.
