### ISSUE TITLE
Builds fail with exception when owners property is not set

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#5852]
Builds fail with exception in Buildbot v2.10.1 sometimes. Seems like this issue happens when owners property is not set (while sending patches through buildbot try).

```
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1514, in gotResult
    current_context.run(_inlineCallbacks, r, g, status)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
    return f(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
    return f(*args, **kwargs)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/buildbot/process/build.py", line 340, in startBuild
    self.setupBuild()  # create .steps
  File "/usr/local/lib/python3.6/site-packages/buildbot/process/build.py", line 507, in setupBuild
    self.setProperty('owners', sorted(owners), 'Build')
builtins.TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by aj062** [comment]
This issue happens only with triggered builds (builds which are triggered from another build).

**Comment by p12tic** [comment]
@aj062 I did not find problems with the try scheduler code that may cause this issue. Could it be that `buildset_properties` or `change_properties` tables somehow contain None values of `owner` property? Note that the value column contains json-encoded value, so querying the database is not simple.
