### ISSUE TITLE
Unknown component name: BuildStatusGenerator

### ISSUE THREAD

**Issue by lfdmn** [buildbot/buildbot#5892]
Hi,

I'm trying to create a status generator using the example code

```python
from buildbot.plugins import reporters

template=u'''\
<h4>Build status: {{ summary }}</h4>
<p> Worker used: {{ workername }}</p>
{% for step in build['steps'] %}
<p> {{ step['name'] }}: {{ step['results'] }}</p>
{% endfor %}
<p><b> -- The Buildbot</b></p>
'''

generator = reporters.BuildStatusGenerator(
    mode=('failing',),
    message_formatter=reporters.MessageFormatter(
        template=template, template_type='html',
        wantProperties=True, wantSteps=True))

c['services'] = [
    reporters.MailNotifier(
        fromaddr="buildbot@example.org",
        sendToInterestedUsers=False,
        mode=('failing',),
        extraRecipients=['listaddr@example.org'],
        generators=[generator]
    )
]
```

I get this error
```
2021-03-12 16:59:48+0200 [-] Loading buildbot.tac...
2021-03-12 16:59:49+0200 [-] Loaded.
2021-03-12 16:59:49+0200 [-] twistd 21.2.0 (/home/damien/ci/master/env/bin/python3 3.6.9) starting up.
2021-03-12 16:59:49+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2021-03-12 16:59:49+0200 [-] Starting BuildMaster -- buildbot.version: 3.0.0
2021-03-12 16:59:49+0200 [-] Loading configuration from '/home/damien/ci/master/master.cfg'
2021-03-12 16:59:49+0200 [-] error while parsing config file:
	Traceback (most recent call last):
	  File "/home/damien/ci/master/env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 255, in <lambda>
	    ctx, func, *args, **kw
	  File "/home/damien/ci/master/env/lib/python3.6/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/damien/ci/master/env/lib/python3.6/site-packages/twisted/python/context.py", line 83, in callWithContext
	    return func(*args, **kw)
	  File "/home/damien/ci/master/env/lib/python3.6/site-packages/buildbot/config.py", line 152, in loadConfig
	    self.basedir, self.configFileName)
	--- <exception caught here> ---
	  File "/home/damien/ci/master/env/lib/python3.6/site-packages/buildbot/config.py", line 114, in loadConfigDict
	    execfile(filename, localDict)
	  File "/home/damien/ci/master/env/lib/python3.6/site-packages/twisted/python/compat.py", line 225, in execfile
	    exec(code, globals, locals)
	  File "/home/damien/ci/master/master.cfg", line 5, in <module>
	    import blabla
	  File "/home/damien/ci/master/blabla.py", line 12, in <module>
	    generator = reporters.BuildStatusGenerator(
	  File "/home/damien/ci/master/env/lib/python3.6/site-packages/buildbot/plugins/db.py", line 278, in __getattr__
	    raise AttributeError(str(e)) from e
	builtins.AttributeError: Unknown component name: BuildStatusGenerator
	
2021-03-12 16:59:49+0200 [-] Configuration Errors:
2021-03-12 16:59:49+0200 [-]   error while parsing config file: Unknown component name: BuildStatusGenerator (traceback in logfile)
2021-03-12 16:59:49+0200 [-] Halting master.
2021-03-12 16:59:49+0200 [-] BuildMaster startup failed
2021-03-12 16:59:49+0200 [-] BuildMaster is stopped
2021-03-12 16:59:49+0200 [-] Main loop terminated.
2021-03-12 16:59:49+0200 [-] Server Shut Down.
```

I'm having difficulties tracking this one down.

**Comment by p12tic** [comment]
@lfdmn Thanks for the bug report, this will be fixed in #5895. I believe you can still use `BuildStatusGenerator` as `from buildbot.reporters.generators.build import BuildStatusGenerator`.
