### ISSUE TITLE
AttributeError: module 'sqlalchemy.engine.strategies' has no attribute 'PlainEngineStrategy'

### ISSUE THREAD

**Issue by daltenty** [buildbot/buildbot#5910]
On buildbot version 3.0.1, since upgrading SQLAlchemy to version 1.4, `buildbot create-master` now throws an error:

```
Traceback (most recent call last):
  File "/opt/buildbot/master/venv/bin/buildbot", line 8, in <module>
    sys.exit(run())
  File "/opt/buildbot/master/venv/lib/python3.8/site-packages/buildbot/scripts/runner.py", line 772, in run
    subcommandFunction = reflect.namedObject(subconfig.subcommandFunction)
  File "/opt/buildbot/master/venv/lib/python3.8/site-packages/twisted/python/reflect.py", line 170, in namedObject
    module = namedModule(".".join(classSplit[:-1]))
  File "/opt/buildbot/master/venv/lib/python3.8/site-packages/twisted/python/reflect.py", line 157, in namedModule
    topLevel = __import__(name)
  File "/opt/buildbot/master/venv/lib/python3.8/site-packages/buildbot/scripts/create_master.py", line 25, in <module>
    from buildbot.master import BuildMaster
  File "/opt/buildbot/master/venv/lib/python3.8/site-packages/buildbot/master.py", line 35, in <module>
    from buildbot.db import connector as dbconnector
  File "/opt/buildbot/master/venv/lib/python3.8/site-packages/buildbot/db/connector.py", line 30, in <module>
    from buildbot.db import enginestrategy
  File "/opt/buildbot/master/venv/lib/python3.8/site-packages/buildbot/db/enginestrategy.py", line 154, in <module>
    class BuildbotEngineStrategy(strategies.PlainEngineStrategy):
AttributeError: module 'sqlalchemy.engine.strategies' has no attribute 'PlainEngineStrategy'
````

Restricting the sqlalchemy version to 1.3.23 seems to resolve this issue.

Seems related to the removal of this interface in SQLAlchemy 1.4: https://github.com/sqlalchemy/sqlalchemy/commit/dfb20f07d8796ec27732df84c40b4ce4857fd83b

**Comment by yan12125** [comment]
Hi, is there a plan to make buildbot compatible with sqlalchemy 1.4? I'm maintaining the [buildbot](https://archlinux.org/packages/community/any/buildbot/) package at Arch Linux, and there are discussions about upgrading sqlalchemy to 1.4.

**Comment by karolyi** [comment]
+1 here, FreeBSD started to have this issue too.

**Comment by p12tic** [comment]
This bug has been properly fixed in #6156 and released in Buildbot v3.3.0.

**Comment by antyung88** [comment]
I think FreeBSD is having this issue again

**Comment by karolyi** [comment]
The bug on the FreeBSD issue tracker seems to have a solution for this, read there:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259599
