### ISSUE TITLE
AttributeError: module 'sqlalchemy.engine.strategies' has no attribute 'PlainEngineStrategy'

### ISSUE THREAD

**Issue by ynezz** [buildbot/buildbot#5911]
`sqlalchemy>=1.2.0` dependency allows installing of latest 1.4.0 which results in the following exception:

```python
Traceback (most recent call last):
  File "/usr/local/bin/buildbot", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/buildbot/scripts/runner.py", line 772, in run
    subcommandFunction = reflect.namedObject(subconfig.subcommandFunction)
  File "/usr/local/lib/python3.7/dist-packages/twisted/python/reflect.py", line 170, in namedObject
    module = namedModule(".".join(classSplit[:-1]))
  File "/usr/local/lib/python3.7/dist-packages/twisted/python/reflect.py", line 157, in namedModule
    topLevel = __import__(name)
  File "/usr/local/lib/python3.7/dist-packages/buildbot/scripts/create_master.py", line 25, in <module>
    from buildbot.master import BuildMaster
  File "/usr/local/lib/python3.7/dist-packages/buildbot/master.py", line 35, in <module>
    from buildbot.db import connector as dbconnector
  File "/usr/local/lib/python3.7/dist-packages/buildbot/db/connector.py", line 31, in <module>
    from buildbot.db import enginestrategy
  File "/usr/local/lib/python3.7/dist-packages/buildbot/db/enginestrategy.py", line 154, in <module>
    class BuildbotEngineStrategy(strategies.PlainEngineStrategy):
AttributeError: module 'sqlalchemy.engine.strategies' has no attribute 'PlainEngineStrategy'
```

**Comment by ynezz** [comment]
Duplicate of #5910
