### ISSUE TITLE
MailNotifier fails to send email

### ISSUE THREAD

**Issue by muks** [buildbot/buildbot#5943]
I have a `MailNotifier` configured like this:

```python
s = reporters.MailNotifier(
    fromaddr='buildbot@example.org',
    extraRecipients=['notify@example.org'],
    sendToInterestedUsers=False,
    relayhost='mail.example.org',
    smtpPort=587,
    useTls=True,
    smtpUser='buildbot@example.org',
    smtpPassword='randomstring')
c['services'].append(s)
```
Notification mails are not sent. The following messages are logged in `twistd.log`:

```
2021-03-23 21:47:39+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f7742e74d90>
2021-03-23 21:47:39+0000 [ESMTPSender,client] Got exception when handling reporter events
        Traceback (most recent call last):
          File "/home/buildbot/venv/lib64/python3.8/site-packages/twisted/internet/defer.py", line 1514, in gotResult
            current_context.run(_inlineCallbacks, r, g, status)
          File "/home/buildbot/venv/lib64/python3.8/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
            result = current_context.run(result.throwExceptionIntoGenerator, g)
          File "/home/buildbot/venv/lib64/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/home/buildbot/venv/lib64/python3.8/site-packages/buildbot/reporters/base.py", line 95, in _got_event
            log.err(e, 'Got exception when handling reporter events')
        --- <exception caught here> ---
          File "/home/buildbot/venv/lib64/python3.8/site-packages/buildbot/reporters/base.py", line 93, in _got_event
            yield self.sendMessage(reports)
        twisted.mail._except.TLSRequiredError: 502 Server does not support secure communication via TLS / SSL
        <<< 250-8BITMIME
        <<< 250-DSN
        <<< 250-SMTPUTF8
        <<< 250 CHUNKING
```

This used to work before, so it appears something has changed in the software versions. `pyOpenSSL` is available in the venv.

```sh
(venv) [buildbot@dev ~]$ pip list | grep -i -E '(pyopenssl|cryptography)'
cryptography            3.4.6
pyOpenSSL               20.0.1
(venv) [buildbot@dev ~]$ 
```
The server does support STARTTLS on port 587. We all use it with various email clients for email submission. As an example, Gerrit is able to send emails via this same email submission service.

**Comment by muks** [comment]
Sample session with `openssl s_client` to prove that STARTTLS is available on port 587:

```
[buildbot@dev ~]$ openssl s_client -connect mail.example.org:587 -starttls smtp
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = [REDACTED]
verify return:1
---
Certificate chain
 0 s:CN = [REDACTED]
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----

... [REDACTED] ...

-----END CERTIFICATE-----
subject=CN = REDACTED]

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2871 bytes and written 429 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
250 CHUNKING
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: [REDACTED]
    Session-ID-ctx:
    Resumption PSK: [REDACTED]
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
	... [REDACTED] ...

    Start Time: 1616536878
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
quit
221 2.0.0 Bye
closed
[buildbot@dev ~]$
```

**Comment by muks** [comment]
Briefly reading through the `twisted/src/twisted/mail/smtp.py` code, the output logged (after `EHLO`) in the report above by `SMTPClient.lineReceived()` appears incomplete compared to what the server returns. The output logged above is:

```
        twisted.mail._except.TLSRequiredError: 502 Server does not support secure communication via TLS / SSL
        <<< 250-8BITMIME
        <<< 250-DSN
        <<< 250-SMTPUTF8
        <<< 250 CHUNKING
```

whereas the SMTP server on port 587 returns the following messages after `EHLO` is sent by the client:

```
250-mail.example.org
250-PIPELINING
250-SIZE 163840000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
```

It appears the first few lines that include `250-STARTTLS` are lost, and so `ESMTPClient.esmtpState_serverConfig()` doesn't include it in the `items` dict, and `canTLS` is `False` in `ESMTPClient.tryTLS()`.

**Comment by LuluDavid** [comment]
Have exactly the same error here, but it works again if I downgrade Twisted to 20.3.0.
Seems that it could come from [this issue on Twisted](https://github.com/matrix-org/synapse/issues/6211) that led to the migration from 20.3.0 to 21.2.0.

**Comment by hadleyrich** [comment]
> Have exactly the same error here, but it works again if I downgrade Twisted to 20.3.0.
> Seems that it could come from [this issue on Twisted](https://github.com/matrix-org/synapse/issues/6211) that led to the migration from 20.3.0 to 21.2.0.

Ditto

**Comment by Swansky** [comment]
Hi, this problem is always present. 
The downgrade from twisted to 20.3.0 was working for the office365 smtp server until microsoft removed the TLS 1.0, 1.1 support for TLS1.2. Today I am facing a critical deadlock where sending mail does not work anymore. I have tried all recent twisted packages (from 20.3.0) none of them fixes the problem. Disabling 'useTls' for 'useSmtps' does not change anything. 
The error message is the same as in the first post, and so is my configuration.
If you have any idea, even temporary, I'm interested.
Thank you.

**Comment by tenta4** [comment]
This is because new Twisted 21.2.0+ required `hostname` argument in the ESMTPSenderFactory
So in buildbot 2.10.X I fixed it by next patch
`diff --git a/reporters/mail.py b/reporters/mail.py
index 54e9c88..79d2886 100644
--- a/reporters/mail.py
+++ b/reporters/mail.py
@@ -351,7 +351,7 @@ class MailNotifier(ReporterBase):
             unicode2bytes(self.smtpUser), unicode2bytes(self.smtpPassword),
             parseaddr(self.fromaddr)[1], recipients, BytesIO(s),
             result, requireTransportSecurity=self.useTls,
-            requireAuthentication=useAuth)
+            requireAuthentication=useAuth, hostname=self.relayhost)
 
         if self.useSmtps:
             reactor.connectSSL(self.relayhost, self.smtpPort,
`

**Comment by muks** [comment]
@p12tic Please can you take a look at the patch in the previous comment, and merge it if it appears correct?

**Comment by doberkofler** [comment]
> This is because new Twisted 21.2.0+ required `hostname` argument in the ESMTPSenderFactory So in buildbot 2.10.X I fixed it by next patch
> 
> ```diff
> index 54e9c88..79d2886 100644
> --- a/reporters/mail.py
> +++ b/reporters/mail.py
> @@ -351,7 +351,7 @@ class MailNotifier(ReporterBase):
>              unicode2bytes(self.smtpUser), unicode2bytes(self.smtpPassword),
>              parseaddr(self.fromaddr)[1], recipients, BytesIO(s),
>              result, requireTransportSecurity=self.useTls,
> -            requireAuthentication=useAuth)
> +            requireAuthentication=useAuth, hostname=self.relayhost)
>  
>          if self.useSmtps:
>              reactor.connectSSL(self.relayhost, self.smtpPort,
> ```

I have tried this workaround but was not successful.

**Comment by cryptable** [comment]
This workaround by adding the hostname to the ESMTPSenderFactory solved my problem sending mails through gmail. Can this be integrated or shall I ask for a pull request?

**Comment by tenta4** [comment]
Created PR https://github.com/buildbot/buildbot/pull/6579

**Comment by muks** [comment]
> Created PR #6579

Please don't resolve this ticket after merging PR #6579 as it does not fix the problem for the reporter of this ticket, and others on this ticket. What PR #6579 fixes may in fact be a different bug that has similar symptoms.

The third comment on this ticket describes what occurs for this bug, that PR #6579 is unlikely to solve (from its diff).

**Comment by muks** [comment]
Perhaps an `msmtpd` daemon, running on the same host as the Buildbot master, acting as a proxy to the real SMTP submission service, would offer a workaround for the bug.

**Comment by cryptable** [comment]
I use buildbot master on Linux (ubuntu 22.04) and use Ansible now to patch the ESMTPSenderFactory. It would be nice I don't have to patch that file when installing builldbot. Any advise would be welcome if alternative is possible.

**Comment by tardyp** [comment]
@muks could you please try upgrading twisted and apply #6579.
it appears to me that the original issue is actually a Twisted issue.

**Comment by doberkofler** [comment]
@tardyp Still not able to send email via gmail from buildbot master **3.6.0** running in docker container!

Python version: 3.9.2
Buildbot version: 3.6.0
Twisted version: 22.4.0

```
master-config-buildbot-1  | 2022-08-29 05:16:35+0000 [ESMTPSender,client] Got exception when handling reporter events
master-config-buildbot-1  |     Traceback (most recent call last):
master-config-buildbot-1  |       File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1750, in gotResult
master-config-buildbot-1  |         current_context.run(_inlineCallbacks, r, gen, status)
master-config-buildbot-1  |       File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
master-config-buildbot-1  |         result = current_context.run(
master-config-buildbot-1  |       File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
master-config-buildbot-1  |         return g.throw(self.type, self.value, self.tb)
master-config-buildbot-1  |       File "/buildbot_venv/lib/python3.9/site-packages/buildbot/reporters/base.py", line 113, in _got_event
master-config-buildbot-1  |         log.err(e, 'Got exception when handling reporter events')
master-config-buildbot-1  |     --- <exception caught here> ---
master-config-buildbot-1  |       File "/buildbot_venv/lib/python3.9/site-packages/buildbot/reporters/base.py", line 111, in _got_event
master-config-buildbot-1  |         yield self.sendMessage(reports)
master-config-buildbot-1  |     twisted.mail._except.TLSRequiredError: 502 Server does not support secure communication via TLS / SSL
```

```python
c['services'] = []

from emailLookup import EmailLookup

generator = reporters.BuildStatusGenerator(
	mode=('change'),
	)

mn = reporters.MailNotifier(
	fromaddr=private.auth_username,
	sendToInterestedUsers=True,
	extraRecipients=[],
	useTls=True,
	relayhost='smtp.gmail.com',
	smtpPort=587,
	smtpUser=private.auth_username,
	smtpPassword=private.auth_password,
	lookup=EmailLookup(),
	generators=[generator],
	)

c['services'].append(mn)
```

**Comment by muks** [comment]
@tardyp The issue still occurs. Versions of software used:
```
Package                 Version
----------------------- -----------
alembic                 1.14.0
attrs                   24.2.0
autobahn                24.4.2
Automat                 24.8.1
buildbot                4.1.0
buildbot-console-view   4.1.0
buildbot-grid-view      4.1.0
buildbot-waterfall-view 4.1.0
buildbot-worker         4.1.0
buildbot-www            4.1.0
certifi                 2024.8.30
cffi                    1.17.1
charset-normalizer      3.4.0
constantly              23.10.4
croniter                5.0.1
cryptography            43.0.3
hyperlink               21.0.0
idna                    3.10
incremental             24.7.2
Jinja2                  3.1.4
Mako                    1.3.6
MarkupSafe              3.0.2
msgpack                 1.1.0
packaging               24.2
pip                     24.3.1
pyasn1                  0.6.1
pyasn1_modules          0.4.1
pycparser               2.22
PyJWT                   2.9.0
pyOpenSSL               24.2.1
python-dateutil         2.9.0.post0
pytz                    2024.2
PyYAML                  6.0.2
requests                2.32.3
service-identity        24.2.0
setuptools              75.3.0
six                     1.16.0
SQLAlchemy              2.0.36
treq                    24.9.1
Twisted                 24.10.0
txaio                   23.1.1
typing_extensions       4.12.2
unidiff                 0.7.5
urllib3                 2.2.3
zope.interface          7.1.1
```

Logs from `twistd.log`:
```
2024-11-04 05:59:36+0000 [-] sending mail (825 bytes) to ['example-list@exampe.com']
2024-11-04 05:59:36+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f6c245942c0>
2024-11-04 05:59:36+0000 [ESMTPSender,client] Got exception when handling reporter events
        Traceback (most recent call last):
          File "/home/buildbot/venv/lib64/python3.12/site-packages/twisted/internet/defer.py", line 1949, in _gotResultInlineCallbacks
            _inlineCallbacks(r, gen, status, context)
          File "/home/buildbot/venv/lib64/python3.12/site-packages/twisted/internet/defer.py", line 1999, in _inlineCallbacks
            result = context.run(
          File "/home/buildbot/venv/lib64/python3.12/site-packages/twisted/python/failure.py", line 519, in throwExceptionIntoGenerator
            return g.throw(self.value.with_traceback(self.tb))
          File "/home/buildbot/venv/lib64/python3.12/site-packages/buildbot/reporters/base.py", line 126, in _got_event
            log.err(e, 'Got exception when handling reporter events')
        --- <exception caught here> ---
          File "/home/buildbot/venv/lib64/python3.12/site-packages/buildbot/reporters/base.py", line 124, in _got_event
            yield self.sendMessage(reports)
        twisted.mail._except.TLSRequiredError: 502 Server does not support secure communication via TLS / SSL
        <<< 250-8BITMIME
        <<< 250-DSN
        <<< 250-SMTPUTF8
        <<< 250 CHUNKING


```

**Comment by muks** [comment]
@doberkofler I see you've reported this as #6451; can you try *testing* the following patch (or some variant of it) and check if it fixes the issue for you:
```
diff --git a/master/buildbot/reporters/mail.py b/master/buildbot/reporters/mail.py
index c33d81e7c..e9974fe25 100644
--- a/master/buildbot/reporters/mail.py
+++ b/master/buildbot/reporters/mail.py
@@ -357,6 +357,7 @@ class MailNotifier(ReporterBase):
         s = unicode2bytes(s)
         recipients = [parseaddr(r)[1] for r in recipients]
         hostname = self.relayhost if self.useTls or useAuth else None
+        contextFactory = optionsForClientTLS(self.relayhost) if self.useTls or useAuth else None
         sender_factory = ESMTPSenderFactory(
             unicode2bytes(self.smtpUser),
             unicode2bytes(self.smtpPassword),
@@ -367,6 +368,7 @@ class MailNotifier(ReporterBase):
             requireTransportSecurity=self.useTls,
             requireAuthentication=useAuth,
             hostname=hostname,
+            contextFactory=contextFactory,
         )
 
         if self.useSmtps:
```

I don't know if `self.relayhost` is a string or a byte array. I haven't tested this patch yet.. I can only do it tomorrow. If it complains about `self.relayhost` not being a string, replace it with `self.relayhost.decode('utf8')`.

**Comment by muks** [comment]
The patch above fixed the issue in my Buildbot instance. After a build:
```
2024-11-27 18:25:33+0000 [-]  <Build loop-builder number:24 results:success>: build finished
2024-11-27 18:25:33+0000 [-] releaseLocks(<Worker 'buildbot-loop-fedora-41-amd64-2'>): []
2024-11-27 18:25:33+0000 [-] sending mail (1902 bytes) to [anonymous@example.com']
2024-11-27 18:25:33+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7ff5a8dbacf0>
2024-11-27 18:25:33+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7ff5a8dbacf0>
```
No errors. It was delivered at the MTA.

**Comment by p12tic** [comment]
@muks Thanks a lot for investigation and fixing the problem. 

I don't understand how the fix works. Current Twisted will call optionsForClientTLS if contextFactory argument is not set. Something is weird if this change makes a difference to you.

Which version of Twisted have you patched? Thanks again

**Comment by muks** [comment]
> @muks Thanks a lot for investigation and fixing the problem.
> 
> I don't understand how the fix works. Current Twisted will call optionsForClientTLS internally if contextFactory argument is not set. Something is weird if this change makes a difference to you.

Even I thought it was weird at first as I too noticed the internal call during review of the Twisted SMTP code. I suspected a fault in the line reader code, but I didn't find any bugs there. However, the change above definitely makes it work, so there is some difference.

> Which version of Twisted are you using?

Here are all the dependent package versions:
```
(venv) [buildbot@dev ~]$ pip list
Package                 Version
----------------------- -----------
alembic                 1.14.0
attrs                   24.2.0
autobahn                24.4.2
Automat                 24.8.1
buildbot                4.1.0
buildbot-console-view   4.1.0
buildbot-grid-view      4.1.0
buildbot-waterfall-view 4.1.0
buildbot-worker         4.1.0
buildbot-www            4.1.0
certifi                 2024.8.30
cffi                    1.17.1
charset-normalizer      3.4.0
constantly              23.10.4
croniter                5.0.1
cryptography            43.0.3
hyperlink               21.0.0
idna                    3.10
incremental             24.7.2
Jinja2                  3.1.4
Mako                    1.3.6
MarkupSafe              3.0.2
msgpack                 1.1.0
packaging               24.2
pip                     24.3.1
pyasn1                  0.6.1
pyasn1_modules          0.4.1
pycparser               2.22
PyJWT                   2.9.0
pyOpenSSL               24.2.1
python-dateutil         2.9.0.post0
pytz                    2024.2
PyYAML                  6.0.2
requests                2.32.3
service-identity        24.2.0
setuptools              75.4.0
six                     1.16.0
SQLAlchemy              2.0.36
treq                    24.9.1
Twisted                 24.3.0
txaio                   23.1.1
typing_extensions       4.12.2
unidiff                 0.7.5
urllib3                 2.2.3
zope.interface          7.1.1
(venv) [buildbot@dev ~]$ 
```

I'll attach a standalone `smtpclient_tls.py` program here that reproduces the problem. Try it with some MTA host that does STARTTLS on port 587. Then uncomment the `contextFactory` argument in the call to `ESMTPSenderFactory()` and try again.

Execute it so after changing the arguments to match the MTA you're testing against:
```sh
python smtpclient_tls.py --username your-username --password your-password --from-address sender@example.com --to-address recepient@example.com --smtp-host mail.example.com --smtp-port 587 --message somefile.txt
```

**Comment by p12tic** [comment]
I see the difference in `smtpclient_tls.py` - it doesn't pass smtpHost to ESMTPSenderFactory. This way optionsForClientTLS won't be called. But it's weird that it changes how Buildbot behaves.

**Comment by p12tic** [comment]
The relevant commit is 8ff8adc58b147c7b68b2769ba0fe7facbda8c555 which has been released in Buildbot 3.10

**Comment by muks** [comment]
@p12tic Today I reverted back to the stock Buildbot 4.1.0 MailNotifier and it worked properly. So it was indeed the `hostname` argument that fixed the issue.

I apologize for the confusion as it appears the error log messages that I last pasted above were logged by an older version of Buildbot.

You may close this issue now.
