### ISSUE TITLE
Question: How to set up GithubStatusPush reporter

### ISSUE THREAD

**Issue by mvousden** [buildbot/buildbot#6129]
Firstly, apologies if this is the wrong place for this question.

I'm interested in using a `GithubStatusPush` reporter (described at https://docs.buildbot.net/3.2.0/manual/configuration/reporters/github_status.html#reporter-GitHubStatusPush) to interact with the checks interface, so that members of my project can understand if the changes suggested in a PR cause tests to fail.

My project exists within an organisation. In addition to a "GitHub OAuth App" for logging into BuildBot via GitHub, I have created a "GitHub App" with read and write permissions on "Pull Requests". My schedulers are triggered using either a `GitPoller` or a `GitHubPullrequestPoller`:

```
c["change_source"] = [
    changes.GitPoller(repoUrl,
        branches=["development"],
        workdir="poller"),
    changes.GitHubPullrequestPoller(repoOwner, repoName)
]
```

My app has a client secret generated, which is placed (for now, I'm keeping it simple), in a file I'm reading from in configuration. I am constructing my service like so:

```
secretFile = open("../secrets/github_check_app", "r")
secret = secretFile.read()
secretFile.close()

c["services"] = [
    reporters.GitHubStatusPush(
        token=secret,
        context=util.Interpolate("bb/%(prop:buildername)s"))
]
```

However, when my build completes, I see no feedback from BuildBot in the pull request. I see the following in the log however (`<ORGANISATION>` and `<REPO>` substituted in to hopefully make it easier to read):

```
[...]
2021-06-28 13:02:51+0100 [-]  step 'Make (Debug)' complete: success (None)
2021-06-28 13:02:51+0100 [-]  <Build Debug build number:17 results:success>: build finished
2021-06-28 13:02:51+0100 [-] releaseLocks(<Worker 'worker'>): []
2021-06-28 13:02:51+0100 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] Failed to update "success" for <ORGANISATION>/<REPO> at 61b230d9ed66d62b30896d7779e4bc65999ba776, context "bb/Debug build", issue None. http 401, b'{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}'
        Traceback (most recent call last):
          File "/opt/miniconda3/envs/buildbot-poets/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/opt/miniconda3/envs/buildbot-poets/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
            _inlineCallbacks(r, g, status)
          File "/opt/miniconda3/envs/buildbot-poets/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/opt/miniconda3/envs/buildbot-poets/lib/python3.7/site-packages/buildbot/reporters/github.py", line 190, in send
            code=code, content=content))
        --- <exception caught here> ---
          File "/opt/miniconda3/envs/buildbot-poets/lib/python3.7/site-packages/buildbot/reporters/github.py", line 169, in send
            raise Exception()
        builtins.Exception:
```

So I'm guessing I have set up something wrong in my authorisation, but I don't know how to debug this further, and I know very little about GitHub's API and what the various tokens/keys mean/do.

Can anyone please suggest how I might diagnose this issue further? I've hunted for guides on this topic, but I'm at a loss for how to proceed.

I'm happy to provide more information if needed (but I'm not sure what is useful here).

**Comment by p12tic** [comment]
Could you try to generate a "Personal access token" instead? In one of my repositories I have "repo" and "workflow" scopes enabled, so this should definitely work.

**Comment by mvousden** [comment]
Thanks for the suggestion. I guess best practice would be to make a "robot" GitHub account that owns the token, to ensure the token isn't used for anything outside of the Organisation it's designed to.

I'll give this a go tomorrow (hurrah for meetings).

Cheers for the help!

**Comment by mvousden** [comment]
Can confirm this fixed this user-error issue. I:

 - Created a robot Github account
 - Created a personal access token (via the developer settings menu)
 - Passed that token to the `token` field in my `GitHubStatusPush` object

Thanks again.
