### ISSUE TITLE
Docker latent worker frequently throws errors on startup

### ISSUE THREAD

**Issue by gregorydlogan** [buildbot/buildbot#6175]
I have a set of latent docker workers, and they're frequently spitting out error like the following on startup:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 662, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1514, in gotResult
    current_context.run(_inlineCallbacks, r, g, status)
  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
    result = current_context.run(result.throwExceptionIntoGenerator, g)
  File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/usr/lib/python3.8/site-packages/buildbot/process/build.py", line 351, in startBuild
    ready_or_failure = yield workerforbuilder.substantiate_if_needed(self)
  File "/usr/lib/python3.8/site-packages/buildbot/worker/latent.py", line 291, in _substantiate
    start_success = yield self.start_instance(build)
  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1443, in _inlineCallbacks
    result = current_context.run(result.throwExceptionIntoGenerator, g)
  File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python3.8/site-packages/buildbot/worker/docker.py", line 225, in start_instance
    res = yield threads.deferToThread(self._thd_start_instance, image,
  File "/usr/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/buildbot/worker/docker.py", line 253, in _thd_start_instance
    docker_client.remove_container(instance['Id'], v=True, force=True)
  File "/usr/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/docker/api/container.py", line 1012, in remove_container
    self._raise_for_status(res)
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error for http://localhost:2376/v1.41/containers/ed3654604b1039650a9d4b1bc578853a50a7aa833f88067f1f275eb17dc4f5c8?v=True&link=False&force=True: Conflict ("removal of container ed3654604b1039650a9d4b1bc578853a50a7aa833f88067f1f275eb17dc4f5c8 is already in progress")
```

Examples can be found on ci.opencast.org, c.f http://ci.opencast.org/#/builders/99/builds/1622.  This started happening when we upgrade out of the 2.3.x codebase into the 3.x.  At the time I also upgraded the Docker installs on the worker nodes, so it's quite possible that's confusing things too.  Currently experiencing this on Docker 20.10.7, although 19.03.15 also exhibits the same behaviour on my internal test cluster.

**Comment by JohannesKauffmann** [comment]
Hi, did you ever find a way to resolve this, or a possible workaround? I'm experiencing similar errors during worker instantiation:

```
Traceback (most recent call last):
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1750, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/buildbot_venv/lib/python3.9/site-packages/buildbot/process/build.py", line 360, in startBuild
    ready_or_failure = yield workerforbuilder.substantiate_if_needed(self)
  File "/buildbot_venv/lib/python3.9/site-packages/buildbot/worker/latent.py", line 289, in _substantiate
    start_success = yield self.start_instance(build)
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/buildbot_venv/lib/python3.9/site-packages/buildbot/worker/docker.py", line 233, in start_instance
    res = yield threads.deferToThread(self._thd_start_instance, docker_host, image,
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/buildbot_venv/lib/python3.9/site-packages/buildbot/worker/docker.py", line 334, in _thd_start_instance
    docker_client.start(instance)
  File "/buildbot_venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/buildbot_venv/lib/python3.9/site-packages/docker/api/container.py", line 1109, in start
    self._raise_for_status(res)
  File "/buildbot_venv/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/buildbot_venv/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for http://hostname.domain.com:2375/v1.41/containers/69ceededcd5c4efc9b8b3875cac9b39a324aea93e4e85d1a6b564894d716c043/start: Internal Server Error ("container 69ceededcd5c4efc9b8b3875cac9b39a324aea93e4e85d1a6b564894d716c043 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The password for this account has expired. (0x532)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF751B6A41B: (caller: 00007FF751B25C9B) Exception(2) tid(388) 80070532 The password for this account has expired.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess] 
 Provider: 00000000-0000-0000-0000-000000000000]")
```

The error message is telling me that "The password for this account has expired", which is strange; I've verified that all used credentials are still valid.

Happy to provide more details if needed.

**Comment by JohannesKauffmann** [comment]
Update: The Windows user accounts inside of latent Windows Docker workers have a password expiration date of 42 days, counting from the day the image was built... 42 days is the default value (https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/maximum-password-age).

From inside the Docker container, you can't change this value from the command line like you can in a full-fledged Windows installation. Solution include running Powershell commands from the ActiveDirectory module, but this module isn't available inside the Docker container and can't be installed.

The only workaround ended up rebuilding the images every month or so, to reset the password expiry day counter. But in the end, we switched to normal workers running under Windows.

**Comment by gregorydlogan** [comment]
This eventually went away on its own for me. Could have been bad images, could have been an update to buildbot. Dunno.
