### ISSUE TITLE
Cannot install with setuptools 58

### ISSUE THREAD

**Issue by rjarry** [buildbot/buildbot#6222]
[Setuptools 58.0.0 removes the support for 2to3](https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0) which breaks the installation of [Tempita](https://pypi.org/project/Tempita/) (dependency of [sqlalchemy-migrate](https://pypi.org/project/sqlalchemy-migrate/)).

This leads to a semi-silent installation error:

```
Collecting Tempita>=0.4
  Downloading https://....../Tempita-0.5.2.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     ...
    Complete output (1 lines):
    error in Tempita setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://......./Tempita-0.5.2.tar.gz
Command errored out with exit status 1: python setup.py egg_info
Check the logs for full command output.
  Downloading https://...../Tempita-0.5.1.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     ...
    Complete output (1 lines):
    error in Tempita setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://...../Tempita-0.5.1.tar.gz
Command errored out with exit status 1: python setup.py egg_info
Check the logs for full command output.
  Downloading https://......./Tempita-0.4.tar.gz (21 kB)
...
  Building wheel for Tempita (setup.py) ... done
  Created wheel for Tempita: filename=Tempita-0.4-py3-none-any.whl
```

[Tempita is a dead project. Last commit activity dates from 2013.](https://pypi.org/project/Tempita/) Versions 0.5.x have `use_2to3=True` in their `setup.py` scripts which allowed silent conversion of code to python3 syntax. With setuptools 58, this conversion is not possible anymore. pip falls back to version 0.4 of tempita which is not compatible with python 3 at all. Leading to an error when starting buildbot:

```
Traceback (most recent call last):
  File "twisted/application/app.py", line 448, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "twisted/application/service.py", line 404, in loadApplication
    application = sob.loadValueFromFile(filename, "application")
  File "twisted/persisted/sob.py", line 176, in loadValueFromFile
    eval(codeObj, d, d)
  File "buildbot.tac", line 155, in <module>
    from buildbot.master import BuildMaster
  File "buildbot/master.py", line 35, in <module>
    from buildbot.db import connector as dbconnector
  File "buildbot/db/connector.py", line 35, in <module>
    from buildbot.db import model
  File "buildbot/db/model.py", line 18, in <module>
    import migrate.versioning.repository
  File "migrate/versioning/repository.py", line 10, in <module>
    from tempita import Template as TempitaTemplate
builtins.SyntaxError: invalid syntax (__init__.py, line 295)
```

Indeed, here is an excerpt from `tempita/__init__.py` (the source code is not browseable anymore):

```python
290     def _eval(self, code, ns, pos):
291         __traceback_hide__ = True
292         try:
293             try:
294                 value = eval(code, self.default_namespace, ns)
295             except SyntaxError, e:
296                 raise SyntaxError(
297                     'invalid syntax in expression: %s' % code)
298             return value
299         except:
300             exc_info = sys.exc_info()
301             e = exc_info[1]
302             if getattr(e, 'args', None):
303                 arg0 = e.args[0]
304             else:
305                 arg0 = coerce_text(e)
306             e.args = (self._add_line_info(arg0, pos),)
307             raise exc_info[0], e, exc_info[2]
```

This is obviously Python 2 syntax only.

The wise choice would be to switch from [sqlalchemy-migrate](https://opendev.org/x/sqlalchemy-migrate) to [alembic](https://github.com/sqlalchemy/alembic) which is officially supported by sqlalchemy maintainers. I don't know what it implies in buildbot codebase.

**Comment by rjarry** [comment]
Here is an exact reproducer on debian stable:

```
jarry@dio:~$ python3 --version
Python 3.9.2
jarry@dio:~$ python3 -m venv bbot-env
jarry@dio:~$ ./bbot-env/bin/pip install -U setuptools
Requirement already satisfied: setuptools in ./bbot-env/lib/python3.9/site-packages (44.1.1)
Collecting setuptools
  Downloading setuptools-58.0.2-py3-none-any.whl (816 kB)
     |████████████████████████████████| 816 kB 24.9 MB/s
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.1.1
    Uninstalling setuptools-44.1.1:
      Successfully uninstalled setuptools-44.1.1
Successfully installed setuptools-58.0.2
jarry@dio:~$ ./bbot-env/bin/pip install --no-cache-dir buildbot
Collecting buildbot
  Downloading buildbot-3.3.0-py3-none-any.whl (836 kB)
     |████████████████████████████████| 836 kB 26.5 MB/s
Collecting Jinja2>=2.1
  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 120.4 MB/s
Requirement already satisfied: setuptools>=8.0 in ./bbot-env/lib/python3.9/site-packages (from buildbot) (58.0.2)
Collecting pyyaml
  Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
     |████████████████████████████████| 630 kB 96.2 MB/s
Collecting sqlalchemy-migrate>=0.13
  Downloading sqlalchemy_migrate-0.13.0-py2.py3-none-any.whl (109 kB)
     |████████████████████████████████| 109 kB 141.9 MB/s
Collecting autobahn>=0.16.0
  Downloading autobahn-21.3.1-py2.py3-none-any.whl (495 kB)
     |████████████████████████████████| 495 kB 104.2 MB/s
Collecting sqlalchemy<1.5,>=1.2.0
  Downloading SQLAlchemy-1.4.23-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 105.0 MB/s
Collecting zope.interface>=4.1.1
  Downloading zope.interface-5.4.0-cp39-cp39-manylinux2010_x86_64.whl (255 kB)
     |████████████████████████████████| 255 kB 92.5 MB/s
Collecting python-dateutil>=1.5
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 108.3 MB/s
Collecting PyJWT
  Downloading PyJWT-2.1.0-py3-none-any.whl (16 kB)
Collecting Twisted>=17.9.0
  Downloading Twisted-21.7.0-py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 109.1 MB/s
Collecting txaio>=2.2.2
  Downloading txaio-21.2.1-py2.py3-none-any.whl (30 kB)
Collecting cryptography>=3.4.6
  Downloading cryptography-3.4.8-cp36-abi3-manylinux_2_24_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 137.2 MB/s
Collecting hyperlink>=21.0.0
  Downloading hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
     |████████████████████████████████| 74 kB 127.1 MB/s
Collecting cffi>=1.12
  Downloading cffi-1.14.6-cp39-cp39-manylinux1_x86_64.whl (405 kB)
     |████████████████████████████████| 405 kB 141.0 MB/s
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 148.4 MB/s
Collecting idna>=2.5
  Downloading idna-3.2-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 148.3 MB/s
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting greenlet!=0.4.17
  Downloading greenlet-1.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
     |████████████████████████████████| 147 kB 133.6 MB/s
Collecting pbr>=1.8
  Downloading pbr-5.6.0-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 159.0 MB/s
Collecting sqlparse
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 66.1 MB/s
Collecting Tempita>=0.4
  Downloading Tempita-0.5.2.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/jarry/bbot-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l3myae0m/tempita_8f139639c3184515a3c1fa374a4649fd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l3myae0m/tempita_8f139639c3184515a3c1fa374a4649fd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ddrv6im8
         cwd: /tmp/pip-install-l3myae0m/tempita_8f139639c3184515a3c1fa374a4649fd/
    Complete output (1 lines):
    error in Tempita setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/56/c8/8ed6eee83dbddf7b0fc64dd5d4454bc05e6ccaafff47991f73f2894d9ff4/Tempita-0.5.2.tar.gz#sha256=cacecf0baa674d356641f1d406b8bff1d756d739c46b869a54de515d08e6fc9c (from https://pypi.org/simple/tempita/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading Tempita-0.5.1.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/jarry/bbot-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l3myae0m/tempita_9dbdbfe4e90f495cb03b63545c8866d2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l3myae0m/tempita_9dbdbfe4e90f495cb03b63545c8866d2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pl3ob403
         cwd: /tmp/pip-install-l3myae0m/tempita_9dbdbfe4e90f495cb03b63545c8866d2/
    Complete output (1 lines):
    error in Tempita setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3f/70/d22ffcf0c1aa88077260de058845d0ef00b4b3044da7c10fc39068801a03/Tempita-0.5.1.tar.gz#sha256=0ebe6938ca7401db79bac279849fffcb5752029150bcb6f3c3edbe7aa9a077d8 (from https://pypi.org/simple/tempita/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading Tempita-0.4.tar.gz (21 kB)
Collecting decorator
  Downloading decorator-5.0.9-py3-none-any.whl (8.9 kB)
Collecting constantly>=15.1
  Downloading constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
Collecting Automat>=0.8.0
  Downloading Automat-20.2.0-py2.py3-none-any.whl (31 kB)
Collecting typing-extensions>=3.6.5
  Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting incremental>=21.3.0
  Downloading incremental-21.3.0-py2.py3-none-any.whl (15 kB)
Collecting attrs>=19.2.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 124.5 MB/s
Using legacy 'setup.py install' for Tempita, since package 'wheel' is not installed.
Installing collected packages: pycparser, six, idna, greenlet, cffi, attrs, zope.interface, typing-extensions, txaio, Tempita, sqlparse, sqlalchemy, pbr, MarkupSafe, incremental, hyperlink, decorator, cryptography, constantly, Automat, Twisted, sqlalchemy-migrate, pyyaml, python-dateutil, PyJWT, Jinja2, autobahn, buildbot
    Running setup.py install for Tempita ... done
Successfully installed Automat-20.2.0 Jinja2-3.0.1 MarkupSafe-2.0.1 PyJWT-2.1.0 Tempita-0.4 Twisted-21.7.0 attrs-21.2.0 autobahn-21.3.1 buildbot-3.3.0 cffi-1.14.6 constantly-15.1.0 cryptography-3.4.8 decorator-5.0.9 greenlet-1.1.1 hyperlink-21.0.0 idna-3.2 incremental-21.3.0 pbr-5.6.0 pycparser-2.20 python-dateutil-2.8.2 pyyaml-5.4.1 six-1.16.0 sqlalchemy-1.4.23 sqlalchemy-migrate-0.13.0 sqlparse-0.4.1 txaio-21.2.1 typing-extensions-3.10.0.2 zope.interface-5.4.0

jarry@dio:~$ ./bbot-env/bin/buildbot create-master master
Traceback (most recent call last):
  File "/home/jarry/./bbot-env/bin/buildbot", line 8, in <module>
    sys.exit(run())
  File "/home/jarry/bbot-env/lib/python3.9/site-packages/buildbot/scripts/runner.py", line 789, in run
    subcommandFunction = reflect.namedObject(subconfig.subcommandFunction)
  File "/home/jarry/bbot-env/lib/python3.9/site-packages/twisted/python/reflect.py", line 170, in namedObject
    module = namedModule(".".join(classSplit[:-1]))
  File "/home/jarry/bbot-env/lib/python3.9/site-packages/twisted/python/reflect.py", line 157, in namedModule
    topLevel = __import__(name)
  File "/home/jarry/bbot-env/lib/python3.9/site-packages/buildbot/scripts/create_master.py", line 25, in <module>
    from buildbot.master import BuildMaster
  File "/home/jarry/bbot-env/lib/python3.9/site-packages/buildbot/master.py", line 35, in <module>
    from buildbot.db import connector as dbconnector
  File "/home/jarry/bbot-env/lib/python3.9/site-packages/buildbot/db/connector.py", line 35, in <module>
    from buildbot.db import model
  File "/home/jarry/bbot-env/lib/python3.9/site-packages/buildbot/db/model.py", line 18, in <module>
    import migrate.versioning.repository
  File "/home/jarry/bbot-env/lib/python3.9/site-packages/migrate/versioning/repository.py", line 10, in <module>
    from tempita import Template as TempitaTemplate
  File "/home/jarry/bbot-env/lib/python3.9/site-packages/tempita/__init__.py", line 276
    except SyntaxError, e:
                      ^
SyntaxError: invalid syntax
```
