### ISSUE TITLE
Random hangs in build scripts on Windows (only if buildbot runs them)

### ISSUE THREAD

**Issue by acidtonic** [buildbot/buildbot#6311]
I am logging this as a last chance effort to save the weeks I put into setting up a buildbot farm to do CI testing of the software my team is developing.

Seems like no matter what I do scripts that work totally fine when *I* run them, hang in various places and simply seem to be sitting there doing nothing...

For instance, linking a tests exe that takes about 10 seconds, will just pause and sit there. No exe on disk, taskman shows 0% cpu, no disk or network activity, I'll see an entry in there for bash.exe and if I view the command line it's my cmake build just paused there doing nothing.

I am using the LibVirt worker on a remote ssh host that has the qemu hooks to delete the TEMP vm image between runs and every start copies BASE back to TEMP. So the machine state is literally the same every run but I get wildly varying build times and it always seems to timeout and hang.

So I spent time adjusting all my VM's buildbot.tac and lowered keepalives from 600 to 30. Still absolutely no difference. I am on a lan with the servers that keep all timing out in various places. Machine has 64 CPU's and 256gig of ram on and another 64 cores sitting idle (128core Epyc).

So I again adjusted my build steps to just be a single shell command and tried redirecting that output to a file, then specifying that log as one I want to monitor hoping that getting python off stdout may fix the hangs via some buffering bug....

Still happening.... Seems like only short small little baby builds work. Building the software our team built, can take upwards of 12 hours yet we can't make it there because buildbot will timeout somewhere during compiling OpenCV or some other dependency and not even make it to the part where we build our software.

Seems like this is only really usable for testing direct small builds and is not stable enough to run any kind of long process that tests fully scaffolding a build machine from scratch.

For what it's worth most of my builds on windows are supposed to go through mingw64-w64 and I finally settled on directly placing bash.exe as the first argument to the shellcommand to avoid starting with cmd.exe.

I have so much time into this and it's exactly what I want if the thing could just run a long build without *constant* random pauses or hangs. I can even login to the VM before it's shutdown, go to the same script, run it, and watch it immediately go on.

Frustrating!

**Comment by vibbo** [comment]
Hi.

Does the worker has any time sync when you start it? I have experienced something similar on VMware VMs. It happens when time on the worker machine is synchronizes (updated) during the build (or rather any time after the Buildbot worker service has been started). When the build hangs, examine timestamps in worker's twisted log to see if there is a mismatch with real time.

I resolved it by running the time sync on VM via remote command, before starting the Buildbot worker service.

Hope this helps.

**Comment by acidtonic** [comment]
I'll check the clock sync and report back, seems to be when linking. When I forcefully shut off the VM (since I'd expect the step timeout of 1200 to have killed it before 3 hours elapsed) I did get this stack trace on the web console from buildbot.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 701, in errback
    self._startRunCallbacks(fail)
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 1751, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/usr/lib/python3.9/site-packages/buildbot/process/buildstep.py", line 482, in startStep
    self.results = yield self.run()
  File "/usr/lib/python3.9/site-packages/buildbot/steps/shell.py", line 203, in run
    yield self.runCommand(cmd)
  File "/usr/lib/python3.9/site-packages/buildbot/process/buildstep.py", line 750, in runCommand
    res = yield command.run(self, self.remote, self.build.builder.name)
  File "/usr/lib/python3.9/site-packages/buildbot/process/remotecommand.py", line 146, in _finished
    yield self.remoteComplete(failure)
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/usr/lib/python3.9/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python3.9/site-packages/buildbot/steps/shell.py", line 203, in run
    yield self.runCommand(cmd)
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/usr/lib/python3.9/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python3.9/site-packages/buildbot/process/buildstep.py", line 750, in runCommand
    res = yield command.run(self, self.remote, self.build.builder.name)
  File "/usr/lib/python3.9/site-packages/buildbot/process/remotecommand.py", line 146, in _finished
    yield self.remoteComplete(failure)
builtins.AttributeError: 'RemoteShellCommand' object has no attribute '_unwrap'
```

**Comment by acidtonic** [comment]
I checked clocks and it looks like clock sync service was delayed_start so if running long enough I'd venture to guess you were correct about the clock sync triggering at a later point.

I added w32tm /resync to the beginning of the script in scheduled task to run on startup after switching the time service to be automatic start. I just fired a build and watched the clock jump before buildbot started so lets hope thats it!

Thanks a bunch for the comment, I'll report back once I know.

**Comment by acidtonic** [comment]
Turned out to be the case. I adjusted clocks on the various systems and all the weird hangs went away. I'd still personally attempt to fix that condition if it was my codebase, clock timing shouldn't be that big of an impact but if it is perhaps buildbot should sync clocks within it's own protocol maybe?

Anyways I'm happy and back to setting up the rest of my build farm now that it's completing builds :)

@vibbo, thanks a ton, your comment saved my day.

**Comment by p12tic** [comment]
@acidtonic Thanks for filling the issue. I think the issue should stay open because buildbot should support small clock changes.
