### ISSUE TITLE
 worker workername cannot attach:   builtins.AssertionError: 

### ISSUE THREAD

**Issue by abma** [buildbot/buildbot#6324]
we have the problem, that a worker cannot connect:

2022-01-07 17:45:14+0100 [Broker,215,54.37.56.77] worker 'workername' attaching from IPv4Address(type='TCP', host='someip', port=31427)
2022-01-07 17:45:14+0100 [Broker,215,54.37.56.77] Got workerinfo from 'workername'
2022-01-07 17:45:14+0100 [Broker,215,54.37.56.77] worker workername cannot attach
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/local/lib/python3.9/dist-packages/buildbot/worker/base.py", line 719, in attached
            log.err(e, "worker {} cannot attach".format(self.name))
        --- <exception caught here> ---
          File "/usr/local/lib/python3.9/dist-packages/buildbot/worker/base.py", line 717, in attached
            yield super().attached(bot)
        builtins.AssertionError: 

on the status page, it shows that it is already connected:

https://buildbot.springrts.com/#/workers

but it isn't!

**Comment by abma** [comment]
logs related at least: #4678

**Comment by abma** [comment]
also one offline worker was always shown as online.

i've renamed it from workername to workername2 and now it seems to be offline as expected.
