### ISSUE TITLE
Docker latent worker stuck at worker_preparation when followStartupLogs is used

### ISSUE THREAD

**Issue by iomartin** [buildbot/buildbot#6405]
We recently added a Docker latent worker to our buildbot and it works mostly fine, except that if we use `followStartupLogs=True` and if there are queued builds when the current build finishes, the next one will get stuck at "worker_preparation". If there are no queued builds when it finishes or if `followStartupLogs` is False, then the next time a new build comes up, it runs fine.

We noticed that when `followStartupLogs` was used, it threw an error like this when the build finished, regardless of if there was something queued up (host, company and repo-name redacted).

Running buildbot 3.4.1

```Feb 17 14:58:14 <host> buildbot[3615251]: 14:58:14 [-] Updated status with "error" for <company>/<repo-name> at e6537b89768b3333e3f08b8528645f7d9ef367a0, context "pkg / <repo-name> / eid-buildbot", issue None.
Feb 17 14:58:15 <host> buildbot[3615251]: 14:58:15 [-] Updated status with "pending" for <company>/<repo-name> at f87ab969e4349b45ef85162fc435cacc207c2798, context "pkg / <repo-name> / eid-buildbot", issue None.
Feb 17 14:58:15 <host> buildbot[3615251]: 14:58:15 [_GenericHTTPChannelProtocol,8,127.0.0.1]  <Build <repo-name>_pkg number:33 results:success>: stopping build: no reason 6
Feb 17 14:58:15 <host> buildbot[3615251]: 14:58:15 [_GenericHTTPChannelProtocol,8,127.0.0.1] insubstantiating worker <DockerLatentWorker 'rhel8_sw_latent_worker'>
Feb 17 14:58:15 <host> buildbot[3615251]: 14:58:15 [_GenericHTTPChannelProtocol,8,127.0.0.1] while insubstantiating worker <DockerLatentWorker 'rhel8_sw_latent_worker'>: waiting until previous start_instance/stop_instance finishes
Feb 17 14:58:16 <host> buildbot[3615251]: 14:58:16 [Broker,5,172.17.0.4] worker 'rhel8_sw_latent_worker' attaching from IPv4Address(type='TCP', host='172.17.0.4', port=41866)
Feb 17 14:58:16 <host> buildbot[3615251]: 14:58:16 [Broker,5,172.17.0.4] Got workerinfo from 'rhel8_sw_latent_worker'
Feb 17 14:58:16 <host> buildbot[3615251]: 14:58:16 [Broker,5,172.17.0.4] Worker rhel8_sw_latent_worker received connection while not trying to substantiate.Disconnecting.
Feb 17 14:58:16 <host> buildbot[3615251]: 14:58:16 [Broker,5,172.17.0.4] waiting for worker to finish disconnecting
Feb 17 14:58:16 <host> buildbot[3615251]: 14:58:16 [Broker,5,172.17.0.4] Peer will receive following PB traceback:
Feb 17 14:58:16 <host> buildbot[3615251]: 14:58:16 [Broker,5,172.17.0.4] Unhandled Error
Feb 17 14:58:16 <host> buildbot[3615251]:         Traceback (most recent call last):
Feb 17 14:58:16 <host> buildbot[3615251]:           File "/var/lib/buildbot/eid-buildbot/bbenv/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
Feb 17 14:58:16 <host> buildbot[3615251]:             result = current_context.run(gen.send, result)
Feb 17 14:58:16 <host> buildbot[3615251]:           File "/var/lib/buildbot/eid-buildbot/bbenv/lib/python3.8/site-packages/buildbot/worker/protocols/pb.py", line 111, in attached
Feb 17 14:58:16 <host> buildbot[3615251]:             yield self.worker.attached(self)
Feb 17 14:58:16 <host> buildbot[3615251]:           File "/var/lib/buildbot/eid-buildbot/bbenv/lib/python3.8/site-packages/twisted/internet/defer.py", line 1909, in unwindGenerator
Feb 17 14:58:16 <host> buildbot[3615251]:             return _cancellableInlineCallbacks(gen)  # type: ignore[unreachable]
Feb 17 14:58:16 <host> buildbot[3615251]:           File "/var/lib/buildbot/eid-buildbot/bbenv/lib/python3.8/site-packages/twisted/internet/defer.py", line 1816, in _cancellableInlineCallbacks
Feb 17 14:58:16 <host> buildbot[3615251]:             _inlineCallbacks(None, gen, status)
Feb 17 14:58:16 <host> buildbot[3615251]:         --- <exception caught here> ---
Feb 17 14:58:16 <host> buildbot[3615251]:           File "/var/lib/buildbot/eid-buildbot/bbenv/lib/python3.8/site-packages/buildbot/pbmanager.py", line 176, in requestAvatar
Feb 17 14:58:16 <host> buildbot[3615251]:             yield persp.attached(mind)
Feb 17 14:58:16 <host> buildbot[3615251]:           File "/var/lib/buildbot/eid-buildbot/bbenv/lib/python3.8/site-packages/buildbot/worker/protocols/pb.py", line 111, in attached
Feb 17 14:58:16 <host> buildbot[3615251]:             yield self.worker.attached(self)
Feb 17 14:58:16 <host> buildbot[3615251]:           File "/var/lib/buildbot/eid-buildbot/bbenv/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
Feb 17 14:58:16 <host> buildbot[3615251]:             result = current_context.run(gen.send, result)
Feb 17 14:58:16 <host> buildbot[3615251]:           File "/var/lib/buildbot/eid-buildbot/bbenv/lib/python3.8/site-packages/buildbot/worker/latent.py", line 331, in attached
Feb 17 14:58:16 <host> buildbot[3615251]:             raise RuntimeError(msg)
Feb 17 14:58:16 <host> buildbot[3615251]:         builtins.RuntimeError: Worker rhel8_sw_latent_worker received connection while not trying to substantiate.Disconnecting.
Feb 17 14:58:16 <host> buildbot[3615251]:                
```

**Comment by iomartin** [comment]
https://github.com/buildbot/buildbot/pull/6344 might be related, but since that is not on a release tag yet, we haven't tried it
