### ISSUE TITLE
Exception "worker {} cannot attach"

### ISSUE THREAD

**Issue by mojca** [buildbot/buildbot#6455]
A few days back one of the workers (which was experiencing some intermittent issues and seems to be ok since the reboot) stopped processing build jobs. It appears to be online, but it refuses to do anything.

I don't see anything weird on the buildbot worker (all the logs look fine) which is running buildbot worken 3.4.0 using Python 3.10 under macOS 11 / arm64.

The master is running buildbot 3.3.0 using Python 3.6.8 (Twisted 19.10.0) on some RedHat-flavoured linux.

The logs on the master reveal the following:

```
YYYY-MM-DD HH:MM:SS+ZZZZ [Broker,283,xxx.xxx.xxx.xxx] worker darwin-arm64
cannot attach
   Traceback (most recent call last):
     File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
       _inlineCallbacks(None, g, status)
     File "/usr/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
       result = result.throwExceptionIntoGenerator(g)
     File "/usr/lib64/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
       return g.throw(self.type, self.value, self.tb)
     File "/usr/lib/python3.6/site-packages/buildbot/worker/base.py", line 719, in attached
       log.err(e, "worker {} cannot attach".format([self.name](http://self.name/)))
   --- <exception caught here> ---
     File "/usr/lib/python3.6/site-packages/buildbot/worker/base.py", line 717, in attached
       yield super().attached(bot)
   builtins.AssertionError:
```

I would be grateful for any hints about how to proceed.

**Comment by mojca** [comment]
Indeed.

I disconnected / disabled the worker in question and it still appears as if it was connected on the master. I restarted the master as well, but it doesn't seem to help in any way (while all other workers still appear offline, the one in question is immediately green).

No, I don't have two workers with the same name.

It looks as if the buildbot master in fact ends up believing that the worker is connected. How can I convince it to reset that status?

**Comment by mojca** [comment]
On the worker that's trying to connect to the server I'm getting
```
> tail -f /var/log/system.log
Mar 14 16:42:43 hostname com.apple.xpc.launchd[1] (org.xxx.yyy.zzz[39776]): Service exited with abnormal code: 1
Mar 14 16:42:43 hostname com.apple.xpc.launchd[1] (org.xxx.yyy.zzz): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by tardyp** [comment]
The connected_worker table does not get cleaned at master shutdown, so it is possible that the UI state remains "connected".
only configured_worker gets cleaned in https://github.com/buildbot/buildbot/blob/master/master/buildbot/data/workers.py#L195

This is not a big deal as this is just a UI state.


But self.conn can only be updated in BaseWorker.attached(), so restarting the master must reset it.

So there might be somehow two instances connecting (as you have instant connect, maybe its a local worker?)

I would do some debug prints in attached to validate this hypothesis.

https://github.com/buildbot/buildbot/pull/6456
