### ISSUE TITLE
buildbot.steps.source.git.Git fails with full mode + copy method

### ISSUE THREAD

**Issue by minyang** [buildbot/buildbot#6539]
When checking out git source tree with `full` mode and `copy` method, `buildbot.steps.source.git.Git` fails.

Buildbot master versions (I'm using docker):
```
buildbot_1  | 2022-06-08 17:15:55+0000 [-] Loading /buildbot/buildbot.tac...
buildbot_1  | 2022-06-08 17:15:57+0000 [-] Loaded.
buildbot_1  | 2022-06-08 17:15:57+0000 [-] twistd 22.4.0 (/buildbot_venv/bin/python 3.9.2) starting up.
buildbot_1  | 2022-06-08 17:15:57+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
buildbot_1  | 2022-06-08 17:15:57+0000 [-] Starting BuildMaster -- buildbot.version: 3.5.1-dev212
```

`master.cfg` is configured as follows:
```
f.addStep(steps.Git(
            repourl = REPO_URL,
            mode = 'full', method = 'copy',
            sshKnownHosts = util.Secret("known_hosts"),
            sshPrivateKey = util.Secret("id_rsa")))
```

Run-time python error (`builtins.ValueError`):
```
buildbot_1  | 2022-06-08 17:16:21+0000 [-] BuildStep.failed; traceback follows
buildbot_1  |   Traceback (most recent call last):
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 700, in errback
buildbot_1  |       self._startRunCallbacks(fail)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 763, in _startRunCallbacks
buildbot_1  |       self._runCallbacks()
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
buildbot_1  |       current.result = callback(  # type: ignore[misc]
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1750, in gotResult
buildbot_1  |       current_context.run(_inlineCallbacks, r, gen, status)
buildbot_1  |   --- <exception caught here> ---
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/process/buildstep.py", line 486, in startStep
buildbot_1  |       self.results = yield self.run()
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/steps/source/base.py", line 287, in run
buildbot_1  |       res = yield self.run_vc(branch, revision, patch)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/steps/source/git.py", line 141, in run_vc
buildbot_1  |       yield self._getAttrGroupMember('mode', self.mode)()
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/steps/source/git.py", line 158, in mode_full
buildbot_1  |       yield self.copy()
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/steps/source/git.py", line 257, in copy
buildbot_1  |       yield self.runCommand(cmd)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/process/buildstep.py", line 766, in runCommand
buildbot_1  |       res = yield command.run(self, self.remote, self.build.builder.name)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/process/remotecommand.py", line 164, in _finished
buildbot_1  |       yield self.remoteComplete(failure)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
buildbot_1  |       result = current_context.run(
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
buildbot_1  |       return g.throw(self.type, self.value, self.tb)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/steps/source/base.py", line 287, in run
buildbot_1  |       res = yield self.run_vc(branch, revision, patch)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
buildbot_1  |       result = current_context.run(gen.send, result)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/steps/source/git.py", line 141, in run_vc
buildbot_1  |       yield self._getAttrGroupMember('mode', self.mode)()
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
buildbot_1  |       result = current_context.run(
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
buildbot_1  |       return g.throw(self.type, self.value, self.tb)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/steps/source/git.py", line 158, in mode_full
buildbot_1  |       yield self.copy()
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
buildbot_1  |       result = current_context.run(
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
buildbot_1  |       return g.throw(self.type, self.value, self.tb)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/steps/source/git.py", line 257, in copy
buildbot_1  |       yield self.runCommand(cmd)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
buildbot_1  |       result = current_context.run(
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
buildbot_1  |       return g.throw(self.type, self.value, self.tb)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/process/buildstep.py", line 766, in runCommand
buildbot_1  |       res = yield command.run(self, self.remote, self.build.builder.name)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/process/remotecommand.py", line 164, in _finished
buildbot_1  |       yield self.remoteComplete(failure)
buildbot_1  |   buildbot.process.remotecommand.RemoteException: b'builtins.ValueError': CopyDirectory is missing args: to_path
buildbot_1  |   Traceback unavailable
```

Based on this trace, it appears `CopyDirectory` does not work when attempting to copy `source` directory to `build`.

**Comment by schanzen** [comment]
I can confirm this is happening to us as well after an update to 3.6.0

**Comment by schanzen** [comment]
This is the offending commit: https://github.com/buildbot/buildbot/commit/9deed41fe7655f69b1d5d139baa15e633019ca15
It the arguments have not been changed in the cms logic, e.g. https://github.com/buildbot/buildbot/blob/master/master/buildbot/steps/source/git.py#L251

**Comment by randarnold** [comment]
For anybody else that runs into this and attempts to go back to 3.5

I attempted to uninstall and then buildbot 3.5 with mixed success.

My buildbot is now building again, however while the worker is at 3.5, the master is still at 3.6

pip uninstall buildbot                
Found existing installation: buildbot 3.6.0
Uninstalling buildbot-3.6.0:
...
Successfully uninstalled buildbot-3.6.0

pip install -Iv buildbot==3.5
Collecting buildbot==3.5
  Using cached buildbot-3.5.0-py3-none-any.whl (982 kB)
...
Successfully installed ... buildbot-3.6.0 ...

pip uninstall buildbot
pip uninstall buildbot-worker
pip uninstall buildbot-www
pip uninstall buildbot-waterfall
pip uninstall buildbot-console_view
pip uninstall buildbot-grid_view

pip install -Iv buildbot==3.5
pip install -Iv buildbot-worker==3.5
pip install -Iv buildbot-www==3.5
pip install -Iv buildbot-waterfall-view==3.5
pip install -Iv buildbot-console_view==3.5
pip install -Iv buildbot-grid_view==3.5

**Comment by p12tic** [comment]
@randarnold @minyang Thanks for bug report. The issue should be fixed in https://github.com/buildbot/buildbot/issues/6539.
