### ISSUE TITLE
BitBucket hook fails

### ISSUE THREAD

**Issue by kiinoda** [buildbot/buildbot#6606]
I have set up a BitBucket hook and, upon triggering the hook, Buildbot  fails with the error below:

```log
2022-08-16 11:40:32+0200 [_GenericHTTPChannelProtocol,2,18.246.31.231] adding changes from web hook
	Traceback (most recent call last):
	 File "/home/app/buildbot/master/sandbox/lib/python3.8/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
	   result = current_context.run(gen.send, result)
	 File "/home/app/buildbot/master/sandbox/lib/python3.8/site-packages/buildbot/www/change_hook.py", line 107, in getAndSubmitChanges
	   changes, src = yield self.getChanges(request)
	 File "/home/app/buildbot/master/sandbox/lib/python3.8/site-packages/twisted/internet/defer.py", line 1905, in unwindGenerator
	   return _cancellableInlineCallbacks(gen)
	 File "/home/app/buildbot/master/sandbox/lib/python3.8/site-packages/twisted/internet/defer.py", line 1815, in _cancellableInlineCallbacks
	   _inlineCallbacks(None, gen, status)
	--- <exception caught here> ---
	 File "/home/app/buildbot/master/sandbox/lib/python3.8/site-packages/buildbot/www/change_hook.py", line 107, in getAndSubmitChanges
	   changes, src = yield self.getChanges(request)
	 File "/home/app/buildbot/master/sandbox/lib/python3.8/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
	   result = current_context.run(gen.send, result)
	 File "/home/app/buildbot/master/sandbox/lib/python3.8/site-packages/buildbot/www/change_hook.py", line 168, in getChanges
	   changes, src = yield handler.getChanges(request)
	 File "/home/app/buildbot/master/sandbox/lib/python3.8/site-packages/buildbot/www/hooks/bitbucket.py", line 46, in getChanges
	   print(bytes2unicode(request.args[b'payload'][0]))
	builtins.KeyError: b'payload'
```

Further investigation indicated that the actual API at BitBucket has changed. I managed to fix it on my local installation and would like to submit a patch. Here's the BitBucket API docs - https://atlassian.com/bitbucket-cloud/docs/event-payloads/#Push

The patch I want to submit is below.

The questions I have:

* not sure on the workflow since http://trac.buildbot.net/wiki/SubmittingPatches is dead.
* not sure on what to add to the `files[]` property of the change since BitBucket does NOT send changed files in the payload
* not sure what I should add to the `revlink` property of the change

Would someone please advise. Thanks!

```diff
diff --git a/master/bitbucket_orig.py b/master/sandbox/lib/python3.8/site-packages/buildbot/www/hooks/bitbucket.py
index 374f312..aa1f5a1 100644
--- a/master/bitbucket_orig.py
+++ b/master/sandbox/lib/python3.8/site-packages/buildbot/www/hooks/bitbucket.py
@@ -41,30 +41,33 @@ class BitBucketHandler(BaseHookHandler):
 
         event_type = request.getHeader(_HEADER_EVENT)
         event_type = bytes2unicode(event_type)
-        payload = json.loads(bytes2unicode(request.args[b'payload'][0]))
-        repo_url = f"{payload['canon_url']}{payload['repository']['absolute_url']}"
+        content = request.content.read()
+        content = bytes2unicode(content)
+        payload = json.loads(content)
+        repo_url = f"{payload['repository']['links']['html']['href']}"
         project = request.args.get(b'project', [b''])[0]
         project = bytes2unicode(project)
 
         changes = []
-        for commit in payload['commits']:
-            changes.append({
-                'author': commit['raw_author'],
-                'files': [f['file'] for f in commit['files']],
-                'comments': commit['message'],
-                'revision': commit['raw_node'],
-                'when_timestamp': dateparse(commit['utctimestamp']),
-                'branch': commit['branch'],
-                'revlink': f"{repo_url}commits/{commit['raw_node']}",
-                'repository': repo_url,
-                'project': project,
-                'properties': {
-                    'event': event_type,
-                },
-            })
-            log.msg(f"New revision: {commit['node']}")
-
-        log.msg(f'Received {len(changes)} changes from bitbucket')
+        for chg in payload['push']['changes']:
+            for commit in chg['commits']:
+                changes.append({
+                    'author': commit['author']['raw'],
+                    'files': [],
+                    'comments': commit['message'],
+                    'revision': commit['hash'],
+                    'when_timestamp': dateparse(commit['date']),
+                    'branch': chg['new']['name'],
+                    'revlink': f"",
+                    'repository': repo_url,
+                    'project': project,
+                    'properties': {
+                        'event': event_type,
+                    },
+                })
+                log.msg(f"New revision: {commit['hash']}")
+
+        log.msg(f'Received {len(changes)} changes from bitbucket')
         return (changes, payload['repository']['scm'])
```

**Comment by p12tic** [comment]
Hi, thanks for the bug report.

Could it be that you need to use `bitbucketcloud` hook instead of the `bitbucket` hook?

**Comment by p12tic** [comment]
@kiinoda just a friendly ping.. :-)

**Comment by kiinoda** [comment]
I'll take a look and report back.

**Comment by kiinoda** [comment]
@p12tic You're correct, that was the proper course of action. On the bright side, I now have a better understanding on Buildbot. :)
