### ISSUE TITLE
 triggerable step with docker latent worker   

### ISSUE THREAD

**Issue by romankln** [buildbot/buildbot#6638]
Python version: 3.10.4
Buildbot version: 3.5.0
Twisted version: 22.4.0

In my buildbot setup I have added Docker Latent worker with custom docker image. 
           
```
worker.DockerLatentWorker('fw-build-docker-sign', '<password>',
                                              docker_host='tcp://fw-build-d2:2375',
                                              image='buildbot-worker/sign',
                                              volumes=['/home/build/.azure:/home/build/.azure',
                                                            '/home/build/packages:/home/build/packages',
                                                            '/mnt/artifacts:/mnt/artifacts'],
                                               hostconfig={'network_mode': 'host'},
                                               followStartupLogs=True,
                                               max_builds=1,
                                               hostname='signing_docker_worker'),
 
```

All is working as expected except for the triggerable step which is in use to call the builder on this worker, sometimes the step returns success without actually running the triggered build. The main build is waiting for some time (20-40 seconds) to get the worker available and sometimes returns success without invoking the build.
            
```
f.addStep(steps.Trigger(name="Signing %s packages" % t1,
                                    schedulerNames=['signing_docker_scheduler'],
                                    waitForFinish=True,
                                    sourceStamps=[{'revision': Property('sdk'), 'codebase': ''}],
                                    set_properties={'factory': util.Property('%sfactorypackage' % t1),
                                                    'field': util.Property('%sfieldpackage' % t1),
                                                    'target': Property('target'),
                                                    'TYPE': t1,
                                                    'dst_folder': Property('nbf'),
                                                    'action': azure_sign_action,
                                                    },
                                    haltOnFailure=True))  
```

When there are more than one request for the build, sometimes the build does not run and it returns success and no build URL in the buildbot webUI shows up.
![image](https://user-images.githubusercontent.com/34251479/191377119-60d68d20-1069-4a29-913b-729f27630170.png)

I have been using steps.Trigger for a while and have not seen any issues with not docker based workers.

Might it be a buildbot issue ?

**Comment by romankln** [comment]
In an attempt to find a solution and following the issue https://github.com/buildbot/buildbot/issues/6486 I have added the following code
```
def collapseRequests(master, builder, req1, req2):
    return False

c['collapseRequests'] = collapseRequests
```
I have not seen a build returning success without actually running but at some point the following error appeared
`Traceback (most recent call last):
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1750, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/buildbot/steps/trigger.py", line 308, in run
    yield self.addLogWithException(e)
--- <exception caught here> ---
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/buildbot/steps/trigger.py", line 306, in run
    _, brids = yield idsDeferred
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/buildbot/schedulers/base.py", line 315, in addBuildsetForSourceStampsWithDefaults
    rv = yield self.addBuildsetForSourceStamps(
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/buildbot/schedulers/base.py", line 427, in addBuildsetForSourceStamps
    bsid, brids = yield self.master.data.updates.addBuildset(
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/buildbot/data/buildsets.py", line 156, in addBuildset
    yield BuildRequestCollapser(self.master, list(brids.values())).collapse()
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/buildbot/process/buildrequest.py", line 81, in collapse
    canCollapse = yield collapseRequestsFn(self.master, bldr, br, unclaim_br)
  File "/home/buildmaster/bb-master3/buildbot_venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1901, in unwindGenerator
    raise TypeError(
builtins.TypeError: inlineCallbacks requires <function collapseRequests at 0x7f97ef741a20> to produce a generator; instead got False` 
According to buildbot documentation collapseRequests can return False and it looks like a bug in trigger.py ?

**Comment by romankln** [comment]
Changing collapseRequests made the trick and now I am not getting builds become green before even triggering any steps.
```
def collapseRequests(master, builder, req1, req2):
    yield False

c['collapseRequests'] = collapseRequests
```
