### ISSUE TITLE
Reporter Error

### ISSUE THREAD

**Issue by jethornton** [buildbot/buildbot#6682]
Debian 12 Mate Desktop
Buildbot version: 3.5.0-1
Twisted version: 22.4.0

On startup I get this error from the reporter.
```
2022-11-19 09:20:15-0600 [IRC,IrcStatusBot] Joined #bbot
2022-11-19 09:20:15-0600 [IrcStatusBot,client] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 253, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 2616, in dataReceived
	    basic.LineReceiver.dataReceived(self, data)
	  File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 549, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 2628, in lineReceived
	    self.handleCommand(command, prefix, params)
	--- <exception caught here> ---
	  File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 2680, in handleCommand
	    method(prefix, params)
	  File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 1969, in irc_JOIN
	    self.joined(channel)
	  File "/usr/lib/python3/dist-packages/buildbot/reporters/irc.py", line 348, in joined
	    channel.add_notification_events(self.notify_events)
	  File "/usr/lib/python3/dist-packages/buildbot/reporters/words.py", line 196, in add_notification_events
	    self.validate_notification_event(event)
	  File "/usr/lib/python3/dist-packages/buildbot/reporters/words.py", line 147, in validate_notification_event
	    raise UsageError("Try '" + self.bot.commandPrefix + "notify on|off _EVENT_'.")
	buildbot.reporters.words.UsageError: Try 'notify on|off _EVENT_'.
```

master.cfg
```
c['services'] = []
c['services'].append(reporters.IRC(host="irc.libera.chat",
 nick="reporter", password='xxxxxxx',
 authz={'': True, 'force': True, 'notify': True, ('stop', 'shutdown'): ['fred-flintstone']},
 notify_events=['start', 'finish'], channels=[{"channel": "#xxxx"}]))
```

**Comment by jethornton** [comment]
The current docs say 
```
notify_events

    (optional) A list or set of events to be notified on the IRC channels. At the moment, irc bot can listen to build ‘start’ and ‘finish’ events.
```
which is misleading...

The code in buildbot/reporter/word.py says:
```
    def validate_notification_event(self, event):
        if not re.compile("^(started|finished|success|warnings|failure|exception|"
                          "cancelled|problem|recovery|worse|better|worker|"
                          # this is deprecated list
                          "(success|warnings|failure|exception)To"
                          "(Success|Warnings|Failure|Exception))$").match(event):
            raise UsageError("Try '" + self.bot.commandPrefix + "notify on|off _EVENT_'.")
```

So the documents are broken, Are the docs in github so a pr can be added to fix the error or are they built automagicly?

JT

**Comment by jethornton** [comment]
PR to fix misleading docs.

JT
