### ISSUE TITLE
Exception while adding new user

### ISSUE THREAD

**Issue by ml86** [buildbot/buildbot#6768]
Hi,

i am running buildbot 3.7.0 on python 3.10.9 with twisted 22.10.0.
When i try to add a new user via `buildbot user --master localhost:9989 --op=add --username=user1 --passwd=pass --info=email=a@b.c` i get:
```
Traceback (most recent call last):
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 696, in callback
    self._startRunCallbacks(result)
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 798, in _startRunCallbacks
    self._runCallbacks()
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 1792, in gotResult
    _inlineCallbacks(r, gen, status, context)
--- <exception caught here> ---
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/buildbot/scripts/user.py", line 47, in user
    output = yield uc.send(op, bb_username, bb_password, ids, info)
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/twisted/spread/pb.py", line 1370, in _cbResponse
    return challenger.callRemote("respond", respond(challenge, password), client)
  File "/home/ml/buildbot-test/master_root/sandbox/lib/python3.10/site-packages/twisted/spread/pb.py", line 1253, in respond
    m.update(password)
builtins.TypeError: Strings must be encoded before hashing


Am I doing something wrong? If not is there a workaround?

**Comment by akshaya-hub** [comment]
can you assign me

**Comment by akshaya-hub** [comment]
buildbot user --master localhost:9989 --op=add --username=user1 --passwd=pass --info=email=a@b.c --passwdencoding=utf-8
 TRY THIS

**Comment by ml86** [comment]
Thank you for the suggestion but `--passwdencoding` is not even defined as parameter. So no need for anybody else to try this.
As it turns out this was anyway not what i wanted. I was looking for any way of user authentication and finally found https://docs.buildbot.net/latest/manual/configuration/www.html#authentication-plugins which fits my needs.
