### ISSUE TITLE
Error while decoding JWT session

### ISSUE THREAD

**Issue by felixsinger** [buildbot/buildbot#6872]
I get this error in the twistd.log during the startup. I am using Buildbot 3.8.0.

```
2023-05-14 08:08:50+0200 [_GenericHTTPChannelProtocol,0,127.0.0.1] while decoding JWT session
	Traceback (most recent call last):
	  File "/home/buildbot/testmaster/lib/python3.10/site-packages/twisted/web/server.py", line 521, in getSession
	    session = self.site.getSession(sessionCookie)
	  File "/home/buildbot/testmaster/lib/python3.10/site-packages/buildbot/www/service.py", line 178, in getSession
	    return BuildbotSession(self, uid)
	  File "/home/buildbot/testmaster/lib/python3.10/site-packages/buildbot/www/service.py", line 74, in __init__
	    self._fromToken(token)
	  File "/home/buildbot/testmaster/lib/python3.10/site-packages/buildbot/www/service.py", line 88, in _fromToken
	    log.err(e, "while decoding JWT session")
	--- <exception caught here> ---
	  File "/home/buildbot/testmaster/lib/python3.10/site-packages/buildbot/www/service.py", line 83, in _fromToken
	    decoded = jwt.decode(token, self.site.session_secret, algorithms=[
	  File "/home/buildbot/testmaster/lib/python3.10/site-packages/jwt/api_jwt.py", line 210, in decode
	    decoded = self.decode_complete(
	  File "/home/buildbot/testmaster/lib/python3.10/site-packages/jwt/api_jwt.py", line 151, in decode_complete
	    decoded = api_jws.decode_complete(
	  File "/home/buildbot/testmaster/lib/python3.10/site-packages/jwt/api_jws.py", line 209, in decode_complete
	    self._verify_signature(signing_input, header, signature, key, algorithms)
	  File "/home/buildbot/testmaster/lib/python3.10/site-packages/jwt/api_jws.py", line 310, in _verify_signature
	    raise InvalidSignatureError("Signature verification failed")
	jwt.exceptions.InvalidSignatureError: Signature verification failed
```

**Comment by GoofyBluff** [comment]
The error message is indicating there is a problem decoding JWT session. You should investigate the code that generates and verifies the JWT tokens. Ensure that the correct signing key and algorithm are being used consistently. You can also regenerate the token or update the verification logic to address the signature verification failure.

**Comment by p12tic** [comment]
The error message has been improved in https://github.com/buildbot/buildbot/pull/6909. Most likely the internal buildbot secret has changed and after buildbot has been started the old clients still attempt to reconnect, resulting in the exception.
