### ISSUE TITLE
random-like UTF-8 problem when starting workers

### ISSUE THREAD

**Issue by Try2Code** [buildbot/buildbot#6932]
Hi!

I run a server with multiple workers on identical hard/software. When connecting these workers some refuse to connect with the following log:
```txt
2023-07-10 15:04:33+0200 [-] Loading buildbot.tac...
2023-07-10 15:04:33+0200 [-] Loaded.
2023-07-10 15:04:33+0200 [-] twistd 22.10.0 (/home/m/m21AAAA/.conda/envs/bb-3.11/bin/python3.11 3.11.4) starting up.
2023-07-10 15:04:33+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2023-07-10 15:04:33+0200 [-] Starting Worker -- version: 3.8.0
2023-07-10 15:04:33+0200 [-] recording hostname in twistd.hostname
2023-07-10 15:04:33+0200 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x7f8b07c0bc10>
2023-07-10 15:04:33+0200 [Broker,client] message from master: attached
2023-07-10 15:04:33+0200 [Broker,client] Peer will receive following PB traceback:
2023-07-10 15:04:33+0200 [Broker,client] Unhandled Error
        Traceback (most recent call last):
          File "/home/m/m21AAAA/.conda/envs/bb-3.11/lib/python3.11/site-packages/twisted/spread/banana.py", line 176, in gotItem
            self.callExpressionReceived(item)
          File "/home/m/m21AAAA/.conda/envs/bb-3.11/lib/python3.11/site-packages/twisted/spread/banana.py", line 137, in callExpressionReceived
            self.expressionReceived(obj)
          File "/home/m/m21AAAA/.conda/envs/bb-3.11/lib/python3.11/site-packages/twisted/spread/pb.py", line 607, in expressionReceived
            method(*sexp[1:])
          File "/home/m/m21AAAA/.conda/envs/bb-3.11/lib/python3.11/site-packages/twisted/spread/pb.py", line 999, in proto_message
            self._recvMessage(
        --- <exception caught here> ---
          File "/home/m/m21AAAA/.conda/envs/bb-3.11/lib/python3.11/site-packages/twisted/spread/pb.py", line 1053, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "/home/m/m21AAAA/.conda/envs/bb-3.11/lib/python3.11/site-packages/twisted/spread/flavors.py", line 131, in remoteMessageReceived
            state = method(*args, **kw)
          File "/home/m/m21AAAA/.conda/envs/bb-3.11/lib/python3.11/site-packages/buildbot_worker/base.py", line 222, in remote_getWorkerInfo
            files[f] = fin.read()
          File "<frozen codecs>", line 322, in decode

        builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 3: invalid start byte

2023-07-10 15:04:33+0200 [Broker,client] ReconnectingPBClientFactory.failedToGetPerspective
2023-07-10 15:04:33+0200 [Broker,client] While trying to connect:
        Traceback from remote host -- twisted.spread.pb.RemoteError: 'utf-8' codec can't decode byte 0x9f in position 3: invalid start byte

2023-07-10 15:04:33+0200 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x7f8b07c0bc10>
2023-07-10 15:04:33+0200 [-] Main loop terminated.
2023-07-10 15:04:33+0200 [-] Server Shut Down.
```

my starting command is `TERM=xterm buildbot-worker start $(pwd)`. I also tested with `export LANG=C` but error is persistent.

This log is from a python-3.11 test setup. 

The production version throws this error with python-3.10:

```txt
2023-07-10 15:24:05+0200 [-] Loaded.
2023-07-10 15:24:05+0200 [-] twistd 22.2.0 (/home/m/m21AAAA/.conda/envs/buildbot-worker/bin/python3.10 3.10.9) starting up.
2023-07-10 15:24:05+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2023-07-10 15:24:05+0200 [-] Starting Worker -- version: 3.7.0
2023-07-10 15:24:05+0200 [-] recording hostname in twistd.hostname
2023-07-10 15:24:05+0200 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x7f725e708100>
2023-07-10 15:24:05+0200 [Broker,client] message from master: attached
2023-07-10 15:24:05+0200 [Broker,client] Peer will receive following PB traceback:
2023-07-10 15:24:05+0200 [Broker,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/m/m21AAAA/.conda/envs/buildbot-worker/lib/python3.10/site-packages/twisted/spread/banana.py", line 176, in gotItem
	    self.callExpressionReceived(item)
	  File "/home/m/m21AAAA/.conda/envs/buildbot-worker/lib/python3.10/site-packages/twisted/spread/banana.py", line 137, in callExpressionReceived
	    self.expressionReceived(obj)
	  File "/home/m/m21AAAA/.conda/envs/buildbot-worker/lib/python3.10/site-packages/twisted/spread/pb.py", line 607, in expressionReceived
	    method(*sexp[1:])
	  File "/home/m/m21AAAA/.conda/envs/buildbot-worker/lib/python3.10/site-packages/twisted/spread/pb.py", line 999, in proto_message
	    self._recvMessage(
	--- <exception caught here> ---
	  File "/home/m/m21AAAA/.conda/envs/buildbot-worker/lib/python3.10/site-packages/twisted/spread/pb.py", line 1053, in _recvMessage
	    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
	  File "/home/m/m21AAAA/.conda/envs/buildbot-worker/lib/python3.10/site-packages/twisted/spread/flavors.py", line 131, in remoteMessageReceived
	    state = method(*args, **kw)
	  File "/home/m/m21AAAA/.conda/envs/buildbot-worker/lib/python3.10/site-packages/buildbot_worker/base.py", line 222, in remote_getWorkerInfo
	    files[f] = fin.read()
	  File "/home/m/m21AAAA/.conda/envs/buildbot-worker/lib/python3.10/codecs.py", line 322, in decode
	    (result, consumed) = self._buffer_decode(data, self.errors, final)
	builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 3: invalid start byte
	
2023-07-10 15:24:05+0200 [Broker,client] ReconnectingPBClientFactory.failedToGetPerspective
2023-07-10 15:24:05+0200 [Broker,client] While trying to connect:
	Traceback from remote host -- twisted.spread.pb.RemoteError: 'utf-8' codec can't decode byte 0x9f in position 3: invalid start byte
	
2023-07-10 15:24:05+0200 [-] Stopping factory <buildbot_worker.pb.BotFactory object at 0x7f725e708100>
2023-07-10 15:24:05+0200 [-] Main loop terminated.
2023-07-10 15:24:05+0200 [-] Server Shut Down.
```
Hence: same error with different versions of the worker software and different python versions.

Server info:
- Python version: 3.10.9
- Buildbot version: 3.6.0
- Twisted version: 22.10.0

I searched around but could not find any further input on this. Any ideas and tips are welcome!

thx

**Comment by Try2Code** [comment]
By accident I noticed, that I can get avoid the error, when I remove the `info` directory on the client side. The error also does not show up, when I create the info directory with `buildbot-worker create-worker` and leave it unchanged. But as soon as I edit the two textfiles (keeping them pure ASCII) the error is there again.
