### ISSUE TITLE
Buildbot integration issue with Rhodecode 

### ISSUE THREAD

**Issue by samala-praveen-reddy** [buildbot/buildbot#7106]
**Buildbot integration issue with Rhodecode **
=======================================

2023-09-13 09:20:13.667 [281630] INFO  [rhodecode.config.environment] Enabled VCS backends: ['hg', 'git']

2023-09-13 09:20:13.699 [281631] INFO  [rhodecode.model] RhodeCode 4.27.1 initializing db for postgresql://rhodecode:XXXXX@rhoadcode-db.test.kfupm.edu.sa:5432/rhodecode

2023-09-13 09:20:13.703 [281631] INFO  [root] before importin buildbot

2023-09-13 09:20:13.712 [281631] ERROR [root] exception occurred while importing

Traceback (most recent call last):

  File "/home/code/.rccontrol/community-1/rcextensions/hooks.py", line 26, in <module>

    from .buildbot_hook import logger, BuildDirector, add_buildbot_venv_to_python_path

  File "/opt/rhodecode/store/ask5fwcnxkqhi9g6py5hg6a9xbd5xrz2-python2.7-gevent-1.5.0/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__

    result = _import(*args, **kwargs)

  File "/home/code/.rccontrol/community-1/rcextensions/buildbot_hook.py", line 16, in <module>

    from buildbot.clients import sendchange

  File "/opt/rhodecode/store/ask5fwcnxkqhi9g6py5hg6a9xbd5xrz2-python2.7-gevent-1.5.0/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__

    result = _import(*args, **kwargs)

ImportError: No module named buildbot.clients

printing exception No module named buildbot.clients

from .buildbot_hook import logger, BuildDirector, add_buildbot_venv_to_python_path

**Comment by p12tic** [comment]
Thank you for the bug report. It seems that the error comes from `/home/code/.rccontrol/community-1/rcextensions/buildbot_hook.py` file which is not part of Buildbot. You should contact whoever wrote that file.

Additionally, I see that you're running code in Python 2.7. Buildbot no longer supports Python 2.7 version, only 3.7 and newer.
