### ISSUE TITLE
Cannot get values ​​from a long JSON string (more than 4096 bytes)

### ISSUE THREAD

**Issue by ivanov17** [buildbot/buildbot#7192]
Hello again. I need to parse JSON file generated on the worker to get several properties. Unfortunately, the file contains a very long JSON string. 

To do this I use the `SetPropertyFromCommand` step which performs `cat` command on the worker and then try to parse the output using a lambda function placed in the `extract_fn` parameter:

```python
steps.SetPropertyFromCommand(
    name='location-properties',
    description=['getting', 'locations'],
    command=['cat', 'file.json'],
    extract_fn=lambda rc, stdout, stderr: dict((k, v) for k, v in list(
        json.loads(stdout.strip()).items()) if k in (
            'key1', 'key2', 'key3')),
    logEnviron=False, haltOnFailure=True
)
```

When executing the step I got an exception:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1792, in gotResult
    _inlineCallbacks(r, gen, status, context)
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "/usr/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/usr/lib/python3.11/site-packages/buildbot/process/buildstep.py", line 486, in startStep
    self.results = yield self.run()
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/usr/lib/python3.11/site-packages/buildbot/steps/shell.py", line 131, in run
    new_props = self.extract_fn(cmd.rc,
  File "/data/master.cfg", line 626, in <lambda>
    json.loads(stdout.strip()).items()) if k in (
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 4096 (char 4095)
```
I think this must be related to https://github.com/buildbot/buildbot/pull/3521 because it introduces line splitting:

https://github.com/buildbot/buildbot/blob/3bc2181a6ee38381a72272f31923ee599d61c7e0/master/buildbot/util/lineboundaries.py#L30-L32

Accordingly, I tried to correct my code to join multiple lines received from the worker on the master:

```python
steps.SetPropertyFromCommand(
    name='location-properties',
    description=['getting', 'locations'],
    command=['cat', 'file.json'],
    extract_fn=lambda rc, stdout, stderr: dict((k, v) for k, v in list(
        json.loads(''.join(stdout.splitlines())).items()) if k in (
            'key1', 'key2', 'key3')),
    logEnviron=False, haltOnFailure=True
)
```

Then I got the following exception:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1792, in gotResult
    _inlineCallbacks(r, gen, status, context)
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "/usr/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/usr/lib/python3.11/site-packages/buildbot/process/buildstep.py", line 486, in startStep
    self.results = yield self.run()
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/usr/lib/python3.11/site-packages/buildbot/steps/shell.py", line 131, in run
    new_props = self.extract_fn(cmd.rc,
  File "/data/master.cfg", line 626, in <lambda>
    json.loads(''.join(stdout.splitlines())).items()) if k in (
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 8194 (char 8193)
```

It looks like the lines are being returned in the wrong order, so the concatenated JSON string is broken. 

At least as far as I can see, in the stdio output the end and beginning of the lines do not match.

The JSON string in the generated file is correct.

```
$ buildbot --version
Buildbot version: 3.9.2
Twisted version: 22.10.0
```

**Comment by ivanov17** [comment]
I compared the source file and the output as it appears in the Web UI. This is even more interesting than I thought. 

In the output the JSON string is divided into lines containing 4096 characters. But only odd lines and the last line (even) are displayed. So, out of 20 parts of the JSON string, I only see 11. To be more precise, the following parts are displayed: 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 20. All other parts are lost.

I think in cases like this it would be useful to have something like a `SetPropertiesFromEnv` step, but for JSON files. This would avoid passing long strings to the master.

**Comment by aj062** [comment]
We also hit this issue recently when we upgraded `buildbot-worker` package from 2.10.5 to 4.3.0. See:  https://bugs.webkit.org/show_bug.cgi?id=302654

It's a regression in `buildbot-worker` version 3.6.0 caused specifically by https://github.com/buildbot/buildbot/pull/6580

In that PR the buildbot-worker package started splitting the long lines (longer than 4096 characters), which caused this regression. PR description also says: `Now splitting of update output lines is done on worker side`

cc @p12tic @mokibit @clopez

**Comment by aj062** [comment]
@p12tic @mokibit is it possible to revert https://github.com/buildbot/buildbot/pull/6580 ?

**Comment by tdesveaux** [comment]
Closing in favor of #8996 and #8997 that will serve as central point around this issue.
