### ISSUE TITLE
SSL build issue. Works with legacy SSL.

### ISSUE THREAD

**Issue by gl-yziquel** [buildbot/buildbot#7247]
I experienced the following build failure:

```console
cd buildbot-master/www/waterfall_view && yarnpkg run build
yarn run v1.22.19
$ rimraf buildbot_waterfall_view/static && webpack --bail --progress --profile --env prod
10% building 0/2 modules 2 active ...el/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/import-glob-loader/index.js!/home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/src/styles/styles.less
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/mini-me/home/backyard/hephaestus/buildbot-master/www/waterfall_view/node_modules/babel-loader/lib/index.js:55:71
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error: Recipe `build` failed on line 9 with exit code 1
error: Recipe `build` failed on line 2 with exit code 1
```

Machine information:

```console
mini-me@virtucon ~/h/b/hephaestus> uname -a
Linux virtucon 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Build instructions:

```console
cd buildbot
make frontend_deps
cd www/waterfall_view
yarn install
yarnpkg run build
```

The fix is to add `export SET NODE_OPTIONS=--openssl-legacy-provider` in build script of package.json of waterfall_view. See PR https://github.com/buildbot/buildbot/pull/7246

However, I believe this fix comes with security flaws, from what I've read on the net.

**Comment by mokibit** [comment]
Hi, @gl-yziquel,
this issue was only relevant when AngularJS frontend was used for Buildot UI in older versions. 
Now React frontend is used and AngularJS has been removed recently (https://github.com/buildbot/buildbot/pull/7287), therefore I will close this issue.

**Comment by mokibit** [comment]
I removed all these workarounds in https://github.com/buildbot/buildbot/pull/7297 as AngularJS is not used anymore.

**Comment by gl-yziquel** [comment]
cool. this did confuse me when diving into that.

**Comment by gl-yziquel** [comment]
Just tried out the latest `HEAD`. The installation instruction by default on the web site still rely in some way on `www` and not on `react-www`. Still have not tried configuring `master.cfg`, but I do not see in the `master.cfg.sample` which is deployed with `buildbot create-master` a way to ensure it depends on `www` and not `react-www`.

**Comment by mokibit** [comment]
This problem is not connected to SSL. 
Migration to `react-www` is still ongoing, so there might be some minor problems until 4.0 as there is more work on the way.

**Comment by gl-yziquel** [comment]
It was connected to ubuntu 22.04. The ssl problem disappeared when building on ubuntu 23.04.
