### ISSUE TITLE
"should create a build with a dedicated reason and stop it during execution" e2e test fails on webkit

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#7307]
After recent test flakiness fixes this test fails much more frequently than before. E.g. https://buildbot.buildbot.net/#/builders/123/builds/899.

```
[37/51] [webkit] › buildsnavigation.spec.ts:53:7 › forceandstop › should create a build with a dedicated reason and stop it during execution
1) [webkit] › buildsnavigation.spec.ts:53:7 › forceandstop › should create a build with a dedicated reason and stop it during execution
Test timeout of 30000ms exceeded.
Error: locator.click: Test timeout of 30000ms exceeded.
Call log:
- waiting for locator('button:text("Stop")')
at pages/builder.ts:127
125 |
126 | static async clickStopButton(page: Page) {
> 127 | await page.locator('button:text("Stop")').click();
| ^
128 | }
129 |
130 | static async clickPreviousButtonAndWait(page: Page) {
at Function.clickStopButton (/buildbot/buildbot-job/build/smokes-react/tests/pages/builder.ts:127:47)
at /buildbot/buildbot-job/build/smokes-react/tests/buildsnavigation.spec.ts:58:23
[38/51] [webkit] › home.spec.ts:24:7 › home page › should go to the home page and check if panel with builder name exists
```

**Comment by p12tic** [comment]
Test has been disabled in https://github.com/buildbot/buildbot/pull/7352, should be re-enabled when issue is fixed.
