### ISSUE TITLE
"force and cancel › should create a build with a dedicated reason and Start it" e2e test fails on webkit

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#7355]
E.g. https://buildbot.buildbot.net/#/builders/127/builds/40.

```
[43/51] [webkit] › reason_force.spec.ts:45:7 › force and cancel › should create a build with a dedicated reason and Start it
1) [webkit] › reason_force.spec.ts:45:7 › force and cancel › should create a build with a dedicated reason and Start it
Error: builds are no longer running
expect(received).toBeTruthy()
Received: false
Call Log:
- Timeout 15000ms exceeded while waiting on the predicate
at pages/home.ts:42
40 | }, {
41 | message: "builds are no longer running"
> 42 | }).toBeTruthy();
| ^
43 | }
44 | }
45 |
at Function.waitAllBuildsFinished (/buildbot/buildbot-job/build/smokes-react/tests/pages/home.ts:42:8)
at /buildbot/buildbot-job/build/smokes-react/tests/reason_force.spec.ts:25:5
```

**Comment by p12tic** [comment]
Test disabled in https://github.com/buildbot/buildbot/pull/7352, should be re-enabled when issue is fixed.

**Comment by mokibit** [comment]
Tests were enabled in https://github.com/buildbot/buildbot/pull/7443.
This issue was fixed by https://github.com/buildbot/buildbot/pull/7434.
