### ISSUE TITLE
buildbot-worker fails with exception in _render_renderables

### ISSUE THREAD

**Issue by glaubitz** [buildbot/buildbot#7372]
This may not be a bug in buildbot itself but probably a configuration issue, but I'm posting it here anyways in the hope that someone will be able to help.

The buildbot-worker for building LLVM on Linux sparc64 (Debian unstable) triggers an exception with the following backtrace:

```
Traceback (most recent call last):
--- <exception caught here> ---
  File "/Users/buildbot/buildbot/master/buildbot/process/buildstep.py", line 513, in startStep
    yield self._render_renderables()
  File "/Users/buildbot/buildbot/master/buildbot/process/buildstep.py", line 637, in _render_renderables
    yield defer.gatherResults(dl)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#4, [Failure instance: Traceback: <class 'TypeError'>: expected str, bytes or os.PathLike object, not DeferredList
/Users/buildbot/venv/lib/python3.11/site-packages/twisted/internet/defer.py:206:maybeDeferred
/Users/buildbot/buildbot/master/buildbot/process/properties.py:938:getRenderingFor
/Users/buildbot/buildbot/master/buildbot/process/properties.py:938:<listcomp>
/Users/buildbot/buildbot/master/buildbot/process/properties.py:209:render
--- <exception caught here> ---
/Users/buildbot/venv/lib/python3.11/site-packages/twisted/internet/defer.py:206:maybeDeferred
/Users/buildbot/llvm-zorg/zorg/buildbot/process/properties.py:48:getRenderingFor
<frozen posixpath>:54:normcase
]]
]]
```

The full output from the buildbot-worker in question can be found in [1]. I appreciate any advise that would help me resolve this issue.

> [1] https://lab.llvm.org/staging/#/builders/159/builds/12

**Comment by glaubitz** [comment]
Seems like this issue was resolved on the server side. Works now.
