### ISSUE TITLE
Docker: `could not find buildbot-www`

### ISSUE THREAD

**Issue by senyai** [buildbot/buildbot#7396]
Hello!

 I'm using "buildbot/buildbot-master:master" and I'm seeing this error in the logs:

```
...
buildbot_1  | 2024-01-25 13:57:06+0000 [-] adding 1 new change_sources, removing 0
buildbot_1  | 2024-01-25 13:57:06+0000 [-] gitpoller: using workdir '/buildbot/gitpoller-workdir'
buildbot_1  | 2024-01-25 13:57:06+0000 [-] adding 1 new builders, removing 0
buildbot_1  | 2024-01-25 13:57:06+0000 [-] adding 2 new schedulers, removing 0
buildbot_1  | 2024-01-25 13:57:06+0000 [-] while starting BuildMaster
buildbot_1  |   Traceback (most recent call last):
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 2000, in _inlineCallbacks
buildbot_1  |       result = context.run(gen.send, result)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/util/service.py", line 48, in reconfigServiceWithBuildbotConfig
buildbot_1  |       yield svc.reconfigServiceWithBuildbotConfig(new_config)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 2256, in unwindGenerator
buildbot_1  |       return _cancellableInlineCallbacks(gen)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 2168, in _cancellableInlineCallbacks
buildbot_1  |       _inlineCallbacks(None, gen, status, _copy_context())
buildbot_1  |   --- <exception caught here> ---
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/master.py", line 312, in startService
buildbot_1  |       yield self.reconfigServiceWithBuildbotConfig(self.config)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/util/service.py", line 48, in reconfigServiceWithBuildbotConfig
buildbot_1  |       yield svc.reconfigServiceWithBuildbotConfig(new_config)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 2000, in _inlineCallbacks
buildbot_1  |       result = context.run(gen.send, result)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/www/service.py", line 225, in reconfigServiceWithBuildbotConfig
buildbot_1  |       self.setupSite(new_config)
buildbot_1  |     File "/buildbot_venv/lib/python3.9/site-packages/buildbot/www/service.py", line 318, in setupSite
buildbot_1  |       raise RuntimeError("could not find buildbot-www; is it installed?")
buildbot_1  |   builtins.RuntimeError: could not find buildbot-www; is it installed?
buildbot_1  |
buildbot_1  | 2024-01-25 13:57:06+0000 [-] BuildMaster startup failed
buildbot_1  | 2024-01-25 13:57:06+0000 [-] Initiating clean shutdown
buildbot_1  | 2024-01-25 13:57:06+0000 [-] No running jobs, starting shutdown immediately
buildbot_1  | 2024-01-25 13:57:06+0000 [-] BuildMaster is stopped
buildbot_1  | 2024-01-25 13:57:06+0000 [-] Main loop terminated.
buildbot_1  | 2024-01-25 13:57:06+0000 [-] Server Shut Down.
```

At [Dockerfile.master](https://github.com/buildbot/buildbot/blob/master/Dockerfile.master) I see a comment saying that UI is installed from pypi, but I can't see where exactly UI is installed.

**Comment by senyai** [comment]
Wait a minute. I see, it's `ls -1 | grep -v 'buildbot-worker'`. And there must be no `buildbot-www`. I believe `ls -1 | grep -v 'buildbot-worker'` should be replaced with exact list of packages, so that when something fails an error is seen early.

**Comment by senyai** [comment]
I'm seeing this error, when trying to build `Dockerfile.master`:
```
Step 9/21 : RUN cd /usr/src/buildbot && make tarballs
 ---> Running in dc1832373711
make: *** No rule to make target 'tarballs'.  Stop.
The command '/bin/sh -c cd /usr/src/buildbot && make tarballs' returned a non-zero code: 2
```

**Comment by hollie** [comment]
Hi,

confirming I am running into the same issue. I'm attempting to follow the buildbot tutorial with docker that is documented [here](https://docs.buildbot.net/current/tutorial/docker.html) and it fails with the same error.

**Comment by p12tic** [comment]
Please use v3.10.1 tag for now.

The docker release process should be fixed to have the `master` tag track the latest published tag not just go after the latest master commit.

**Comment by hollie** [comment]
Hey @p12tic 

thanks for your response. I updated the relevant line in the `docker-compose.yml` file of the `buildbot-docker-example-config/simple` to:

```
image: buildbot/buildbot-master:v3.10.1
```

And now I get when running `docker compose up`:

```
db-1        | ERROR:  relation "version" does not exist at character 15
db-1        | STATEMENT:  select * from version limit 1
db-1        | ERROR:  relation "migrate_version" does not exist at character 15
db-1        | STATEMENT:  select * from migrate_version limit 1
buildbot-1  | Got fatal Exception on DB
buildbot-1  | Traceback (most recent call last):
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/threadpool.py", line 285, in <lambda>
buildbot-1  |     inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/context.py", line 117, in callWithContext
buildbot-1  |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/twisted/python/context.py", line 82, in callWithContext
buildbot-1  |     return func(*args, **kw)
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/buildbot/db/pool.py", line 234, in __thd
buildbot-1  |     log.err(e, 'Got fatal Exception on DB')
buildbot-1  | --- <exception caught here> ---
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/buildbot/db/pool.py", line 207, in __thd
buildbot-1  |     rv = callable(arg, *args, **kwargs)
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/buildbot/db/model.py", line 1136, in thd
buildbot-1  |     context.run_migrations()
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
buildbot-1  |     for step in self._migrations_fn(heads, self):
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/buildbot/db/model.py", line 1122, in upgrade
buildbot-1  |     return alembic_scripts._upgrade_revs(current_script_rev_head, rev)
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/alembic/script/base.py", line 455, in _upgrade_revs
buildbot-1  |     return [
buildbot-1  |   File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
buildbot-1  |     self.gen.throw(type, value, traceback)
buildbot-1  |   File "/buildbot_venv/lib/python3.9/site-packages/alembic/script/base.py", line 283, in _catch_revision_errors
buildbot-1  |     raise util.CommandError(resolution) from re
buildbot-1  | alembic.util.exc.CommandError: Can't locate revision identified by '066'
```

I have in the mean time followed the regular 'install in pyenv' version of the getting started and that is working as expected. So I will continue with that to run further experiments.

Kind regards,
 Lieven.

**Comment by senyai** [comment]
@hollie I had this issue too. I think it's because the db schema has changed. I "fixed" it by mounting PGDATA path in volumes section:

```
volumes:
  - /home/YOURPATH/pgdata:/var/lib/postgresql/data
```
I'm sure this line must be inside the provided docker-compose.yml, because otherwise it's impossible to update `postgres` container.

**Comment by p12tic** [comment]
I think this issue can be closed. The problems with buildbot-www have been resolved and fixing confusing error message will be done as part of https://github.com/buildbot/buildbot/issues/7420.
