### ISSUE TITLE
"force and cancel › should create a build with a dedicated reason and Start it" e2e test fails on firefox sometimes

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#7408]
See e.g. https://buildbot.buildbot.net/#/builders/127/builds/162

```
[1A[2K[26/51] [firefox] › reason_force.spec.ts:45:7 › force and cancel › should create a build with a dedicated reason and Start it
[1A[2K 2) [firefox] › reason_force.spec.ts:45:7 › force and cancel › should create a build with a dedicated reason and Start it
Error: Waited until finished loading
expect.poll.toEqual: Target page, context or browser has been closed
at pages/base.ts:40
38 | }, {
39 | message: "Waited until finished loading"
> 40 | }).toEqual(0);
| ^
41 | }
42 |
43 | static async waitUntilUrlChanged(page: Page, urlChangeFunction: () => Promise<void>) {
at Function.waitUntilFinishedLoading (/buildbot/buildbot-job/build/smokes-react/tests/pages/base.ts:40:8)
at Function.goto (/buildbot/buildbot-job/build/smokes-react/tests/pages/builder.ts:30:20)
at Function.gotoForce (/buildbot/buildbot-job/build/smokes-react/tests/pages/builder.ts:34:5)
at /buildbot/buildbot-job/build/smokes-react/tests/reason_force.spec.ts:50:5
```

**Comment by mokibit** [comment]
@p12tic 
Can not reproduce this issue anymore.
Likely was fixed by https://github.com/buildbot/buildbot/pull/7434.

**Comment by p12tic** [comment]
Thanks, I haven't seen this problem lately.
