### ISSUE TITLE
"previousnextlink › should navigate in the builds history by using the previous next links" e2e test fails on firefox sometimes

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#7409]
See e.g. here https://buildbot.buildbot.net/#/builders/127/builds/162, https://buildbot.buildbot.net/#/builders/127/builds/160: 

```
[19/51] [firefox] › buildsnavigation.spec.ts:28:7 › previousnextlink › should navigate in the builds history by using the previous next links
1) [firefox] › buildsnavigation.spec.ts:28:7 › previousnextlink › should navigate in the builds history by using the previous next links
Error: build count has been incremented
expect.poll.toBeTruthy: Target closed
at pages/builder.ts:108
106 | }, {
107 | message: "build count has been incremented",
> 108 | }).toBeTruthy();
| ^
109 | }
110 |
111 | static async waitGoToBuild(page: Page, expectedBuildNumber: number) {
at Function.waitBuildFinished (/buildbot/buildbot-job/build/smokes-react/tests/pages/builder.ts:108:8)
at /buildbot/buildbot-job/build/smokes-react/tests/buildsnavigation.spec.ts:41:23
```

```
[1A[2K 5) [firefox] › buildsnavigation.spec.ts:28:7 › previousnextlink › should navigate in the builds history by using the previous next links
Error: locator.click: Target closed
=========================== logs ===========================
waiting for getByRole('link', { name: 'runtests', exact: true })
============================================================
at pages/builder.ts:28
26 | static async goto(page: Page, builder: string) {
27 | await BuilderPage.gotoBuildersList(page);
> 28 | await page.getByRole('link', {name: builder, exact: true}).click();
| ^
29 | await page.waitForURL(/\/#\/builders\/[0-9]+$/);
30 | await BasePage.waitUntilFinishedLoading(page);
31 | }
at Function.goto (/buildbot/buildbot-job/build/smokes-react/tests/pages/builder.ts:28:64)
at Function.gotoForce (/buildbot/buildbot-job/build/smokes-react/tests/pages/builder.ts:34:5)
at /buildbot/buildbot-job/build/smokes-react/tests/buildsnavigation.spec.ts:38:5
```

**Comment by mokibit** [comment]
@p12tic
I can not reproduce this issue anymore.
Likely was fixed by https://github.com/buildbot/buildbot/pull/7434.

**Comment by mokibit** [comment]
@p12tic, 
this issue was fixed by https://github.com/buildbot/buildbot/pull/7535.
