### ISSUE TITLE
"change hook › should create a build" e2e test fails on webkit sometimes

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#7539]
E.g. https://buildbot.buildbot.net/#/builders/123/builds/1550

```
[41/54] [webkit] › hook.spec.ts:29:7 › change hook › should create a build
1) [webkit] › hook.spec.ts:29:7 › change hook › should create a build ────────────────────────────
Test timeout of 90000ms exceeded.
Error: page.waitForURL: Test timeout of 90000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
navigated to "http://localhost:8011/#/"
============================================================
at pages/builder.ts:29
27 | await BuilderPage.gotoBuildersList(page);
28 | await page.getByRole('link', {name: builder, exact: true}).click();
> 29 | await page.waitForURL(/\/#\/builders\/[0-9]+$/);
| ^
30 | await BasePage.waitUntilFinishedLoading(page);
31 | }
32 |
at Function.goto (/buildbot/buildbot-job/build/smokes-react/tests/pages/builder.ts:29:16)
at /buildbot/buildbot-job/build/smokes-react/tests/hook.spec.ts:30:5
```

https://buildbot.buildbot.net/#/builders/126/builds/567
```
[41/54] [webkit] › hook.spec.ts:29:7 › change hook › should create a build
1) [webkit] › hook.spec.ts:29:7 › change hook › should create a build ────────────────────────────
Test timeout of 90000ms exceeded.
Error: page.waitForURL: Test timeout of 90000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
navigated to "http://localhost:8011/#/"
============================================================
at pages/builder.ts:29
27 | await BuilderPage.gotoBuildersList(page);
28 | await page.getByRole('link', {name: builder, exact: true}).click();
> 29 | await page.waitForURL(/\/#\/builders\/[0-9]+$/);
| ^
30 | await BasePage.waitUntilFinishedLoading(page);
31 | }
32 |
at Function.goto (/buildbot/buildbot-job/build/smokes-react/tests/pages/builder.ts:29:16)
at /buildbot/buildbot-job/build/smokes-react/tests/hook.spec.ts:30:5
```

**Comment by mokibit** [comment]
@p12tic ,
this issue was fixed by https://github.com/buildbot/buildbot/pull/7545.
