### ISSUE TITLE
Reconfig fails (but restart works?)

### ISSUE THREAD

**Issue by hydrogencl** [buildbot/buildbot#7685]
Dears, 
I have found my buildbot is not able to do the `reconfig` but the `restart`. 
By the twisted.log it shows `raise ValueError(f"{self}: child {svc} should have a defined name attribute")`. However I don't understand this error message. Could someone help to identify what is the issue? I am sure the master.cfg is correct since I did add more builder by this master.cfg and there is no issue after i did the `buildbot restart $buildbot_folder`

buildbot-master version: 3.11.3 
python3 version: 3.10
```
2024-06-03 15:19:36+0000 [-] during reconfig:
	Traceback (most recent call last):
	  File "/home/esm-buildbot/APPS/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 2000, in _inlineCallbacks
	    result = context.run(gen.send, result)
	  File "/home/esm-buildbot/APPS/venv/lib/python3.10/site-packages/buildbot/process/measured_service.py", line 30, in reconfigServiceWithBuildbotConfig
	    yield super().reconfigServiceWithBuildbotConfig(new_config)
	  File "/home/esm-buildbot/APPS/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 2256, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/home/esm-buildbot/APPS/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 2168, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, gen, status, _copy_context())
	--- <exception caught here> ---
	  File "/home/esm-buildbot/APPS/venv/lib/python3.10/site-packages/buildbot/master.py", line 429, in doReconfig
	    yield self.reconfigServiceWithBuildbotConfig(new_config)
	  File "/home/esm-buildbot/APPS/venv/lib/python3.10/site-packages/buildbot/util/service.py", line 49, in reconfigServiceWithBuildbotConfig
	    yield svc.reconfigServiceWithBuildbotConfig(new_config)
	  File "/home/esm-buildbot/APPS/venv/lib/python3.10/site-packages/buildbot/process/measured_service.py", line 30, in reconfigServiceWithBuildbotConfig
	    yield super().reconfigServiceWithBuildbotConfig(new_config)
	  File "/home/esm-buildbot/APPS/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 2000, in _inlineCallbacks
	    result = context.run(gen.send, result)
	  File "/home/esm-buildbot/APPS/venv/lib/python3.10/site-packages/buildbot/util/service.py", line 517, in reconfigServiceWithBuildbotConfig
	    raise ValueError(f"{self}: child {svc} should have a defined name attribute")
	builtins.ValueError: <buildbot.changes.manager.ChangeManager object at 0x7fa53ecc2e60>: child <buildbot.changes.gitpoller.GitPoller object at 0x7fa53e00cdf0> should have a defined name attribute
	
2024-06-03 15:19:36+0000 [-] WARNING: configuration update partially applied; master may malfunction (took 0.113 seconds)
Reconfiguration failed. Please inspect the master.cfg file for errors, correct
```

**Comment by tdesveaux** [comment]
Hi,

If you do not provide a name to your `GitPoller` (eg. `GitPoller(repourl='https://example.com/repo.git', name='poller_example_repo'`), Buildbot will set it's name as `repourl`.

Could you check if you set a name, and if not, if in reconfig, you do correctly provide `repourl`?
A simple `print` should show up in the stdout of reconfig.

**Comment by pmisik** [comment]
Hi

1. Did this issue occur after upgrading Buildbot or did you set up a new instance of Buildbot?
2. If it appeared after the upgrade, could you provide the pre-upgrade version of Buildbot where it worked for you?
3. If you use Buildbot without customizations, you probably configure GitPoller in your `master.cfg`
   Is it possible to share how you configure GitPoller?
   Fill free to obfuscate `repourl` value. Important here is if it is `None` and if you pass `name` argument.
   This is how it looks like in sample.cfg
```
c['change_source'].append(changes.GitPoller(
        'https://github.com/buildbot/hello-world.git',
        workdir='gitpoller-workdir', branch='master',
        pollInterval=300))
```

**Comment by hydrogencl** [comment]
Sorry I was kind of absent from computer for quite sometime. 

1. This issue is not due to upgrading Buildbot master. 
2. I can't provide the version now since it's upgraded, for sure it's version 3.11. 
3. I solved it by including this:
`name='poller_example_repo'` as @tdesveaux had mentioned. 
Now the `buildbot reconfig $folder` works without issue. Thanks pal.
