### ISSUE TITLE
test_setupSiteWithHookAndAuth fails in 4.0.0

### ISSUE THREAD

**Issue by yan12125** [buildbot/buildbot#7754]
I'm preparing buildbot 4.0.0 package for Arch Linux, while a test fails locally:
```
[FAIL]
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/twisted/internet/defer.py", line 2003, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/build/buildbot/src/buildbot-4.0.0/master/buildbot/test/unit/www/test_service.py", line 209, in test_setupSiteWithHookAndAuth
    self.assertIn(b'{"type": "file"}', res)
  File "/usr/lib/python3.12/site-packages/twisted/trial/_synctest.py", line 509, in assertIn
    raise self.failureException(msg or f"{containee!r} not in {container!r}")
twisted.trial.unittest.FailTest: b'{"type": "file"}' not in b'<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta name="viewport" content="initial-scale=1, minimum-scale=1, user-scalable=no, maximum-scale=1, width=device-width">\n    <meta name="theme-color" content="#000000" />\n    <meta name="description" content="Buildbot Web UI"/>\n    <link id="bbicon" href="./icon.png" rel="icon">\n    <link href="./icon.svg" title="Buildbot" rel="fluid-icon">\n    <title>Buildbot</title>\n    <!-- BUILDBOT_THEME_CSS_PLACEHOLDER_BEGIN -->\n    <style id="bb-style">\n      /* when updating the default colors update the following too:\n         - documentation at master/docs/manual/configuration/www.rst\n         - the actual color generation at master/buildbot/www/config.py _known_theme_variables\n      */\n      :root {\n        --bb-sidebar-background-color: #30426a;\n        --bb-sidebar-header-background-color: #273759;\n        --bb-sidebar-header-text-color: #fff;\n        --bb-sidebar-title-text-color: #627cb7;\n        --bb-sidebar-footer-background-color: #273759;\n        --bb-sidebar-button-text-color: #b2bfdc;\n        --bb-sidebar-button-hover-background-color: #1b263d;\n        --bb-sidebar-button-hover-text-color: #fff;\n        --bb-sidebar-button-current-background-color: #273759;\n        --bb-sidebar-button-current-text-color: #b2bfdc;\n        --bb-sidebar-stripe-hover-color: #e99d1a;\n        --bb-sidebar-stripe-current-color: #8c5e10;\n      }\n    </style>\n    <!-- BUILDBOT_THEME_CSS_PLACEHOLDER_END -->\n    <script type="module" crossorigin src="./assets/index-74f03935.js"></script>\n    <link rel="stylesheet" href="./assets/index-342ec232.css">\n  </head>\n  <body>\n    <div id="outdated"></div>\n    <noscript>You need to enable JavaScript to view this website.</noscript>\n    <div id="root"></div>\n  </body>\n  <script src="/browser-warning.js"></script>\n  <link href="/browser-warning.css" rel="stylesheet">\n  <script src="/src/browser-warning-list.js"></script>\n  <!-- BUILDBOT_CONFIG_PLACEHOLDER -->\n  \n</html>'

buildbot.test.unit.www.test_service.Test.test_setupSiteWithHookAndAuth
```

In CI, the test doesn't fail probably because older buildbot-www is used in CI: https://github.com/buildbot/buildbot/blob/v4.0.0/requirements-ci.txt#L5

Here are complete logs:
[buildbot-4.0.0-2-x86_64-build.log](https://github.com/user-attachments/files/16115607/buildbot-4.0.0-2-x86_64-build.log)
[buildbot-4.0.0-2-x86_64-check.log](https://github.com/user-attachments/files/16115609/buildbot-4.0.0-2-x86_64-check.log)
[buildbot-4.0.0-2-x86_64-prepare.log](https://github.com/user-attachments/files/16115610/buildbot-4.0.0-2-x86_64-prepare.log)

The package is built using this packaging script: https://gitlab.archlinux.org/archlinux/packaging/packages/buildbot/-/blob/a9dfb4f307e75c44670d7d8c1f42a14fc4856ed2/PKGBUILD

EDIT: The failure can also be reproduced by using `buildbot-www==4.0.0` in CI: https://github.com/yan12125/buildbot/actions/runs/9819537479

**Comment by p12tic** [comment]
Thanks. This has been fixed in https://github.com/buildbot/buildbot/pull/7756.
