### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by ThomasDevoogdt** [buildbot/buildbot#8094]
I get this error on importlib:

```
Traceback (most recent call last):
  File "/home/buildbot-master/.local/lib/python3.7/site-packages/buildbot/scripts/base.py", line 153, in getConfigFromTac
    exec(f.read(), tacGlobals)  # pylint: disable=exec-used
  File "<string>", line 4, in <module>
  File "/home/buildbot-master/.local/lib/python3.7/site-packages/buildbot/master.py", line 55, in <module>
    from buildbot.www import service as wwwservice
  File "/home/buildbot-master/.local/lib/python3.7/site-packages/buildbot/www/service.py", line 36, in <module>
    from buildbot.plugins.db import get_plugins
  File "/home/buildbot-master/.local/lib/python3.7/site-packages/buildbot/plugins/__init__.py", line 25, in <module>
    from buildbot.plugins.db import get_plugins
  File "/home/buildbot-master/.local/lib/python3.7/site-packages/buildbot/plugins/db.py", line 20, in <module>
    from importlib.metadata import distributions
ModuleNotFoundError: No module named 'importlib.metadata'
```

I can fix it by replacing `importlib.metadata` by `importlib_metadata`, from the [importlib-metadata](https://pypi.org/project/importlib-metadata/) package.

Is it possible to add importlib-metadata to the pip target for older python versions, and catch the ModuleNotFoundError?

Issue seen with version v4.0.3, but the issue is older, since https://github.com/buildbot/buildbot/commit/745a63a0a350884a27a7f96a17604b5d635f07eb.

**Comment by mokibit** [comment]
Hi @ThomasDevoogdt,
Buildbot master requires at least Python-3.8. When you update Python to this version, ModuleNotFoundError will automatically disappear, because `importlib.metadata` was added in Python version 3.8.

**Comment by ThomasDevoogdt** [comment]
Hi, upgrading my python env is not an option (yet), but ok, I can patch it manually for now.

**Comment by mokibit** [comment]
Just curious, what kind of distribution are you using, @ThomasDevoogdt ?

**Comment by ThomasDevoogdt** [comment]
> Just curious, what kind of distribution are you using, @ThomasDevoogdt ?

It's a Debian system.

**Comment by ThomasDevoogdt** [comment]
It's clear that buildbot does no longer support Python 3.7, so I close this issue.
