### ISSUE TITLE
maximum recursion depth exceeded with macos worker

### ISSUE THREAD

**Issue by vbraun** [buildbot/buildbot#8132]
Our macos (M2) worker gets stuck after ~400k lines of stdout, the server log contains
```
2024-10-12 14:54:47+0000 [-] Timing out client: IPv4Address(type='TCP', host='91.64.96.167', port=45988)
2024-10-12 14:54:48+0000 [-] Timing out client: IPv4Address(type='TCP', host='91.64.96.167', port=39082)
2024-10-12 14:54:48+0000 [-] Timing out client: IPv4Address(type='TCP', host='91.64.96.167', port=43700)
2024-10-12 14:57:04+0000 [-] Timing out client: IPv4Address(type='TCP', host='91.64.96.167', port=37562)
2024-10-12 14:57:14+0000 [-] Unhandled error in Deferred:
2024-10-12 14:57:14+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 1074, in _runCallbacks
	    current.result = callback(  # type: ignore[misc]
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 2353, in execute
	    return maybeDeferred(f, *args, **kwargs).addBoth(
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 741, in addBoth
	    return self.addCallbacks(
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 533, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/opt/app-root/lib64/python3.9/site-packages/buildbot/process/remotecommand.py", line 360, in remoteUpdate
	    yield self.add_stdout_lines(cleanup(value), is_flushed)
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 1074, in _runCallbacks
	    current.result = callback(  # type: ignore[misc]
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 2300, in _releaseAndReturn
	    self.release()
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 2441, in release
	    d.callback(self)
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 873, in callback
	    self._startRunCallbacks(result)
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 980, in _startRunCallbacks
	    self._runCallbacks()
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/internet/defer.py", line 1130, in _runCallbacks
	    current.result.cleanFailure()
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/python/failure.py", line 685, in cleanFailure
	    self.__dict__ = self.__getstate__()
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/python/failure.py", line 633, in __getstate__
	    _ = self.parents
	  File "/opt/app-root/lib64/python3.9/site-packages/twisted/python/failure.py", line 425, in parents
	    if inspect.isclass(self.type) and issubclass(self.type, Exception):
	  File "/usr/lib64/python3.9/inspect.py", line 79, in isclass
	    return isinstance(object, type)
	builtins.RecursionError: maximum recursion depth exceeded while calling a Python object
```
I'm a bit confused why the trace is so short, should be loooong for a recursion limit. I guess most of the stack is in another async task? Is there a way to diagnose whats going on?

Our linux workers run fine. I'm guessing macos has a different io buffering that ends up sending logs in more smaller packets?

I'll try to increase the recursion limit next.

**Comment by vbraun** [comment]
For the record, putting
```
sys.setrecursionlimit(10000)
```
to `master.cfg` avoids the RecursionError and the worker did not get stuck
