### ISSUE TITLE
Cannot use Interpolate with db_url with usage reporting

### ISSUE THREAD

**Issue by AlexanderS** [buildbot/buildbot#8168]
Hi,

if I have usage reporting enabled, `utils.Interpolate` in `db_url` does not work:

```
	Traceback (most recent call last):
	  File "/home/buildbot/server/venv/lib/python3.9/site-packages/buildbot/master.py", line 324, in startService
	    self.sendBuildbotNetUsageData()
	  File "/home/buildbot/server/venv/lib/python3.9/site-packages/buildbot/master.py", line 354, in sendBuildbotNetUsageData
	    sendBuildbotNetUsageData(self)
	  File "/home/buildbot/server/venv/lib/python3.9/site-packages/buildbot/buildbot_net_usage_data.py", line 235, in sendBuildbotNetUsageData
	    data = computeUsageData(master)
	  File "/home/buildbot/server/venv/lib/python3.9/site-packages/buildbot/buildbot_net_usage_data.py", line 178, in computeUsageData
	    data = basicData(master)
	  File "/home/buildbot/server/venv/lib/python3.9/site-packages/buildbot/buildbot_net_usage_data.py", line 153, in basicData
	    'db': master.config.db['db_url'].split("://")[0],
	builtins.AttributeError: 'Interpolate' object has no attribute 'split'
```

If I set  `c['buildbotNetUsageData'] = None` `Interpolate` in `db_url` works.

**Comment by tdesveaux** [comment]
Fixed in #8452
