### ISSUE TITLE
Interpolation of repourl in Git step after upgrade to 4.2.0

### ISSUE THREAD

**Issue by dezhin** [buildbot/buildbot#8274]
After upgrading to version 4.2.0, I encountered the following code:
```python
factory.addStep(
    steps.Git(
        repourl=util.Interpolate("%(prop:repository)s"),
    )
)
```

This now causes the following error:
```plain
error while parsing config file:
Traceback (most recent call last):
  File "/home/test/.local/lib/python3.10/site-packages/buildbot/config/master.py", line 93, in loadConfigDict
    execfile(filename, localDict)
  File "/usr/local/lib/python3.10/dist-packages/twisted/python/compat.py", line 213, in execfile
    exec(code, globals, locals)
  File "/home/test/buildbot/master.py", line 67, in <module>
    addScenario(c, "tooldocs")
  File "/home/test/buildbot/master.py", line 58, in addScenario
    scenario = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/test/buildbot/tooldocs/__init__.py", line 107, in <module>
    setup()
  File "/home/test/buildbot/tooldocs/__init__.py", line 49, in setup
    steps.Git(
  File "/home/test/.local/lib/python3.10/site-packages/buildbot/process/buildstep.py", line 140, in __init__
    super().__init__(*args, **kwargs)
  File "/home/test/.local/lib/python3.10/site-packages/buildbot/steps/source/git.py", line 133, in __init__
    self.setupGitStep()
  File "/home/test/.local/lib/python3.10/site-packages/buildbot/util/git.py", line 188, in setupGitStep
    self.repourl = scp_style_to_url_syntax(self.repourl, self.port)
  File "/home/test/.local/lib/python3.10/site-packages/buildbot/util/git.py", line 70, in scp_style_to_url_syntax
    if any(['://' in address, ':\\' in address, ':' not in address]):
builtins.TypeError: argument of type 'Interpolate' is not iterable
```

The code worked without any issues before the upgrade. It seems that interpolation is no longer supported...

**Comment by jennes** [comment]
same here, but I used
```python
factory.addStep(steps.Git(
        haltOnFailure=True,
        repourl=util.Property('repository', default='git://git.internal/src.git'),
        mode='full',
        method='fresh',
    ))
```
the problem was introduced with commit 23d6d34283 and the introduction of calling the new function `scp_style_to_url_syntax` in line 188 of `master/buildbot/util/git.py`, completely ignoring the fact, that `repourl` may be a renderable item.

As a workaround, you can comment or delete line 188 of said file and wait for a patch. That's what I did and will do.
